rust_library(
    name = "payroll-run-storage-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "payroll_run_storage_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/payroll/facade/run-app:payroll-run-app",
        "//app/payroll/core/run-domain:payroll-run-domain",
    ],
)

rust_test(
    name = "payroll-run-storage-inmemory-storage",
    srcs = ["tests/storage.rs"],
    crate = "payroll_run_storage_inmemory_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":payroll-run-storage-inmemory",
        "//app/payroll/facade/run-app:payroll-run-app",
        "//app/payroll/core/run-domain:payroll-run-domain",
    ],
)
