rust_library(
    name = "oya-shared-connector-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_shared_connector_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
