rust_library(
    name = "oya-identity-oidc-issuer-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_identity_oidc_issuer_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
