rust_library(
    name = "oya-intelligence-rag-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_rag_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-rag-api-foundry-rag-retrieve-api",
    srcs = ["tests/foundry_rag_retrieve_api.rs"],
    crate = "oya_intelligence_rag_api_foundry_rag_retrieve_api",
    crate_root = "tests/foundry_rag_retrieve_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-intelligence-rag-api",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
