[package]
name = "oya-platform-policy-cedar-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-policy-cedar-kernel = { path = "../oya-platform-policy-cedar-kernel" }

[lib]
name = "oya_platform_policy_cedar_api"
path = "src/lib.rs"
doctest = false
