[package]
name = "oya-intelligence-policy-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
intelligence-capability-domain = { path = "../../../../intelligence/core/capability-domain" }
data-boundary-kernel = { path = "../../../../data/core/boundary-kernel" }


[lib]
name = "oya_intelligence_policy_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
