rust_library(
    name = "check-backup-retention-discipline",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_backup_retention_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//storage/core/shared-backup-kernel:shared-backup-kernel",
    ],
)

rust_test(
    name = "check-backup-retention-discipline-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_backup_retention_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//storage/core/shared-backup-kernel:shared-backup-kernel",
    ],
)
