[package]
name = "oya-cloud-compute-adapter-oci"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_cloud_compute_adapter_oci"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-cloud-compute-domain = { path = "../oya-cloud-compute-domain" }

[dev-dependencies]
oya-cloud-resource-domain = { path = "../oya-cloud-resource-domain" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-residency-domain = { path = "../../../cloud-network/crates/oya-residency-domain" }

[lints]
workspace = true
