rust_library(
    name = "comms-mail-mailbox-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//comms/adapters/mail-mailbox-postgres:comms-mail-mailbox-postgres",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-usecase:comms-mail-mailbox-usecase",
    ],
)

rust_test(
    name = "comms-mail-mailbox-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//comms/adapters/mail-mailbox-postgres:comms-mail-mailbox-postgres",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-usecase:comms-mail-mailbox-usecase",
    ],
)
