[package]
name = "comms-mail-mailbox-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-mail-mailbox-postgres = { path = "../../adapters/mail-mailbox-postgres" }
comms-mail-mailbox-api = { path = "../../ports/mail-mailbox-api" }
comms-mail-mailbox-usecase = { path = "../mail-mailbox-usecase" }
oya-shared-postgres-command-kernel = { path = "../../../libs/oya-shared-postgres-command-kernel" }
oya-shared-protocol-parity-kernel = { path = "../../../libs/oya-shared-protocol-parity-kernel" }
oya-shared-protocol-transport-kernel = { path = "../../../libs/oya-shared-protocol-transport-kernel" }
oya-shared-transactional-outbox-kernel = { path = "../../../libs/oya-shared-transactional-outbox-kernel" }

[lib]
name = "comms_mail_mailbox_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
