[package]
name = "oya-search-rank-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-search-query-domain = { path = "../oya-search-query-domain" }

[lib]
name = "oya_search_rank_domain"
path = "src/lib.rs"
doctest = false
