rust_library(
    name = "oya-cloud-billing-tax-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_billing_tax_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-cloud-billing-tax-app-cloud-billing-invoice-api",
    srcs = ["tests/cloud_billing_invoice_api.rs"],
    crate = "oya_cloud_billing_tax_app_cloud_billing_invoice_api",
    crate_root = "tests/cloud_billing_invoice_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-billing-tax-app",
    ],
)
