[package]
name = "oya-cloud-storage-object-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-kms-domain = { path = "../../../cloud-kms/crates/oya-cloud-kms-domain" }
compute-resource = { path = "../../../../compute/core/resource" }
oya-cloud-storage-domain = { path = "../oya-cloud-storage-domain" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }

[dev-dependencies]
oya-residency-domain = { path = "../../../cloud-network/crates/oya-residency-domain" }

[lib]
name = "oya_cloud_storage_object_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
