rust_library(
    name = "oya-production-planning-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_production_planning_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-production-planning-domain-production-planning",
    srcs = ["tests/production_planning.rs"],
    crate = "oya_production_planning_domain_production_planning",
    crate_root = "tests/production_planning.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-production-planning-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
