rust_binary(
    name = "check-adr-shape-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/check/adr-shape-kernel:check-adr-shape-kernel",
    ],
)

rust_test(
    name = "check-adr-shape-app-integration",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/check/adr-shape-kernel:check-adr-shape-kernel",
    ],
)
