rust_library(
    name = "oya-global-trade-compliance-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_global_trade_compliance_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-global-trade-compliance-domain-global-trade-compliance",
    srcs = ["tests/global_trade_compliance.rs"],
    crate = "oya_global_trade_compliance_domain_global_trade_compliance",
    crate_root = "tests/global_trade_compliance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-global-trade-compliance-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
