rust_library(
    name = "oya-check-container-base-image",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_container_base_image",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
