rust_library(
    name = "oya-application-shell-frontend",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_application_shell_frontend",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-oidc-client-kernel:oya-shared-oidc-client-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:console_error_panic_hook",
        "third-party//:leptos",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:wasm-bindgen",
        "third-party//:wasm-bindgen-futures",
        "third-party//:web-sys",
    ],
)

rust_binary(
    name = "oya-application-shell-frontend-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/application/crates/oya-application-shell-frontend:oya-application-shell-frontend",
        "//libs/oya-shared-oidc-client-kernel:oya-shared-oidc-client-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:console_error_panic_hook",
        "third-party//:leptos",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:wasm-bindgen",
        "third-party//:wasm-bindgen-futures",
        "third-party//:web-sys",
    ],
)

rust_test(
    name = "oya-application-shell-frontend-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_application_shell_frontend",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-oidc-client-kernel:oya-shared-oidc-client-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:console_error_panic_hook",
        "third-party//:leptos",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:wasm-bindgen",
        "third-party//:wasm-bindgen-futures",
        "third-party//:web-sys",
    ],
)
