[package]
name = "oya-cloud-iam-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
oya-cloud-iam-domain = { path = "../oya-cloud-iam-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }

[lints]
workspace = true
