rust_library(
    name = "oya-shared-object-store-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_object_store_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
