rust_library(
    name = "os-machine-config-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "os_machine_config_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/kernel:os-kernel",
    ],
)

filegroup(
    name = "testdata",
    srcs = glob(["testdata/**"]),
)

rust_test(
    name = "os-machine-config-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt", "testdata/**"]),
    crate = "os_machine_config_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    env = {
        "OYA_TESTDATA_DIR": "$(location :testdata)/testdata",
    },
    deps = [
        "//os/core/kernel:os-kernel",
    ],
)
