[package]
name = "oya-workflow-engine-event-bus-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-event-bus-api = { path = "../oya-workflow-engine-event-bus-api" }

[lib]
name = "oya_workflow_engine_event_bus_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
