rust_library(
    name = "workspace-chat-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workspace_chat_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//comms/core/messenger-domain:comms-messenger-domain",
    ],
)

rust_test(
    name = "workspace-chat-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workspace_chat_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//comms/core/messenger-domain:comms-messenger-domain",
    ],
)

rust_test(
    name = "workspace-chat-api-workspace-chat-api",
    srcs = ["tests/workspace_chat_api.rs"],
    crate = "workspace_chat_api_workspace_chat_api",
    crate_root = "tests/workspace_chat_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":workspace-chat-api",
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//comms/core/messenger-domain:comms-messenger-domain",
    ],
)
