rust_library(
    name = "oya-global-trade-compliance-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_global_trade_compliance_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
