rust_library(
    name = "oya-check-data-class",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_check_data_class",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
