[package]
name = "oya-platform-cell-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }
oya-platform-residency-kernel = { path = "../oya-platform-residency-kernel" }

[lib]
name = "oya_platform_cell_kernel"
path = "src/lib.rs"
doctest = false
