[package]
name = "oya-workspace-forms-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }
oya-workspace-forms-kernel = { path = "../oya-workspace-forms-kernel" }

[lib]
name = "oya_workspace_forms_api"
path = "src/lib.rs"
doctest = false
