[package]
name = "oya-workspace-forms-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-connect-forms-domain = { path = "../oya-connect-forms-domain" }

[lib]
name = "oya_workspace_forms_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
