rust_library(
    name = "oya-search-query-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_search_query_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
