rust_library(
    name = "k8s-control-plane-host-adapter-capi",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_control_plane_host_adapter_capi",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:k8s-openapi",
        "third-party//:kube",
        "third-party//:kube-runtime",
        "third-party//:tokio",
    ],
)
