rust_library(
    name = "oya-workflow-studio-dsl-emitter-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_studio_dsl_emitter_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
