rust_library(
    name = "oya-intelligence-assist-draft-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_intelligence_assist_draft_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-assist-draft-usecase:oya-intelligence-assist-draft-usecase",
    ],
)
