[package]
name = "oya-workflow-engine-event-bus-sdk"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-event-bus-rest = { path = "../oya-workflow-engine-event-bus-rest" }

[lib]
name = "oya_workflow_engine_event_bus_sdk"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
