rust_library(
    name = "oya-ontology-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_ontology_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/ontology/crates/oya-ontology-domain:oya-ontology-domain",
    ],
)

rust_test(
    name = "oya-ontology-api-object-graph-entity-upsert-api",
    srcs = ["tests/object_graph_entity_upsert_api.rs"],
    crate = "oya_ontology_api_object_graph_entity_upsert_api",
    crate_root = "tests/object_graph_entity_upsert_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-ontology-api",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/ontology/crates/oya-ontology-domain:oya-ontology-domain",
    ],
)
