rust_library(
    name = "oya-cloud-network-dns-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_network_dns_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-network-dns-api-cloud-network-dns-api",
    srcs = ["tests/cloud_network_dns_api.rs"],
    crate = "oya_cloud_network_dns_api_cloud_network_dns_api",
    crate_root = "tests/cloud_network_dns_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-network-dns-api",
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
