rust_library(
    name = "oya-billing",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_billing",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:tokio-1",
    ],
)

rust_binary(
    name = "oya-billing",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-billing/crates/oya-billing:oya-billing",
        "third-party//:tokio-1",
    ],
)
