_DEPS = [
    "//oya/identity/crates/oya-identity-workload-svid-kernel:oya-identity-workload-svid-kernel",
    "//cloud/cloud-os/crates/oya-cloud-os-trustd-domain:oya-cloud-os-trustd-domain",
]

rust_library(
    name = "oya-identity-workload-svid-trustd-adapter",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "oya_identity_workload_svid_trustd_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = _DEPS,
)

rust_test(
    name = "oya-identity-workload-svid-trustd-adapter-unittest",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "oya_identity_workload_svid_trustd_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = _DEPS,
)
