rust_library(
    name = "shared-transactional-outbox-adapter-sqlx",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_transactional_outbox_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/postgres-command-kernel:shared-postgres-command-kernel",
        "//data/core/transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "third-party//:sqlx",
    ],
)

rust_test(
    name = "shared-transactional-outbox-adapter-sqlx-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_transactional_outbox_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/postgres-command-kernel:shared-postgres-command-kernel",
        "//data/core/transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "third-party//:sqlx",
    ],
)
