rust_library(
    name = "oya-shared-transactional-outbox-adapter-sqlx",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_transactional_outbox_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "third-party//:sqlx",
    ],
)
