[package]
name = "oya-cloud-cell-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-kernel = { path = "../oya-cloud-region-kernel" }
oya-platform-cell-kernel = { path = "../oya-platform-cell-kernel" }
oya-platform-residency-kernel = { path = "../oya-platform-residency-kernel" }

[lib]
name = "oya_cloud_cell_app"
path = "src/lib.rs"
doctest = false
