[package]
name = "workflow-state-machine-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-state-machine-kernel = { path = "../state-machine-kernel" }

[lib]
name = "workflow_state_machine_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
