[package]
name = "oya-community-social-post-composition-rest"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-shared-postgres-command-kernel = { path = "../../../../libs/oya-shared-postgres-command-kernel" }
oya-community-social-app = { path = "../oya-community-social-app" }
oya-community-social-post-composition-api = { path = "../oya-community-social-post-composition-api" }
oya-community-social-post-composition-usecase = { path = "../oya-community-social-post-composition-usecase" }
oya-shared-hyperscaler-metrics-kernel = { path = "../../../../libs/oya-shared-hyperscaler-metrics-kernel" }

[lib]
name = "oya_community_social_post_composition_rest"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
