rust_library(
    name = "intelligence-capability-registry-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_capability_registry_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/capability-registry-domain:intelligence-capability-registry-domain",
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
    ],
)

rust_test(
    name = "intelligence-capability-registry-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_capability_registry_app",
    crate_root = "src/lib.rs",
    env = {"CARGO_MANIFEST_DIR": "."},
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/capability-registry-domain:intelligence-capability-registry-domain",
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
    ],
)
