[package]
name = "intelligence-capability-registry-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "intelligence_capability_registry_app"
path = "src/lib.rs"
doctest = false

[dependencies]
intelligence-capability-registry-kernel = { path = "../capability-registry-kernel" }
intelligence-capability-registry-domain = { path = "../capability-registry-domain" }

[lints]
workspace = true
