rust_library(
    name = "checkout-guard-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "checkout_guard_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)

rust_binary(
    name = "checkout-guard",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":checkout-guard-app",
    ],
)

rust_test(
    name = "checkout-guard-app-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "checkout_guard_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)
