//! Pure verdict predicate: `evaluate()`.
//!
//! Given materialized bytes (provided by the executor) and a manifest, emits
//! findings — NO I/O, NO clock, NO subprocess.
//!
//! Two predicate classes (ADR-0595 / ADR-0596):
//!   - Committed-class artifacts: byte-parity — committed bytes must equal the
//!     regenerated bytes.
//!   - De-commit-class artifacts: the determinism canary — two regeneration passes
//!     must produce byte-identical output. With byte-parity-to-committed removed,
//!     a nondeterministic producer MUST hard-fail here (CP-3).

use std::collections::{BTreeMap, BTreeSet};

use crate::model::{ArtifactId, Bytes, ControlPlane};

/// A finding code emitted by `evaluate()`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum FindingCode {
    /// A committed-class artifact's regenerated bytes differ from the committed copy.
    GeneratedArtifactStale,
    /// A de-commit-class artifact's two canary passes produced different bytes.
    GeneratedArtifactNondeterministic,
    /// A de-commit-class artifact was not produced by regeneration.
    DecommitArtifactMissing,
    /// A committed-class artifact has a committed copy but no regenerated copy.
    CommittedArtifactNotRegenerated,
}

impl FindingCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            FindingCode::GeneratedArtifactStale => "generated_artifact_stale",
            FindingCode::GeneratedArtifactNondeterministic => "generated_artifact_nondeterministic",
            FindingCode::DecommitArtifactMissing => "decommit_artifact_missing",
            FindingCode::CommittedArtifactNotRegenerated => "committed_artifact_not_regenerated",
        }
    }
}

impl std::fmt::Display for FindingCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A single finding from `evaluate()`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Finding {
    pub code: FindingCode,
    pub artifact_id: ArtifactId,
    pub detail: String,
}

impl Finding {
    fn new(
        code: FindingCode,
        artifact_id: impl Into<ArtifactId>,
        detail: impl Into<String>,
    ) -> Self {
        Self {
            code,
            artifact_id: artifact_id.into(),
            detail: detail.into(),
        }
    }
}

/// The set of findings produced by `evaluate()`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Findings {
    pub findings: Vec<Finding>,
}

impl Findings {
    pub fn is_green(&self) -> bool {
        self.findings.is_empty()
    }
}

/// THE VERDICT PREDICATE — pure.
///
/// - `pass_a`: first-pass materialized bytes, keyed by artifact_id.
/// - `pass_b`: second-pass materialized bytes (canary); empty slice if not canary.
/// - `committed`: committed bytes for committed-class artifacts, keyed by artifact_id.
/// - `manifest`: the control-plane manifest (MF-1 note: in E3, the caller supplies
///   the merge-base manifest for the exemption-set computation; this parameter shape
///   is designed to accept that without a schema break).
///
/// CP-3: feeding nondeterministic two-pass bytes yields a RED finding.
pub fn evaluate(
    pass_a: &[(ArtifactId, Bytes)],
    pass_b: &[(ArtifactId, Bytes)],
    committed: &[(ArtifactId, Bytes)],
    manifest: &ControlPlane,
) -> Findings {
    let pass_a_map: BTreeMap<&str, &str> = pass_a
        .iter()
        .map(|(id, bytes)| (id.as_str(), bytes.as_str()))
        .collect();
    let pass_b_map: BTreeMap<&str, &str> = pass_b
        .iter()
        .map(|(id, bytes)| (id.as_str(), bytes.as_str()))
        .collect();
    let committed_map: BTreeMap<&str, &str> = committed
        .iter()
        .map(|(id, bytes)| (id.as_str(), bytes.as_str()))
        .collect();

    let decommit_ids: BTreeSet<&str> = manifest
        .artifacts
        .iter()
        .filter(|a| a.is_not_tracked_in_git())
        .map(|a| a.artifact_id.as_str())
        .collect();

    let mut findings: BTreeSet<Finding> = BTreeSet::new();

    for artifact in &manifest.artifacts {
        let id = artifact.artifact_id.as_str();

        if decommit_ids.contains(id) {
            // De-commit class: verify regeneration succeeded and is deterministic.
            // INTENTIONAL asymmetry: `committed` bytes are ignored for this class —
            // de-commit artifacts have no committed copy by definition (byte-parity-to-
            // committed is structurally removed), so only the two canary passes matter.
            match (pass_a_map.get(id), pass_b_map.get(id)) {
                (None, _) => {
                    findings.insert(Finding::new(
                        FindingCode::DecommitArtifactMissing,
                        id,
                        "de-commit-class artifact was not produced by regeneration (pass A)",
                    ));
                }
                (Some(a), Some(b)) if a != b => {
                    // CP-3: nondeterminism is a hard RED.
                    findings.insert(Finding::new(
                        FindingCode::GeneratedArtifactNondeterministic,
                        id,
                        "de-commit-class artifact produced different bytes across two canary passes",
                    ));
                }
                // Both passes present and equal — GREEN for this artifact.
                _ => {}
            }
        } else {
            // Committed class: byte-parity check.
            // INTENTIONAL asymmetry: `pass_b` (the second canary pass) is ignored for
            // this class — committed artifacts are verified by parity against the
            // committed copy, not by the two-pass determinism canary.
            match (pass_a_map.get(id), committed_map.get(id)) {
                (Some(regen), Some(committed_bytes)) if *regen == *committed_bytes => {
                    // GREEN.
                }
                (Some(_), Some(_)) => {
                    findings.insert(Finding::new(
                        FindingCode::GeneratedArtifactStale,
                        id,
                        "committed bytes differ from regenerated bytes",
                    ));
                }
                (None, Some(_)) => {
                    findings.insert(Finding::new(
                        FindingCode::CommittedArtifactNotRegenerated,
                        id,
                        "committed artifact was not produced by regeneration",
                    ));
                }
                (_, None) => {
                    // No committed copy — nothing to check for committed-class.
                }
            }
        }
    }

    let mut sorted: Vec<Finding> = findings.into_iter().collect();
    sorted.sort();
    Findings { findings: sorted }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::ControlPlane;

    fn simple_manifest(is_decommit: bool) -> ControlPlane {
        let mode = if is_decommit {
            "not-tracked-in-git"
        } else {
            "merge-candidate"
        };
        let json = format!(
            r#"{{
          "schema_version": 2,
          "runner_registry": [],
          "artifacts": [{{
            "artifact_id": "face-a",
            "path": "ci/a.generated.json",
            "materialization_mode": "{mode}",
            "generator": {{
              "runner": "buck2",
              "generator_target": "//ci:a",
              "operation_id": "emit-a",
              "output_mode": "stdout-json"
            }}
          }}]
        }}"#
        );
        ControlPlane::from_json(&json).unwrap()
    }

    #[test]
    fn canary_catches_nondeterminism() {
        // CP-3: two different canary passes -> RED.
        let manifest = simple_manifest(true);
        let pass_a = vec![("face-a".to_owned(), "bytes-v1".to_owned())];
        let pass_b = vec![("face-a".to_owned(), "bytes-v2-different".to_owned())];
        let result = evaluate(&pass_a, &pass_b, &[], &manifest);
        assert!(!result.is_green());
        assert_eq!(
            result.findings[0].code,
            FindingCode::GeneratedArtifactNondeterministic
        );
    }

    #[test]
    fn canary_green_when_deterministic() {
        let manifest = simple_manifest(true);
        let pass_a = vec![("face-a".to_owned(), "bytes".to_owned())];
        let pass_b = vec![("face-a".to_owned(), "bytes".to_owned())];
        let result = evaluate(&pass_a, &pass_b, &[], &manifest);
        assert!(result.is_green(), "deterministic producer should be GREEN");
    }

    #[test]
    fn committed_class_byte_parity_stale() {
        let manifest = simple_manifest(false);
        let pass_a = vec![("face-a".to_owned(), "regenerated".to_owned())];
        let committed = vec![("face-a".to_owned(), "old-committed".to_owned())];
        let result = evaluate(&pass_a, &[], &committed, &manifest);
        assert!(!result.is_green());
        assert_eq!(result.findings[0].code, FindingCode::GeneratedArtifactStale);
    }

    #[test]
    fn committed_class_byte_parity_green() {
        let manifest = simple_manifest(false);
        let pass_a = vec![("face-a".to_owned(), "same".to_owned())];
        let committed = vec![("face-a".to_owned(), "same".to_owned())];
        let result = evaluate(&pass_a, &[], &committed, &manifest);
        assert!(result.is_green());
    }

    #[test]
    fn decommit_missing_is_red() {
        let manifest = simple_manifest(true);
        // No regeneration result for face-a.
        let result = evaluate(&[], &[], &[], &manifest);
        assert!(!result.is_green());
        assert_eq!(
            result.findings[0].code,
            FindingCode::DecommitArtifactMissing
        );
    }
}
