rust_library(
    name = "compute-functions-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_functions_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-functions-api-cloud-compute-functions-api",
    srcs = ["tests/cloud_compute_functions_api.rs"],
    crate = "compute_functions_api_cloud_compute_functions_api",
    crate_root = "tests/cloud_compute_functions_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":compute-functions-api",
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
