rust_library(
    name = "messenger-admission-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_admission_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/conversation-api:messenger-conversation-api",
    ],
)

rust_test(
    name = "messenger-admission-usecase-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_admission_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/conversation-api:messenger-conversation-api",
    ],
)

rust_test(
    name = "messenger-admission-usecase-contract",
    srcs = ["tests/contract.rs"],
    crate = "contract",
    crate_root = "tests/contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":messenger-admission-usecase",
        "//app/messenger/adapters/authority-memory:messenger-authority-memory",
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/conversation-api:messenger-conversation-api",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)
