rust_library(
    name = "shared-olap-clickhouse-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_olap_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/olap-client-kernel:shared-olap-client-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:clickhouse",
    ],
)

rust_test(
    name = "shared-olap-clickhouse-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_olap_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/olap-client-kernel:shared-olap-client-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:clickhouse",
    ],
)
