rust_library(
    name = "oya-shared-protocol-transport-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_protocol_transport_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
    ],
)
