[package]
name = "oya-cloud-kms-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../../../cloud-cell/crates/oya-cloud-region-domain" }
compute-resource = { path = "../../../../compute/core/resource" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-residency-domain = { path = "../../../cloud-network/crates/oya-residency-domain" }

[lib]
name = "oya_cloud_kms_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
