[package]
name = "community-social-post-composition-grpc"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-protocol-transport-kernel = { path = "../../../../gateway/core/protocol-transport-kernel" }
shared-postgres-command-kernel = { path = "../../../../data/core/postgres-command-kernel" }


community-social-app = { path = "../../facade/social-app" }
community-social-post-composition-api = { path = "../../ports/social-post-composition-api" }

[lib]
name = "community_social_post_composition_grpc"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
