rust_library(
    name = "oya-payments-dispute-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_payments_dispute_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/payments/crates/oya-payments-charge-kernel:oya-payments-charge-kernel",
        "//oya/payments/crates/oya-payments-dispute-domain:oya-payments-dispute-domain",
    ],
)
