rust_library(
    name = "billing-accounting-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_accounting_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//billing/core/accounting-journal:billing-accounting-journal",
    ],
)

rust_test(
    name = "billing-accounting-app-app-envelopes",
    srcs = ["tests/app_envelopes.rs"],
    crate = "billing_accounting_app_app_envelopes",
    crate_root = "tests/app_envelopes.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-accounting-app",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//billing/core/accounting-journal:billing-accounting-journal",
    ],
)
