[package]
name = "billing-accounting-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../base/data-boundary-kernel" }
billing-accounting-journal = { path = "../accounting-journal" }

[lib]
name = "billing_accounting_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
