rust_library(
    name = "oya-workflow-engine-execution-engine-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_execution_engine_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-kernel:oya-workflow-engine-execution-engine-kernel",
    ],
)
