{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zitadel
  namespace: identity-{{ .Values.packLabel }}
  labels:
    app.kubernetes.io/part-of: identity
    pack: {{ .Values.packLabel | quote }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zitadel
{{- end }}
