[package]
name = "oya-intelligence-guardrails-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
intelligence-guardrails-domain = { path = "../../../../intelligence/core/guardrails-domain" }

[lib]
name = "oya_intelligence_guardrails_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
