apiVersion: openslo/v1
kind: SLO
metadata:
  name: treasury-latency-p99
  labels:
    service: treasury
    sap_code: "TRM"
spec:
  description: "Treasury treasury-latency-p99 objective; benchmarks SAP TRM Treasury and Risk Management | Oracle Fusion Cash Management | Workday Financial Management cash and treasury counterpart | NetSuite Cash Management | Microsoft Dynamics 365 Finance Cash and Bank"
  service: treasury
  indicator:
    metadata:
      name: treasury-latency-p99-sli
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(http_request_duration_seconds_bucket{service=\"treasury\",le=\"0.35\"}[5m]))"
        total:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(http_request_duration_seconds_count{service=\"treasury\"}[5m]))"
  objectives:
    - displayName: treasury-latency-p99
      target: 0.99
