rust_library(
    name = "storage-recordings-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_recordings_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//comms/core/meet-domain:comms-meet-domain",
    ],
)

rust_test(
    name = "storage-recordings-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_recordings_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//comms/core/meet-domain:comms-meet-domain",
    ],
)
