rust_library(
    name = "oya-hr-employment-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_hr_employment_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
