rust_library(
    name = "oya-hr-employment-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_hr_employment_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-hr-employment-api-contracts",
    srcs = ["tests/contracts.rs"],
    crate = "oya_hr_employment_api_contracts",
    crate_root = "tests/contracts.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-hr-employment-api",
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
