rust_library(
    name = "data-search-index-vector",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_search_index_vector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/search-crawler:data-search-crawler",
        "//data/core/search-parser:data-search-parser",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "data-search-index-vector-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_search_index_vector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/search-crawler:data-search-crawler",
        "//data/core/search-parser:data-search-parser",
        "third-party//:serde_json",
    ],
)
