[package]
name = "oya-cloud-kms-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
oya-cloud-kms-domain = { path = "../oya-cloud-kms-domain" }
oya-cloud-region-domain = { path = "../oya-cloud-region-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }

[dev-dependencies]
oya-residency-domain = { path = "../oya-residency-domain" }

[lints]
workspace = true
