rust_library(
    name = "oya-accounting-journal-runtime",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_accounting_journal_runtime",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//oya/accounting/crates/oya-accounting-journal-api:oya-accounting-journal-api",
        "//oya/accounting/crates/oya-accounting-journal-app:oya-accounting-journal-app",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
    ],
)
