[package]
name = "oya-shared-backbone-grpc-generated-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"
build = "build.rs"

[dependencies]
oya-community-social-app = { path = "../../oya/community/crates/oya-community-social-app" }
comms-messenger-stream-app = { path = "../../comms/core/messenger-stream-app" }
comms-mail-mailbox-app = { path = "../../comms/core/mail-mailbox-app" }
oya-community-post-store-app = { path = "../../oya/community/crates/oya-community-post-store-app" }
oya-community-post-store-api = { path = "../../oya/community/crates/oya-community-post-store-api" }
oya-community-post-store-domain = { path = "../../oya/community/crates/oya-community-post-store-domain" }
oya-community-post-store-grpc = { path = "../../oya/community/crates/oya-community-post-store-grpc" }
comms-mail-mailbox-api = { path = "../../comms/ports/mail-mailbox-api" }
comms-mail-mailbox-grpc = { path = "../../comms/facade/mail-mailbox-grpc" }
comms-messenger-stream-api = { path = "../../comms/ports/messenger-stream-api" }
comms-messenger-stream-grpc = { path = "../../comms/facade/messenger-stream-grpc" }
oya-shared-postgres-command-kernel = { path = "../oya-shared-postgres-command-kernel" }
oya-community-social-post-composition-api = { path = "../../oya/community/crates/oya-community-social-post-composition-api" }
oya-community-social-post-composition-grpc = { path = "../../oya/community/crates/oya-community-social-post-composition-grpc" }
oya-shared-backbone-proto-contracts-kernel = { path = "../oya-shared-backbone-proto-contracts-kernel" }
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
