[package]
name = "oya-shared-postgres-command-adapter-sqlx"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-shared-postgres-command-kernel = { path = "../oya-shared-postgres-command-kernel" }
sqlx.workspace = true

[lib]
name = "oya_shared_postgres_command_adapter_sqlx"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
