[package]
name = "iam-tenant-rbac-postgres-rls-runtime-evidence"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-postgres-rls-storage = { path = "../../adapters/tenant-rbac-postgres-rls-storage" }

[lib]
name = "iam_tenant_rbac_postgres_rls_runtime_evidence"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
