rust_library(
    name = "check-cost-budget",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_cost_budget",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "check-cost-budget-cost-budget",
    srcs = ["tests/cost_budget.rs"],
    crate = "check_cost_budget_cost_budget",
    crate_root = "tests/cost_budget.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":check-cost-budget",
        "//base/data-boundary-kernel:data-boundary-kernel",
    ],
)
