[package]
name = "oya-cloud-region-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../oya-cloud-region-domain" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_region_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
