rust_library(
    name = "check-doc-axis",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_doc_axis",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/governance-adr-shape-kernel:governance-adr-shape-kernel",
        "third-party//:tempfile",
    ],
)

rust_test(
    name = "check-doc-axis-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_doc_axis",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/governance-adr-shape-kernel:governance-adr-shape-kernel",
        "third-party//:tempfile",
    ],
)

rust_test(
    name = "check-doc-axis-doc-axis-validation",
    srcs = ["tests/doc_axis_validation.rs"],
    crate = "check_doc_axis_doc_axis_validation",
    crate_root = "tests/doc_axis_validation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":check-doc-axis",
        "third-party//:tempfile",
    ],
)
