rust_library(
    name = "intelligence-codex-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_codex_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/kernel:intelligence-kernel",
        "third-party//:bytes",
        "third-party//:bytes",
        "third-party//:futures-core",
        "third-party//:futures-util",
        "third-party//:reqwest",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
        # UNRESOLVED: httpmock ^0.7
    ],
)

rust_test(
    name = "intelligence-codex-adapter-tests",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_codex_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/kernel:intelligence-kernel",
        "third-party//:bytes",
        "third-party//:futures-core",
        "third-party//:futures-util",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)
