rust_library(
    name = "oya-tenant-rbac-postgres-rls-storage",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_tenant_rbac_postgres_rls_storage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
