[package]
name = "shared-transactional-outbox-poller-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-transactional-outbox-kernel = { path = "../shared-transactional-outbox-kernel" }
shared-transactional-outbox-worker-app = { path = "../shared-transactional-outbox-worker-app" }

[lib]
name = "shared_transactional_outbox_poller_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
