rust_library(
    name = "oya-check-step-up-auth-coverage",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_step_up_auth_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_yaml",
        "third-party//:serde_yaml",
    ],
)

rust_test(
    name = "oya-check-step-up-auth-coverage-step-up-auth-coverage",
    srcs = ["tests/step_up_auth_coverage.rs"],
    crate = "oya_check_step_up_auth_coverage_step_up_auth_coverage",
    crate_root = "tests/step_up_auth_coverage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-check-step-up-auth-coverage",
        "third-party//:serde",
        "third-party//:serde_yaml",
        "third-party//:serde_yaml",
    ],
)
