rust_library(
    name = "oya-tooling-agent-read",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tooling_agent_read",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "oya-tooling-agent-read-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tools/oya-tooling-agent-read:oya-tooling-agent-read",
    ],
)

rust_test(
    name = "oya-tooling-agent-read-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tooling_agent_read",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-tooling-agent-read-contract",
    srcs = ["tests/contract.rs"],
    crate = "oya_tooling_agent_read_contract",
    crate_root = "tests/contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tooling-agent-read",
    ],
)
