[package]
name = "oya-payments-kyc-kyb-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_payments_kyc_kyb_domain"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-payments-charge-kernel = { path = "../oya-payments-charge-kernel" }

[lints]
workspace = true
