[package]
name = "oya-search-rag-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-search-serp-domain = { path = "../oya-search-serp-domain" }
oya-search-query-domain = { path = "../oya-search-query-domain" }

[dev-dependencies]
oya-search-rank-domain = { path = "../oya-search-rank-domain" }

[lib]
name = "oya_search_rag_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
