rust_library(
    name = "community-social-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_social_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//libs/shared-protocol-parity-kernel:shared-protocol-parity-kernel",
        "//libs/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//libs/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//app/community/adapters/social-post-composition-postgres:community-social-post-composition-postgres",
        "//app/community/ports/social-post-composition-api:community-social-post-composition-api",
        "//app/community/core/social-post-composition-usecase:community-social-post-composition-usecase",
    ],
)

rust_test(
    name = "community-social-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_social_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//libs/shared-protocol-parity-kernel:shared-protocol-parity-kernel",
        "//libs/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//libs/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//app/community/adapters/social-post-composition-postgres:community-social-post-composition-postgres",
        "//app/community/ports/social-post-composition-api:community-social-post-composition-api",
        "//app/community/core/social-post-composition-usecase:community-social-post-composition-usecase",
    ],
)
