rust_library(
    name = "oya-check-openapi-rest-route-parity",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_openapi_rest_route_parity",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
