use cell_placement::CellId;

use crate::{
    BindingDigest32, BindingGeneration, BindingOperationKey, BindingOperationRevision,
    BindingReservationAttemptRevision, BindingRevision, WriteAuthorityEpoch,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum BindingAbortContextV1 {
    InitialPlacement,
    MigrationBeforeAuthorityAllocation,
    MigrationWithAuthorityAllocation {
        migration_fence_claim_digest: BindingDigest32,
        authority_high_water_record_digest: BindingDigest32,
        source_authority: Box<crate::ServingAuthorityInstanceV1>,
        source_freeze_intent_digest: BindingDigest32,
        claim_identity_digest: BindingDigest32,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BindingMovedAuditEffectV1 {
    pub source_cell_id: CellId,
    pub target_cell_id: CellId,
    pub expected_generation: BindingGeneration,
    pub expected_revision: BindingRevision,
    pub committed_generation: BindingGeneration,
    pub committed_revision: BindingRevision,
    pub write_authority_epoch: WriteAuthorityEpoch,
    pub authority_high_water_revision: crate::TenantWriteAuthorityHighWaterRevision,
    pub authority_high_water_record_digest: BindingDigest32,
    pub assurance_requirements_digest: BindingDigest32,
    pub assurance_evidence_digest: BindingDigest32,
    pub recovery_evidence_digest: BindingDigest32,
    pub binding_attempt_digest: BindingDigest32,
    pub required_reservation_set_digest: BindingDigest32,
    pub placement_decision_digest: BindingDigest32,
    pub reservation_commit_permit_digest: BindingDigest32,
    pub transfer_authorization_set_digest: BindingDigest32,
    pub write_fence_digest: BindingDigest32,
    pub source_fencing_completion_digest: BindingDigest32,
    pub source_authority: crate::ServingAuthorityInstanceV1,
    pub source_authority_terminal_closure_digest: BindingDigest32,
    pub migration_commit_seal_digest: BindingDigest32,
    pub binding_outcome_digest: BindingDigest32,
    pub control_contribution_digest: BindingDigest32,
    pub projection_digest: BindingDigest32,
    pub target_authority: crate::ServingAuthorityInstanceV1,
    pub installation_issuance_digest: BindingDigest32,
    pub primary_location_digest: BindingDigest32,
    pub recovery_location_digest: Option<BindingDigest32>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum BindingAuditEffectV1 {
    ControlContributionPublished {
        projection_digest: BindingDigest32,
        target: crate::BindingControlContributionTargetV1,
        handoff_digest: BindingDigest32,
    },
    ControlContributionAcknowledged {
        projection_digest: BindingDigest32,
        target: crate::BindingControlContributionTargetV1,
        acknowledgment_digest: BindingDigest32,
    },
    CellIndexContributionsApplied {
        applied_contribution_root_digest: BindingDigest32,
        applied_checkpoint_root_digest: BindingDigest32,
        target_projection_digest: BindingDigest32,
    },
    ServingAuthorityIndependentlyRetired {
        instance: crate::ServingAuthorityInstanceV1,
        retirement_digest: BindingDigest32,
        installation_issuance_digest: BindingDigest32,
    },
    ServingAuthorityInstalled {
        instance: crate::ServingAuthorityInstanceV1,
        installation_issuance_digest: BindingDigest32,
        first_local_lease_issuance_digest: BindingDigest32,
        result_digest: BindingDigest32,
    },
    ServingAuthorityFrozen {
        instance: crate::ServingAuthorityInstanceV1,
        freeze_intent_digest: BindingDigest32,
        result_digest: BindingDigest32,
        committed_horizon: crate::ServingAuthorityCommittedIssuanceHorizonV1,
    },
    ServingAuthorityHandoffRecorded {
        instance: crate::ServingAuthorityInstanceV1,
        handoff_record_digest: BindingDigest32,
        authenticated_result_digest: BindingDigest32,
    },
    WorkSnapshotPageCommitted {
        key: crate::BindingWorkSnapshotKeyV1,
        start_ordinal: u64,
        next_ordinal: u64,
        progress_record_digest: BindingDigest32,
    },
    WorkSnapshotSealed {
        key: crate::BindingWorkSnapshotKeyV1,
        progress_record_digest: BindingDigest32,
    },
    ReservationAttemptOpened {
        binding_attempt_digest: BindingDigest32,
        binding_precondition_digest: BindingDigest32,
        placement_decision_digest: BindingDigest32,
        required_reservation_set_digest: BindingDigest32,
        arm_intent_set_digest: BindingDigest32,
    },
    ReservationAttemptCheckpointed {
        binding_attempt_digest: BindingDigest32,
        attempt_revision: BindingReservationAttemptRevision,
        evidence_digest: BindingDigest32,
    },
    InitialBindingCommitted {
        target_cell_id: CellId,
        committed_generation: BindingGeneration,
        committed_revision: BindingRevision,
        write_authority_epoch: WriteAuthorityEpoch,
        authority_high_water_revision: crate::TenantWriteAuthorityHighWaterRevision,
        authority_high_water_record_digest: BindingDigest32,
        assurance_requirements_digest: BindingDigest32,
        assurance_evidence_digest: BindingDigest32,
        recovery_evidence_digest: BindingDigest32,
        binding_attempt_digest: BindingDigest32,
        required_reservation_set_digest: BindingDigest32,
        placement_decision_digest: BindingDigest32,
        reservation_commit_permit_digest: BindingDigest32,
        participant_preparation_closure_digest: BindingDigest32,
        control_contribution_digest: BindingDigest32,
        projection_audience_policy_digest: BindingDigest32,
        binding_outcome_digest: BindingDigest32,
        projection_digest: BindingDigest32,
        target_authority: crate::ServingAuthorityInstanceV1,
        installation_issuance_digest: BindingDigest32,
        primary_location_digest: BindingDigest32,
        recovery_location_digest: Option<BindingDigest32>,
    },
    BindingMoved(Box<BindingMovedAuditEffectV1>),
    BindingOutcomeAborted {
        context: BindingAbortContextV1,
        binding_attempt_digest: BindingDigest32,
        attempt_revision: BindingReservationAttemptRevision,
        required_reservation_set_digest: BindingDigest32,
        armed_reservation_set_digest: BindingDigest32,
        binding_outcome_digest: BindingDigest32,
    },
    MigrationFenceClaimed {
        source_cell_id: CellId,
        target_cell_id: CellId,
        source_generation: BindingGeneration,
        source_revision: BindingRevision,
        successor_generation: BindingGeneration,
        write_authority_epoch: WriteAuthorityEpoch,
        authority_high_water_revision: crate::TenantWriteAuthorityHighWaterRevision,
        authority_high_water_record_digest: BindingDigest32,
        source_authority: crate::ServingAuthorityInstanceV1,
        source_freeze_intent_digest: BindingDigest32,
        claim_identity_digest: BindingDigest32,
        binding_attempt_digest: BindingDigest32,
        migration_fence_claim_digest: BindingDigest32,
        movement_permit_digest: BindingDigest32,
        transfer_authorization_set_digest: BindingDigest32,
        transfer_effect_manifest_digest: BindingDigest32,
        participant_manifest_digest: BindingDigest32,
        prepared_participant_closure_digest: BindingDigest32,
    },
    MigrationWriteFenceCommitted {
        source_cell_id: CellId,
        target_cell_id: CellId,
        source_generation: BindingGeneration,
        source_revision: BindingRevision,
        successor_generation: BindingGeneration,
        write_authority_epoch: WriteAuthorityEpoch,
        binding_attempt_digest: BindingDigest32,
        migration_fence_claim_digest: BindingDigest32,
        write_fence_digest: BindingDigest32,
        source_fencing_completion_digest: BindingDigest32,
        final_delta_digest: BindingDigest32,
    },
    ParticipantManifestCommitted {
        participant_manifest_digest: BindingDigest32,
        cell_commitment_digest: BindingDigest32,
    },
    ParticipantReceiptAppended {
        phase: crate::ParticipantReceiptPhaseV1,
        participant_id: crate::CapabilityParticipantId,
        receipt_digest: BindingDigest32,
        ledger_record_digest: BindingDigest32,
    },
    ParticipantPhaseClosed {
        phase: crate::ParticipantReceiptPhaseV1,
        closure_digest: BindingDigest32,
    },
    TransferEffectManifestCommitted {
        manifest_digest: BindingDigest32,
    },
    TransferAuthorizationAppended {
        effect_fingerprint: BindingDigest32,
        authorization_digest: BindingDigest32,
        journal_record_digest: BindingDigest32,
    },
    TransferAuthorizationSetSealed {
        authorization_set_digest: BindingDigest32,
        journal_record_digest: BindingDigest32,
    },
    TransferExecutionPermitIssued {
        effect_fingerprint: BindingDigest32,
        execution_permit_digest: BindingDigest32,
        ledger_record_digest: BindingDigest32,
    },
    TransferExecutionOutcomeRecorded {
        effect_fingerprint: BindingDigest32,
        outcome_digest: BindingDigest32,
        ledger_record_digest: BindingDigest32,
    },
    SourceFenceDirectiveIssued {
        participant_id: crate::CapabilityParticipantId,
        directive_digest: BindingDigest32,
        ledger_record_digest: BindingDigest32,
    },
    WriteAuthorityLeaseRenewalCommitted {
        instance: crate::ServingAuthorityInstanceV1,
        cell_id: CellId,
        binding_generation: BindingGeneration,
        binding_revision: BindingRevision,
        write_authority_epoch: WriteAuthorityEpoch,
        previous_lease_digest: BindingDigest32,
        renewal_lease_digest: BindingDigest32,
        renewal_lease_issuance_digest: BindingDigest32,
        maximum_write_authority_lease_expires_at_unix_seconds: u64,
        write_authority_lease_state_digest: BindingDigest32,
    },
    WriteAuthorityLeasePublished {
        instance: crate::ServingAuthorityInstanceV1,
        cell_id: CellId,
        binding_generation: BindingGeneration,
        binding_revision: BindingRevision,
        write_authority_epoch: WriteAuthorityEpoch,
        lease_digest: BindingDigest32,
        issuance_record_digest: BindingDigest32,
    },
    MigrationReleaseFinalized {
        target_activation_closure_digest: BindingDigest32,
        source_release_closure_digest: BindingDigest32,
        projection_convergence_digest: BindingDigest32,
        source_reservation_release_permit_digest: BindingDigest32,
    },
    OperationCancelled {
        target_operation: BindingOperationKey,
        expected_target_revision: BindingOperationRevision,
        result_digest: BindingDigest32,
    },
    OperationCheckpointed {
        checkpoint_digest: BindingDigest32,
    },
    OperationRepaired {
        target_operation: BindingOperationKey,
        expected_target_revision: BindingOperationRevision,
        repair_authority_digest: BindingDigest32,
        applied_checkpoint_digest: BindingDigest32,
    },
    OperationRefused {
        refusal_digest: BindingDigest32,
    },
    OperationFailed {
        failure_digest: BindingDigest32,
    },
}
