rust_library(
    name = "oya-tenant-rbac-identity-provider-verification",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_identity_provider_verification",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-auth-app:oya-tenant-rbac-auth-app",
    ],
)
