use std::error::Error;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

const MEMBERSHIPS: [(&str, &str, bool); 6] = [
    ("src/items", "lib.generated.rs", true),
    ("src/test_items", "tests.generated.rs", false),
    ("tests/usecase_items", "usecases.generated.rs", false),
    (
        "tests/leave_balance_items",
        "leave_balance.generated.rs",
        true,
    ),
    (
        "tests/leave_carryover_forfeiture_items",
        "leave_carryover_forfeiture.generated.rs",
        true,
    ),
    ("tests/onboarding_items", "onboarding.generated.rs", true),
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);

    for (relative_dir, output_name, required) in MEMBERSHIPS {
        let item_dir = manifest_dir.join(relative_dir);
        println!("cargo:rerun-if-changed={}", item_dir.display());
        let generated =
            render_configured_membership(&item_dir, required).map_err(std::io::Error::other)?;
        fs::write(out_dir.join(output_name), generated)?;
    }

    Ok(())
}

fn render_configured_membership(item_dir: &Path, required: bool) -> Result<String, String> {
    if !item_dir.exists() && !required {
        return Ok(String::from(
            "// @generated by build.rs from direct Rust item files; do not edit.\n\n",
        ));
    }
    render_membership(item_dir)
}

fn render_membership(item_dir: &Path) -> Result<String, String> {
    let entries = fs::read_dir(item_dir).map_err(|error| {
        format!(
            "cannot read membership directory {}: {error}",
            item_dir.display()
        )
    })?;
    let mut items = Vec::new();

    for entry in entries {
        let entry = entry.map_err(|error| {
            format!(
                "cannot read membership entry in {}: {error}",
                item_dir.display()
            )
        })?;
        let file_type = entry.file_type().map_err(|error| {
            format!(
                "cannot inspect membership entry {}: {error}",
                entry.path().display()
            )
        })?;
        if !file_type.is_file() || entry.path().extension() != Some(OsStr::new("rs")) {
            continue;
        }

        let file_name = entry
            .file_name()
            .into_string()
            .map_err(|_| "direct Rust item name is not valid UTF-8".to_string())?;
        let stem = file_name
            .strip_suffix(".rs")
            .ok_or_else(|| format!("invalid direct Rust item name {file_name}"))?;
        let mut chars = stem.chars();
        if !chars.next().is_some_and(|ch| ch.is_ascii_lowercase())
            || !chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_')
        {
            return Err(format!("invalid direct Rust item name {file_name}"));
        }
        items.push((file_name, entry.path()));
    }

    items.sort_by(|left, right| left.0.cmp(&right.0));
    let mut generated =
        String::from("// @generated by build.rs from direct Rust item files; do not edit.\n\n");
    let item_count = items.len();
    for (index, (file_name, path)) in items.into_iter().enumerate() {
        let contents = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read direct Rust item {}: {error}", path.display()))?;
        generated.push_str("// source: ");
        generated.push_str(&file_name);
        generated.push('\n');
        generated.push_str(&contents);
        if !contents.ends_with('\n') {
            generated.push('\n');
        }
        if index + 1 < item_count {
            generated.push('\n');
        }
    }
    Ok(generated)
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicUsize, Ordering};

    static NEXT_FIXTURE: AtomicUsize = AtomicUsize::new(0);

    struct Fixture {
        root: PathBuf,
    }

    impl Fixture {
        fn new() -> Self {
            let sequence = NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed);
            let root = std::env::temp_dir().join(format!(
                "hr-employment-domain-scanner-{}-{sequence}",
                std::process::id()
            ));
            fs::create_dir(&root).expect("scanner fixture directory must be created");
            Self { root }
        }

        fn path(&self) -> &Path {
            &self.root
        }

        fn write(&self, name: &str, contents: &str) {
            fs::write(self.root.join(name), contents).expect("scanner fixture must be written");
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.root).expect("scanner fixture must be removed");
        }
    }

    #[test]
    fn direct_rust_entries_are_sorted_and_deterministic() {
        let fixture = Fixture::new();
        fixture.write("z_last.rs", "pub const LAST: u8 = 2;\n");
        fixture.write("a_first.rs", "pub const FIRST: u8 = 1;\n");
        fixture.write("notes.txt", "not Rust\n");
        fs::create_dir(fixture.path().join("nested")).expect("nested fixture must be created");
        fixture.write("nested.rs.bak", "not a direct Rust item\n");

        let expected = concat!(
            "// @generated by build.rs from direct Rust item files; do not edit.\n\n",
            "// source: a_first.rs\n",
            "pub const FIRST: u8 = 1;\n\n",
            "// source: z_last.rs\n",
            "pub const LAST: u8 = 2;\n",
        );
        assert_eq!(super::render_membership(fixture.path()).unwrap(), expected);
        assert_eq!(super::render_membership(fixture.path()).unwrap(), expected);
    }

    #[test]
    fn add_rename_and_remove_refresh_membership_without_an_index_edit() {
        let fixture = Fixture::new();
        fixture.write("b_existing.rs", "pub const EXISTING: u8 = 1;\n");
        assert!(
            super::render_membership(fixture.path())
                .unwrap()
                .contains("source: b_existing.rs")
        );

        fixture.write("a_added.rs", "pub const ADDED: u8 = 2;\n");
        let added = super::render_membership(fixture.path()).unwrap();
        assert!(added.find("a_added.rs") < added.find("b_existing.rs"));

        fs::rename(
            fixture.path().join("b_existing.rs"),
            fixture.path().join("c_renamed.rs"),
        )
        .expect("fixture item must be renamed");
        let renamed = super::render_membership(fixture.path()).unwrap();
        assert!(!renamed.contains("b_existing.rs"));
        assert!(renamed.contains("c_renamed.rs"));

        fs::remove_file(fixture.path().join("a_added.rs")).expect("fixture item must be removed");
        let removed = super::render_membership(fixture.path()).unwrap();
        assert!(!removed.contains("a_added.rs"));
        assert!(removed.contains("c_renamed.rs"));
    }

    #[test]
    fn invalid_rust_item_name_fails_closed() {
        let fixture = Fixture::new();
        fixture.write("Not-Snake.rs", "pub const INVALID: u8 = 1;\n");

        let error = super::render_membership(fixture.path()).unwrap_err();
        assert!(error.contains("invalid direct Rust item name Not-Snake.rs"));
    }

    #[test]
    fn missing_membership_directory_fails_closed() {
        let fixture = Fixture::new();
        let missing = fixture.path().join("missing");

        let error = super::render_membership(&missing).unwrap_err();
        assert!(error.contains("cannot read membership directory"));
    }

    #[test]
    fn configured_empty_membership_is_generated_without_a_placeholder_item() {
        let fixture = Fixture::new();
        let missing = fixture.path().join("reserved");

        assert_eq!(
            super::render_configured_membership(&missing, false).unwrap(),
            "// @generated by build.rs from direct Rust item files; do not edit.\n\n"
        );
        assert!(super::render_configured_membership(&missing, true).is_err());
    }
}
