rust_library(
    name = "oya-identity-workload-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_identity_workload_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-authz-cedar-adapter:oya-identity-workload-authz-cedar-adapter",
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "//oya/identity/crates/oya-identity-workload-oidc-adapter:oya-identity-workload-oidc-adapter",
        "third-party//:aws-lc-rs-1",
        "third-party//:base64",
    ],
)
