# A list of available rules and their signatures can be found here: https://buck2.build/docs/prelude/globals/

genrule(
    name = "hello_world",
    out = "out.txt",
    cmd = "echo BUILT BY BUCK2> $OUT",
)


genrule(
    name = "buck2-authority-policy-check",
    srcs = {
        ".github/branch-protection.yaml": ".github/branch-protection.yaml",
        ".github/workflows/backbone-microservices-ci.yml": ".github/workflows/backbone-microservices-ci.yml",
        "BUCK": "BUCK",
        "Makefile": "Makefile",
        "docs/decisions/ADR-0346-oya-verify-must-run-full-ci-mirror.md": "docs/decisions/ADR-0346-oya-verify-must-run-full-ci-mirror.md",
        "docs/decisions/ADR-0360-ci-pipeline-optimization-program.md": "docs/decisions/ADR-0360-ci-pipeline-optimization-program.md",
        "docs/decisions/ADR-0361-jenkins-native-cicd-revamp-execution.md": "docs/decisions/ADR-0361-jenkins-native-cicd-revamp-execution.md",
        "docs/decisions/ADR-0363-retire-agentic-vcs-foundry-to-intelligence-forgejo-substrate.md": "docs/decisions/ADR-0363-retire-agentic-vcs-foundry-to-intelligence-forgejo-substrate.md",
        "docs/decisions/ADR-0392-buck2-canonical-build-graph.md": "docs/decisions/ADR-0392-buck2-canonical-build-graph.md",
        "docs/decisions/ADR-0408-buck2-driven-ci-cd.md": "docs/decisions/ADR-0408-buck2-driven-ci-cd.md",
        "docs/decisions/ADR-0511-ci-orchestration-argo-workflows-supersede-jenkins.md": "docs/decisions/ADR-0511-ci-orchestration-argo-workflows-supersede-jenkins.md",
        "docs/decisions/ADR-0515-buck2-native-oci-static-musl-base.md": "docs/decisions/ADR-0515-buck2-native-oci-static-musl-base.md",
        "docs/TOOLCHAIN.md": "docs/TOOLCHAIN.md",
        "docs/standards/code-style.md": "docs/standards/code-style.md",
        "docs/standards/rust-release-optimization.md": "docs/standards/rust-release-optimization.md",
        "infra/branch-protection/dev.json": "infra/branch-protection/dev.json",
        "infra/ci/buck2-affected-gate.sh": "infra/ci/buck2-affected-gate.sh",
        "infra/ci/jenkins/agent-image/Dockerfile": "infra/ci/jenkins/agent-image/Dockerfile",
        "infra/ci/jenkins/codegen-measure-seed.groovy": "infra/ci/jenkins/codegen-measure-seed.groovy",
        "infra/ci/jenkins/farmwide-seed.groovy": "infra/ci/jenkins/farmwide-seed.groovy",
        "infra/ci/jenkins/parallel-lanes-seed.groovy": "infra/ci/jenkins/parallel-lanes-seed.groovy",
        "infra/ci/jenkins/reported-status-contexts.json": "infra/ci/jenkins/reported-status-contexts.json",
        "infra/ci/jenkins/shared-library/vars/oyaCiLane.groovy": "infra/ci/jenkins/shared-library/vars/oyaCiLane.groovy",
        "infra/ci/jenkins/smoke-seed.groovy": "infra/ci/jenkins/smoke-seed.groovy",
        "scripts/agent-pre-push-validate.sh": "scripts/agent-pre-push-validate.sh",
        "scripts/asyncapi-lint.mjs": "scripts/asyncapi-lint.mjs",
        "scripts/branch-protection-apply.sh": "scripts/branch-protection-apply.sh",
        "scripts/build/build-and-push-cloud-intelligence.sh": "scripts/build/build-and-push-cloud-intelligence.sh",
        "cloud/cloud-intelligence/iac/oci/BUCK": "//cloud/cloud-intelligence/iac/oci:BUCK",
        "scripts/ci/enforce-buck2-authority.py": "scripts/ci/enforce-buck2-authority.py",
        "scripts/ci/oya-ci-post.sh": "scripts/ci/oya-ci-post.sh",
        "scripts/ci/regen-third-party.sh": "scripts/ci/regen-third-party.sh",
        "scripts/gen_first_party_buck.py": "scripts/gen_first_party_buck.py",
        "scripts/hooks/pre-push.sh": "scripts/hooks/pre-push.sh",
        "scripts/install-trivy-ci.sh": "scripts/install-trivy-ci.sh",
        "scripts/onprem-bring-up.sh": "scripts/onprem-bring-up.sh",
        "scripts/proto-lint.mjs": "scripts/proto-lint.mjs",
        "scripts/supply-chain-adr0039.sh": "scripts/supply-chain-adr0039.sh",
        "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh": "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh",
        "scripts/validate-adr-shape.mjs": "scripts/validate-adr-shape.mjs",
        "scripts/validate-foundry-phase00-evidence.mjs": "scripts/validate-foundry-phase00-evidence.mjs",
        "specs/buck2-authority-policy.json": "specs/buck2-authority-policy.json",
        "tools/hooks/no-cargo-enforcer.sh": "tools/hooks/no-cargo-enforcer.sh",
    },
    out = "buck2-authority-policy-check.json",
    cmd = "OYA_REPO_ROOT=$PWD python3 scripts/ci/enforce-buck2-authority.py --policy specs/buck2-authority-policy.json > $OUT",
    visibility = ["PUBLIC"],
)
