# A list of available rules and their signatures can be found here: https://buck2.build/docs/prelude/globals/

genrule(
    name = "hello_world",
    out = "out.txt",
    cmd = "echo BUILT BY BUCK2> $OUT",
)


# Buck2 root BUCK dialect rejects def-based src helpers in this repository;
# keep current service CI files explicitly declared here, while
# specs/buck2-authority-policy.json expands command_scan_globs
# (cloud/*/ci/Jenkinsfile, oya/*/ci/Jenkinsfile) in the Python scanner.
genrule(
    name = "buck2-authority-policy-check",
    srcs = {
        ".github/workflows/backbone-microservices-ci.yml": ".github/workflows/backbone-microservices-ci.yml",
        "infra/ci/jenkins/shared-library/vars/oyaCiLane.groovy": "infra/ci/jenkins/shared-library/vars/oyaCiLane.groovy",
        "infra/ci/buck2-affected-gate.sh": "infra/ci/buck2-affected-gate.sh",
        "infra/ci/jenkins/farmwide-seed.groovy": "infra/ci/jenkins/farmwide-seed.groovy",
        "infra/ci/jenkins/codegen-measure-seed.groovy": "infra/ci/jenkins/codegen-measure-seed.groovy",
        "infra/ci/jenkins/parallel-lanes-seed.groovy": "infra/ci/jenkins/parallel-lanes-seed.groovy",
        "infra/ci/jenkins/smoke-seed.groovy": "infra/ci/jenkins/smoke-seed.groovy",
        "infra/ci/jenkins/agent-image/Dockerfile": "infra/ci/jenkins/agent-image/Dockerfile",
        "scripts/branch-protection-apply.sh": "scripts/branch-protection-apply.sh",
        "scripts/onprem-bring-up.sh": "scripts/onprem-bring-up.sh",
        "scripts/install-trivy-ci.sh": "scripts/install-trivy-ci.sh",
        "scripts/supply-chain-adr0039.sh": "scripts/supply-chain-adr0039.sh",
        "scripts/hooks/pre-push.sh": "scripts/hooks/pre-push.sh",
        "scripts/ci/enforce-buck2-authority.py": "scripts/ci/enforce-buck2-authority.py",
        "scripts/ci/oya-ci-post.sh": "scripts/ci/oya-ci-post.sh",
        "scripts/ci/assert-pr-required-context.py": "scripts/ci/assert-pr-required-context.py",
        "scripts/tests/phase0_required_context_rollup_check.test.sh": "scripts/tests/phase0_required_context_rollup_check.test.sh",
        "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json": "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json": "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json",
        "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json": "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json",
        "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json": "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json",
        "scripts/ci/regen-third-party.sh": "scripts/ci/regen-third-party.sh",
        "scripts/gen_first_party_buck.py": "scripts/gen_first_party_buck.py",
        "scripts/agent-pre-push-validate.sh": "scripts/agent-pre-push-validate.sh",
        "scripts/build/build-and-push-cloud-intelligence.sh": "scripts/build/build-and-push-cloud-intelligence.sh",
        "cloud/cloud-intelligence/iac/oci/BUCK": "//cloud/cloud-intelligence/iac/oci:BUCK",
        "scripts/asyncapi-lint.mjs": "scripts/asyncapi-lint.mjs",
        "scripts/proto-lint.mjs": "scripts/proto-lint.mjs",
        "scripts/validate-adr-shape.mjs": "scripts/validate-adr-shape.mjs",
        "scripts/validate-foundry-phase00-evidence.mjs": "scripts/validate-foundry-phase00-evidence.mjs",
        "tools/hooks/no-cargo-enforcer.sh": "tools/hooks/no-cargo-enforcer.sh",
        "Makefile": "Makefile",
        "docs/TOOLCHAIN.md": "docs/TOOLCHAIN.md",
        "docs/standards/code-style.md": "docs/standards/code-style.md",
        "docs/standards/rust-release-optimization.md": "docs/standards/rust-release-optimization.md",
        "docs/standards/testing.md": "docs/standards/testing.md",
        "docs/standards/ci-lanes.md": "docs/standards/ci-lanes.md",
        "docs/standards/release-management.md": "docs/standards/release-management.md",
        "docs/standards/multi-agent-tool-map.md": "docs/standards/multi-agent-tool-map.md",
        "docs/security.md": "docs/security.md",
        "cloud/cloud-intelligence/Dockerfile": "cloud/cloud-intelligence/Dockerfile",
        "oya/ci-webhook-gateway/Dockerfile": "//oya/ci-webhook-gateway:Dockerfile",
        "oya/governance/iac/build/Dockerfile.distroless-rust": "oya/governance/iac/build/Dockerfile.distroless-rust",
        "oya/application/crates/oya-application-shell-frontend-prototype/client-manifest.json": "//oya/application/crates/oya-application-shell-frontend-prototype:client-manifest.json",
        ".github/branch-protection.yaml": ".github/branch-protection.yaml",
        "infra/branch-protection/dev.json": "infra/branch-protection/dev.json",
        "infra/ci/jenkins/reported-status-contexts.json": "infra/ci/jenkins/reported-status-contexts.json",
        "scripts/tests/phase0_ci_enforcement_baseline_catalog_check.py": "scripts/tests/phase0_ci_enforcement_baseline_catalog_check.py",
        "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh": "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh",
        "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh": "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh",
        "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh": "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh",
        "scripts/ci/arm-auto-merge.sh": "scripts/ci/arm-auto-merge.sh",
        "scripts/trigger-next-queue-automerge.sh": "scripts/trigger-next-queue-automerge.sh",
        "scripts/check-sequential-pr-merge-conflicts.sh": "scripts/check-sequential-pr-merge-conflicts.sh",
        "scripts/tests/forgejo_auto_merge_after_ci.test.sh": "scripts/tests/forgejo_auto_merge_after_ci.test.sh",
        "scripts/tests/phase0_auto_merge_after_ci_contract_check.py": "scripts/tests/phase0_auto_merge_after_ci_contract_check.py",
        "docs/ci/auto-merge-flow.md": "docs/ci/auto-merge-flow.md",
        "docs/ci/forge-of-record.md": "docs/ci/forge-of-record.md",
        "docs/decisions/ADR-0513-oya-ci-bespoke-rust-prow-cicd-platform.md": "docs/decisions/ADR-0513-oya-ci-bespoke-rust-prow-cicd-platform.md",
        "docs/decisions/ADR-0514-build-ci-cd-pipeline-target-architecture-hyperscaler-remediation.md": "docs/decisions/ADR-0514-build-ci-cd-pipeline-target-architecture-hyperscaler-remediation.md",
        "specs/phase0-auto-merge-after-ci.json": "specs/phase0-auto-merge-after-ci.json",
        "oya/ci-tide/crates/oya-ci-tide-kernel/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-kernel:lib-src",
        "oya/ci-tide/crates/oya-ci-tide-app/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-app:lib-src",
        "oya/ci-tide/crates/oya-ci-tide-forgejo-adapter/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-forgejo-adapter:lib-src",
        "docs/decisions/ADR-0346-oya-verify-must-run-full-ci-mirror.md": "docs/decisions/ADR-0346-oya-verify-must-run-full-ci-mirror.md",
        "docs/decisions/ADR-0361-jenkins-native-cicd-revamp-execution.md": "docs/decisions/ADR-0361-jenkins-native-cicd-revamp-execution.md",
        "docs/decisions/ADR-0392-buck2-canonical-build-graph.md": "docs/decisions/ADR-0392-buck2-canonical-build-graph.md",
        "docs/decisions/ADR-0408-buck2-driven-ci-cd.md": "docs/decisions/ADR-0408-buck2-driven-ci-cd.md",
        "docs/decisions/ADR-0515-buck2-native-oci-static-musl-base.md": "docs/decisions/ADR-0515-buck2-native-oci-static-musl-base.md",
        "docs/decisions/ADR-0360-ci-pipeline-optimization-program.md": "docs/decisions/ADR-0360-ci-pipeline-optimization-program.md",
        "docs/decisions/ADR-0363-retire-agentic-vcs-foundry-to-intelligence-forgejo-substrate.md": "docs/decisions/ADR-0363-retire-agentic-vcs-foundry-to-intelligence-forgejo-substrate.md",
        "docs/decisions/ADR-0511-ci-orchestration-argo-workflows-supersede-jenkins.md": "docs/decisions/ADR-0511-ci-orchestration-argo-workflows-supersede-jenkins.md",
        "BUCK": "BUCK",
        "specs/buck2-authority-policy.json": "specs/buck2-authority-policy.json",
        "cloud/cell-lifecycle/ci/Jenkinsfile": "cloud/cell-lifecycle/ci/Jenkinsfile",
        "cloud/cell-rebalancer/ci/Jenkinsfile": "cloud/cell-rebalancer/ci/Jenkinsfile",
        "cloud/cloud-billing-tax/ci/Jenkinsfile": "cloud/cloud-billing-tax/ci/Jenkinsfile",
        "cloud/cloud-billing/ci/Jenkinsfile": "cloud/cloud-billing/ci/Jenkinsfile",
        "cloud/cloud-data/ci/Jenkinsfile": "cloud/cloud-data/ci/Jenkinsfile",
        "cloud/cloud-iac/ci/Jenkinsfile": "cloud/cloud-iac/ci/Jenkinsfile",
        "cloud/cloud-iam/ci/Jenkinsfile": "cloud/cloud-iam/ci/Jenkinsfile",
        "cloud/cloud-intelligence/ci/Jenkinsfile": "cloud/cloud-intelligence/ci/Jenkinsfile",
        "cloud/cloud-k8s/ci/Jenkinsfile": "cloud/cloud-k8s/ci/Jenkinsfile",
        "cloud/cloud-kms/ci/Jenkinsfile": "cloud/cloud-kms/ci/Jenkinsfile",
        "cloud/cloud-network-dns/ci/Jenkinsfile": "cloud/cloud-network-dns/ci/Jenkinsfile",
        "cloud/cloud-network/ci/Jenkinsfile": "cloud/cloud-network/ci/Jenkinsfile",
        "cloud/cloud-secrets/ci/Jenkinsfile": "cloud/cloud-secrets/ci/Jenkinsfile",
        "cloud/cloud-storage/ci/Jenkinsfile": "cloud/cloud-storage/ci/Jenkinsfile",
        "cloud/tenancy/ci/Jenkinsfile": "cloud/tenancy/ci/Jenkinsfile",
        "oya/accounting/ci/Jenkinsfile": "oya/accounting/ci/Jenkinsfile",
        "oya/analytics/ci/Jenkinsfile": "oya/analytics/ci/Jenkinsfile",
        "oya/api-gateway/ci/Jenkinsfile": "oya/api-gateway/ci/Jenkinsfile",
        "oya/application/ci/Jenkinsfile": "oya/application/ci/Jenkinsfile",
        "oya/audit-chain/ci/Jenkinsfile": "oya/audit-chain/ci/Jenkinsfile",
        "oya/calendar/ci/Jenkinsfile": "oya/calendar/ci/Jenkinsfile",
        "oya/comms-email/ci/Jenkinsfile": "oya/comms-email/ci/Jenkinsfile",
        "oya/community/ci/Jenkinsfile": "oya/community/ci/Jenkinsfile",
        "oya/compliance/ci/Jenkinsfile": "oya/compliance/ci/Jenkinsfile",
        "oya/connector/ci/Jenkinsfile": "oya/connector/ci/Jenkinsfile",
        "oya/consent-graph/ci/Jenkinsfile": "oya/consent-graph/ci/Jenkinsfile",
        "oya/contact-center/ci/Jenkinsfile": "oya/contact-center/ci/Jenkinsfile",
        "oya/contract-lifecycle-management/ci/Jenkinsfile": "oya/contract-lifecycle-management/ci/Jenkinsfile",
        "oya/crm/ci/Jenkinsfile": "oya/crm/ci/Jenkinsfile",
        "oya/data-pipeline/ci/Jenkinsfile": "oya/data-pipeline/ci/Jenkinsfile",
        "oya/data-warehouse/ci/Jenkinsfile": "oya/data-warehouse/ci/Jenkinsfile",
        "oya/design-collaboration/ci/Jenkinsfile": "oya/design-collaboration/ci/Jenkinsfile",
        "oya/detection/ci/Jenkinsfile": "oya/detection/ci/Jenkinsfile",
        "oya/developer-sdk/ci/Jenkinsfile": "oya/developer-sdk/ci/Jenkinsfile",
        "oya/diagnostics/ci/Jenkinsfile": "oya/diagnostics/ci/Jenkinsfile",
        "oya/docs/ci/Jenkinsfile": "oya/docs/ci/Jenkinsfile",
        "oya/drive/ci/Jenkinsfile": "oya/drive/ci/Jenkinsfile",
        "oya/emergency/ci/Jenkinsfile": "oya/emergency/ci/Jenkinsfile",
        "oya/emr/ci/Jenkinsfile": "oya/emr/ci/Jenkinsfile",
        "oya/feature-flags/ci/Jenkinsfile": "oya/feature-flags/ci/Jenkinsfile",
        "oya/financial-planning/ci/Jenkinsfile": "oya/financial-planning/ci/Jenkinsfile",
        "oya/finops-portal/ci/Jenkinsfile": "oya/finops-portal/ci/Jenkinsfile",
        "oya/forms/ci/Jenkinsfile": "oya/forms/ci/Jenkinsfile",
        "oya/global-trade/ci/Jenkinsfile": "oya/global-trade/ci/Jenkinsfile",
        "oya/governance/ci/Jenkinsfile": "oya/governance/ci/Jenkinsfile",
        "oya/healthcare-integration/ci/Jenkinsfile": "oya/healthcare-integration/ci/Jenkinsfile",
        "oya/hr/ci/Jenkinsfile": "oya/hr/ci/Jenkinsfile",
        "oya/identity/ci/Jenkinsfile": "oya/identity/ci/Jenkinsfile",
        "oya/imaging/ci/Jenkinsfile": "oya/imaging/ci/Jenkinsfile",
        "oya/incident-management/ci/Jenkinsfile": "oya/incident-management/ci/Jenkinsfile",
        "oya/intelligence/ci/Jenkinsfile": "oya/intelligence/ci/Jenkinsfile",
        "oya/itsm/ci/Jenkinsfile": "oya/itsm/ci/Jenkinsfile",
        "oya/learning-management/ci/Jenkinsfile": "oya/learning-management/ci/Jenkinsfile",
        "oya/mail/ci/Jenkinsfile": "oya/mail/ci/Jenkinsfile",
        "oya/marketing-automation/ci/Jenkinsfile": "oya/marketing-automation/ci/Jenkinsfile",
        "oya/marketplace/ci/Jenkinsfile": "oya/marketplace/ci/Jenkinsfile",
        "oya/meet/ci/Jenkinsfile": "oya/meet/ci/Jenkinsfile",
        "oya/messenger/ci/Jenkinsfile": "oya/messenger/ci/Jenkinsfile",
        "oya/notes/ci/Jenkinsfile": "oya/notes/ci/Jenkinsfile",
        "oya/observability/ci/Jenkinsfile": "oya/observability/ci/Jenkinsfile",
        "oya/ontology/ci/Jenkinsfile": "oya/ontology/ci/Jenkinsfile",
        "oya/ops-dashboard-control-center/ci/Jenkinsfile": "oya/ops-dashboard-control-center/ci/Jenkinsfile",
        "oya/patient-monitoring/ci/Jenkinsfile": "oya/patient-monitoring/ci/Jenkinsfile",
        "oya/payments/ci/Jenkinsfile": "oya/payments/ci/Jenkinsfile",
        "oya/payroll/ci/Jenkinsfile": "oya/payroll/ci/Jenkinsfile",
        "oya/performance-management/ci/Jenkinsfile": "oya/performance-management/ci/Jenkinsfile",
        "oya/pharmacy/ci/Jenkinsfile": "oya/pharmacy/ci/Jenkinsfile",
        "oya/plant-maintenance/ci/Jenkinsfile": "oya/plant-maintenance/ci/Jenkinsfile",
        "oya/plugin-app-store/ci/Jenkinsfile": "oya/plugin-app-store/ci/Jenkinsfile",
        "oya/production-planning/ci/Jenkinsfile": "oya/production-planning/ci/Jenkinsfile",
        "oya/quality-management/ci/Jenkinsfile": "oya/quality-management/ci/Jenkinsfile",
        "oya/real-estate/ci/Jenkinsfile": "oya/real-estate/ci/Jenkinsfile",
        "oya/recordings/ci/Jenkinsfile": "oya/recordings/ci/Jenkinsfile",
        "oya/sheets/ci/Jenkinsfile": "oya/sheets/ci/Jenkinsfile",
        "oya/sites/ci/Jenkinsfile": "oya/sites/ci/Jenkinsfile",
        "oya/slides/ci/Jenkinsfile": "oya/slides/ci/Jenkinsfile",
        "oya/social/ci/Jenkinsfile": "oya/social/ci/Jenkinsfile",
        "oya/supply-chain-planning/ci/Jenkinsfile": "oya/supply-chain-planning/ci/Jenkinsfile",
        "oya/tasks/ci/Jenkinsfile": "oya/tasks/ci/Jenkinsfile",
        "oya/tenant-rbac/ci/Jenkinsfile": "oya/tenant-rbac/ci/Jenkinsfile",
        "oya/translate/ci/Jenkinsfile": "oya/translate/ci/Jenkinsfile",
        "oya/treasury/ci/Jenkinsfile": "oya/treasury/ci/Jenkinsfile",
        "oya/warehouse/ci/Jenkinsfile": "oya/warehouse/ci/Jenkinsfile",
        "oya/whiteboard/ci/Jenkinsfile": "oya/whiteboard/ci/Jenkinsfile",
        "oya/workflow-engine/ci/Jenkinsfile": "oya/workflow-engine/ci/Jenkinsfile",
        "oya/workflow-studio/ci/Jenkinsfile": "oya/workflow-studio/ci/Jenkinsfile",
        "oya/workplace-integration/ci/Jenkinsfile": "oya/workplace-integration/ci/Jenkinsfile",
    },
    out = "buck2-authority-policy-check.json",
    cmd = "PYTHONDONTWRITEBYTECODE=1 OYA_REPO_ROOT=$PWD python3 scripts/ci/enforce-buck2-authority.py --policy specs/buck2-authority-policy.json > $OUT",
    visibility = ["PUBLIC"],
)

# P0.0 baseline catalog closure: every checked-in executable fixture under
# specs/fixtures/phase0-ci-enforcement-baseline must be listed by the baseline
# packet and reachable through Buck2, not operator memory. The fixture glob is
# intentional: newly added fixtures must enter the Buck action sandbox even when
# the baseline forgets to catalog them.
genrule(
    name = "phase0-ci-enforcement-baseline-catalog-check",
    srcs = {
        "scripts/tests/phase0_ci_enforcement_baseline_catalog_check.py": "scripts/tests/phase0_ci_enforcement_baseline_catalog_check.py",
        "specs/phase0-ci-enforcement-baseline.json": "specs/phase0-ci-enforcement-baseline.json",
        "specs/phase0-ci-enforcement-result-schema.json": "specs/phase0-ci-enforcement-result-schema.json",
        "specs/phase0-override-packet-schema.json": "specs/phase0-override-packet-schema.json",
        "specs/phase0-trusted-target-inventory-schema.json": "specs/phase0-trusted-target-inventory-schema.json",
        "specs/toolchain-tenant-isolation-fixtures.json": "specs/toolchain-tenant-isolation-fixtures.json",
    } | {path: path for path in glob(["specs/fixtures/phase0-ci-enforcement-baseline/*.json"])},
    out = "phase0-ci-enforcement-baseline-catalog-check.json",
    cmd = "PYTHONDONTWRITEBYTECODE=1 OYA_REPO_ROOT=$PWD python3 scripts/tests/phase0_ci_enforcement_baseline_catalog_check.py > $OUT",
    visibility = ["PUBLIC"],
)


# P0.0 auto-merge-after-CI bridge check: Forgejo dry-run payload must use the
# cloud-ci/oya-ci required context, schedule merge after checks pass, and pin the
# PR head SHA. This is local/static evidence, not a live Forgejo mutation.
genrule(
    name = "forgejo-auto-merge-after-ci-check",
    srcs = {
        "scripts/tests/forgejo_auto_merge_after_ci.test.sh": "scripts/tests/forgejo_auto_merge_after_ci.test.sh",
        "scripts/ci/arm-auto-merge.sh": "scripts/ci/arm-auto-merge.sh",
        "docs/ci/auto-merge-flow.md": "docs/ci/auto-merge-flow.md",
        "docs/ci/forge-of-record.md": "docs/ci/forge-of-record.md",
    },
    out = "forgejo-auto-merge-after-ci-check.txt",
    cmd = "bash scripts/tests/forgejo_auto_merge_after_ci.test.sh > $OUT",
    visibility = ["PUBLIC"],
)

# P0.0 GitHub bootstrap mirror auto-merge check: live scheduling must refuse
# required-context drift and non-squash merge methods before arming auto-merge.
# This is local/static evidence over a fake gh CLI, not a live GitHub mutation.
genrule(
    name = "github-auto-merge-after-ci-check",
    srcs = {
        "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh": "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh",
        "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh": "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh",
        "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh": "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh",
        "scripts/tests/phase0_required_context_rollup_check.test.sh": "scripts/tests/phase0_required_context_rollup_check.test.sh",
        "scripts/ci/assert-pr-required-context.py": "scripts/ci/assert-pr-required-context.py",
        "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json": "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json": "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json",
        "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json": "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json",
        "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json": "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json",
        "scripts/trigger-next-queue-automerge.sh": "scripts/trigger-next-queue-automerge.sh",
        "scripts/check-sequential-pr-merge-conflicts.sh": "scripts/check-sequential-pr-merge-conflicts.sh",
        "infra/branch-protection/dev.json": "infra/branch-protection/dev.json",
    },
    out = "github-auto-merge-after-ci-check.txt",
    cmd = "(bash scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh && bash scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh && bash scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh && bash scripts/tests/phase0_required_context_rollup_check.test.sh) > $OUT",
    visibility = ["PUBLIC"],
)

# P0.0 auto-merge-after-CI contract check: closes the checked-in Forgejo/GitHub
# auto-merge contract over scripts, docs, Tide adapter code, and Buck2 policy.
genrule(
    name = "phase0-auto-merge-after-ci-contract-check",
    srcs = {
        "scripts/tests/phase0_auto_merge_after_ci_contract_check.py": "scripts/tests/phase0_auto_merge_after_ci_contract_check.py",
        "specs/phase0-auto-merge-after-ci.json": "specs/phase0-auto-merge-after-ci.json",
        "specs/buck2-authority-policy.json": "specs/buck2-authority-policy.json",
        "scripts/ci/arm-auto-merge.sh": "scripts/ci/arm-auto-merge.sh",
        "scripts/trigger-next-queue-automerge.sh": "scripts/trigger-next-queue-automerge.sh",
        "scripts/check-sequential-pr-merge-conflicts.sh": "scripts/check-sequential-pr-merge-conflicts.sh",
        "scripts/tests/forgejo_auto_merge_after_ci.test.sh": "scripts/tests/forgejo_auto_merge_after_ci.test.sh",
        "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh": "scripts/tests/trigger-next-queue-automerge-required-contexts.test.sh",
        "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh": "scripts/tests/trigger-next-queue-automerge-conflict-guard.test.sh",
        "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh": "scripts/tests/check_sequential_pr_merge_conflicts_fetch_remote.test.sh",
        "scripts/tests/phase0_required_context_rollup_check.test.sh": "scripts/tests/phase0_required_context_rollup_check.test.sh",
        "scripts/ci/assert-pr-required-context.py": "scripts/ci/assert-pr-required-context.py",
        "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json": "specs/fixtures/phase0-required-context-rollup/good-oya-ci-required-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json": "specs/fixtures/phase0-required-context-rollup/bad-no-checks-reported.json",
        "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json": "specs/fixtures/phase0-required-context-rollup/bad-missing-oya-ci-required.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-failure.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-completed-failure.json",
        "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json": "specs/fixtures/phase0-required-context-rollup/good-nested-cloud-ci-oya-ci-success.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-missing-producer.json",
        "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json": "specs/fixtures/phase0-required-context-rollup/bad-oya-ci-required-success-untrusted-producer.json",
        "docs/ci/auto-merge-flow.md": "docs/ci/auto-merge-flow.md",
        "docs/ci/forge-of-record.md": "docs/ci/forge-of-record.md",
        "oya/ci-tide/crates/oya-ci-tide-kernel/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-kernel:lib-src",
        "oya/ci-tide/crates/oya-ci-tide-app/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-app:lib-src",
        "oya/ci-tide/crates/oya-ci-tide-forgejo-adapter/src/lib.rs": "//oya/ci-tide/crates/oya-ci-tide-forgejo-adapter:lib-src",
    },
    out = "phase0-auto-merge-after-ci-contract-check.json",
    cmd = "PYTHONDONTWRITEBYTECODE=1 OYA_REPO_ROOT=$PWD python3 scripts/tests/phase0_auto_merge_after_ci_contract_check.py > $OUT",
    visibility = ["PUBLIC"],
)
