rust_library(
    name = "iac-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iac_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iac/core/domain:iac-domain",
    ],
)

rust_test(
    name = "iac-api-iac-app-api",
    srcs = ["tests/iac_app_api.rs"],
    crate = "iac_api_iac_app_api",
    crate_root = "tests/iac_app_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iac-api",
        "//iac/core/domain:iac-domain",
    ],
)
