rust_library(
    name = "oya-identity-workload-oidc-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_identity_workload_oidc_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "third-party//:aws-lc-rs",
        "third-party//:base64",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
