rust_library(
    name = "oya-cloud-iac-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_iac_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
    ],
)

rust_test(
    name = "oya-cloud-iac-rest-cloud-iac-rest",
    srcs = ["tests/cloud_iac_rest.rs"],
    crate = "oya_cloud_iac_rest_cloud_iac_rest",
    crate_root = "tests/cloud_iac_rest.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-iac-rest",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
    ],
)
