rust_library(
    name = "oya-workflow-engine-state-machine-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_state_machine_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-state-machine-domain:oya-workflow-engine-state-machine-domain",
        "//oya/workflow-engine/crates/oya-workflow-engine-state-machine-kernel:oya-workflow-engine-state-machine-kernel",
    ],
)
