rust_library(
    name = "k8s-sla-observability-adapter-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_sla_observability_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/ports/sla-observability-api:k8s-sla-observability-api",
        "//k8s/core/sla-observability-kernel:k8s-sla-observability-kernel",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "k8s-sla-observability-adapter-inmemory-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_sla_observability_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/ports/sla-observability-api:k8s-sla-observability-api",
        "//k8s/core/sla-observability-kernel:k8s-sla-observability-kernel",
        "third-party//:tokio",
    ],
)
