rust_binary(
    name = "oya-governance-predictable-naming-app",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-predictable-naming-kernel:oya-governance-predictable-naming-kernel",
    ],
)
