[package]
name = "oya-governance-predictable-naming-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "oya-governance-predictable-naming-app"
path = "src/main.rs"

[dependencies]
check-predictable-naming-kernel = { path = "../../governance/check/predictable-naming-kernel" }

[lints]
workspace = true
