[package]
name = "storage-provider-object-oci-draft"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
doctest = false

[dependencies]
storage-provider-draft = { path = "../../../ports/draft/provider" }

[lints]
workspace = true
