rust_library(
    name = "iam-identity-workload-svid-operator-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_svid_operator_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/adapters/identity-workload-svid-operator-k8s:iam-identity-workload-svid-operator-k8s",
        "//iam/core/identity-workload-svid-operator-kernel:iam-identity-workload-svid-operator-kernel",
    ],
)

rust_binary(
    name = "iam-svid-operator",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-svid-operator-app",
        "//iam/adapters/identity-workload-svid-operator-k8s:iam-identity-workload-svid-operator-k8s",
        "//iam/core/identity-workload-svid-operator-kernel:iam-identity-workload-svid-operator-kernel",
        "third-party//:kube",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "iam-identity-workload-svid-operator-app-tests",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs"]),
    crate = "iam_identity_workload_svid_operator_app_tests",
    crate_root = "tests/app.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-svid-operator-app",
        "//iam/adapters/identity-workload-svid-operator-k8s:iam-identity-workload-svid-operator-k8s",
        "//iam/core/identity-workload-svid-operator-kernel:iam-identity-workload-svid-operator-kernel",
    ],
)
