rust_library(
    name = "compliance-ediscovery",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_ediscovery",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/retention:compliance-retention",
    ],
)

rust_test(
    name = "compliance-ediscovery-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_ediscovery",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/retention:compliance-retention",
    ],
)
