[package]
name = "oya-platform-regulatory-pack-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-regional-pack-kernel = { path = "../oya-platform-regional-pack-kernel" }
oya-platform-residency-kernel = { path = "../oya-platform-residency-kernel" }

[lib]
name = "oya_platform_regulatory_pack_api"
path = "src/lib.rs"
doctest = false
