[package]
name = "oya-platform-regulatory-pack-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-regional-pack-domain = { path = "../oya-regional-pack-domain" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_platform_regulatory_pack_api"
path = "src/lib.rs"
doctest = false
