rust_library(
    name = "compliance-trust-portal",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_trust_portal",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/dsr:compliance-dsr",
    ],
)

rust_test(
    name = "compliance-trust-portal-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_trust_portal",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/dsr:compliance-dsr",
    ],
)
