rust_library(
    name = "oya-shared-wasm-runtime-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_wasm_runtime_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
