rust_library(
    name = "iam-identity-oidc-issuer-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_oidc_issuer_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-identity-oidc-issuer-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_oidc_issuer_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "iam-identity-oidc-issuer-kernel-oidc-issuer-kernel",
    srcs = ["tests/oidc_issuer_kernel.rs"],
    crate = "iam_identity_oidc_issuer_kernel_oidc_issuer_kernel",
    crate_root = "tests/oidc_issuer_kernel.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-oidc-issuer-kernel",
    ],
)
