[package]
name = "payroll-run-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../../libs/data-boundary-kernel" }
payroll-run-domain = { path = "../../core/run-domain" }

[lib]
name = "payroll_run_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
