[package]
name = "oya-ontology-query-engine-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-ontology-kernel = { path = "../oya-ontology-kernel" }
oya-ontology-query-engine-domain = { path = "../oya-ontology-query-engine-domain" }

[lib]
name = "oya_ontology_query_engine_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
