[package]
name = "shared-protocol-transport-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-protocol-parity-kernel = { path = "../protocol-parity-kernel" }

[lib]
name = "shared_protocol_transport_kernel"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
