rust_library(
    name = "comms-mail-mailbox-grpc",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/core/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-app:comms-mail-mailbox-app",
    ],
)

rust_test(
    name = "comms-mail-mailbox-grpc-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/core/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-app:comms-mail-mailbox-app",
    ],
)
