[package]
name = "comms-mail-mailbox-grpc"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-mail-mailbox-api = { path = "../../ports/mail-mailbox-api" }
comms-mail-mailbox-app = { path = "../../core/mail-mailbox-app" }
oya-shared-postgres-command-kernel = { path = "../../../libs/oya-shared-postgres-command-kernel" }
oya-shared-protocol-transport-kernel = { path = "../../../libs/oya-shared-protocol-transport-kernel" }

[lib]
name = "comms_mail_mailbox_grpc"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
