rust_library(
    name = "oya-shared-transactional-outbox-worker-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_transactional_outbox_worker_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-transactional-outbox-adapter-sqlx:oya-shared-transactional-outbox-adapter-sqlx",
        "//libs/oya-shared-transactional-outbox-dispatch-app:oya-shared-transactional-outbox-dispatch-app",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
    ],
)
