rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_trigger_orchestrator_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-rest:oya-workflow-engine-trigger-orchestrator-rest",
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-sdk:oya-workflow-engine-trigger-orchestrator-sdk",
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-worker:oya-workflow-engine-trigger-orchestrator-worker",
    ],
)
