[package]
name = "oya-workflow-engine-trigger-orchestrator-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-trigger-orchestrator-rest = { path = "../oya-workflow-engine-trigger-orchestrator-rest" }
oya-workflow-engine-trigger-orchestrator-sdk = { path = "../oya-workflow-engine-trigger-orchestrator-sdk" }
oya-workflow-engine-trigger-orchestrator-worker = { path = "../oya-workflow-engine-trigger-orchestrator-worker" }

[lib]
name = "oya_workflow_engine_trigger_orchestrator_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
