rust_library(
    name = "oya-shared-i18n-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_i18n_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-shared-i18n-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_i18n_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-shared-i18n-kernel-coverage",
    srcs = ["tests/coverage.rs"],
    crate = "oya_shared_i18n_kernel_coverage",
    crate_root = "tests/coverage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-shared-i18n-kernel",
    ],
)
