rust_library(
    name = "oya-plant-maintenance-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_plant_maintenance_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-plant-maintenance-domain-plant-maintenance",
    srcs = ["tests/plant_maintenance.rs"],
    crate = "oya_plant_maintenance_domain_plant_maintenance",
    crate_root = "tests/plant_maintenance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-plant-maintenance-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
