[package]
name = "oya-workflow-engine-execution-engine-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-execution-engine-domain = { path = "../oya-workflow-engine-execution-engine-domain" }

[lib]
name = "oya_workflow_engine_execution_engine_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
