[package]
name = "oya-office-collab-gateway-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_office_collab_gateway_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "oya-office-collab-gateway-app"
path = "src/main.rs"

[lints]
workspace = true
