rust_library(
    name = "oya-cloud-iam-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_iam_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/policy/crates/oya-policy-cedar-domain:oya-policy-cedar-domain",
    ],
)

rust_test(
    name = "oya-cloud-iam-app-cedar-policy-bind",
    srcs = ["tests/cedar_policy_bind.rs"],
    crate = "oya_cloud_iam_app_cedar_policy_bind",
    crate_root = "tests/cedar_policy_bind.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-iam-app",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/policy/crates/oya-policy-cedar-domain:oya-policy-cedar-domain",
    ],
)
