rust_library(
    name = "network-vpc",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_vpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "network-vpc-cloud-network-vpc-api",
    srcs = ["tests/cloud_network_vpc_api.rs"],
    crate = "network_vpc_cloud_network_vpc_api",
    crate_root = "tests/cloud_network_vpc_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":network-vpc",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
