[package]
name = "workflow-execution-engine-postgres"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-execution-engine-usecase = { path = "../../core/execution-engine-usecase" }

[lib]
name = "workflow_execution_engine_postgres"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
