_DEPS = [
    "//iam/core/identity-workload-svid-operator-kernel:iam-identity-workload-svid-operator-kernel",
    "//iam/core/identity-workload-svid-kernel:iam-identity-workload-svid-kernel",
    "//iam/core/node-trust-domain:os-trustd-domain",
    "third-party//:base64",
    "third-party//:futures",
    "third-party//:k8s-openapi",
    "third-party//:kube",
    "third-party//:kube-runtime",
    "third-party//:serde_json",
    "third-party//:tokio",
    "third-party//:tracing",
    "third-party//:x509-parser",
]

rust_library(
    name = "iam-identity-workload-svid-operator-k8s",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_svid_operator_k8s",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = _DEPS,
)

rust_test(
    name = "iam-identity-workload-svid-operator-k8s-tests",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs"]),
    crate = "iam_identity_workload_svid_operator_k8s_tests",
    crate_root = "tests/adapter.rs",
    visibility = ["PUBLIC"],
    deps = _DEPS + [
        ":iam-identity-workload-svid-operator-k8s",
    ],
)
