rust_library(
    name = "oya-intelligence-architecture-map-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_architecture_map_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-architecture-map-kernel:oya-intelligence-architecture-map-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-architecture-map-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_architecture_map_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-architecture-map-kernel:oya-intelligence-architecture-map-kernel",
    ],
)
