rust_library(
    name = "oya-accounting-journal-storage-adapter-inmemory",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_accounting_journal_storage_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/accounting/crates/oya-accounting-journal-app:oya-accounting-journal-app",
        "//oya/accounting/crates/oya-accounting-journal-domain:oya-accounting-journal-domain",
    ],
)
