rust_library(
    name = "iam-tenant-rbac-identity-provider-verification",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_identity_provider_verification",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-auth-app:iam-tenant-rbac-auth-app",
    ],
)

rust_test(
    name = "iam-tenant-rbac-identity-provider-verification-identity-provider",
    srcs = ["tests/identity_provider.rs"],
    crate = "iam_tenant_rbac_identity_provider_verification_identity_provider",
    crate_root = "tests/identity_provider.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-identity-provider-verification",
        "//iam/core/tenant-rbac-auth-app:iam-tenant-rbac-auth-app",
    ],
)
