[package]
name = "iam-tenant-rbac-identity-provider-verification"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-auth-app = { path = "../../core/tenant-rbac-auth-app" }

[lib]
name = "iam_tenant_rbac_identity_provider_verification"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
