rust_library(
    name = "billing-finops",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_finops",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "billing-finops-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_finops",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)
