[package]
name = "billing-finops"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
billing-domain = { path = "../billing" }
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../../../compute/core/resource" }
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }
billing-metering = { path = "../metering" }

[lib]
name = "billing_finops"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
