rust_library(
    name = "shared-compliance-evidence-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_compliance_evidence_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "shared-compliance-evidence-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_compliance_evidence_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "shared-compliance-evidence-kernel-coverage-and-dsar",
    srcs = ["tests/coverage_and_dsar.rs"],
    crate = "shared_compliance_evidence_kernel_coverage_and_dsar",
    crate_root = "tests/coverage_and_dsar.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":shared-compliance-evidence-kernel",
    ],
)
