rust_library(
    name = "oya-intelligence-context-aware-retrieval-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_intelligence_context_aware_retrieval_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-context-aware-retrieval-domain:oya-intelligence-context-aware-retrieval-domain",
    ],
)
