rust_library(
    name = "oya-intelligence-dashboard-dry-run-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_dashboard_dry_run_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//oya/intelligence/crates/oya-intelligence-dashboard-kernel:oya-intelligence-dashboard-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-dashboard-dry-run-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_dashboard_dry_run_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//oya/intelligence/crates/oya-intelligence-dashboard-kernel:oya-intelligence-dashboard-kernel",
    ],
)
