rust_library(
    name = "oya-managed-k8s-sla-observability-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_managed_k8s_sla_observability_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-managed-k8s-sla-observability-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_managed_k8s_sla_observability_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-managed-k8s-sla-observability-kernel-mwmb-acceptance",
    srcs = ["tests/mwmb_acceptance.rs"],
    crate = "oya_managed_k8s_sla_observability_kernel_mwmb_acceptance",
    crate_root = "tests/mwmb_acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-managed-k8s-sla-observability-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
