[package]
name = "comms-messenger-stream-grpc"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-messenger-stream-app = { path = "../../core/messenger-stream-app" }
comms-messenger-stream-api = { path = "../../ports/messenger-stream-api" }
shared-postgres-command-kernel = { path = "../../../base/shared-postgres-command-kernel" }
shared-protocol-transport-kernel = { path = "../../core/shared-protocol-transport-kernel" }

[lib]
name = "comms_messenger_stream_grpc"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
