rust_library(
    name = "oya-search-index-inverted-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_search_index_inverted_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/search/crates/oya-search-crawler-domain:oya-search-crawler-domain",
        "//oya/search/crates/oya-search-parser-domain:oya-search-parser-domain",
    ],
)
