rust_library(
    name = "iam-tenant-rbac-disbursement-evidence",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_disbursement_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-tenant-rbac-disbursement-evidence-disbursement",
    srcs = ["tests/disbursement.rs"],
    crate = "iam_tenant_rbac_disbursement_evidence_disbursement",
    crate_root = "tests/disbursement.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-disbursement-evidence",
    ],
)
