rust_library(
    name = "oya-secrets-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_secrets_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "third-party//:zeroize-1",
    ],
)
