rust_test(
    name = "cloud-iam-openapi-parity",
    srcs = glob(["tests/**/*.rs", "openapi/**/*.yaml"]),
    crate = "cloud_iam_openapi_parity",
    crate_root = "tests/openapi_parity.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/ports/cloud-api:iam-cloud-api",
    ],
)
