rust_library(
    name = "network-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "network-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "network-domain-cloud-network-dns-guardrails",
    srcs = ["tests/cloud_network_dns_guardrails.rs"],
    crate = "network_domain_cloud_network_dns_guardrails",
    crate_root = "tests/cloud_network_dns_guardrails.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":network-domain",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
