[package]
name = "network-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../../../compute/core/resource" }

network-residency = { path = "../residency" }

[lib]
name = "network_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
