rust_library(
    name = "workflow-event-bus-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_event_bus_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/ports/event-bus-sdk:workflow-event-bus-sdk",
        "//workflow/ports/event-bus-worker:workflow-event-bus-worker",
    ],
)

rust_test(
    name = "workflow-event-bus-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_event_bus_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/ports/event-bus-sdk:workflow-event-bus-sdk",
        "//workflow/ports/event-bus-worker:workflow-event-bus-worker",
    ],
)
