rust_library(
    name = "oya-intelligence-api-websocket-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_api_websocket_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-api-rest-kernel:oya-intelligence-api-rest-kernel",
        "//oya/intelligence/crates/oya-intelligence-api-websocket-kernel:oya-intelligence-api-websocket-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-api-websocket-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_api_websocket_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-api-rest-kernel:oya-intelligence-api-rest-kernel",
        "//oya/intelligence/crates/oya-intelligence-api-websocket-kernel:oya-intelligence-api-websocket-kernel",
    ],
)
