[package]
name = "oya-foundry-step-adapter-file"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-step-kernel = { path = "../oya-foundry-step-kernel" }
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }

[lib]
name = "oya_foundry_step_adapter_file"
path = "src/lib.rs"
doctest = false
