[package]
name = "community-post-store-adapter-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
oya-shared-postgres-command-kernel = { path = "../../../../libs/oya-shared-postgres-command-kernel" }

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
