[package]
name = "oya-payments-charge-rest"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_payments_charge_rest"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-payments-charge-usecase = { path = "../oya-payments-charge-usecase" }

[lints]
workspace = true
