rust_library(
    name = "iam-identity-workload-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-identity-workload-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "iam-identity-workload-domain-workload-principal-lifecycle",
    srcs = ["tests/workload_principal_lifecycle.rs"],
    crate = "iam_identity_workload_domain_workload_principal_lifecycle",
    crate_root = "tests/workload_principal_lifecycle.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-domain",
    ],
)
