[package]
name = "comms-meet-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../base/data-boundary-kernel" }

[lib]
name = "comms_meet_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
