rust_library(
    name = "os-controllers-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "os_controllers_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/network-domain:os-network-domain",
    ],
)

rust_test(
    name = "os-controllers-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "os_controllers_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/network-domain:os-network-domain",
    ],
)
