rust_library(
    name = "oya-cloud-iam-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_iam_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
