rust_library(
    name = "oya-cloud-intelligence-claude-agent-sdk",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_intelligence_claude_agent_sdk",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
