[package]
name = "governance-adapter-with-no-importer-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "governance-adapter-with-no-importer-app"
path = "src/main.rs"

[dependencies]
governance-adapter-with-no-importer-kernel = { path = "../../libs/governance-adapter-with-no-importer-kernel" }

[lints]
workspace = true
