[package]
name = "oya-saas-plugin-runtime"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-saas-plugin-marketplace = { path = "../oya-saas-plugin-marketplace" }

[lib]
name = "oya_saas_plugin_runtime"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
