rust_library(
    name = "console-workspace-shell-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_workspace_shell_app",
    crate_root = "src/lib.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "console-workspace-shell-app"},
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//console/adapters/workspace-shell-adapter:console-workspace-shell-adapter",
        "//console/ports/workspace-shell-kernel:console-workspace-shell-kernel",
        "//console/facade/workspace-shell-rest:console-workspace-shell-rest",
        "//console/core/workspace-shell-usecase:console-workspace-shell-usecase",
        "third-party//:tokio",
    ],
)

rust_binary(
    name = "console-workspace-shell",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "console-workspace-shell-app"},
    visibility = ["PUBLIC"],
    deps = [
        "//console/facade/workspace-shell-app:console-workspace-shell-app",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//console/adapters/workspace-shell-adapter:console-workspace-shell-adapter",
        "//console/ports/workspace-shell-kernel:console-workspace-shell-kernel",
        "//console/facade/workspace-shell-rest:console-workspace-shell-rest",
        "//console/core/workspace-shell-usecase:console-workspace-shell-usecase",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "console-workspace-shell-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_workspace_shell_app",
    crate_root = "src/lib.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "console-workspace-shell-app"},
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//console/adapters/workspace-shell-adapter:console-workspace-shell-adapter",
        "//console/ports/workspace-shell-kernel:console-workspace-shell-kernel",
        "//console/facade/workspace-shell-rest:console-workspace-shell-rest",
        "//console/core/workspace-shell-usecase:console-workspace-shell-usecase",
        "third-party//:tokio",
    ],
)
