rust_library(
    name = "oya-treasury-cash-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_treasury_cash_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-treasury-cash-domain-cash-position",
    srcs = ["tests/cash_position.rs"],
    crate = "oya_treasury_cash_domain_cash_position",
    crate_root = "tests/cash_position.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-treasury-cash-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-treasury-cash-domain-env-tier-outbound-metadata",
    srcs = ["tests/env_tier_outbound_metadata.rs"],
    crate = "oya_treasury_cash_domain_env_tier_outbound_metadata",
    crate_root = "tests/env_tier_outbound_metadata.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-treasury-cash-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
