rust_library(
    name = "oya-hr-employment-storage-adapter-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_hr_employment_storage_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
    ],
)
