rust_library(
    name = "oya-hr-employment-storage-adapter-inmemory",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_hr_employment_storage_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
    ],
)
