rust_library(
    name = "compute-oci-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_oci_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-oci-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_oci_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)
