rust_library(
    name = "oya-tenant-rbac-slo-evidence",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_slo_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-tenant-rbac-slo-evidence-slo-evidence",
    srcs = ["tests/slo_evidence.rs"],
    crate = "oya_tenant_rbac_slo_evidence_slo_evidence",
    crate_root = "tests/slo_evidence.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-slo-evidence",
    ],
)
