rust_library(
    name = "oya-mail-mailbox-store-adapter-postgres",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_mail_mailbox_store_adapter_postgres",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
    ],
)
