rust_library(
    name = "iam-tenant-rbac-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)

rust_test(
    name = "iam-tenant-rbac-usecase-incident",
    srcs = ["tests/incident.rs"],
    crate = "iam_tenant_rbac_usecase_incident",
    crate_root = "tests/incident.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)

rust_test(
    name = "iam-tenant-rbac-usecase-ops",
    srcs = ["tests/ops.rs"],
    crate = "iam_tenant_rbac_usecase_ops",
    crate_root = "tests/ops.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)

rust_test(
    name = "iam-tenant-rbac-usecase-workflow",
    srcs = ["tests/workflow.rs"],
    crate = "iam_tenant_rbac_usecase_workflow",
    crate_root = "tests/workflow.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)
