[package]
name = "iam-tenant-rbac-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../data/core/boundary-kernel" }
iam-tenant-rbac-domain = { path = "../tenant-rbac-domain" }

[lib]
name = "iam_tenant_rbac_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
