[package]
name = "http-middleware-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
http-router-kernel = { path = "../http-router-kernel" }

[lib]
name = "http_middleware_kernel"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
