rust_library(
    name = "community-post-store-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_post_store_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//base/shared-protocol-parity-kernel:shared-protocol-parity-kernel",
        "//comms/core/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//data/core/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//app/community/adapters/post-store-adapter-postgres:community-post-store-adapter-postgres",
        "//app/community/ports/post-store-api:community-post-store-api",
        "//app/community/core/post-store-domain:community-post-store-domain",
        "//app/community/core/post-store-usecase:community-post-store-usecase",
    ],
)

rust_test(
    name = "community-post-store-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_post_store_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//base/shared-protocol-parity-kernel:shared-protocol-parity-kernel",
        "//comms/core/shared-protocol-transport-kernel:shared-protocol-transport-kernel",
        "//data/core/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//app/community/adapters/post-store-adapter-postgres:community-post-store-adapter-postgres",
        "//app/community/ports/post-store-api:community-post-store-api",
        "//app/community/core/post-store-domain:community-post-store-domain",
        "//app/community/core/post-store-usecase:community-post-store-usecase",
    ],
)
