rust_library(
    name = "oya-cloud-ci-multi-region-disposition-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_ci_multi_region_disposition_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-cloud-ci-multi-region-disposition-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_ci_multi_region_disposition_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-cloud-ci-multi-region-disposition-app-gate",
    srcs = glob(["tests/**/*.rs"]),
    crate = "oya_cloud_ci_multi_region_disposition_app_corpus",
    crate_root = "tests/multi_region_disposition.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-ci-multi-region-disposition-app",
        "third-party//:serde_json",
    ],
)
