rust_library(
    name = "secrets-kms-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_kms_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "secrets-kms-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_kms_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/residency:network-residency",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
