[package]
name = "secrets-kms-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../../../compute/core/resource" }
data-boundary-kernel = { path = "../../../data/core/boundary-kernel" }
network-residency = { path = "../../../network/core/residency" }

[lib]
name = "secrets_kms_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
