rust_library(
    name = "oya-governance-audit-event-emission",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_governance_audit_event_emission",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow",
        "third-party//:serde",
        "third-party//:serde_yaml",
        "third-party//:walkdir",
    ],
)
