[package]
name = "oya-foundry-eval-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-eval-kernel = { path = "../oya-foundry-eval-kernel" }

[lib]
name = "oya_foundry_eval_app"
path = "src/lib.rs"
doctest = false
