rust_library(
    name = "oya-analytics-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_analytics_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
