rust_library(
    name = "oya-itsm-on-call-schedule",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_itsm_on_call_schedule",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
    ],
)
