rust_library(
    name = "cell-regional-pack",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_regional_pack",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "cell-regional-pack-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_regional_pack",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
