[package]
name = "gateway-epic-fhir-connector"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "gateway_epic_fhir_connector"
path = "src/lib.rs"
doctest = false

[dependencies]
shared-connector-kernel = { path = "../../../libs/shared-connector-kernel" }

[lints]
workspace = true
