rust_library(
    name = "intelligence-context-aware-retrieval-worker",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_context_aware_retrieval_worker",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/adapters/context-aware-retrieval-adapter:intelligence-context-aware-retrieval-adapter",
        "//intelligence/core/context-aware-retrieval-usecase:intelligence-context-aware-retrieval-usecase",
    ],
)

rust_test(
    name = "intelligence-context-aware-retrieval-worker-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_context_aware_retrieval_worker",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/adapters/context-aware-retrieval-adapter:intelligence-context-aware-retrieval-adapter",
        "//intelligence/core/context-aware-retrieval-usecase:intelligence-context-aware-retrieval-usecase",
    ],
)
