rust_library(
    name = "oya-check-metric-cardinality",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_metric_cardinality",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
