rust_library(
    name = "oya-cargo-lock-merge-driver-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cargo_lock_merge_driver_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:toml_edit",
    ],
)

rust_binary(
    name = "oya-cargo-lock-merge-driver",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cargo-lock-merge-driver-app",
    ],
)

rust_test(
    name = "oya-cargo-lock-merge-driver-app-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cargo_lock_merge_driver_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:toml_edit",
    ],
)

rust_test(
    name = "oya-cargo-lock-merge-driver-app-fixtures",
    srcs = ["tests/merge_fixtures.rs"],
    crate = "oya_cargo_lock_merge_driver_app_fixtures",
    crate_root = "tests/merge_fixtures.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cargo-lock-merge-driver-app",
    ],
)

rust_test(
    name = "oya-cargo-lock-merge-driver-app-cli-fixtures",
    srcs = ["tests/cli_fixtures.rs"],
    crate = "oya_cargo_lock_merge_driver_app_cli_fixtures",
    crate_root = "tests/cli_fixtures.rs",
    env = {
        "OYA_CARGO_LOCK_MERGE_DRIVER": "$(location :oya-cargo-lock-merge-driver)",
    },
    visibility = ["PUBLIC"],
)
