[package]
name = "oya-intelligence-adapter-gemini-api-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_intelligence_adapter_gemini_api_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-intelligence-account-domain = { path = "../oya-intelligence-account-domain" }
oya-intelligence-adapter-gemini-api-kernel = { path = "../oya-intelligence-adapter-gemini-api-kernel" }

[lints]
workspace = true
