[package]
name = "console-workspace-shell-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
console-workspace-shell-kernel = { path = "../../ports/workspace-shell-kernel" }


[lib]
name = "console_workspace_shell_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
