rust_library(
    name = "application-ontology-card",
    srcs = glob(["src/**/*.rs"]),
    crate = "application_ontology_card",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "application-ontology-card-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "application_ontology_card",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
