rust_library(
    name = "oya-cloud-os-controllers-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_controllers_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
    ],
)

rust_test(
    name = "oya-cloud-os-controllers-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_controllers_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
    ],
)
