[package]
name = "governance-predictable-naming-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "governance-predictable-naming-app"
path = "src/main.rs"

[dependencies]
governance-predictable-naming-kernel = { path = "../../libs/governance-predictable-naming-kernel" }

[lints]
workspace = true
