[package]
name = "oya-workflow-engine-state-machine-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-state-machine-usecase = { path = "../oya-workflow-engine-state-machine-usecase" }
oya-workflow-engine-state-machine-kernel = { path = "../oya-workflow-engine-state-machine-kernel" }

[lib]
name = "oya_workflow_engine_state_machine_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
