rust_library(
    name = "oya-data-sql-adapter-sqlx",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_data_sql_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/sql-kernel:data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
    ],
)

rust_test(
    name = "oya-data-sql-adapter-sqlx-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_data_sql_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/sql-kernel:data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
        "third-party//:tokio",
    ],
)
