apiVersion: v1
kind: Service
metadata:
  name: zitadel
  namespace: identity-{{ .Values.packLabel }}
  labels:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/part-of: identity
    pack: {{ .Values.packLabel | quote }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zitadel
  ports:
    - name: oidc
      port: 8443
      targetPort: oidc
      protocol: TCP
    - name: admin
      port: 8080
      targetPort: admin
      protocol: TCP
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
