[package]
name = "oya-ops-docs-portal-application"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-ops-docs-portal-kernel = { path = "../oya-ops-docs-portal-kernel" }


[lib]
name = "oya_ops_docs_portal_application"
path = "src/lib.rs"
doctest = false
