[package]
name = "workflow-event-bus-postgres"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-event-bus-adapter = { path = "../event-bus-adapter" }

[lib]
name = "workflow_event_bus_postgres"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
