rust_library(
    name = "k8s-sla-observability-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_sla_observability_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/adapters/sla-observability-adapter-inmemory:k8s-sla-observability-adapter-inmemory",
        "//k8s/ports/sla-observability-api:k8s-sla-observability-api",
        "//k8s/core/sla-observability-kernel:k8s-sla-observability-kernel",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "k8s-sla-observability-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_sla_observability_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/adapters/sla-observability-adapter-inmemory:k8s-sla-observability-adapter-inmemory",
        "//k8s/ports/sla-observability-api:k8s-sla-observability-api",
        "//k8s/core/sla-observability-kernel:k8s-sla-observability-kernel",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)
