rust_library(
    name = "iam-tenant-rbac-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//iam/ports/tenant-rbac-api:iam-tenant-rbac-api",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-tenant-rbac-app-runtime",
    srcs = ["tests/runtime.rs"],
    crate = "iam_tenant_rbac_app_runtime",
    crate_root = "tests/runtime.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-app",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//iam/ports/tenant-rbac-api:iam-tenant-rbac-api",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
