[package]
name = "iam-tenant-rbac-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-platform-contracts-kernel = { path = "../../core/platform-contracts-kernel" }
http-runtime-hyper-adapter = { path = "../../../gateway/adapters/http-runtime-hyper" }
http-router-kernel = { path = "../../../gateway/core/http-router-kernel" }
http-middleware-kernel = { path = "../../../gateway/core/http-middleware-kernel" }
iam-tenant-rbac-api = { path = "../../ports/tenant-rbac-api" }
iam-tenant-rbac-usecase = { path = "../../core/tenant-rbac-usecase" }
iam-tenant-rbac-domain = { path = "../../core/tenant-rbac-domain" }





serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
name = "iam_tenant_rbac_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
