rust_binary(
    name = "oya-tenant",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "tenancy-cli"},
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap",
        "third-party//:clap_complete",
    ],
)
