[package]
name = "oya-platform-metering-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }
oya-platform-eventing-kernel = { path = "../oya-platform-eventing-kernel" }
oya-platform-metering-kernel = { path = "../oya-platform-metering-kernel" }

[lib]
name = "oya_platform_metering_app"
path = "src/lib.rs"
doctest = false
