[package]
name = "community-post-store-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
shared-postgres-command-kernel = { path = "../../../../data/core/postgres-command-kernel" }


[lib]
name = "community_post_store_postgres"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
