apiVersion: openslo/v1
kind: SLO
metadata:
  name: lease-contract-success-rate
  labels:
    service: real-estate
    sap_code: "RE-FX"
spec:
  description: "Real Estate lease-contract-success-rate objective; benchmarks SAP RE-FX Flexible Real Estate Management | Oracle Fusion Lease Accounting | Workday Lease Accounting | NetSuite Fixed Assets and lease-accounting counterpart | Microsoft Dynamics 365 Finance Lease Accounting"
  service: real-estate
  indicator:
    metadata:
      name: lease-contract-success-rate-sli
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(oya_real_estate_lease_contract_success_total[5m]))"
        total:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(oya_real_estate_lease_contract_attempt_total[5m]))"
  objectives:
    - displayName: lease-contract-success-rate
      target: 0.999
