[package]
name = "oya-payments-charge-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_payments_charge_app"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-payments-charge-rest = { path = "../oya-payments-charge-rest" }
oya-payments-charge-grpc = { path = "../oya-payments-charge-grpc" }

[lints]
workspace = true
