rust_library(
    name = "comms-mail-mailbox-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/mail-domain:comms-mail-domain",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
    ],
)

rust_test(
    name = "comms-mail-mailbox-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/mail-domain:comms-mail-domain",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
    ],
)
