[package]
name = "comms-mail-mailbox-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-mail-domain = { path = "../mail-domain" }
comms-mail-mailbox-api = { path = "../../ports/mail-mailbox-api" }

[lib]
name = "comms_mail_mailbox_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
