rust_library(
    name = "intelligence-mcp-gateway-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_mcp_gateway_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
    ],
)

rust_test(
    name = "intelligence-mcp-gateway-domain-mcp-gateway",
    srcs = ["tests/mcp_gateway.rs"],
    crate = "intelligence_mcp_gateway_domain_mcp_gateway",
    crate_root = "tests/mcp_gateway.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-mcp-gateway-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
    ],
)
