[package]
name = "oya-observability-tracing-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-observability-domain = { path = "../oya-observability-domain" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lib]
name = "oya_observability_tracing_adapter"
path = "src/lib.rs"
doctest = false
