rust_library(
    name = "oya-workflow-engine-execution-engine-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_execution_engine_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-usecase:oya-workflow-engine-execution-engine-usecase",
    ],
)
