rust_library(
    name = "iam-identity-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "iam-identity-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "iam-identity-domain-credential-revocation",
    srcs = ["tests/credential_revocation.rs"],
    crate = "iam_identity_domain_credential_revocation",
    crate_root = "tests/credential_revocation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-domain",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "iam-identity-domain-sts-credentials",
    srcs = ["tests/sts_credentials.rs"],
    crate = "iam_identity_domain_sts_credentials",
    crate_root = "tests/sts_credentials.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-domain",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)
