rust_library(
    name = "oya-shared-transactional-outbox-runtime-tokio-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_transactional_outbox_runtime_tokio_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//libs/oya-shared-transactional-outbox-poller-app:oya-shared-transactional-outbox-poller-app",
        "//libs/oya-shared-transactional-outbox-worker-app:oya-shared-transactional-outbox-worker-app",
        "third-party//:tokio-1",
    ],
)
