rust_library(
    name = "oya-shared-transactional-outbox-runtime-tokio-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_transactional_outbox_runtime_tokio_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//data/core/shared-transactional-outbox-poller-app:shared-transactional-outbox-poller-app",
        "//data/core/shared-transactional-outbox-worker-app:shared-transactional-outbox-worker-app",
        "third-party//:tokio",
    ],
)
