[package]
name = "oya-shared-transactional-outbox-runtime-tokio-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-transactional-outbox-kernel = { path = "../../data/core/shared-transactional-outbox-kernel" }
shared-transactional-outbox-poller-app = { path = "../../data/core/shared-transactional-outbox-poller-app" }
shared-transactional-outbox-worker-app = { path = "../../data/core/shared-transactional-outbox-worker-app" }
tokio = { workspace = true, features = ["time"] }

[lib]
name = "oya_shared_transactional_outbox_runtime_tokio_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
