rust_library(
    name = "check-tenant-cost-labels-coverage",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_tenant_cost_labels_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "check-tenant-cost-labels-coverage-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_tenant_cost_labels_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
