apiVersion: v1
kind: ServiceAccount
metadata:
  name: oya-docs
  namespace: docs
  annotations:
    openbao.io/role: oya-docs
    spiffe.io/identity: spiffe://oyatie.dev/ns/docs/sa/oya-docs
  labels:
    oyatie.dev/microservice: docs
