use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let source = manifest_dir.join("src/items");
    println!("cargo:rerun-if-changed={}", source.display());
    concatenate_rust_items(
        &source,
        &PathBuf::from(std::env::var("OUT_DIR")?).join("lib.generated.rs"),
    )
}

fn concatenate_rust_items(source: &Path, output: &Path) -> Result<(), Box<dyn Error>> {
    let mut paths = fs::read_dir(source)?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<Vec<_>, _>>()?;
    paths.retain(|path| path.extension().is_some_and(|extension| extension == "rs"));
    paths.sort();
    let mut generated = String::from("// @generated by build.rs; do not edit.\n");
    for path in paths {
        generated.push_str(&fs::read_to_string(path)?);
        if !generated.ends_with('\n') {
            generated.push('\n');
        }
    }
    fs::write(output, generated)?;
    Ok(())
}
