[package]
name = "oya-cloud-region-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cell-domain = { path = "../oya-cell-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_region_domain"
path = "src/lib.rs"
doctest = false
