rust_library(
    name = "oya-cloud-observability-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_observability_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//cloud/cloud-observability/crates/oya-cloud-observability-domain:oya-cloud-observability-domain",
    ],
)

rust_test(
    name = "oya-cloud-observability-api-cloud-observability-audit-api",
    srcs = ["tests/cloud_observability_audit_api.rs"],
    crate = "oya_cloud_observability_api_cloud_observability_audit_api",
    crate_root = "tests/cloud_observability_audit_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-observability-api",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//cloud/cloud-observability/crates/oya-cloud-observability-domain:oya-cloud-observability-domain",
    ],
)
