rust_library(
    name = "data-ontology-scorecards-resolver",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_ontology_scorecards_resolver",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_binary(
    name = "data-ontology-scorecards-resolver-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/facade/ontology-scorecards-resolver:data-ontology-scorecards-resolver",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "data-ontology-scorecards-resolver-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_ontology_scorecards_resolver",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
