[package]
name = "data-ontology-scorecards-resolver"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"
default-run = "data-ontology-scorecards-resolver"

[lib]
name = "data_ontology_scorecards_resolver"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "data-ontology-scorecards-resolver"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }

[lints]
workspace = true
