rust_library(
    name = "oya-contact-center-voice-routing-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_contact_center_voice_routing_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-contact-center-voice-routing",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/contact-center/crates/oya-contact-center-voice-routing-app:oya-contact-center-voice-routing-app",
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
