rust_library(
    name = "oya-contact-center-voice-routing-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_contact_center_voice_routing_app",
    crate_root = "src/lib.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "oya-contact-center-voice-routing-app"},
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-contact-center-voice-routing",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "oya-contact-center-voice-routing-app"},
    visibility = ["PUBLIC"],
    deps = [
        "//oya/contact-center/crates/oya-contact-center-voice-routing-app:oya-contact-center-voice-routing-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "oya-contact-center-voice-routing-app-integration",
    srcs = ["tests/integration.rs"],
    crate = "oya_contact_center_voice_routing_app_integration",
    crate_root = "tests/integration.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-contact-center-voice-routing-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
