[package]
name = "oya-cloud-billing-application"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-billing-domain = { path = "../oya-cloud-billing-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-eventing-domain = { path = "../oya-eventing-domain" }
oya-metering-domain = { path = "../oya-metering-domain" }

[lib]
name = "oya_cloud_billing_application"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
