[package]
name = "pipeline-repository-git"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
pipeline-repository = { path = "../../ports/repository" }
sha1-checked.workspace = true
sha2.workspace = true

[lints]
workspace = true
