rust_binary(
    name = "oya-xtask-metadata-augment",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow",
        "third-party//:clap",
        "third-party//:serde_json",
        "third-party//:tempfile",
        "third-party//:toml_edit",
    ],
)
