rust_library(
    name = "tenancy-tenant-lifecycle-authz-port",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_authz_port",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)

rust_test(
    name = "tenancy-tenant-lifecycle-authz-port-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_authz_port",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)
