rust_library(
    name = "iam-policy-cedar-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_policy_cedar_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//policy/core/cedar-domain:policy-cedar-domain",
    ],
)
