rust_binary(
    name = "governance-sunset-lifecycle-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/governance-sunset-lifecycle-kernel:governance-sunset-lifecycle-kernel",
        "third-party//:tempfile",
    ],
)
