rust_library(
    name = "oya-shared-outbox-broker-http-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_outbox_broker_http_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-transactional-outbox-dispatch-app:oya-shared-transactional-outbox-dispatch-app",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
    ],
)
