[package]
name = "oya-shared-outbox-broker-http-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
shared-transactional-outbox-dispatch-app = { path = "../../data/core/shared-transactional-outbox-dispatch-app" }

[dev-dependencies]
shared-transactional-outbox-kernel = { path = "../../data/core/shared-transactional-outbox-kernel" }

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
