rust_library(
    name = "billing-metering-pipeline-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_metering_pipeline_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "billing-metering-pipeline-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_metering_pipeline_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "billing-metering-pipeline-kernel-conformance",
    srcs = glob(["tests/**/*.rs"]),
    crate = "billing_metering_pipeline_kernel_conformance",
    crate_root = "tests/reference_sink.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-metering-pipeline-kernel",
    ],
)
