rust_library(
    name = "oya-intelligence-rag-endpoint-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_rag_endpoint_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
        "//intelligence/core/rag-endpoint-domain:intelligence-rag-endpoint-domain",
        "//oya/intelligence/crates/oya-intelligence-rag-endpoint-kernel:oya-intelligence-rag-endpoint-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-rag-endpoint-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_rag_endpoint_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
        "//intelligence/core/rag-endpoint-domain:intelligence-rag-endpoint-domain",
        "//oya/intelligence/crates/oya-intelligence-rag-endpoint-kernel:oya-intelligence-rag-endpoint-kernel",
    ],
)
