[package]
name = "foundry-records-sqlite-draft"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
foundry-records-draft = { path = "../../../ports/draft/records" }
rusqlite = { workspace = true }

[lints]
workspace = true
