rust_library(
    name = "os-init-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "os_init_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/block-domain:os-block-domain",
        "//os/core/controllers-domain:os-controllers-domain",
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/machined-domain:os-machined-domain",
        "//os/core/network-domain:os-network-domain",
        "//os/core/platform-domain:os-platform-domain",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_binary(
    name = "oya-cloud-os-init-app-init-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":os-init-app",
        "//os/core/block-domain:os-block-domain",
        "//os/core/controllers-domain:os-controllers-domain",
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/machined-domain:os-machined-domain",
        "//os/core/network-domain:os-network-domain",
        "//os/core/platform-domain:os-platform-domain",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_binary(
    name = "oya-cloud-os-init-app-svc-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/svc.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":os-init-app",
        "//os/core/block-domain:os-block-domain",
        "//os/core/controllers-domain:os-controllers-domain",
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/machined-domain:os-machined-domain",
        "//os/core/network-domain:os-network-domain",
        "//os/core/platform-domain:os-platform-domain",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_test(
    name = "os-init-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "os_init_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/block-domain:os-block-domain",
        "//os/core/controllers-domain:os-controllers-domain",
        "//os/core/cosi-domain:os-cosi-domain",
        "//os/core/kernel:os-kernel",
        "//os/core/machine-config-domain:os-machine-config-domain",
        "//os/core/machined-domain:os-machined-domain",
        "//os/core/network-domain:os-network-domain",
        "//os/core/platform-domain:os-platform-domain",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
        "third-party//:libc",
    ],
)
