rust_library(
    name = "oya-check-tenant-cost-labels-coverage",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_check_tenant_cost_labels_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
