rust_library(
    name = "storage-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//base/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "storage-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//base/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "storage-domain-cloud-storage-foundation",
    srcs = ["tests/cloud_storage_foundation.rs"],
    crate = "storage_domain_cloud_storage_foundation",
    crate_root = "tests/cloud_storage_foundation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":storage-domain",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//base/data-boundary-kernel:data-boundary-kernel",
    ],
)
