use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const SOURCES: &[(&str, &str)] = &[
    ("src/items", "domain.generated.rs"),
    ("src/cas_items", "cas.generated.rs"),
    ("src/test_items", "domain_tests.generated.rs"),
    ("src/cas_test_items", "cas_tests.generated.rs"),
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);

    for (source, output) in SOURCES {
        let source = manifest_dir.join(source);
        println!("cargo:rerun-if-changed={}", source.display());
        concatenate_rust_items(&source, &out_dir.join(output))?;
    }

    Ok(())
}

fn concatenate_rust_items(source: &Path, output: &Path) -> Result<(), Box<dyn Error>> {
    let mut paths = fs::read_dir(source)?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<Vec<_>, _>>()?;
    paths.retain(|path| path.extension().is_some_and(|extension| extension == "rs"));
    paths.sort();

    let mut generated = String::from("// @generated by build.rs; do not edit.\n");
    for path in paths {
        generated.push_str(&fs::read_to_string(path)?);
        if !generated.ends_with('\n') {
            generated.push('\n');
        }
    }
    fs::write(output, generated)?;
    Ok(())
}
