[package]
name = "storage-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-kms-domain = { path = "../../../cloud/cloud-kms/crates/oya-cloud-kms-domain" }
oya-cloud-region-domain = { path = "../../../cloud/cloud-cell/crates/oya-cloud-region-domain" }
compute-resource = { path = "../../../compute/core/resource" }
oya-data-boundary-kernel = { path = "../../../libs/oya-data-boundary-kernel" }
oya-residency-domain = { path = "../../../cloud/cloud-network/crates/oya-residency-domain" }

[lib]
name = "storage_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
