[package]
name = "storage-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
blake3 = "1.8.5"
data-classification = { path = "../../../data/ports/classification" }
secrets-kms-domain = { path = "../../../secrets/core/kms-domain" }
cell-location = { path = "../../../cell/ports/location" }
compute-resource = { path = "../../../compute/core/resource" }

network-residency = { path = "../../../network/core/residency" }
storage-provider-draft = { path = "../../ports/draft/provider" }

[lib]
doctest = false

[lints]
workspace = true
