rust_binary(
    name = "shared-architecture-check-cli",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "shared-architecture-check-cli"},
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow",
        "third-party//:clap",
    ],
)
