rust_library(
    name = "compute-vm-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_vm_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-vm-api-cloud-compute-vm-api",
    srcs = ["tests/cloud_compute_vm_api.rs"],
    crate = "compute_vm_api_cloud_compute_vm_api",
    crate_root = "tests/cloud_compute_vm_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":compute-vm-api",
        "//compute/core/domain:compute-domain",
        "//compute/core/resource:compute-resource",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
