rust_library(
    name = "oya-cloud-compute-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_compute_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-compute/crates/oya-cloud-resource-domain:oya-cloud-resource-domain",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-compute-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_compute_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-compute/crates/oya-cloud-resource-domain:oya-cloud-resource-domain",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-compute-domain-cloud-compute-foundation",
    srcs = ["tests/cloud_compute_foundation.rs"],
    crate = "oya_cloud_compute_domain_cloud_compute_foundation",
    crate_root = "tests/cloud_compute_foundation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-compute-domain",
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-compute/crates/oya-cloud-resource-domain:oya-cloud-resource-domain",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
