rust_library(
    name = "oya-intelligence-credential-resolver-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_credential_resolver_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
