[package]
name = "oya-cloud-billing-tax-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-billing-kernel = { path = "../oya-cloud-billing-kernel" }
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }
oya-platform-metering-kernel = { path = "../oya-platform-metering-kernel" }

[lib]
name = "oya_cloud_billing_tax_app"
path = "src/lib.rs"
doctest = false
