rust_library(
    name = "iac-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iac_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iac/core/api:iac-api",
        "//iac/core/domain:iac-domain",
        "//iac/ports/rest:iac-rest",
        "//base/http-middleware-kernel:http-middleware-kernel",
        "//base/http-router-kernel:http-router-kernel",
        "//base/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
    ],
)

rust_test(
    name = "iac-infrastructure-cloud-iac-infrastructure",
    srcs = ["tests/cloud_iac_infrastructure.rs"],
    crate = "iac_infrastructure_cloud_iac_infrastructure",
    crate_root = "tests/cloud_iac_infrastructure.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iac-infrastructure",
        "//iac/core/api:iac-api",
        "//iac/core/domain:iac-domain",
        "//iac/ports/rest:iac-rest",
        "//base/http-middleware-kernel:http-middleware-kernel",
        "//base/http-router-kernel:http-router-kernel",
        "//base/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
    ],
)
