[package]
name = "iac-infrastructure"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iac-api = { path = "../../core/api" }
iac-domain = { path = "../../core/domain" }
iac-rest = { path = "../../ports/rest" }
http-middleware-kernel = { path = "../../../libs/http-middleware-kernel" }
http-router-kernel = { path = "../../../libs/http-router-kernel" }
http-runtime-hyper-adapter = { path = "../../../libs/http-runtime-hyper-adapter" }

[lib]
name = "iac_infrastructure"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
