rust_library(
    name = "intelligence-eventsink-valkey-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_eventsink_valkey_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/kernel:intelligence-kernel",
        "third-party//:redis",
        "third-party//:serde",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)

rust_test(
    name = "intelligence-eventsink-valkey-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_eventsink_valkey_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/kernel:intelligence-kernel",
        "third-party//:redis",
        "third-party//:serde",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)
