rust_library(
    name = "cell-bind-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_bind_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "cell-bind-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_bind_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "cell-bind-api-cloud-cell-bind-api",
    srcs = ["tests/cloud_cell_bind_api.rs"],
    crate = "cell_bind_api_cloud_cell_bind_api",
    crate_root = "tests/cloud_cell_bind_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":cell-bind-api",
    ],
)
