[package]
name = "gateway-gusto-connector"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "gateway_gusto_connector"
path = "src/lib.rs"
doctest = false

[dependencies]
shared-connector-kernel = { path = "../../core/shared-connector-kernel" }

[lints]
workspace = true
