rust_library(
    name = "oya-analytics-tenant-bootstrap-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_analytics_tenant_bootstrap_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-analytics-tenant-bootstrap",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/analytics/crates/oya-analytics-tenant-bootstrap-app:oya-analytics-tenant-bootstrap-app",
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
