[package]
name = "comms-messenger-stream-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-messenger-stream-postgres = { path = "../../adapters/messenger-stream-postgres" }
comms-messenger-stream-api = { path = "../../ports/messenger-stream-api" }
comms-messenger-stream-usecase = { path = "../messenger-stream-usecase" }
oya-shared-postgres-command-kernel = { path = "../../../libs/oya-shared-postgres-command-kernel" }
oya-shared-protocol-parity-kernel = { path = "../../../libs/oya-shared-protocol-parity-kernel" }
oya-shared-protocol-transport-kernel = { path = "../../../libs/oya-shared-protocol-transport-kernel" }
oya-shared-transactional-outbox-kernel = { path = "../../../libs/oya-shared-transactional-outbox-kernel" }

[lib]
name = "comms_messenger_stream_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
