rust_library(
    name = "oya-workspace-forms-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workspace_forms_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/forms/crates/oya-forms-domain:oya-forms-domain",
    ],
)
