rust_library(
    name = "oya-cloud-region-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_region_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
    ],
)
