rust_library(
    name = "intelligence-context-aware-retrieval-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_context_aware_retrieval_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/context-aware-retrieval-kernel:intelligence-context-aware-retrieval-kernel",
    ],
)

rust_test(
    name = "intelligence-context-aware-retrieval-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_context_aware_retrieval_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/context-aware-retrieval-kernel:intelligence-context-aware-retrieval-kernel",
    ],
)
