#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::{self, Read};
use std::path::PathBuf;
use std::process::ExitCode;

use serde_json::Value;

use ci_generated_artifact_policy::generated_output_diff_policy_violations_with_ratchet_context;

/// De-committed face materialized by `oya-cloud-ci-materialize-generated-faces-bin`
/// (`materialize_ratchet_merge_base_contents`): declared `normal-source-merge` artifact path ->
/// its content at the merge-base. HERMETIC: this gate never calls git itself
/// (ci-gate-self-conformance forbids subprocess/network/clock/randomness primitives in gate
/// production code) — the materializer owns the one sanctioned git boundary (a merge-base
/// worktree checkout) and this gate only reads the resulting plain JSON file.
const RATCHET_MERGE_BASE_FACE: &str =
    "ci/facade/generated-artifact-policy/ratchet-merge-base.generated.json";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(code) => code,
    }
}

struct Args {
    manifest_path: String,
    repo_root: PathBuf,
}

fn run() -> Result<(), ExitCode> {
    let args = parse_args()?;
    let manifest_bytes = fs::read(&args.manifest_path).map_err(|error| {
        eprintln!(
            "generated-output-diff-policy: read {}: {error}",
            args.manifest_path
        );
        ExitCode::from(2)
    })?;
    let manifest: Value = serde_json::from_slice(&manifest_bytes).map_err(|error| {
        eprintln!(
            "generated-output-diff-policy: parse {}: {error}",
            args.manifest_path
        );
        ExitCode::from(2)
    })?;

    let mut diff_name_status = String::new();
    io::stdin()
        .read_to_string(&mut diff_name_status)
        .map_err(|error| {
            eprintln!("generated-output-diff-policy: read diff-name-status stdin: {error}");
            ExitCode::from(2)
        })?;

    // Ratchet context: merge-base content of every normal-source-merge declared artifact (read
    // from the materialized face — see RATCHET_MERGE_BASE_FACE doc), paired with the current
    // candidate content (a plain fs read), so a hand-curated-ratchet baseline's plain modify can
    // be verified against shrink-only/move-plan-relabel, never blanket-allowed. Plus the anti-
    // laundering move-plan crate-dir pairs read from the materialized move-manifest — the SAME
    // rename-aware-relabel face (ADR-0563), byte-bound to the actual candidate-tree move, not a
    // bare claim in a hand-authored plan file.
    let ratchet_contents = collect_ratchet_contents(&args, &manifest);
    let move_plan_pairs = read_move_manifest_crate_dirs(&args.repo_root);

    let (manifest_findings, violations) =
        generated_output_diff_policy_violations_with_ratchet_context(
            &manifest,
            &diff_name_status,
            &ratchet_contents,
            &move_plan_pairs,
        );
    if !manifest_findings.is_empty() {
        eprintln!("generated-output-diff-policy: manifest is not policy-valid:");
        for finding in manifest_findings {
            eprintln!("  {} {}", finding.code, finding.key);
        }
        return Err(ExitCode::from(2));
    }

    if !violations.is_empty() {
        eprintln!(
            "Generated outputs are regenerated by cloud-ci and must not be PR merge surfaces:"
        );
        for violation in violations {
            eprintln!("  {} {}", violation.status, violation.path);
        }
        eprintln!(
            "Delete obsolete generated outputs or change canonical sources/generators instead. \
             A hand-curated-ratchet baseline (normal-source-merge) may ONLY shrink debt or apply \
             a move-plan-backed key substitution (see specs/reorg/move-manifest.generated.json). \
             If ratchet-merge-base.generated.json is stale/missing, re-run: \
             buck2 run //ci/facade/generated-artifact-freshness:oya-cloud-ci-materialize-generated-faces-bin -- --repo-root ."
        );
        return Err(ExitCode::FAILURE);
    }

    println!("generated-output-diff-policy: no non-deletion generated output edits.");
    Ok(())
}

/// Pair each declared `normal-source-merge` artifact's merge-base content (from the materialized
/// [`RATCHET_MERGE_BASE_FACE`]) with its current candidate content (a plain fs read). A path
/// missing either side (not in the face — e.g. brand new at merge-base — or unreadable on disk)
/// is simply omitted; the gate then fails closed on it (no verifiable evidence, no exemption).
fn collect_ratchet_contents(args: &Args, manifest: &Value) -> BTreeMap<String, (String, String)> {
    let mut out = BTreeMap::new();
    let Some(artifacts) = manifest.get("artifacts").and_then(Value::as_array) else {
        return out;
    };
    let normal_source_merge_paths: Vec<&str> = artifacts
        .iter()
        .filter(|a| a.get("merge_policy").and_then(Value::as_str) == Some("normal-source-merge"))
        .filter_map(|a| a.get("path").and_then(Value::as_str))
        .collect();
    if normal_source_merge_paths.is_empty() {
        return out;
    }

    let face_path = args.repo_root.join(RATCHET_MERGE_BASE_FACE);
    let Ok(face_text) = fs::read_to_string(&face_path) else {
        return out;
    };
    let Ok(face) = serde_json::from_str::<Value>(&face_text) else {
        return out;
    };
    for path in normal_source_merge_paths {
        let Some(merge_base_content) = face.get(path).and_then(Value::as_str) else {
            continue;
        };
        let Ok(candidate) = fs::read_to_string(args.repo_root.join(path)) else {
            continue;
        };
        out.insert(path.to_owned(), (merge_base_content.to_owned(), candidate));
    }
    out
}

/// The anti-laundering-verified crate-dir `(old_path, new_path)` pairs from the materialized
/// move-manifest (`specs/reorg/move-manifest.generated.json`, ADR-0563) — regenerated by
/// `oya-cloud-ci-materialize-generated-faces-bin` from the SINGLE committed move-plan, ONLY
/// emitted for a move that actually landed in the candidate tree (byte-bound, not a bare claim
/// in a hand-authored plan file). Missing/malformed face -> empty (fail-closed: no pairs to
/// authenticate a substitution against).
fn read_move_manifest_crate_dirs(repo_root: &std::path::Path) -> Vec<(String, String)> {
    let path = repo_root.join("specs/reorg/move-manifest.generated.json");
    let Ok(text) = fs::read_to_string(&path) else {
        return Vec::new();
    };
    let Ok(value) = serde_json::from_str::<Value>(&text) else {
        return Vec::new();
    };
    value
        .get("crate_dirs")
        .and_then(Value::as_array)
        .map(|rows| {
            rows.iter()
                .filter_map(|row| {
                    let old = row.get("old_path")?.as_str()?.to_owned();
                    let new = row.get("new_path")?.as_str()?.to_owned();
                    Some((old, new))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn parse_args() -> Result<Args, ExitCode> {
    let mut args = env::args().skip(1);
    let mut manifest_path = None;
    let mut repo_root = PathBuf::from(".");
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--manifest" => {
                manifest_path = args.next();
            }
            "--repo-root" => {
                if let Some(value) = args.next() {
                    repo_root = PathBuf::from(value);
                }
            }
            "--help" | "-h" => {
                println!(
                    "usage: oya-cloud-ci-generated-output-diff-policy --manifest <path> \
                     [--repo-root <path>] < diff-name-status.tsv"
                );
                return Err(ExitCode::SUCCESS);
            }
            other => {
                eprintln!("generated-output-diff-policy: unknown argument {other}");
                return Err(ExitCode::from(2));
            }
        }
    }
    let manifest_path = manifest_path.ok_or_else(|| {
        eprintln!("generated-output-diff-policy: --manifest is required");
        ExitCode::from(2)
    })?;
    Ok(Args {
        manifest_path,
        repo_root,
    })
}
