rust_library(
    name = "oya-observability-tracing-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_observability_tracing_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/observability/crates/oya-observability-domain:oya-observability-domain",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
