rust_library(
    name = "compliance-retention",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_retention",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "compliance-retention-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_retention",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)
