rust_library(
    name = "iam-tenant-rbac-tenant-image-provenance-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_image_provenance_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "iam-tenant-rbac-tenant-image-provenance-contract-image-provenance",
    srcs = ["tests/image_provenance.rs"],
    crate = "iam_tenant_rbac_tenant_image_provenance_contract_image_provenance",
    crate_root = "tests/image_provenance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-image-provenance-contract",
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)
