rust_library(
    name = "oya-production-planning-mrp-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_production_planning_mrp_app",
    crate_root = "src/lib.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "oya-production-planning-mrp-app"},
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-production-planning-mrp",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "oya-production-planning-mrp-app"},
    visibility = ["PUBLIC"],
    deps = [
        "//oya/production-planning/crates/oya-production-planning-mrp-app:oya-production-planning-mrp-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "oya-production-planning-mrp-app-integration",
    srcs = ["tests/integration.rs"],
    crate = "oya_production_planning_mrp_app_integration",
    crate_root = "tests/integration.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-production-planning-mrp-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
