rust_library(
    name = "oya-workflow-engine-execution-engine-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_execution_engine_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
