rust_library(
    name = "oya-check-realtime-transport-tier",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_realtime_transport_tier",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-realtime-transport-kernel:oya-shared-realtime-transport-kernel",
    ],
)
