rust_library(
    name = "oya-analytics-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_analytics_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-api:oya-analytics-api",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-analytics-app",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/analytics/crates/oya-analytics-app:oya-analytics-app",
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-api:oya-analytics-api",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
