rust_library(
    name = "oya-analytics-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_analytics_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-api:oya-analytics-api",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-analytics-app-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/analytics/crates/oya-analytics-app:oya-analytics-app",
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-api:oya-analytics-api",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "oya-analytics-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_analytics_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//oya/analytics/crates/oya-analytics-api:oya-analytics-api",
        "//oya/analytics/crates/oya-analytics-domain:oya-analytics-domain",
        "//oya/analytics/crates/oya-analytics-usecase:oya-analytics-usecase",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
