rust_library(
    name = "data-boundary-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "data_boundary_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "data-boundary-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "data_boundary_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
