rust_library(
    name = "bus-outbox-file",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "bus_outbox_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//bus/core/domain:messaging-domain",
    ],
)

rust_test(
    name = "bus-outbox-file-file-outbox",
    srcs = ["tests/file_outbox.rs"],
    crate = "bus_outbox_file_file_outbox",
    crate_root = "tests/file_outbox.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":bus-outbox-file",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//bus/core/domain:messaging-domain",
    ],
)
