[package]
name = "data-ontology-query-engine-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }
data-ontology-kernel = { path = "../ontology-kernel" }
data-ontology-query-engine-domain = { path = "../ontology-query-engine-domain" }

[lib]
name = "data_ontology_query_engine_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
