rust_library(
    name = "oya-payments-kyc-kyb-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_payments_kyc_kyb_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/payments/crates/oya-payments-charge-kernel:oya-payments-charge-kernel",
        "//oya/payments/crates/oya-payments-kyc-kyb-domain:oya-payments-kyc-kyb-domain",
    ],
)
