rust_library(
    name = "oya-cloud-intelligence-eventsink-clickhouse-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_cloud_intelligence_eventsink_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-intelligence/crates/oya-cloud-intelligence-kernel:oya-cloud-intelligence-kernel",
        "//libs/oya-shared-olap-clickhouse-adapter:oya-shared-olap-clickhouse-adapter",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "third-party//:serde",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)
