[package]
name = "kernel-asterinas-abi-matrix"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "kernel_asterinas_abi_matrix"
path = "src/lib.rs"

[dependencies]
kernel-asterinas-boundary = { path = "../asterinas-boundary" }
serde_json = "1"
