rust_binary(
    name = "mail-parity-app-bin",
    srcs = glob(["src/**/*.rs"]),
    crate = "mail_parity_app",
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:reqwest",
        "third-party//:sha2",
    ],
)

rust_test(
    name = "mail-parity-app-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "mail_parity_app",
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:reqwest",
        "third-party//:sha2",
    ],
)

rust_test(
    name = "mail-parity-app-cli",
    srcs = ["tests/cli.rs"],
    crate = "cli",
    crate_root = "tests/cli.rs",
    env = {"MAIL_PARITY_BINARY": "$(location :mail-parity-app-bin)"},
    deps = ["third-party//:serde_json", "third-party//:tempfile"],
)
