[package]
name = "flags-server"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[[bin]]
name = "oya-flags"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
flags-evaluation-domain = { path = "../evaluation-domain" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
