[package]
name = "intelligence-run-file-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
intelligence-capability-domain = { path = "../../core/capability-domain" }
intelligence-run-domain = { path = "../../core/run-domain" }


[lib]
name = "intelligence_run_file_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
