rust_library(
    name = "corpus-core",
    srcs = glob(["src/**/*.rs", "**/*.json"]),
    crate = "corpus_core",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:blake3",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "corpus-core-unittest",
    srcs = glob(["src/**/*.rs", "**/*.json"]),
    crate = "corpus_core",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:blake3",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
