[package]
name = "calendar-event-memory"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
calendar-event-api = { path = "../../ports/event-api" }
calendar-event-domain = { path = "../../core/event-domain" }

[dev-dependencies]
calendar-event-usecase = { path = "../../core/event-usecase" }

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
