rust_binary(
    name = "oya-shared-architecture-check-cli",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow",
        "third-party//:clap",
    ],
)
