rust_library(
    name = "billing-finops-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_finops_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//billing/core/finops:billing-finops",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "billing-finops-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_finops_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//billing/core/finops:billing-finops",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "billing-finops-api-cloud-finops-report-api",
    srcs = ["tests/cloud_finops_report_api.rs"],
    crate = "billing_finops_api_cloud_finops_report_api",
    crate_root = "tests/cloud_finops_report_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-finops-api",
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//billing/core/finops:billing-finops",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
