rust_library(
    name = "oya-tenant-rbac-listener-gateway",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_listener_gateway",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-auth-app:oya-tenant-rbac-auth-app",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-cloud-deployment-manifest:oya-tenant-rbac-cloud-deployment-manifest",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-local-runtime-composition:oya-tenant-rbac-local-runtime-composition",
    ],
)

rust_test(
    name = "oya-tenant-rbac-listener-gateway-listener-gateway",
    srcs = ["tests/listener_gateway.rs"],
    crate = "oya_tenant_rbac_listener_gateway_listener_gateway",
    crate_root = "tests/listener_gateway.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-listener-gateway",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-auth-app:oya-tenant-rbac-auth-app",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-cloud-deployment-manifest:oya-tenant-rbac-cloud-deployment-manifest",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-local-runtime-composition:oya-tenant-rbac-local-runtime-composition",
    ],
)
