[package]
name = "oya-tenant-rbac-listener-gateway"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-tenant-rbac-auth-app = { path = "../oya-tenant-rbac-auth-app" }
oya-tenant-rbac-cloud-deployment-manifest = { path = "../oya-tenant-rbac-cloud-deployment-manifest" }
oya-tenant-rbac-local-runtime-composition = { path = "../oya-tenant-rbac-local-runtime-composition" }

[lib]
name = "oya_tenant_rbac_listener_gateway"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
