rust_library(
    name = "oya-workflow-studio-dsl-loader-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_studio_dsl_loader_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-studio/crates/oya-workflow-studio-dsl-emitter-domain:oya-workflow-studio-dsl-emitter-domain",
        "third-party//:serde_json",
    ],
)
