rust_library(
    name = "oya-workflow-studio-dsl-loader-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_studio_dsl_loader_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-studio/crates/oya-workflow-studio-dsl-emitter-domain:oya-workflow-studio-dsl-emitter-domain",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-workflow-studio-dsl-loader-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_studio_dsl_loader_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-studio/crates/oya-workflow-studio-dsl-emitter-domain:oya-workflow-studio-dsl-emitter-domain",
        "third-party//:serde_json",
    ],
)
