rust_library(
    name = "billing-accounting-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_accounting_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/accounting-app:billing-accounting-app",
        "//billing/core/accounting-journal:billing-accounting-journal",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "billing-accounting-api-contracts",
    srcs = ["tests/contracts.rs"],
    crate = "billing_accounting_api_contracts",
    crate_root = "tests/contracts.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-accounting-api",
        "//billing/core/accounting-app:billing-accounting-app",
        "//billing/core/accounting-journal:billing-accounting-journal",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
