rust_library(
    name = "oya-intelligence-cli-session-driver",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_cli_session_driver",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//intelligence/core/supervisor-kernel:intelligence-supervisor-kernel",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "oya-intelligence-cli-session-driver-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_cli_session_driver",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//intelligence/core/supervisor-kernel:intelligence-supervisor-kernel",
        "third-party//:tokio",
    ],
)
