rust_library(
    name = "tenancy-reserved-namespace",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_reserved_namespace",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
