rust_library(
    name = "network-dns",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_dns",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "network-dns-cloud-network-dns-api",
    srcs = ["tests/cloud_network_dns_api.rs"],
    crate = "network_dns_cloud_network_dns_api",
    crate_root = "tests/cloud_network_dns_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":network-dns",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)
