apiVersion: openslo/v1
kind: SLO
metadata:
  name: healthcare-integration-read-latency
  labels:
    service: healthcare-integration
    adr: ADR-0139
spec:
  service: healthcare-integration
  indicator:
    metadata:
      name: read-latency
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: prometheus
            spec:
              query: sum(rate(oya_healthcare_integration_read_latency_good_total[5m]))
        total:
          metricSource:
            type: prometheus
            spec:
              query: sum(rate(oya_healthcare_integration_read_latency_total[5m]))
  objectives:
    - displayName: Healthcare Integration read-latency
      target: 0.999
  timeWindow:
    - duration: 30d
      isRolling: true
