rust_library(
    name = "oya-data-warehouse-tenant-olap-service",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_data_warehouse_tenant_olap_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-data-warehouse-service",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/data-warehouse/crates/oya-data-warehouse-tenant-olap-service:oya-data-warehouse-tenant-olap-service",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
