[package]
name = "workflow-state-machine-postgres"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-state-machine-usecase = { path = "../../core/state-machine-usecase" }
workflow-state-machine-kernel = { path = "../../core/state-machine-kernel" }

[lib]
name = "workflow_state_machine_postgres"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
