rust_library(
    name = "oya-intelligence-audit-tap-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_intelligence_audit_tap_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-audit-tap-usecase:oya-intelligence-audit-tap-usecase",
    ],
)
