rust_library(
    name = "oya-identity-workload-svid-kernel",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "oya_identity_workload_svid_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
    ],
)

rust_test(
    name = "oya-identity-workload-svid-kernel-unittest",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "oya_identity_workload_svid_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
    ],
)
