rust_library(
    name = "oya-check-saga-shape",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_saga_shape",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-check-saga-shape-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_saga_shape",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-check-saga-shape-saga-shape",
    srcs = ["tests/saga_shape.rs"],
    crate = "oya_check_saga_shape_saga_shape",
    crate_root = "tests/saga_shape.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-check-saga-shape",
    ],
)
