rust_library(
    name = "iam-tenant-rbac-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-tenant-rbac-api-contracts",
    srcs = ["tests/contracts.rs"],
    crate = "iam_tenant_rbac_api_contracts",
    crate_root = "tests/contracts.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-api",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
