rust_library(
    name = "oya-mail-mailbox-store-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_mail_mailbox_store_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/mail/crates/oya-mail-domain:oya-mail-domain",
        "//oya/mail/crates/oya-mail-mailbox-store-api:oya-mail-mailbox-store-api",
    ],
)
