[package]
name = "oya-vcs-polyglot-indexer-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-vcs-kernel = { path = "../oya-vcs-kernel" }
oya-vcs-ast-index-kernel = { path = "../oya-vcs-ast-index-kernel" }

[lib]
name = "oya_vcs_polyglot_indexer_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
