rust_library(
    name = "oya-cloud-os-k8s-control-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_k8s_control_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-kubelet-domain:oya-cloud-os-kubelet-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
    ],
)
