rust_library(
    name = "intelligence-pr-review-dispatcher-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_pr_review_dispatcher_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-kernel:intelligence-account-kernel",
        "//intelligence/core/subagent-runtime-kernel:intelligence-subagent-runtime-kernel",
        "//intelligence/core/subagent-runtime-usecase:intelligence-subagent-runtime-usecase",
        "third-party//:tempfile",
    ],
)

rust_binary(
    name = "intelligence-pr-review-dispatcher-app-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/pr-review-dispatcher-app:intelligence-pr-review-dispatcher-app",
        "//intelligence/core/account-kernel:intelligence-account-kernel",
        "//intelligence/core/subagent-runtime-kernel:intelligence-subagent-runtime-kernel",
        "//intelligence/core/subagent-runtime-usecase:intelligence-subagent-runtime-usecase",
        "third-party//:tempfile",
    ],
)

rust_test(
    name = "intelligence-pr-review-dispatcher-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_pr_review_dispatcher_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-kernel:intelligence-account-kernel",
        "//intelligence/core/subagent-runtime-kernel:intelligence-subagent-runtime-kernel",
        "//intelligence/core/subagent-runtime-usecase:intelligence-subagent-runtime-usecase",
        "third-party//:tempfile",
    ],
)
