rust_library(
    name = "data-analytics-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "//data/core/analytics-usecase:data-analytics-usecase",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "data-analytics-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "//data/core/analytics-usecase:data-analytics-usecase",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "data-analytics-api-contract",
    srcs = ["tests/analytics_api_contract.rs"],
    crate = "data_analytics_api_contract",
    crate_root = "tests/analytics_api_contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":data-analytics-api",
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "//data/core/analytics-usecase:data-analytics-usecase",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
