# plugin-app-store-cosign default values
replicaCount: 3
image:
  repository: oyatie-internal/plugin-app-store-cosign
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
networkPolicy:
  enabled: true
  ciliumLayered: true
  ambientZtunnel: true
