rust_library(
    name = "cell-regional-pack-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_regional_pack_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/regional-pack:cell-regional-pack",
        "//network/core/residency:network-residency",
    ],
)

rust_test(
    name = "cell-regional-pack-api-regulatory-pack-bind-api",
    srcs = ["tests/regulatory_pack_bind_api.rs"],
    crate = "cell_regional_pack_api_regulatory_pack_bind_api",
    crate_root = "tests/regulatory_pack_bind_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":cell-regional-pack-api",
        "//cell/core/regional-pack:cell-regional-pack",
        "//network/core/residency:network-residency",
    ],
)
