[package]
name = "oya-community-post-store-grpc"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-community-post-store-api = { path = "../oya-community-post-store-api" }
oya-community-post-store-app = { path = "../oya-community-post-store-app" }
oya-community-post-store-domain = { path = "../oya-community-post-store-domain" }
oya-shared-postgres-command-kernel = { path = "../../../../libs/oya-shared-postgres-command-kernel" }
oya-shared-protocol-transport-kernel = { path = "../../../../libs/oya-shared-protocol-transport-kernel" }

[lib]
name = "oya_community_post_store_grpc"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
