[package]
name = "oya-connector-slack-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_connector_slack_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-shared-connector-kernel = { path = "../../../../libs/oya-shared-connector-kernel" }

[lints]
workspace = true
