rust_library(
    name = "oya-crate-registrar-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_crate_registrar_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-crate-registrar-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_crate_registrar_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
