rust_library(
    name = "intelligence-shuffle-sharding",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_shuffle_sharding",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "intelligence-shuffle-sharding-shuffle-sharding",
    srcs = ["tests/shuffle_sharding.rs"],
    crate = "intelligence_shuffle_sharding_shuffle_sharding",
    crate_root = "tests/shuffle_sharding.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-shuffle-sharding",
    ],
)
