[package]
name = "global-trade-compliance-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../../base/data-boundary-kernel" }

[lib]
name = "global_trade_compliance_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
