[package]
name = "storage-s3-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
doctest = false

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
storage-domain = { path = "../../core/domain" }

[lints]
workspace = true
