rust_library(
    name = "oya-intelligence-model-routing-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_model_routing_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-model-routing-domain:oya-intelligence-model-routing-domain",
    ],
)

rust_test(
    name = "oya-intelligence-model-routing-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_model_routing_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-model-routing-domain:oya-intelligence-model-routing-domain",
    ],
)

rust_test(
    name = "oya-intelligence-model-routing-usecase-acceptance",
    srcs = ["tests/acceptance.rs"],
    crate = "oya_intelligence_model_routing_usecase_acceptance",
    crate_root = "tests/acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-intelligence-model-routing-usecase",
        "//oya/intelligence/crates/oya-intelligence-model-routing-domain:oya-intelligence-model-routing-domain",
    ],
)
