[package]
name = "oya-platform-object-graph-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }
oya-platform-object-graph-kernel = { path = "../oya-platform-object-graph-kernel" }

[lib]
name = "oya_platform_object_graph_api"
path = "src/lib.rs"
doctest = false
