rust_library(
    name = "audit-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "audit_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//audit/core/chain-domain:audit-chain-domain",
        "//bus/core/domain:messaging-domain",
    ],
)

rust_test(
    name = "audit-usecase-audit-event-emit",
    srcs = ["tests/audit_event_emit.rs"],
    crate = "audit_usecase_audit_event_emit",
    crate_root = "tests/audit_event_emit.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":audit-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//audit/core/chain-domain:audit-chain-domain",
        "//bus/core/domain:messaging-domain",
    ],
)

rust_test(
    name = "audit-usecase-audit-event-emit-authz",
    srcs = ["tests/audit_event_emit_authz.rs"],
    crate = "audit_usecase_audit_event_emit_authz",
    crate_root = "tests/audit_event_emit_authz.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":audit-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//audit/core/chain-domain:audit-chain-domain",
        "//bus/core/domain:messaging-domain",
    ],
)
