[package]
name = "audit-usecase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
audit-chain-domain = { path = "../chain-domain" }
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }
messaging-domain = { path = "../../../bus/core/domain" }

[lib]
name = "audit_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
