rust_library(
    name = "oya-cloud-os-kubernetes-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_kubernetes_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/kernel:os-kernel",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
    ],
)

rust_test(
    name = "oya-cloud-os-kubernetes-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt", "testdata/**"]),
    crate = "oya_cloud_os_kubernetes_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//os/core/kernel:os-kernel",
        "//os/core/runtime-cri-domain:os-runtime-cri-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-secrets-domain:oya-cloud-os-secrets-domain-modeled",
    ],
)
