rust_library(
    name = "workflow-state-machine-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_state_machine_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/core/state-machine-kernel:workflow-state-machine-kernel",
        "//workflow/core/state-machine-usecase:workflow-state-machine-usecase",
    ],
)

rust_test(
    name = "workflow-state-machine-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_state_machine_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/core/state-machine-kernel:workflow-state-machine-kernel",
        "//workflow/core/state-machine-usecase:workflow-state-machine-usecase",
    ],
)
