rust_library(
    name = "oya-workflow-engine-event-bus-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_event_bus_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
