rust_library(
    name = "oya-community-social-post-composition-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_social_post_composition_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/community/crates/oya-community-social-domain:oya-community-social-domain",
        "//oya/community/crates/oya-community-social-post-composition-api:oya-community-social-post-composition-api",
    ],
)
