rust_library(
    name = "tenancy-tenant-lifecycle-store-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_store_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
    ],
)

rust_test(
    name = "tenancy-tenant-lifecycle-store-inmemory-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_store_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "//compute/core/resource-provider-contract-kernel:shared-resource-provider-contract-kernel",
        "third-party//:tokio",
    ],
)
