rust_library(
    name = "oya-design-collaboration-creative-artifact-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_design_collaboration_creative_artifact_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-design-collaboration-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/design-collaboration/crates/oya-design-collaboration-creative-artifact-service:oya-design-collaboration-creative-artifact-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
