rust_library(
    name = "oya-workplace-integration-doc-set-scaffold",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workplace_integration_doc_set_scaffold",
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-workplace-integration-doc-set-scaffold-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workplace_integration_doc_set_scaffold",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
