[package]
name = "comms-calendar-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-calendar-domain = { path = "../calendar-domain" }
comms-calendar-api = { path = "../../ports/calendar-api" }

[lib]
name = "comms_calendar_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
