rust_library(
    name = "oya-tenant-rbac-tenant-cost-allocation-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_tenant_cost_allocation_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "oya-tenant-rbac-tenant-cost-allocation-contract-cost-allocation",
    srcs = ["tests/cost_allocation.rs"],
    crate = "oya_tenant_rbac_tenant_cost_allocation_contract_cost_allocation",
    crate_root = "tests/cost_allocation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-tenant-cost-allocation-contract",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)
