[package]
name = "oya-payments-settlement-worker"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_payments_settlement_worker"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-payments-settlement-domain = { path = "../oya-payments-settlement-domain" }

[lints]
workspace = true
