[package]
name = "oya-social-post-composition-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-connect-social-domain = { path = "../oya-connect-social-domain" }
oya-social-post-composition-api = { path = "../oya-social-post-composition-api" }

[lib]
name = "oya_social_post_composition_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
