rust_library(
    name = "community-social-post-composition-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_social_post_composition_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-hyperscaler-metrics-kernel:oya-shared-hyperscaler-metrics-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//app/community/facade/social-app:community-social-app",
        "//app/community/ports/social-post-composition-api:community-social-post-composition-api",
        "//app/community/core/social-post-composition-usecase:community-social-post-composition-usecase",
    ],
)

rust_test(
    name = "community-social-post-composition-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "community_social_post_composition_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-hyperscaler-metrics-kernel:oya-shared-hyperscaler-metrics-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//app/community/facade/social-app:community-social-app",
        "//app/community/ports/social-post-composition-api:community-social-post-composition-api",
        "//app/community/core/social-post-composition-usecase:community-social-post-composition-usecase",
    ],
)
