rust_library(
    name = "oya-tenancy-dr-pairing-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_tenancy_dr_pairing_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
