rust_library(
    name = "corpus-extract",
    srcs = glob(["src/**/*.rs", "**/*.json"]),
    crate = "corpus_extract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/core:corpus-core",
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:quote",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:syn",
    ],
)

rust_binary(
    name = "app",
    srcs = glob(["src/**/*.rs", "**/*.json"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":corpus-extract",
        "//governance/corpus/core:corpus-core",
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:quote",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:syn",
    ],
)

rust_test(
    name = "corpus-extract-unittest",
    srcs = glob(["src/**/*.rs", "**/*.json"]),
    crate = "corpus_extract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/core:corpus-core",
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:quote",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:syn",
    ],
)
