rust_library(
    name = "iam-identity-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/identity-domain:iam-identity-domain",
    ],
)

rust_test(
    name = "iam-identity-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/identity-domain:iam-identity-domain",
    ],
)

rust_test(
    name = "iam-identity-usecase-identity-token-issue",
    srcs = ["tests/identity_token_issue.rs"],
    crate = "iam_identity_usecase_identity_token_issue",
    crate_root = "tests/identity_token_issue.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-usecase",
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/identity-domain:iam-identity-domain",
    ],
)

rust_test(
    name = "iam-identity-usecase-observability",
    srcs = ["tests/observability.rs"],
    crate = "iam_identity_usecase_observability",
    crate_root = "tests/observability.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-usecase",
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/identity-domain:iam-identity-domain",
    ],
)
