rust_library(
    name = "oya-intelligence-credential-resolver-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_intelligence_credential_resolver_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-credential-resolver-domain:oya-intelligence-credential-resolver-domain",
    ],
)
