rust_library(
    name = "comms-messenger-stream-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_stream_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/messenger-domain:comms-messenger-domain",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
    ],
)

rust_test(
    name = "comms-messenger-stream-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_stream_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/messenger-domain:comms-messenger-domain",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
    ],
)

rust_test(
    name = "comms-messenger-stream-usecase-delivery-receipt-acceptance",
    srcs = ["tests/delivery_receipt_acceptance.rs"],
    crate = "comms_messenger_stream_usecase_delivery_receipt_acceptance",
    crate_root = "tests/delivery_receipt_acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":comms-messenger-stream-usecase",
        "//comms/core/messenger-domain:comms-messenger-domain",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
    ],
)
