[package]
name = "comms-messenger-stream-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-messenger-domain = { path = "../messenger-domain" }
comms-messenger-stream-api = { path = "../../ports/messenger-stream-api" }

[lib]
name = "comms_messenger_stream_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
