rust_library(
    name = "iam-tenant-rbac-postgres-rls-write-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_postgres_rls_write_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/adapters/tenant-rbac-postgres-rls-storage:iam-tenant-rbac-postgres-rls-storage",
    ],
)

rust_test(
    name = "iam-tenant-rbac-postgres-rls-write-contract-write-contract",
    srcs = ["tests/write_contract.rs"],
    crate = "iam_tenant_rbac_postgres_rls_write_contract_write_contract",
    crate_root = "tests/write_contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-postgres-rls-write-contract",
        "//iam/adapters/tenant-rbac-postgres-rls-storage:iam-tenant-rbac-postgres-rls-storage",
    ],
)
