rust_library(
    name = "iam-tenant-rbac-listener-runtime-evidence",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_listener_runtime_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/facade/tenant-rbac-listener-gateway:iam-tenant-rbac-listener-gateway",
    ],
)

rust_test(
    name = "iam-tenant-rbac-listener-runtime-evidence-listener-runtime-evidence",
    srcs = ["tests/listener_runtime_evidence.rs"],
    crate = "iam_tenant_rbac_listener_runtime_evidence_listener_runtime_evidence",
    crate_root = "tests/listener_runtime_evidence.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-listener-runtime-evidence",
        "//iam/facade/tenant-rbac-listener-gateway:iam-tenant-rbac-listener-gateway",
    ],
)
