rust_library(
    name = "oya-identity-workload-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_identity_workload_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
