rust_library(
    name = "oya-identity-workload-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_identity_workload_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-identity-workload-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_identity_workload_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-identity-workload-api-contracts",
    srcs = ["tests/contracts.rs"],
    crate = "oya_identity_workload_api_contracts",
    crate_root = "tests/contracts.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-identity-workload-api",
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
