apiVersion: openslo/v1
kind: SLO
metadata:
  name: global-trade-availability
  labels:
    service: global-trade
    sap_code: "GTS"
spec:
  description: "Global Trade global-trade-availability objective; benchmarks SAP GTS Global Trade Services | Oracle Global Trade Management | Workday supplier-compliance workflow counterpart | NetSuite international tax and trade counterpart | Microsoft Dynamics 365 global trade and export-control counterpart"
  service: global-trade
  indicator:
    metadata:
      name: global-trade-availability-sli
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(http_requests_total{service=\"global-trade\",status=~\"2..\"}[5m]))"
        total:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(http_requests_total{service=\"global-trade\"}[5m]))"
  objectives:
    - displayName: global-trade-availability
      target: 0.999
