apiVersion: openslo/v1
kind: SLO
metadata:
  name: global-trade-throughput
  labels:
    service: global-trade
    sap_code: "GTS"
spec:
  description: "Global Trade global-trade-throughput objective; benchmarks SAP GTS Global Trade Services | Oracle Global Trade Management | Workday supplier-compliance workflow counterpart | NetSuite international tax and trade counterpart | Microsoft Dynamics 365 global trade and export-control counterpart"
  service: global-trade
  indicator:
    metadata:
      name: global-trade-throughput-sli
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(oya_global_trade_accepted_total[5m]))"
        total:
          metricSource:
            type: prometheus
            spec:
              query: "sum(rate(oya_global_trade_received_total[5m]))"
  objectives:
    - displayName: global-trade-throughput
      target: 0.995
