rust_library(
    name = "oya-cloud-kms-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_kms_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//cloud/cloud-kms/crates/oya-cloud-kms-domain:oya-cloud-kms-domain",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-kms-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_kms_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//cloud/cloud-kms/crates/oya-cloud-kms-domain:oya-cloud-kms-domain",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-kms-api-cloud-kms-api",
    srcs = ["tests/cloud_kms_api.rs"],
    crate = "oya_cloud_kms_api_cloud_kms_api",
    crate_root = "tests/cloud_kms_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-kms-api",
        "//cell/core/region:cell-region",
        "//cloud/cloud-kms/crates/oya-cloud-kms-domain:oya-cloud-kms-domain",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
