[package]
name = "oya-cloud-kms-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
oya-cloud-kms-domain = { path = "../oya-cloud-kms-domain" }
cell-region = { path = "../../../../cell/core/region" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }

[dev-dependencies]
network-residency = { path = "../../../../network/core/residency" }

[lints]
workspace = true
