rust_library(
    name = "oya-ci-webhook-gateway-github-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_ci_webhook_gateway_github_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ci-webhook-gateway/crates/oya-ci-webhook-gateway-kernel:oya-ci-webhook-gateway-kernel",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        # UNRESOLVED: httpmock ^0.7
    ],
)
