[package]
name = "oya-regional-pack-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-regional-pack-domain = { path = "../oya-regional-pack-domain" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_regional_pack_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
