use cargo_lock_merge_driver_app::{MergeErrorKind, merge_lockfiles};

fn lockfile(packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{packages}"
    )
}

fn package(name: &str, version: &str) -> String {
    format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n")
}

fn package_with_deps(name: &str, version: &str, dependencies: &[&str]) -> String {
    let deps = dependencies
        .iter()
        .map(|dependency| format!(" \"{dependency}\",\n"))
        .collect::<String>();
    format!(
        "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"0000000000000000000000000000000000000000000000000000000000000000\"\ndependencies = [\n{deps}]\n"
    )
}

fn lockfile_with_version(version: u8, packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = {version}\n\n{packages}"
    )
}

fn assert_merge_ok(base: &str, ours: &str, theirs: &str) -> String {
    match merge_lockfiles(base, ours, theirs) {
        Ok(output) => output,
        Err(err) => panic!("merge should have succeeded, got {err}"),
    }
}

fn assert_merge_conflict(base: &str, ours: &str, theirs: &str, wanted_detail: &str) {
    match merge_lockfiles(base, ours, theirs) {
        Ok(output) => panic!("merge should have conflicted, got output:\n{output}"),
        Err(err) => {
            assert_eq!(err.kind(), MergeErrorKind::Conflict);
            assert!(
                err.to_string().contains(wanted_detail),
                "wanted detail {wanted_detail:?} in error {err}"
            );
        }
    }
}

#[test]
fn disjoint_adds_merge_both_new_package_sections() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));
    let theirs = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("prost", "0.14.0")
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert!(merged.contains("name = \"serde\""));
    assert!(merged.contains("name = \"tokio\""));
    assert!(merged.contains("name = \"prost\""));
}

#[test]
fn version_divergence_conflicts_for_same_package_identity() {
    let base = lockfile("");
    let ours = lockfile(&package("serde", "1.0.1"));
    let theirs = lockfile(&package("serde", "1.0.2"));

    assert_merge_conflict(&base, &ours, &theirs, "version-divergence");
}

#[test]
fn removal_vs_edit_conflicts_for_existing_package() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile("");
    let theirs = lockfile(&package("serde", "1.0.1"));

    assert_merge_conflict(&base, &ours, &theirs, "removal-vs-edit");
}

#[test]
fn unchanged_three_way_merge_is_idempotent() {
    let base = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));

    let merged = assert_merge_ok(&base, &base, &base);

    assert_eq!(merged, base);
}

#[test]
fn generated_header_and_lockfile_version_are_preserved() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));
    let theirs = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("prost", "0.14.0")
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert!(merged.starts_with(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n"
    ));
}

#[test]
fn modified_dependencies_are_structurally_unionable() {
    let base = lockfile(&format!(
        "{}\n{}",
        package_with_deps("workspace-app", "0.1.0", &["serde"]),
        package("serde", "1.0.0")
    ));
    let ours = lockfile(&format!(
        "{}\n{}\n{}",
        package_with_deps("workspace-app", "0.1.0", &["left-crate", "serde"]),
        package("serde", "1.0.0"),
        package("left-crate", "0.1.0")
    ));
    let theirs = lockfile(&format!(
        "{}\n{}\n{}",
        package_with_deps("workspace-app", "0.1.0", &["right-crate", "serde"]),
        package("serde", "1.0.0"),
        package("right-crate", "0.1.0")
    ));
    let wanted = lockfile(&format!(
        "{}\n{}\n{}\n{}",
        package_with_deps(
            "workspace-app",
            "0.1.0",
            &["left-crate", "right-crate", "serde"]
        ),
        package("serde", "1.0.0"),
        package("left-crate", "0.1.0"),
        package("right-crate", "0.1.0")
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert_eq!(merged, wanted);
}

#[test]
fn one_sided_dependency_removal_is_not_resurrected() {
    let base = lockfile(&package_with_deps("workspace-app", "0.1.0", &["a", "x"]));
    let ours = lockfile(&package_with_deps("workspace-app", "0.1.0", &["a", "b"]));
    let theirs = lockfile(&package_with_deps(
        "workspace-app",
        "0.1.0",
        &["a", "c", "x"],
    ));
    let wanted = lockfile(&package_with_deps(
        "workspace-app",
        "0.1.0",
        &["a", "b", "c"],
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert_eq!(merged, wanted);
}

#[test]
fn appended_real_package_blocks_keep_cargo_blank_line_separator() {
    let app = package_with_deps("workspace-app", "0.1.0", &["serde"]);
    let serde = package_with_deps("serde", "1.0.0", &[]);
    let left = package_with_deps("left-crate", "0.1.0", &["serde"]);
    let right = package_with_deps("right-crate", "0.1.0", &["serde"]);
    let base = lockfile(&format!("{app}\n{serde}"));
    let ours = lockfile(&format!("{app}\n{serde}\n{left}"));
    let theirs = lockfile(&format!("{app}\n{serde}\n{right}"));
    let wanted = lockfile(&format!("{app}\n{serde}\n{left}\n{right}"));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert_eq!(merged, wanted);
}

#[test]
fn lockfile_version_mismatch_conflicts() {
    let base = lockfile_with_version(3, &package("serde", "1.0.0"));
    let ours = lockfile_with_version(4, &package("serde", "1.0.0"));
    let theirs = lockfile_with_version(4, &package("serde", "1.0.0"));

    assert_merge_conflict(&base, &ours, &theirs, "lockfile-version");
}

#[test]
fn ambiguous_removal_and_addition_under_shared_stem_conflicts() {
    let syn_one = package_with_deps("syn", "1.0.109", &[]);
    let syn_two = package_with_deps("syn", "2.0.117", &[]);
    let syn_new = package_with_deps("syn", "2.0.118", &[]);
    let base = lockfile(&format!("{syn_one}\n{syn_two}"));
    let ours = lockfile(&syn_new);

    assert_merge_conflict(&base, &ours, &base, "ambiguous-stem-replacement");
}
