export_file(
    name = "lib-src",
    src = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_library(
    name = "oya-governance-gate-catalog-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_governance_gate_catalog_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
