[package]
name = "network-selfhosted"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "network_selfhosted"
path = "src/lib.rs"
doctest = false

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
network-domain = { path = "../../core/domain" }

[dev-dependencies]

network-residency = { path = "../../core/residency" }

[lints]
workspace = true
