[package]
name = "oya-saas-workflow-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-saas-workflow-kernel = { path = "../oya-saas-workflow-kernel" }
oya-saas-workflow-domain = { path = "../oya-saas-workflow-domain" }

[lib]
name = "oya_saas_workflow_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
