rust_library(
    name = "oya-intelligence-api-sse-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_api_sse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/api-rest-kernel:intelligence-api-rest-kernel",
        "//intelligence/core/api-sse-kernel:intelligence-api-sse-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-api-sse-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_api_sse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/api-rest-kernel:intelligence-api-rest-kernel",
        "//intelligence/core/api-sse-kernel:intelligence-api-sse-kernel",
    ],
)
