rust_library(
    name = "iam-tenant-rbac-tenant-resource-quota-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_resource_quota_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "iam-tenant-rbac-tenant-resource-quota-contract-resource-quota",
    srcs = ["tests/resource_quota.rs"],
    crate = "iam_tenant_rbac_tenant_resource_quota_contract_resource_quota",
    crate_root = "tests/resource_quota.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-resource-quota-contract",
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)
