[package]
name = "oya-cloud-dcops-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-kernel = { path = "../oya-cloud-region-kernel" }
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }

[lib]
name = "oya_cloud_dcops_kernel"
path = "src/lib.rs"
doctest = false
