rust_library(
    name = "messenger-policy-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_policy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
    ],
)

rust_test(
    name = "messenger-policy-api-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_policy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
    ],
)
