rust_library(
    name = "oya-data-pipeline-lineage-replay-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_data_pipeline_lineage_replay_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-data-pipeline-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/data-pipeline/crates/oya-data-pipeline-lineage-replay-service:oya-data-pipeline-lineage-replay-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
