rust_library(
    name = "oya-identity",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_identity",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:tokio",
        "third-party//:uuid",
        "third-party//:webauthn-rs",
    ],
)

rust_binary(
    name = "oya-identity-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity:oya-identity",
        "third-party//:tokio",
        "third-party//:uuid",
        "third-party//:webauthn-rs",
    ],
)
