rust_library(
    name = "oya-architecture-graph-generator-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_architecture_graph_generator_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)

rust_binary(
    name = "oya-architecture-graph-generator",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_NAME": "oya-architecture-graph-generator-app", "CARGO_PKG_VERSION": "0.1.0"},
    visibility = ["PUBLIC"],
    deps = [
        "//tools/oya-architecture-graph-generator-app:oya-architecture-graph-generator-app",
        "third-party//:serde_json",
    ],
)
