rust_library(
    name = "compute-dcops",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_dcops",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-dcops-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_dcops",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
