[package]
name = "compute-dcops"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
cell-region = { path = "../../../cell/core/region" }
data-boundary-kernel = { path = "../../../base/data-boundary-kernel" }

[lib]
name = "compute_dcops"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
