[package]
name = "compute-dcops"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../../../cloud/cloud-cell/crates/oya-cloud-region-domain" }
oya-data-boundary-kernel = { path = "../../../libs/oya-data-boundary-kernel" }

[lib]
name = "compute_dcops"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
