[package]
name = "oya-foundry-vcs-promotion-controller"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-vcs-kernel = { path = "../oya-foundry-vcs-kernel" }
oya-foundry-vcs-changebundle-kernel = { path = "../oya-foundry-vcs-changebundle-kernel" }
oya-foundry-vcs-test-standard-gate = { path = "../oya-foundry-vcs-test-standard-gate" }

[lib]
name = "oya_foundry_vcs_promotion_controller"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
