rust_library(
    name = "k8s-tenant-quota-adapter-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_tenant_quota_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/ports/tenant-quota-api:k8s-tenant-quota-api",
        "//k8s/core/tenant-quota-kernel:k8s-tenant-quota-kernel",
        "third-party//:serde",
    ],
)

rust_test(
    name = "k8s-tenant-quota-adapter-inmemory-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_tenant_quota_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/ports/tenant-quota-api:k8s-tenant-quota-api",
        "//k8s/core/tenant-quota-kernel:k8s-tenant-quota-kernel",
        "third-party//:serde",
    ],
)
