rust_library(
    name = "workflow-studio-dsl-loader",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_studio_dsl_loader",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/facade/studio-dsl-emitter:workflow-studio-dsl-emitter",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "workflow-studio-dsl-loader-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_studio_dsl_loader",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/facade/studio-dsl-emitter:workflow-studio-dsl-emitter",
        "third-party//:serde_json",
    ],
)
