[package]
name = "oya-cloud-compute-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-iam-domain = { path = "../oya-cloud-iam-domain" }
oya-cloud-network-domain = { path = "../oya-cloud-network-domain" }
oya-cloud-region-domain = { path = "../oya-cloud-region-domain" }
oya-cloud-resource-domain = { path = "../oya-cloud-resource-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_compute_domain"
path = "src/lib.rs"
doctest = false
