rust_library(
    name = "oya-tenancy-reserved-namespace-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_tenancy_reserved_namespace_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
