rust_library(
    name = "oya-codeview-cli",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_codeview_cli",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow-1",
        "third-party//:chrono",
        "third-party//:clap-4",
        "third-party//:regex-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:walkdir-2",
    ],
)

rust_binary(
    name = "oya-codeview-cli-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-codeview-cli:oya-codeview-cli",
        "third-party//:anyhow-1",
        "third-party//:chrono",
        "third-party//:clap-4",
        "third-party//:regex-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:walkdir-2",
    ],
)
