rust_library(
    name = "iam-tenant-rbac-workflow-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_workflow_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)

rust_test(
    name = "iam-tenant-rbac-workflow-inmemory-workflow",
    srcs = ["tests/workflow.rs"],
    crate = "iam_tenant_rbac_workflow_inmemory_workflow",
    crate_root = "tests/workflow.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-workflow-inmemory",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)
