//! P00 oya-ci ProwJob registry generator/check.
//!
//! This is local/static evidence only. It renders lane-owned desired ProwJob
//! shards into a deterministic aggregate manifest and validates that the
//! checked-in generated file is in sync. It does not apply Kubernetes resources,
//! post GitHub statuses, mutate branch protection, or claim live oya-ci parity.

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const REGISTRY_PATH: &str = "specs/oya-ci-prowjob-registry.json";
const ROOT_HUB_PATH: &str = "specs/root-hub-pointers.json";
const REQUIRED_CONTEXT: &str = "oya-ci-required";
const SHADOW_CONTEXT: &str = "github-lane-unlocker-required";
const CHECK_COMMAND: &str = "buck2 build //:oya-ci-prowjob-registry-check";
const GENERATED_MARKER: &str = "# @generated by scripts/ci/generate-oya-ci-prowjob-registry.rs";
const CONTROLLER_CONFIG_MARKER: &str =
    "# @generated controller config by scripts/ci/generate-oya-ci-prowjob-registry.rs";
const GENERATED_CONTROLLER_CONFIG_PATH: &str =
    "specs/generated/oya-ci-controller-config.generated.yaml";
const GITHUB_REPOSITORY: &str = "jason931225/oyatie";
const ALLOWED_JOB_KINDS: &[&str] = &["presubmit", "postsubmit", "periodic", "batch"];
const REQUIRED_JOB_KINDS: &[&str] = &["presubmit", "postsubmit", "periodic", "batch"];
const REQUIRED_CAPABILITIES: &[&str] = &[
    "prow-prowjob-api-and-config",
    "prow-presubmit-jobs",
    "prow-postsubmit-jobs",
    "prow-periodic-jobs",
    "prow-batch-jobs",
    "prow-crier-status-reporting",
    "prow-status-reconciliation",
    "prow-trusted-untrusted-execution",
    "prow-config-validation",
];
const REQUIRED_REJECTED_ANTI_PATTERNS: &[&str] = &[
    "candidate_owned_manual_status_or_merge_truth",
    "single_hand_edited_workflow_bottleneck",
    "retired_external_substrate_bridge_authority",
    "new_python_or_shell_gate_sprawl",
    "github_actions_as_durable_ci_authority",
    "cargo_or_tarpaulin_as_monorepo_authority_over_buck2",
    "stateful_runner_workspace_pool",
    "pod_local_cache_as_correctness_or_state_authority",
    "cross_trust_cache_poisoning",
    "cross_region_hot_path_ci_io",
    "mutable_or_overwritten_ci_artifacts",
    "unbounded_ephemeral_storage",
    "privileged_dind_or_host_socket_runner",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Job {
    pub shard_id: String,
    pub owner_team: String,
    pub lane_family: String,
    pub editable_surface: String,
    pub id: String,
    pub prow_job_kind: String,
    pub context: String,
    pub required: bool,
    pub controller_owned: bool,
    pub execution_trust: String,
    pub buck2_commands: Vec<String>,
    pub source_prow_capability_ids: Vec<String>,
    pub anti_patterns_rejected: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Evaluation {
    pub verdict: String,
    pub failures: Vec<String>,
    pub registry: String,
    pub generated_output: String,
    pub generated_controller_config: String,
    pub shards_checked: usize,
    pub jobs_checked: usize,
    pub required_context: String,
    pub local_static_only: bool,
    pub live_authority_claimed: bool,
}

fn json_escape(input: &str) -> String {
    input
        .chars()
        .flat_map(|ch| match ch {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            _ => vec![ch],
        })
        .collect()
}

fn yaml_escape(input: &str) -> String {
    json_escape(input)
}

fn compact_json_text(input: &str) -> String {
    input.chars().filter(|ch| !ch.is_whitespace()).collect()
}

fn has_bool(text: &str, key: &str, value: bool) -> bool {
    compact_json_text(text).contains(&format!(
        "\"{}\":{}",
        key,
        if value { "true" } else { "false" }
    ))
}

fn contains_json_string(text: &str, value: &str) -> bool {
    text.contains(&format!("\"{}\"", json_escape(value)))
}

fn read(root: &Path, rel: &str, failures: &mut Vec<String>) -> String {
    match fs::read_to_string(root.join(rel)) {
        Ok(text) => text,
        Err(error) => {
            failures.push(format!("{rel}: read failed: {error}"));
            String::new()
        }
    }
}

fn require(condition: bool, failures: &mut Vec<String>, message: impl Into<String>) {
    if !condition {
        failures.push(message.into());
    }
}

fn skip_ws(text: &str, mut index: usize) -> usize {
    while index < text.len() {
        let Some(ch) = text[index..].chars().next() else {
            break;
        };
        if !ch.is_whitespace() {
            break;
        }
        index += ch.len_utf8();
    }
    index
}

fn parse_json_string_at(text: &str, start: usize) -> Option<(String, usize)> {
    if text[start..].chars().next()? != '"' {
        return None;
    }
    let mut out = String::new();
    let mut escaped = false;
    let mut index = start + 1;
    while index < text.len() {
        let ch = text[index..].chars().next()?;
        index += ch.len_utf8();
        if escaped {
            match ch {
                '"' => out.push('"'),
                '\\' => out.push('\\'),
                '/' => out.push('/'),
                'b' => out.push('\u{0008}'),
                'f' => out.push('\u{000c}'),
                'n' => out.push('\n'),
                'r' => out.push('\r'),
                't' => out.push('\t'),
                _ => return None,
            }
            escaped = false;
            continue;
        }
        match ch {
            '\\' => escaped = true,
            '"' => return Some((out, index)),
            _ => out.push(ch),
        }
    }
    None
}

fn find_field_value_start(text: &str, key: &str) -> Option<usize> {
    let key_needle = format!("\"{}\"", key);
    let mut search_from = 0;
    while search_from < text.len() {
        let key_start = text[search_from..].find(&key_needle)? + search_from;
        let after_key = skip_ws(text, key_start + key_needle.len());
        if text[after_key..].starts_with(':') {
            return Some(skip_ws(text, after_key + 1));
        }
        search_from = key_start + key_needle.len();
    }
    None
}

fn string_field(text: &str, key: &str) -> Option<String> {
    let start = find_field_value_start(text, key)?;
    parse_json_string_at(text, start).map(|(value, _)| value)
}

fn bool_field(text: &str, key: &str) -> Option<bool> {
    let start = find_field_value_start(text, key)?;
    if text[start..].starts_with("true") {
        Some(true)
    } else if text[start..].starts_with("false") {
        Some(false)
    } else {
        None
    }
}

fn bracketed_at(text: &str, start: usize, open: char, close: char) -> Option<(String, usize)> {
    if text[start..].chars().next()? != open {
        return None;
    }
    let mut depth = 0_i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut index = start;
    while index < text.len() {
        let ch = text[index..].chars().next()?;
        if in_string {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == '"' {
                in_string = false;
            }
            index += ch.len_utf8();
            continue;
        }
        if ch == '"' {
            in_string = true;
        } else if ch == open {
            depth += 1;
        } else if ch == close {
            depth -= 1;
            if depth == 0 {
                let end = index + ch.len_utf8();
                return Some((text[start..end].to_owned(), end));
            }
        }
        index += ch.len_utf8();
    }
    None
}

fn array_text_field(text: &str, key: &str) -> Option<String> {
    let start = find_field_value_start(text, key)?;
    bracketed_at(text, start, '[', ']').map(|(value, _)| value)
}

fn string_array_field(text: &str, key: &str) -> Vec<String> {
    let Some(array) = array_text_field(text, key) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    let mut index = 0;
    while index < array.len() {
        let Some(offset) = array[index..].find('"') else {
            break;
        };
        let start = index + offset;
        if let Some((value, end)) = parse_json_string_at(&array, start) {
            out.push(value);
            index = end;
        } else {
            break;
        }
    }
    out
}

fn object_texts_in_array(text: &str, key: &str) -> Vec<String> {
    let Some(array) = array_text_field(text, key) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    let mut index = 0;
    while index < array.len() {
        let Some(offset) = array[index..].find('{') else {
            break;
        };
        let start = index + offset;
        if let Some((object, end)) = bracketed_at(&array, start, '{', '}') {
            out.push(object);
            index = end;
        } else {
            break;
        }
    }
    out
}

pub fn registry_text_failures(registry: &str) -> Vec<String> {
    let mut failures = Vec::new();
    for (needle, message) in [
        (
            "\"status\": \"p00_seed_generated_registry\"",
            "registry status must be p00_seed_generated_registry",
        ),
        (
            "\"controller_owned_required_context\": \"oya-ci-required\"",
            "registry must declare controller-owned oya-ci-required",
        ),
        (
            "\"shadow_context\": \"github-lane-unlocker-required\"",
            "registry must preserve GitHub Actions shadow context as shadow only",
        ),
        (
            "\"generated_output\": \"specs/generated/oya-ci-prowjob-registry.generated.yaml\"",
            "registry must point at the checked-in generated aggregate",
        ),
        (
            "\"generated_controller_config\": \"specs/generated/oya-ci-controller-config.generated.yaml\"",
            "registry must point at the checked-in generated controller config",
        ),
        (
            "\"buck2_check\": \"buck2 build //:oya-ci-prowjob-registry-check\"",
            "registry must publish its Buck2 check command",
        ),
        (
            "\"source_of_truth\": \"registry_shards\"",
            "registry must make shards the source of truth",
        ),
        (
            "\"github_actions_shadow_only\": true",
            "registry claim boundary must keep GitHub Actions shadow-only",
        ),
        (
            "https://docs.prow.k8s.io/docs/life-of-a-prow-job/",
            "registry must cite upstream Prow job lifecycle evidence",
        ),
        (
            "\"stateless_execution_lifecycle\"",
            "registry must define stateless execution lifecycle",
        ),
        (
            "\"state_boundary\": \"ProwJob pods are disposable compute.",
            "registry must distinguish disposable job pods from durable remote state",
        ),
        (
            "\"remote_cache_allowed\": true",
            "registry must allow remote cache as the performance mechanism",
        ),
        (
            "\"local_disk_cache_persists_after_pod\": false",
            "registry must forbid persistent pod-local disk cache",
        ),
        (
            "\"cache_authoritative_for_correctness\": false",
            "registry must keep cache non-authoritative for correctness",
        ),
        (
            "\"content_addressed_only\": true",
            "registry cache policy must require content-addressed cache keys",
        ),
        (
            "\"trusted_postsubmit_promotion_required\": true",
            "registry cache policy must require trusted cache promotion",
        ),
        (
            "\"cold_cache_probe_required\": true",
            "registry cache policy must require cold-cache probes",
        ),
        (
            "\"io_performance_policy\"",
            "registry must define cloud I/O and performance policy",
        ),
        (
            "\"cache_topology\": \"regional_cell_local_remote_cache\"",
            "registry must keep cache close to cloud compute cells",
        ),
        (
            "\"hot_path_cross_region_io_allowed\": false",
            "registry must reject cross-region hot-path I/O",
        ),
        (
            "\"ephemeral_storage_requests_limits_required\": true",
            "registry must require ephemeral storage requests/limits",
        ),
        (
            "\"remote_execution_cas_required\": true",
            "registry must require Buck2 remote execution/CAS path",
        ),
    ] {
        require(registry.contains(needle), &mut failures, message);
    }
    for stage in [
        "trigger",
        "fetch_remote_state",
        "compute_validate",
        "export_artifacts",
        "destroy_ephemeral_workspace",
    ] {
        require(
            contains_json_string(registry, stage),
            &mut failures,
            format!("registry stateless lifecycle missing stage {stage}"),
        );
    }
    for kind in REQUIRED_JOB_KINDS {
        require(
            contains_json_string(registry, kind),
            &mut failures,
            format!("registry required_job_kinds missing {kind}"),
        );
    }
    for capability in REQUIRED_CAPABILITIES {
        require(
            contains_json_string(registry, capability),
            &mut failures,
            format!("registry required_capability_ids missing {capability}"),
        );
    }
    for anti_pattern in REQUIRED_REJECTED_ANTI_PATTERNS {
        require(
            contains_json_string(registry, anti_pattern),
            &mut failures,
            format!("registry anti_patterns_rejected missing {anti_pattern}"),
        );
    }
    for (key, value) in [
        ("local_static_only", true),
        ("live_authority_claimed", false),
        ("live_kubernetes_mutated", false),
        ("full_prow_parity_claimed", false),
        ("not_a_cluster_applied_manifest", true),
    ] {
        require(
            has_bool(registry, key, value),
            &mut failures,
            format!("registry claim boundary missing {key}={value}"),
        );
    }
    failures
}

pub fn parse_shard(rel: &str, text: &str, failures: &mut Vec<String>) -> Vec<Job> {
    let shard_id = string_field(text, "shard_id").unwrap_or_default();
    let owner_team = string_field(text, "owner_team").unwrap_or_default();
    let lane_family = string_field(text, "lane_family").unwrap_or_default();
    let editable_surface = string_field(text, "editable_surface").unwrap_or_default();
    require(
        !shard_id.is_empty(),
        failures,
        format!("{rel}: missing shard_id"),
    );
    require(
        !owner_team.is_empty(),
        failures,
        format!("{rel}: missing owner_team"),
    );
    require(
        !lane_family.is_empty(),
        failures,
        format!("{rel}: missing lane_family"),
    );
    require(
        editable_surface == rel,
        failures,
        format!("{rel}: editable_surface must equal shard path"),
    );
    require(
        bool_field(text, "live_authority_claimed") == Some(false),
        failures,
        format!("{rel}: live_authority_claimed must be false"),
    );

    let job_objects = object_texts_in_array(text, "jobs");
    require(
        !job_objects.is_empty(),
        failures,
        format!("{rel}: no jobs listed"),
    );
    let mut jobs = Vec::new();
    for object in job_objects {
        let id = string_field(&object, "id").unwrap_or_default();
        let prow_job_kind = string_field(&object, "prow_job_kind").unwrap_or_default();
        let context = string_field(&object, "context").unwrap_or_default();
        let required = bool_field(&object, "required").unwrap_or(false);
        let controller_owned = bool_field(&object, "controller_owned").unwrap_or(false);
        let execution_trust = string_field(&object, "execution_trust").unwrap_or_default();
        let buck2_commands = string_array_field(&object, "buck2_commands");
        let source_prow_capability_ids = string_array_field(&object, "source_prow_capability_ids");
        let anti_patterns_rejected = string_array_field(&object, "anti_patterns_rejected");
        let label = if id.is_empty() {
            format!("{rel}:<unknown job>")
        } else {
            format!("{rel}:{id}")
        };
        require(!id.is_empty(), failures, format!("{rel}: job missing id"));
        require(
            ALLOWED_JOB_KINDS.contains(&prow_job_kind.as_str()),
            failures,
            format!("{label}: unsupported prow_job_kind {prow_job_kind:?}"),
        );
        require(
            !context.is_empty(),
            failures,
            format!("{label}: missing context"),
        );
        require(
            controller_owned,
            failures,
            format!("{label}: controller_owned must be true"),
        );
        require(
            !execution_trust.is_empty(),
            failures,
            format!("{label}: missing execution_trust"),
        );
        require(
            !buck2_commands.is_empty(),
            failures,
            format!("{label}: missing buck2_commands"),
        );
        for command in &buck2_commands {
            require(
                command.starts_with("buck2 build //"),
                failures,
                format!(
                    "{label}: non-Buck2 command is not allowed in durable ProwJob registry: {command}"
                ),
            );
        }
        require(
            !source_prow_capability_ids.is_empty(),
            failures,
            format!("{label}: missing source_prow_capability_ids"),
        );
        require(
            source_prow_capability_ids.iter().any(|capability| {
                capability == "prow-prowjob-api-and-config" || capability.contains("jobs")
            }),
            failures,
            format!("{label}: must map to ProwJob/jobs capability"),
        );
        require(
            !anti_patterns_rejected.is_empty(),
            failures,
            format!("{label}: missing anti_patterns_rejected"),
        );
        if context == REQUIRED_CONTEXT {
            require(
                required,
                failures,
                format!("{label}: {REQUIRED_CONTEXT} must be required"),
            );
            require(
                execution_trust.contains("trusted_controller"),
                failures,
                format!("{label}: {REQUIRED_CONTEXT} must be trusted-controller owned"),
            );
        }
        jobs.push(Job {
            shard_id: shard_id.clone(),
            owner_team: owner_team.clone(),
            lane_family: lane_family.clone(),
            editable_surface: editable_surface.clone(),
            id,
            prow_job_kind,
            context,
            required,
            controller_owned,
            execution_trust,
            buck2_commands,
            source_prow_capability_ids,
            anti_patterns_rejected,
        });
    }
    jobs
}

fn render_yaml(jobs: &[Job]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        "# Source of truth: specs/oya-ci-prowjob-registry.json + specs/ci/prow-jobs/*.json\n",
    );
    out.push_str("# Local/static desired graph only; do not kubectl apply this file directly.\n");
    out.push_str("apiVersion: oyatie.dev/v1alpha1\n");
    out.push_str("kind: OyaCIProwJobRegistry\n");
    out.push_str("metadata:\n");
    out.push_str("  name: oya-ci-prowjob-registry\n");
    out.push_str("spec:\n");
    out.push_str(&format!("  requiredContext: \"{}\"\n", REQUIRED_CONTEXT));
    out.push_str(&format!("  shadowContext: \"{}\"\n", SHADOW_CONTEXT));
    out.push_str("  githubActionsShadowOnly: true\n");
    out.push_str("  liveAuthorityClaimed: false\n");
    out.push_str("  generatedBy: \"scripts/ci/generate-oya-ci-prowjob-registry.rs\"\n");
    out.push_str("  jobs:\n");
    for job in jobs {
        out.push_str(&format!("    - id: \"{}\"\n", yaml_escape(&job.id)));
        out.push_str(&format!(
            "      prowJobKind: \"{}\"\n",
            yaml_escape(&job.prow_job_kind)
        ));
        out.push_str(&format!(
            "      context: \"{}\"\n",
            yaml_escape(&job.context)
        ));
        out.push_str(&format!("      required: {}\n", job.required));
        out.push_str(&format!(
            "      controllerOwned: {}\n",
            job.controller_owned
        ));
        out.push_str(&format!(
            "      executionTrust: \"{}\"\n",
            yaml_escape(&job.execution_trust)
        ));
        out.push_str(&format!(
            "      shard: \"{}\"\n",
            yaml_escape(&job.shard_id)
        ));
        out.push_str(&format!(
            "      ownerTeam: \"{}\"\n",
            yaml_escape(&job.owner_team)
        ));
        out.push_str(&format!(
            "      laneFamily: \"{}\"\n",
            yaml_escape(&job.lane_family)
        ));
        out.push_str(&format!(
            "      editableSurface: \"{}\"\n",
            yaml_escape(&job.editable_surface)
        ));
        out.push_str("      buck2Commands:\n");
        for command in &job.buck2_commands {
            out.push_str(&format!("        - \"{}\"\n", yaml_escape(command)));
        }
        out.push_str("      sourceProwCapabilityIds:\n");
        for capability in &job.source_prow_capability_ids {
            out.push_str(&format!("        - \"{}\"\n", yaml_escape(capability)));
        }
        out.push_str("      antiPatternsRejected:\n");
        for anti_pattern in &job.anti_patterns_rejected {
            out.push_str(&format!("        - \"{}\"\n", yaml_escape(anti_pattern)));
        }
    }
    out
}

fn render_string_array_yaml(out: &mut String, indent: &str, values: &[String]) {
    for value in values {
        out.push_str(&format!("{indent}- \"{}\"\n", yaml_escape(value)));
    }
}

fn sorted_unique(values: impl Iterator<Item = String>) -> Vec<String> {
    values.collect::<BTreeSet<_>>().into_iter().collect()
}

fn security_profile(job: &Job) -> &'static str {
    if job.execution_trust.contains("untrusted") {
        "restricted-untrusted-pr"
    } else if job.context == REQUIRED_CONTEXT {
        "trusted-controller-rollup"
    } else {
        "trusted-controller-job"
    }
}

fn service_account(job: &Job) -> &'static str {
    if job.execution_trust.contains("untrusted") {
        "oya-ci-untrusted-runner"
    } else {
        "oya-ci-controller-runner"
    }
}

fn runtime_class(job: &Job) -> &'static str {
    if job.execution_trust.contains("untrusted") {
        "sandboxed"
    } else {
        "default"
    }
}

fn render_controller_config_yaml(jobs: &[Job]) -> String {
    let mut out = String::new();
    out.push_str(CONTROLLER_CONFIG_MARKER);
    out.push('\n');
    out.push_str(
        "# Source of truth: specs/oya-ci-prowjob-registry.json + specs/ci/prow-jobs/*.json\n",
    );
    out.push_str(
        "# Local/static desired controller config only; do not apply this file directly.\n",
    );
    out.push_str("apiVersion: oyatie.dev/v1alpha1\n");
    out.push_str("kind: OyaCIControllerConfig\n");
    out.push_str("metadata:\n");
    out.push_str("  name: oya-ci-controller-config\n");
    out.push_str("  annotations:\n");
    out.push_str("    oyatie.dev/local-static-only: \"true\"\n");
    out.push_str("    oyatie.dev/live-authority-claimed: \"false\"\n");
    out.push_str("spec:\n");
    out.push_str(&format!("  repository: \"{}\"\n", GITHUB_REPOSITORY));
    out.push_str("  sourceOfTruth:\n");
    out.push_str(&format!("    registry: \"{}\"\n", REGISTRY_PATH));
    out.push_str(
        "    generatedRegistry: \"specs/generated/oya-ci-prowjob-registry.generated.yaml\"\n",
    );
    out.push_str("    verticalLaneSurfaces:\n");
    let surfaces = sorted_unique(jobs.iter().map(|job| job.editable_surface.clone()));
    render_string_array_yaml(&mut out, "      ", &surfaces);
    out.push_str("  publicationAdapters:\n");
    out.push_str("    github:\n");
    out.push_str("      temporary: true\n");
    out.push_str("      shadowOnly: true\n");
    out.push_str(&format!("      shadowContext: \"{}\"\n", SHADOW_CONTEXT));
    out.push_str("      mergeAuthority: false\n");
    out.push_str("  rollup:\n");
    out.push_str(&format!("    requiredContext: \"{}\"\n", REQUIRED_CONTEXT));
    out.push_str("    owner: \"trusted-controller\"\n");
    out.push_str("    candidateOwnedTruthAllowed: false\n");
    out.push_str("  executionLifecycle:\n");
    out.push_str("    statelessJobPods: true\n");
    out.push_str("    sequence:\n");
    out.push_str("      - \"trigger\"\n");
    out.push_str("      - \"fetch_remote_state\"\n");
    out.push_str("      - \"compute_validate\"\n");
    out.push_str("      - \"export_artifacts\"\n");
    out.push_str("      - \"destroy_ephemeral_workspace\"\n");
    out.push_str("    podLocalStateAuthority: false\n");
    out.push_str("    durableStateStores:\n");
    out.push_str("      - \"native_scm_or_github_adapter_refs\"\n");
    out.push_str("      - \"buck2_remote_execution_cache_or_content_addressed_cache\"\n");
    out.push_str("      - \"immutable_object_artifact_store\"\n");
    out.push_str("      - \"status_and_audit_ledger\"\n");
    out.push_str("    workspaceDestructionRequired: true\n");
    out.push_str("  remoteCachePolicy:\n");
    out.push_str("    remoteCacheAllowed: true\n");
    out.push_str("    localDiskCachePersistsAfterPod: false\n");
    out.push_str("    cacheAuthoritativeForCorrectness: false\n");
    out.push_str("    contentAddressedOnly: true\n");
    out.push_str("    trustDomainSeparated: true\n");
    out.push_str("    untrustedWritesQuarantined: true\n");
    out.push_str("    trustedPostsubmitPromotionRequired: true\n");
    out.push_str("    coldCacheProbeRequired: true\n");
    out.push_str("    periodicCacheWarmersAllowed: true\n");
    out.push_str("  cloudIoPerformancePolicy:\n");
    out.push_str("    cacheTopology: \"regional-cell-local-remote-cache\"\n");
    out.push_str("    artifactStore: \"immutable-object-store\"\n");
    out.push_str("    hotPathCrossRegionIoAllowed: false\n");
    out.push_str("    asynchronousCrossRegionReplicationAllowed: true\n");
    out.push_str("    ephemeralStorageRequestsLimitsRequired: true\n");
    out.push_str("    remoteExecutionCasRequired: true\n");
    out.push_str("    cacheWarmersTrustDomain: \"trusted-periodic-or-postsubmit-only\"\n");
    out.push_str("    cachePoisoningControls: \"content-addressed-trust-domain-separated-quarantined-untrusted-writes-cold-cache-probes\"\n");
    out.push_str("    requiredMetrics:\n");
    out.push_str("      - \"cache_hit_ratio\"\n");
    out.push_str("      - \"cas_download_bytes\"\n");
    out.push_str("      - \"cas_upload_bytes\"\n");
    out.push_str("      - \"artifact_upload_latency_ms\"\n");
    out.push_str("      - \"ephemeral_storage_evictions\"\n");
    out.push_str("  kubernetesSecurityDefaults:\n");
    out.push_str("    workloadIdentityRequired: true\n");
    out.push_str("    nodeMetadataAccess: \"blocked\"\n");
    out.push_str("    staticCloudSecretsAllowed: false\n");
    out.push_str("    automountServiceAccountToken: false\n");
    out.push_str("    defaultDenyNetworkPolicy: true\n");
    out.push_str("    serviceMeshMtls: \"required-for-service-to-service\"\n");
    out.push_str("    allowPrivilegeEscalation: false\n");
    out.push_str("    readOnlyRootFilesystem: true\n");
    out.push_str("    runAsNonRoot: true\n");
    out.push_str("    seccompProfile: \"RuntimeDefault\"\n");
    out.push_str("    runtimeClassRequiredForUntrusted: true\n");
    out.push_str("    dropCapabilities:\n");
    out.push_str("      - \"ALL\"\n");
    out.push_str("  jobs:\n");
    for job in jobs {
        out.push_str(&format!("    - id: \"{}\"\n", yaml_escape(&job.id)));
        out.push_str(&format!(
            "      prowJobKind: \"{}\"\n",
            yaml_escape(&job.prow_job_kind)
        ));
        out.push_str(&format!(
            "      context: \"{}\"\n",
            yaml_escape(&job.context)
        ));
        out.push_str(&format!("      required: {}\n", job.required));
        out.push_str(&format!(
            "      controllerOwned: {}\n",
            job.controller_owned
        ));
        out.push_str(&format!(
            "      securityProfile: \"{}\"\n",
            security_profile(job)
        ));
        out.push_str(&format!(
            "      serviceAccount: \"{}\"\n",
            service_account(job)
        ));
        out.push_str(&format!(
            "      runtimeClassName: \"{}\"\n",
            runtime_class(job)
        ));
        out.push_str("      workloadIdentity: true\n");
        out.push_str("      nodeMetadataAccess: \"blocked\"\n");
        out.push_str("      automountServiceAccountToken: false\n");
        out.push_str("      allowPrivilegeEscalation: false\n");
        out.push_str("      readOnlyRootFilesystem: true\n");
        out.push_str("      runAsNonRoot: true\n");
        out.push_str("      defaultDenyNetworkPolicy: true\n");
        out.push_str("      dropCapabilities:\n");
        out.push_str("        - \"ALL\"\n");
        out.push_str(&format!(
            "      shard: \"{}\"\n",
            yaml_escape(&job.shard_id)
        ));
        out.push_str(&format!(
            "      ownerTeam: \"{}\"\n",
            yaml_escape(&job.owner_team)
        ));
        out.push_str(&format!(
            "      laneFamily: \"{}\"\n",
            yaml_escape(&job.lane_family)
        ));
        out.push_str("      buck2Commands:\n");
        render_string_array_yaml(&mut out, "        ", &job.buck2_commands);
    }
    out
}

pub fn evaluate(root: &Path) -> Evaluation {
    let mut failures = Vec::new();
    let registry = read(root, REGISTRY_PATH, &mut failures);
    let root_hub = read(root, ROOT_HUB_PATH, &mut failures);
    failures.extend(registry_text_failures(&registry));
    require(
        root_hub.contains("\"oya_ci_prowjob_registry\""),
        &mut failures,
        "root hub must expose oya_ci_prowjob_registry",
    );
    require(
        root_hub.contains("\"current_path\": \"/specs/oya-ci-prowjob-registry.json\""),
        &mut failures,
        "root hub oya_ci_prowjob_registry.current_path must point at /specs/oya-ci-prowjob-registry.json",
    );
    require(
        root_hub.contains("\"oya_ci_prowjob_registry\": \"specs/oya-ci-prowjob-registry.json\""),
        &mut failures,
        "root hub pointers must include oya_ci_prowjob_registry",
    );
    let generated_output = string_field(&registry, "generated_output")
        .unwrap_or_else(|| "specs/generated/oya-ci-prowjob-registry.generated.yaml".to_owned());
    let generated_controller_config = string_field(&registry, "generated_controller_config")
        .unwrap_or_else(|| GENERATED_CONTROLLER_CONFIG_PATH.to_owned());
    let shard_paths = string_array_field(&registry, "registry_shards");
    require(
        shard_paths.len() >= 3,
        &mut failures,
        "registry must list at least three lane-owned shards",
    );

    let mut jobs = Vec::new();
    for shard_path in &shard_paths {
        let text = read(root, shard_path, &mut failures);
        jobs.extend(parse_shard(shard_path, &text, &mut failures));
    }
    let mut ids = BTreeSet::new();
    let mut contexts = BTreeSet::new();
    let mut kinds = BTreeSet::new();
    let mut capabilities = BTreeSet::new();
    let mut jobs_by_shard: BTreeMap<String, usize> = BTreeMap::new();
    for job in &jobs {
        require(
            ids.insert(job.id.clone()),
            &mut failures,
            format!("duplicate job id {}", job.id),
        );
        contexts.insert(job.context.clone());
        kinds.insert(job.prow_job_kind.clone());
        *jobs_by_shard.entry(job.shard_id.clone()).or_default() += 1;
        for capability in &job.source_prow_capability_ids {
            capabilities.insert(capability.clone());
        }
    }
    require(
        jobs.len() >= 6,
        &mut failures,
        format!("expected at least 6 desired jobs, got {}", jobs.len()),
    );
    require(
        contexts.contains(REQUIRED_CONTEXT),
        &mut failures,
        format!("generated desired graph must include aggregate context {REQUIRED_CONTEXT}"),
    );
    for kind in REQUIRED_JOB_KINDS {
        require(
            kinds.contains(*kind),
            &mut failures,
            format!("desired graph missing Prow job kind {kind}"),
        );
    }
    for capability in REQUIRED_CAPABILITIES {
        require(
            capabilities.contains(*capability),
            &mut failures,
            format!("desired graph missing source capability {capability}"),
        );
    }
    for shard in &shard_paths {
        let shard_id =
            string_field(&read(root, shard, &mut failures), "shard_id").unwrap_or_default();
        require(
            jobs_by_shard.get(&shard_id).copied().unwrap_or(0) > 0,
            &mut failures,
            format!("shard {shard} did not contribute jobs"),
        );
    }

    let expected = render_yaml(&jobs);
    let checked_in = read(root, &generated_output, &mut failures);
    require(
        checked_in.starts_with(GENERATED_MARKER),
        &mut failures,
        format!("{generated_output}: missing generated marker"),
    );
    require(
        checked_in == expected,
        &mut failures,
        format!(
            "{generated_output}: generated output is stale; run scripts/ci/generate-oya-ci-prowjob-registry.rs --render"
        ),
    );

    let expected_controller_config = render_controller_config_yaml(&jobs);
    let checked_in_controller_config = read(root, &generated_controller_config, &mut failures);
    require(
        checked_in_controller_config.starts_with(CONTROLLER_CONFIG_MARKER),
        &mut failures,
        format!("{generated_controller_config}: missing generated controller config marker"),
    );
    require(
        checked_in_controller_config == expected_controller_config,
        &mut failures,
        format!(
            "{generated_controller_config}: generated controller config is stale; run scripts/ci/generate-oya-ci-prowjob-registry.rs --render-controller-config"
        ),
    );
    for (needle, message) in [
        (
            "workloadIdentityRequired: true",
            "controller config must require workload identity",
        ),
        (
            "nodeMetadataAccess: \"blocked\"",
            "controller config must block node metadata access",
        ),
        (
            "automountServiceAccountToken: false",
            "controller config must disable default service account token mounting",
        ),
        (
            "defaultDenyNetworkPolicy: true",
            "controller config must require default-deny network policy",
        ),
        (
            "readOnlyRootFilesystem: true",
            "controller config must require immutable container filesystems",
        ),
        (
            "runtimeClassRequiredForUntrusted: true",
            "controller config must require sandboxed runtimes for untrusted jobs",
        ),
        (
            "dropCapabilities:",
            "controller config must drop Linux capabilities",
        ),
        (
            "candidateOwnedTruthAllowed: false",
            "controller config must reject candidate-owned merge truth",
        ),
        (
            "statelessJobPods: true",
            "controller config must make ProwJob pods stateless disposable compute",
        ),
        (
            "podLocalStateAuthority: false",
            "controller config must reject pod-local state authority",
        ),
        (
            "workspaceDestructionRequired: true",
            "controller config must require workspace destruction",
        ),
        (
            "remoteCacheAllowed: true",
            "controller config must preserve remote cache performance path",
        ),
        (
            "localDiskCachePersistsAfterPod: false",
            "controller config must forbid persistent pod-local cache",
        ),
        (
            "cacheAuthoritativeForCorrectness: false",
            "controller config must keep caches non-authoritative for correctness",
        ),
        (
            "contentAddressedOnly: true",
            "controller config must require content-addressed cache",
        ),
        (
            "trustDomainSeparated: true",
            "controller config must separate cache trust domains",
        ),
        (
            "untrustedWritesQuarantined: true",
            "controller config must quarantine untrusted cache writes",
        ),
        (
            "trustedPostsubmitPromotionRequired: true",
            "controller config must require trusted cache promotion",
        ),
        (
            "coldCacheProbeRequired: true",
            "controller config must require cold-cache probes",
        ),
        (
            "cacheTopology: \"regional-cell-local-remote-cache\"",
            "controller config must keep cache close to cloud compute cells",
        ),
        (
            "artifactStore: \"immutable-object-store\"",
            "controller config must publish immutable artifact store",
        ),
        (
            "hotPathCrossRegionIoAllowed: false",
            "controller config must reject cross-region hot-path I/O",
        ),
        (
            "asynchronousCrossRegionReplicationAllowed: true",
            "controller config must allow async cross-region artifact/cache replication",
        ),
        (
            "ephemeralStorageRequestsLimitsRequired: true",
            "controller config must require ephemeral-storage requests/limits",
        ),
        (
            "remoteExecutionCasRequired: true",
            "controller config must require Buck2 remote execution/CAS",
        ),
        (
            "cacheWarmersTrustDomain: \"trusted-periodic-or-postsubmit-only\"",
            "controller config must restrict cache warmers to trusted jobs",
        ),
        (
            "cachePoisoningControls: \"content-addressed-trust-domain-separated-quarantined-untrusted-writes-cold-cache-probes\"",
            "controller config must declare cache poisoning controls",
        ),
        (
            "shadowOnly: true",
            "controller config must keep GitHub adapter shadow-only",
        ),
    ] {
        require(
            checked_in_controller_config.contains(needle),
            &mut failures,
            message,
        );
    }
    require(
        !checked_in_controller_config.contains("kubectl apply"),
        &mut failures,
        "controller config must not instruct live kubectl apply",
    );

    Evaluation {
        verdict: if failures.is_empty() { "PASS" } else { "FAIL" }.to_owned(),
        failures,
        registry: REGISTRY_PATH.to_owned(),
        generated_output,
        generated_controller_config,
        shards_checked: shard_paths.len(),
        jobs_checked: jobs.len(),
        required_context: REQUIRED_CONTEXT.to_owned(),
        local_static_only: true,
        live_authority_claimed: false,
    }
}

fn render_json(evaluation: &Evaluation) -> String {
    let failures = evaluation
        .failures
        .iter()
        .map(|failure| format!("\"{}\"", json_escape(failure)))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "{{\"verdict\":\"{}\",\"registry\":\"{}\",\"generated_output\":\"{}\",\"generated_controller_config\":\"{}\",\"shards_checked\":{},\"jobs_checked\":{},\"required_context\":\"{}\",\"local_static_only\":{},\"live_authority_claimed\":{},\"buck2_check\":\"{}\",\"failures\":[{}]}}",
        evaluation.verdict,
        json_escape(&evaluation.registry),
        json_escape(&evaluation.generated_output),
        json_escape(&evaluation.generated_controller_config),
        evaluation.shards_checked,
        evaluation.jobs_checked,
        json_escape(&evaluation.required_context),
        evaluation.local_static_only,
        evaluation.live_authority_claimed,
        json_escape(CHECK_COMMAND),
        failures
    )
}

fn config() -> (PathBuf, bool, bool, bool) {
    let mut json = false;
    let mut render = false;
    let mut render_controller_config = false;
    for arg in env::args().skip(1) {
        match arg.as_str() {
            "--json" => json = true,
            "--render" => render = true,
            "--render-controller-config" => render_controller_config = true,
            unknown => {
                eprintln!("generate-oya-ci-prowjob-registry: unknown argument {unknown}");
                std::process::exit(2);
            }
        }
    }
    let root = env::var_os("OYA_REPO_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    if render && render_controller_config {
        eprintln!("generate-oya-ci-prowjob-registry: choose one render mode");
        std::process::exit(2);
    }
    (root, json, render, render_controller_config)
}

fn main() {
    let (root, json, render, render_controller_config) = config();
    if render || render_controller_config {
        let mut failures = Vec::new();
        let registry = read(&root, REGISTRY_PATH, &mut failures);
        let mut jobs = Vec::new();
        for shard_path in string_array_field(&registry, "registry_shards") {
            let text = read(&root, &shard_path, &mut failures);
            jobs.extend(parse_shard(&shard_path, &text, &mut failures));
        }
        if !failures.is_empty() {
            for failure in failures {
                eprintln!("{failure}");
            }
            std::process::exit(1);
        }
        if render_controller_config {
            print!("{}", render_controller_config_yaml(&jobs));
        } else {
            print!("{}", render_yaml(&jobs));
        }
        return;
    }

    let evaluation = evaluate(&root);
    if json || evaluation.failures.is_empty() {
        println!("{}", render_json(&evaluation));
    }
    if !evaluation.failures.is_empty() {
        if !json {
            eprintln!("oya-ci-prowjob-registry: RED");
            for failure in &evaluation.failures {
                eprintln!("- {failure}");
            }
        }
        std::process::exit(1);
    }
}
