rust_library(
    name = "intelligence-capability-registry-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_capability_registry_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "intelligence-capability-registry-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_capability_registry_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "intelligence-capability-registry-kernel-lifecycle-integration",
    srcs = ["tests/lifecycle_integration.rs"],
    crate = "intelligence_capability_registry_kernel_lifecycle_integration",
    crate_root = "tests/lifecycle_integration.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-capability-registry-kernel",
    ],
)
