rust_binary(
    name = "oya-governance-sunset-lifecycle-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-sunset-lifecycle-kernel:oya-governance-sunset-lifecycle-kernel",
        "third-party//:tempfile",
    ],
)
