rust_library(
    name = "tenancy-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//tenancy/core/domain:tenancy-domain",
    ],
)

rust_test(
    name = "tenancy-api-tenant-create-api",
    srcs = ["tests/tenant_create_api.rs"],
    crate = "tenancy_api_tenant_create_api",
    crate_root = "tests/tenant_create_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":tenancy-api",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//tenancy/core/domain:tenancy-domain",
    ],
)
