//! Build-time codegen: derive seam-lane constants from the canonical spec
//! source at /specs/cross-cutting/multispectrum-review.json + (future)
//! /registries/cross-cutting/dependency-rationales.json.
//!
//! Resolves CONV-8 from the TG2 11-facet debate synthesis (F1 + F2):
//! n-source-of-truth-without-generator. Lane constants previously hand-
//! rolled in src/lib.rs (EVIDENCE_REQUIRED_FACETS, CHANGE_CLASSES) drifted
//! from the spec silently. Now the build.rs emits *_FROM_SPEC siblings;
//! unit tests in tests/per_subcheck_unit_tests.rs assert spec/code parity
//! and fail CI on drift.
//!
//! Std-only end-to-end: build script uses oya-json-kernel (zero external
//! deps) as a [build-dependencies] entry.

use std::env;
use std::fs;
use std::path::PathBuf;

use oya_json_kernel::extract_object_keys;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // crates/oya-check-dependency-seam/ → workspace root is parent-parent.
    let workspace_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root from CARGO_MANIFEST_DIR");

    let spec_path = workspace_root.join("specs/cross-cutting/multispectrum-review.json");

    // Cargo: rerun build.rs if spec content changes.
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let mut change_classes: Vec<String> = Vec::new();
    let mut all_facets: Vec<String> = Vec::new();
    match fs::read_to_string(&spec_path) {
        Ok(raw) => {
            change_classes = extract_object_keys(&raw, "change_classes");
            all_facets = extract_object_keys(&raw, "facets");
            change_classes.sort();
            all_facets.sort();
        }
        Err(e) => {
            println!(
                "cargo:warning=multispectrum-review.json read failed ({}); emitting empty CONV-8 constants",
                e
            );
        }
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = PathBuf::from(out_dir).join("spec_constants.rs");

    let mut content = String::new();
    content.push_str("// AUTO-GENERATED by build.rs from specs/cross-cutting/multispectrum-review.json.\n");
    content.push_str("// DO NOT EDIT MANUALLY — regenerate via `cargo build -p oya-check-dependency-seam`.\n");
    content.push_str("// CONV-8 (TG2 11-facet debate): resolves n-source-of-truth-without-generator.\n\n");

    content.push_str("/// Canonical change_class_id values derived from spec at build time.\n");
    content.push_str("/// Hand-rolled `CHANGE_CLASSES` must match this; drift caught by unit test.\n");
    content.push_str("pub const CHANGE_CLASSES_FROM_SPEC: &[&str] = &[\n");
    for c in &change_classes {
        content.push_str(&format!("    \"{}\",\n", c));
    }
    content.push_str("];\n\n");

    content.push_str("/// All facet keys (F1..F9 + F10/F11/F13 + M1/M2 + A1..A7) from spec.\n");
    content.push_str("/// `EVIDENCE_REQUIRED_FACETS` must be a subset; drift caught by unit test.\n");
    content.push_str("pub const ALL_FACETS_FROM_SPEC: &[&str] = &[\n");
    for f in &all_facets {
        content.push_str(&format!("    \"{}\",\n", f));
    }
    content.push_str("];\n");

    fs::write(&dest, content).expect("write spec_constants.rs to OUT_DIR");
}
