//! Move-aware path resolution — git + manifest ADAPTERS (ci/adapters).
//!
//! Implements the [`ci_path_resolver_ports`] contract:
//!  * [`ManifestBijection`] — loads the committed move-manifest fail-closed; identity (empty) on a
//!    foreign schema, a malformed row, or a NON-INJECTIVE side (MUST-PASS #3: both old AND new
//!    sides must be injective, else `new_to_old`/`old_to_new` are not well-defined functions).
//!  * [`GitCliFrozenRefSource`] — the live `git merge-base` / `git show` seam (fail-closed).
//!  * [`ManifestPathResolver`] — the presence-verified, straddle-safe, fail-closed resolution.
//!
//! WHY THE MERGE-BASE SPLIT CANNOT LAUNDER DEBT (corrected rationale — MUST-PASS #6). The defense
//! is NOT "registry-drift gate-ordering". It is three concrete, independent facts:
//!   1. IMMUTABLE MERGE-BASE HISTORY — the frozen reference is read from `git merge-base
//!      <bootstrap> HEAD`, a point in committed history an attacker cannot rewrite in a PR.
//!   2. TRUSTED COMPILED SEED — the candidate/current name is a compiled-in const
//!      ([`canonical_current`]), never read from a candidate-tree data file, so there is no
//!      candidate-repointable anchor to aim the merge-base read through (MUST-PASS #1).
//!   3. MANIFEST REGENERATED-FROM-PLAN-BEFORE-READ — the new<->old bridge comes from the
//!      move-manifest, which the materialize step regenerates from the committed move-plan and
//!      whose committed==regenerated byte-parity (registry-drift / freshness) binds it to the
//!      codemod's deterministic output; a hand-forged pair is RED before the firewall consumes the
//!      snapshot.
//! On top of those, the resolver is FAIL-CLOSED: a manifest-declared name absent from BOTH sides
//! of history, or ambiguously present on both, is a HARD ERROR — never a fallback to an empty,
//! candidate, or bootstrap reference (that empty-reference fallback is the exact laundering vector
//! the naive NEW-const flip reopens).
#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::path::Path;
use std::process::Command;

use ci_path_resolver_ports::{
    canonical_current, FrozenRefSource, MergeBaseName, MoveBijection, PathId, PathResolver,
};
use serde_json::Value;

/// The move-manifest schema id (must match the codemod's `REORG_MOVE_MANIFEST_SCHEMA`).
pub const MOVE_MANIFEST_SCHEMA: &str = "oya-ci/reorg-move-manifest/v1";

/// The committed move-manifest's canonical repo-relative path (a root-stable anchor — a well-known
/// config location, injected once, NOT a movable gate self-location).
pub const MOVE_MANIFEST_PATH: &str = "specs/reorg/move-manifest.generated.json";

// ---------------------------------------------------------------------------
// ManifestBijection
// ---------------------------------------------------------------------------

/// The old<->new bijection from the committed move-manifest `files[]`. FAIL-CLOSED: a
/// foreign/absent schema, any malformed row, or a non-injective side yields the EMPTY bijection
/// (identity — no pending move), so the resolver reads the honest current-name reference.
#[derive(Debug, Clone, Default)]
pub struct ManifestBijection {
    old_to_new: BTreeMap<String, String>,
    new_to_old: BTreeMap<String, String>,
}

impl ManifestBijection {
    /// The empty (identity) bijection.
    pub fn empty() -> Self {
        Self::default()
    }

    pub fn is_empty(&self) -> bool {
        self.old_to_new.is_empty()
    }

    /// Parse a manifest `Value` fail-closed. MUST-PASS #3: BOTH sides injective — a duplicated
    /// old_path OR a duplicated new_path collapses to the empty bijection (an ambiguous map is
    /// never partially trusted).
    pub fn from_manifest_value(value: &Value) -> Self {
        if value.get("schema").and_then(Value::as_str) != Some(MOVE_MANIFEST_SCHEMA) {
            return Self::empty();
        }
        let mut old_to_new: BTreeMap<String, String> = BTreeMap::new();
        let mut new_to_old: BTreeMap<String, String> = BTreeMap::new();
        if let Some(files) = value.get("files").and_then(Value::as_array) {
            for row in files {
                match (
                    row.get("old_path").and_then(Value::as_str),
                    row.get("new_path").and_then(Value::as_str),
                ) {
                    (Some(old), Some(new)) if !old.is_empty() && !new.is_empty() => {
                        // A malformed/duplicate row poisons the WHOLE manifest fail-closed
                        // (identity) rather than silently trusting a partial, ambiguous map.
                        if old_to_new.insert(old.to_owned(), new.to_owned()).is_some() {
                            return Self::empty(); // old-side collision (not injective)
                        }
                        if new_to_old.insert(new.to_owned(), old.to_owned()).is_some() {
                            return Self::empty(); // new-side collision — MUST-PASS #3
                        }
                    }
                    _ => return Self::empty(),
                }
            }
        }
        Self {
            old_to_new,
            new_to_old,
        }
    }

    /// Load + parse the committed manifest from the candidate tree fail-closed (missing/unreadable/
    /// unparseable => empty). The registry-drift/freshness byte-binding is the trust root; this is
    /// the in-adapter shape guard.
    pub fn load(repo_root: &Path, manifest_rel_path: &str) -> Self {
        let path = repo_root.join(manifest_rel_path);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return Self::empty();
        };
        match serde_json::from_str::<Value>(&text) {
            Ok(value) => Self::from_manifest_value(&value),
            Err(_) => Self::empty(),
        }
    }
}

impl MoveBijection for ManifestBijection {
    fn new_to_old(&self, new_path: &str) -> Option<&str> {
        self.new_to_old.get(new_path).map(String::as_str)
    }
    fn old_to_new(&self, old_path: &str) -> Option<&str> {
        self.old_to_new.get(old_path).map(String::as_str)
    }
}

// ---------------------------------------------------------------------------
// GitCliFrozenRefSource
// ---------------------------------------------------------------------------

/// The live git merge-base seam (ADR-0515 D3 single sanctioned git boundary). Fail-closed: an
/// unresolvable ref/merge-base is a HARD error (never a silent PR-controlled fallback).
pub struct GitCliFrozenRefSource<'a> {
    repo_root: &'a Path,
}

impl<'a> GitCliFrozenRefSource<'a> {
    pub fn new(repo_root: &'a Path) -> Self {
        Self { repo_root }
    }
}

impl FrozenRefSource for GitCliFrozenRefSource<'_> {
    fn merge_base(&self, base_ref: &str) -> Result<String, String> {
        let output = Command::new("git")
            .arg("-C")
            .arg(self.repo_root)
            .args(["merge-base", base_ref, "HEAD"])
            .output()
            .map_err(|e| format!("merge-base: {e}"))?;
        if !output.status.success() {
            return Err(format!(
                "git merge-base {base_ref} HEAD failed (exit {:?}): {} — the frozen ratchet \
                 reference REQUIRES the base ref; fetch it or repoint ratchet-policy.json base_ref",
                output.status.code(),
                String::from_utf8_lossy(&output.stderr).trim()
            ));
        }
        let sha = String::from_utf8_lossy(&output.stdout).trim().to_owned();
        if sha.len() < 40 || !sha.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(format!("git merge-base produced a non-revision: {sha:?}"));
        }
        Ok(sha)
    }

    fn show_file(&self, revision: &str, path: &str) -> Result<Option<String>, String> {
        let spec = format!("{revision}:{path}");
        let exists = Command::new("git")
            .arg("-C")
            .arg(self.repo_root)
            .args(["cat-file", "-e", &spec])
            .output()
            .map_err(|e| format!("cat-file: {e}"))?;
        if !exists.status.success() {
            return Ok(None);
        }
        let output = Command::new("git")
            .arg("-C")
            .arg(self.repo_root)
            .args(["show", &spec])
            .output()
            .map_err(|e| format!("show: {e}"))?;
        if !output.status.success() {
            return Err(format!(
                "git show {spec} failed (exit {:?}): {}",
                output.status.code(),
                String::from_utf8_lossy(&output.stderr).trim()
            ));
        }
        String::from_utf8(output.stdout)
            .map(Some)
            .map_err(|e| format!("show {spec}: {e}"))
    }
}

// ---------------------------------------------------------------------------
// ManifestPathResolver
// ---------------------------------------------------------------------------

/// The move-aware resolver: compiled current-canonical seed on the candidate side, manifest +
/// immutable-history driven on the merge-base side.
pub struct ManifestPathResolver {
    bijection: ManifestBijection,
}

impl ManifestPathResolver {
    pub fn new(bijection: ManifestBijection) -> Self {
        Self { bijection }
    }

    /// Load the resolver from the candidate tree (committed manifest, fail-closed).
    pub fn load(repo_root: &Path) -> Self {
        Self::new(ManifestBijection::load(repo_root, MOVE_MANIFEST_PATH))
    }
}

impl PathResolver for ManifestPathResolver {
    fn candidate(&self, id: PathId) -> String {
        // The current canonical (post-move NEW) location. `old_to_new` handles the defensive case
        // where the compiled seed is still a pre-move OLD name during the landing PR; once the seed
        // is rebased NEW it is not an old-key, so this is the identity (seed) — the stable path.
        let seed = canonical_current(id);
        self.bijection
            .old_to_new(seed)
            .map(str::to_owned)
            .unwrap_or_else(|| seed.to_owned())
    }

    fn at_merge_base(
        &self,
        id: PathId,
        merge_base: &str,
        src: &dyn FrozenRefSource,
    ) -> Result<MergeBaseName, String> {
        let candidate = self.candidate(id);
        match self.bijection.new_to_old(&candidate) {
            // A pending move declares a pre-move OLD name for this path.
            Some(old) => {
                let old = old.to_owned();
                let old_present = src.show_file(merge_base, &old)?.is_some();
                let new_present = src.show_file(merge_base, &candidate)?.is_some();
                match (old_present, new_present) {
                    // Ambiguous: both names present at the merge-base (double-write / stem
                    // collision). HARD ERROR (MUST-PASS #2 / spec §1.2 step 5) — never guess.
                    (true, true) => Err(format!(
                        "move-manifest declares {old:?} -> {candidate:?} but BOTH are present at \
                         merge-base {merge_base} — ambiguous frozen reference, fail-closed"
                    )),
                    // Genuine pending move (the move PR): the file is under its OLD name at the
                    // pre-move merge-base. Read the frozen reference there.
                    (true, false) => Ok(MergeBaseName::Present(old)),
                    // The move already landed in merge-base history (STRADDLE — MUST-PASS #5: a
                    // rebase PAST the move commit puts NEW, not OLD, at the merge-base). Read the
                    // NEW name — PRESENCE-VERIFIED in immutable history, identical content — so a
                    // merged move cannot hard-error every subsequent PR. NOT an empty fallback.
                    (false, true) => Ok(MergeBaseName::Present(candidate)),
                    // The manifest declares a pre-move name that is absent from BOTH sides of
                    // history: the manifest lies about the pre-move state. HARD ERROR (MUST-PASS
                    // #2) — NEVER fall back to bootstrap/candidate/empty (that reopens laundering).
                    (false, false) => Err(format!(
                        "move-manifest declares {old:?} -> {candidate:?} but NEITHER is present at \
                         merge-base {merge_base} — refusing an empty/forged frozen reference, \
                         fail-closed"
                    )),
                }
            }
            // No pending move for this path: read it at its current name.
            None => match src.show_file(merge_base, &candidate)? {
                Some(_) => Ok(MergeBaseName::Present(candidate)),
                // Genuinely absent and NOT a declared move => genuine repo bootstrap (the PR that
                // introduces the file). Feeds the existing `missing_at_merge_base` path unchanged.
                None => Ok(MergeBaseName::Absent),
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fake merge-base tree: the set of paths that "exist" at the merge-base, each with content.
    struct FakeSource {
        present: BTreeMap<String, String>,
    }
    impl FakeSource {
        fn with(paths: &[(&str, &str)]) -> Self {
            Self {
                present: paths
                    .iter()
                    .map(|(p, c)| ((*p).to_owned(), (*c).to_owned()))
                    .collect(),
            }
        }
    }
    impl FrozenRefSource for FakeSource {
        fn merge_base(&self, _base_ref: &str) -> Result<String, String> {
            Ok("0".repeat(40))
        }
        fn show_file(&self, _revision: &str, path: &str) -> Result<Option<String>, String> {
            Ok(self.present.get(path).cloned())
        }
    }

    const OLD: &str = "cloud/cloud-ci/gates/oya-cloud-ci-firewall-app/ratchet-policy.json";
    const NEW: &str = "ci/facade/baseline-ratchet/ratchet-policy.json";

    fn manifest_with(pairs: &[(&str, &str)]) -> Value {
        serde_json::json!({
            "schema": MOVE_MANIFEST_SCHEMA,
            "files": pairs.iter().map(|(o, n)| serde_json::json!({"old_path": o, "new_path": n})).collect::<Vec<_>>(),
        })
    }

    fn resolver_with(pairs: &[(&str, &str)]) -> ManifestPathResolver {
        ManifestPathResolver::new(ManifestBijection::from_manifest_value(&manifest_with(pairs)))
    }

    /// MUST-PASS #1: `candidate` is the compiled seed — it consults NO candidate data file, and is
    /// the NEW path. (The seed itself is compiled; there is no input through which a candidate tree
    /// could repoint it.)
    #[test]
    fn candidate_is_the_compiled_new_seed() {
        let r = resolver_with(&[(OLD, NEW)]);
        assert_eq!(r.candidate(PathId::RatchetPolicy), NEW);
        // Even with an EMPTY manifest the candidate is the compiled NEW seed (never OLD).
        let r0 = resolver_with(&[]);
        assert_eq!(r0.candidate(PathId::RatchetPolicy), NEW);
    }

    /// Genuine move PR: OLD present at the pre-move merge-base, NEW absent => read OLD.
    #[test]
    fn move_pr_reads_old_at_pre_move_merge_base() {
        let r = resolver_with(&[(OLD, NEW)]);
        let src = FakeSource::with(&[(OLD, "policy")]);
        assert_eq!(
            r.at_merge_base(PathId::RatchetPolicy, "mb", &src).unwrap(),
            MergeBaseName::Present(OLD.to_owned())
        );
    }

    /// MUST-PASS #5 (straddle): move already in merge-base history — OLD absent, NEW present =>
    /// read NEW (present-verified), NOT a hard error, NOT an empty reference.
    #[test]
    fn straddle_reads_new_when_move_already_in_history() {
        let r = resolver_with(&[(OLD, NEW)]);
        let src = FakeSource::with(&[(NEW, "policy")]);
        assert_eq!(
            r.at_merge_base(PathId::RatchetPolicy, "mb", &src).unwrap(),
            MergeBaseName::Present(NEW.to_owned())
        );
    }

    /// MUST-PASS #2 (both absent): manifest declares OLD->NEW but NEITHER exists at the merge-base
    /// => HARD ERROR (never empty/bootstrap/candidate fallback — the laundering vector).
    #[test]
    fn both_absent_is_hard_error_not_empty() {
        let r = resolver_with(&[(OLD, NEW)]);
        let src = FakeSource::with(&[]); // neither present
        let err = r
            .at_merge_base(PathId::RatchetPolicy, "mb", &src)
            .unwrap_err();
        assert!(err.contains("NEITHER"), "unexpected error: {err}");
    }

    /// MUST-PASS #2 (both present): ambiguous double-write at the merge-base => HARD ERROR.
    #[test]
    fn both_present_is_hard_error_ambiguous() {
        let r = resolver_with(&[(OLD, NEW)]);
        let src = FakeSource::with(&[(OLD, "a"), (NEW, "b")]);
        let err = r
            .at_merge_base(PathId::RatchetPolicy, "mb", &src)
            .unwrap_err();
        assert!(err.contains("BOTH"), "unexpected error: {err}");
    }

    /// No pending move + file absent at merge-base => Absent (genuine bootstrap), NOT an error:
    /// preserves the existing `missing_at_merge_base` path (MUST-PASS #4 support).
    #[test]
    fn no_move_and_absent_is_bootstrap_absent() {
        let r = resolver_with(&[]); // empty manifest
        let src = FakeSource::with(&[]);
        assert_eq!(
            r.at_merge_base(PathId::RatchetPolicy, "mb", &src).unwrap(),
            MergeBaseName::Absent
        );
    }

    /// No pending move + file present at merge-base under its current name => Present(NEW).
    #[test]
    fn no_move_and_present_reads_current_name() {
        let r = resolver_with(&[]);
        let src = FakeSource::with(&[(NEW, "policy")]);
        assert_eq!(
            r.at_merge_base(PathId::RatchetPolicy, "mb", &src).unwrap(),
            MergeBaseName::Present(NEW.to_owned())
        );
    }

    /// MUST-PASS #3 (new-side injectivity): a manifest whose NEW side is non-injective (two OLDs
    /// map to the same NEW) is rejected to the EMPTY bijection — `new_to_old` would otherwise be
    /// ill-defined. (The stock parser only checked old-side uniqueness.)
    #[test]
    fn new_side_non_injective_manifest_collapses_to_empty() {
        let b = ManifestBijection::from_manifest_value(&manifest_with(&[
            ("old/a", "new/shared"),
            ("old/b", "new/shared"),
        ]));
        assert!(b.is_empty(), "non-injective new side must fail closed to empty");
        assert_eq!(b.new_to_old("new/shared"), None);
    }

    /// Old-side injectivity is also enforced (duplicate old_path => empty).
    #[test]
    fn old_side_non_injective_manifest_collapses_to_empty() {
        let b = ManifestBijection::from_manifest_value(&manifest_with(&[
            ("old/a", "new/x"),
            ("old/a", "new/y"),
        ]));
        assert!(b.is_empty(), "non-injective old side must fail closed to empty");
    }

    /// A foreign schema fails closed to empty (identity).
    #[test]
    fn foreign_schema_is_empty() {
        let v = serde_json::json!({"schema": "not-ours", "files": [{"old_path": OLD, "new_path": NEW}]});
        assert!(ManifestBijection::from_manifest_value(&v).is_empty());
    }

    /// A malformed row poisons the whole manifest fail-closed.
    #[test]
    fn malformed_row_is_empty() {
        let v = serde_json::json!({"schema": MOVE_MANIFEST_SCHEMA, "files": [{"old_path": OLD}]});
        assert!(ManifestBijection::from_manifest_value(&v).is_empty());
    }

    /// Sanity: the built bijection is a real inverse pair on a well-formed manifest.
    #[test]
    fn well_formed_bijection_inverts() {
        let b = ManifestBijection::from_manifest_value(&manifest_with(&[(OLD, NEW)]));
        assert_eq!(b.old_to_new(OLD), Some(NEW));
        assert_eq!(b.new_to_old(NEW), Some(OLD));
    }
}
