rust_library(
    name = "oya-ci-tide-github-adapter",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml"]),
    crate = "oya_ci_tide_github_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//ci/core/tide-kernel:ci-tide-kernel",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
