//! The production module table: one row per product surface the shell can
//! render. `shell_capability_registry` derives the locked-contract entries and
//! routes from these rows; `shell_context_grants` decides which contexts see them.

/// One production module surface: the locked-contract registry row plus the
/// shell display metadata used to render its module card.
pub(crate) struct RegisteredModule {
    pub(crate) capability_id: &'static str,
    pub(crate) display_name: &'static str,
    pub(crate) module_id: &'static str,
    pub(crate) required_action: &'static str,
    pub(crate) route_prefix: &'static str,
    pub(crate) upstream_service: &'static str,
    pub(crate) group: &'static str,
    pub(crate) description: &'static str,
    pub(crate) action_label: &'static str,
}

pub(crate) const PRODUCTION_MODULES: &[RegisteredModule] = &[
    RegisteredModule {
        capability_id: "tenant-admin",
        display_name: "Tenant Admin",
        module_id: "tenancy",
        required_action: "tenancy.administer",
        route_prefix: "/tenancy",
        upstream_service: "tenancy",
        group: "Control",
        description: "Users, roles, packs, residency, module enablement",
        action_label: "Review posture",
    },
    RegisteredModule {
        capability_id: "cloud-compute",
        display_name: "Cloud Compute",
        module_id: "cloud-compute",
        required_action: "compute.operate",
        route_prefix: "/cloud-compute",
        upstream_service: "cloud-compute",
        group: "Cloud",
        description: "VMs, functions, Kubernetes workloads, and runtime tiers",
        action_label: "Open compute",
    },
    RegisteredModule {
        capability_id: "cloud-network",
        display_name: "Cloud Network",
        module_id: "cloud-network",
        required_action: "network.operate",
        route_prefix: "/cloud-network",
        upstream_service: "cloud-network",
        group: "Cloud",
        description: "VPC, DNS, load balancing, ingress posture",
        action_label: "Open network",
    },
    RegisteredModule {
        capability_id: "finops",
        display_name: "FinOps",
        module_id: "finops",
        required_action: "finops.review",
        route_prefix: "/finops",
        upstream_service: "finops",
        group: "Operations",
        description: "Cost allocation, budgets, sustainability views",
        action_label: "Review spend",
    },
    RegisteredModule {
        capability_id: "audit-chain",
        display_name: "Audit Chain",
        module_id: "audit",
        required_action: "audit.inspect",
        route_prefix: "/audit",
        upstream_service: "audit",
        group: "Trust",
        description: "Sealed evidence and policy event review",
        action_label: "Inspect evidence",
    },
    RegisteredModule {
        capability_id: "work-home",
        display_name: "Work Home",
        module_id: "workspace",
        required_action: "workspace.use",
        route_prefix: "/workspace",
        upstream_service: "workspace",
        group: "Daily",
        description: "Tasks, calendar, mail, messenger, and approvals",
        action_label: "Open home",
    },
    RegisteredModule {
        capability_id: "mail",
        display_name: "Mail",
        module_id: "mail",
        required_action: "mail.use",
        route_prefix: "/mail",
        upstream_service: "mail",
        group: "Daily",
        description: "Mailboxes, threads, and submission over IMAP and JMAP",
        action_label: "Open mail",
    },
    RegisteredModule {
        capability_id: "accounting",
        display_name: "Accounting",
        module_id: "accounting",
        required_action: "accounting.close",
        route_prefix: "/accounting",
        upstream_service: "accounting",
        group: "Corporate",
        description: "Invoices, close tasks, budgets, and exceptions",
        action_label: "Review close",
    },
    RegisteredModule {
        capability_id: "human-resources",
        display_name: "Human Resources",
        module_id: "human-resources",
        required_action: "hr.operate",
        route_prefix: "/human-resources",
        upstream_service: "human-resources",
        group: "Corporate",
        description: "Onboarding, policy acknowledgements, and payroll workflows",
        action_label: "Open HR",
    },
    RegisteredModule {
        capability_id: "approvals",
        display_name: "Approvals",
        module_id: "approvals",
        required_action: "approvals.review",
        route_prefix: "/approvals",
        upstream_service: "approvals",
        group: "Workflow",
        description: "Plain-language approvals with policy context",
        action_label: "Review queue",
    },
    RegisteredModule {
        capability_id: "workflow-studio",
        display_name: "Workflow Studio",
        module_id: "workflow-studio",
        required_action: "workflow.design",
        route_prefix: "/workflow-studio",
        upstream_service: "workflow-studio",
        group: "No-code",
        description: "Design approvals and operating workflows safely",
        action_label: "Open studio",
    },
    RegisteredModule {
        capability_id: "clinical-home",
        display_name: "Clinical Home",
        module_id: "clinical",
        required_action: "care.home",
        route_prefix: "/clinical",
        upstream_service: "clinical",
        group: "Healthcare",
        description: "Care tasks, visits, and secure team messages",
        action_label: "Open home",
    },
    RegisteredModule {
        capability_id: "patient-schedule",
        display_name: "Patient Schedule",
        module_id: "patient-schedule",
        required_action: "care.schedule",
        route_prefix: "/patient-schedule",
        upstream_service: "patient-schedule",
        group: "Healthcare",
        description: "Visit flow with compliance-safe placeholders",
        action_label: "Review schedule",
    },
    RegisteredModule {
        capability_id: "care-workflows",
        display_name: "Care Workflows",
        module_id: "care-workflows",
        required_action: "care.workflows",
        route_prefix: "/care-workflows",
        upstream_service: "care-workflows",
        group: "Healthcare",
        description: "Accredited workflow templates for care coordination",
        action_label: "Open workflows",
    },
    RegisteredModule {
        capability_id: "secure-messenger",
        display_name: "Secure Messenger",
        module_id: "secure-messenger",
        required_action: "care.message",
        route_prefix: "/secure-messenger",
        upstream_service: "secure-messenger",
        group: "Healthcare",
        description: "Team communication with care-context labels",
        action_label: "Open messages",
    },
    RegisteredModule {
        capability_id: "foundry-ontology",
        display_name: "Ontology",
        module_id: "ontology",
        required_action: "foundry.ontology.use",
        route_prefix: "/ontology",
        upstream_service: "foundry-ontology",
        group: "Data",
        description: "Object types, instances, actions, and their audit trail",
        action_label: "Open ontology",
    },
];
