rust_library(
    name = "k8s-control-plane-host-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_control_plane_host_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "k8s-control-plane-host-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_control_plane_host_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
