rust_library(
    name = "iam-tenant-rbac-tenant-autoscaling-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_autoscaling_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "iam-tenant-rbac-tenant-autoscaling-contract-autoscaling",
    srcs = ["tests/autoscaling.rs"],
    crate = "iam_tenant_rbac_tenant_autoscaling_contract_autoscaling",
    crate_root = "tests/autoscaling.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-autoscaling-contract",
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)
