rust_library(
    name = "comms-messenger-stream-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_stream_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/core/messenger-stream-app:comms-messenger-stream-app",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
        "//comms/core/messenger-stream-usecase:comms-messenger-stream-usecase",
    ],
)

rust_test(
    name = "comms-messenger-stream-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_stream_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/core/messenger-stream-app:comms-messenger-stream-app",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
        "//comms/core/messenger-stream-usecase:comms-messenger-stream-usecase",
    ],
)

rust_test(
    name = "comms-messenger-stream-rest-list-messages-read-path",
    srcs = ["tests/list_messages_read_path.rs"],
    crate = "comms_messenger_stream_rest_list_messages_read_path",
    crate_root = "tests/list_messages_read_path.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":comms-messenger-stream-rest",
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/core/messenger-stream-app:comms-messenger-stream-app",
        "//comms/ports/messenger-stream-api:comms-messenger-stream-api",
        "//comms/core/messenger-stream-usecase:comms-messenger-stream-usecase",
    ],
)
