rust_library(
    name = "k8s-control-plane-host-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_control_plane_host_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/adapters/control-plane-host-adapter-capi:k8s-control-plane-host-adapter-capi",
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:axum",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "k8s-control-plane-host-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_control_plane_host_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/adapters/control-plane-host-adapter-capi:k8s-control-plane-host-adapter-capi",
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:axum",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "k8s-control-plane-host-app-acceptance",
    srcs = ["tests/acceptance.rs"],
    crate = "k8s_control_plane_host_app_acceptance",
    crate_root = "tests/acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":k8s-control-plane-host-app",
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:axum",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)

rust_binary(
    name = "k8s-control-plane-host",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/facade/control-plane-host-app:k8s-control-plane-host-app",
        "//k8s/adapters/control-plane-host-adapter-capi:k8s-control-plane-host-adapter-capi",
        "//k8s/adapters/control-plane-host-adapter-inmemory:k8s-control-plane-host-adapter-inmemory",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/core/control-plane-host-kernel:k8s-control-plane-host-kernel",
        "third-party//:axum",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
