rust_library(
    name = "intelligence-codeview-cli",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_codeview_cli",
    crate_root = "src/lib.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "intelligence-codeview-cli"},
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow",
        "third-party//:chrono",
        "third-party//:clap",
        "third-party//:regex",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:walkdir",
    ],
)

rust_binary(
    name = "intelligence-codeview-cli-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_VERSION": "0.1.0", "CARGO_PKG_NAME": "intelligence-codeview-cli"},
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/adapters/codeview-cli:intelligence-codeview-cli",
        "third-party//:anyhow",
        "third-party//:chrono",
        "third-party//:clap",
        "third-party//:regex",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:walkdir",
    ],
)
