rust_library(
    name = "oya-governance-byok-disambiguation",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_governance_byok_disambiguation",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_yaml",
        "third-party//:walkdir-2",
    ],
)

rust_binary(
    name = "oya-governance-byok-disambiguation-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/cli.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-byok-disambiguation:oya-governance-byok-disambiguation",
        "third-party//:anyhow-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_yaml",
        "third-party//:walkdir-2",
    ],
)
