rust_library(
    name = "oya-warehouse-inventory-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_warehouse_inventory_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-warehouse-inventory-domain-inventory",
    srcs = ["tests/inventory.rs"],
    crate = "oya_warehouse_inventory_domain_inventory",
    crate_root = "tests/inventory.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-warehouse-inventory-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
