rust_library(
    name = "oya-learning-management-course-progress-service",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_learning_management_course_progress_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-learning-management-service",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/learning-management/crates/oya-learning-management-course-progress-service:oya-learning-management-course-progress-service",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
