rust_library(
    name = "oya-intelligence-autonomy-ceiling-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_autonomy_ceiling_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/autonomy-ceiling-domain:intelligence-autonomy-ceiling-domain",
        "//intelligence/core/autonomy-ceiling-kernel:intelligence-autonomy-ceiling-kernel",
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-autonomy-ceiling-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_autonomy_ceiling_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/autonomy-ceiling-domain:intelligence-autonomy-ceiling-domain",
        "//intelligence/core/autonomy-ceiling-kernel:intelligence-autonomy-ceiling-kernel",
        "//intelligence/core/capability-registry-kernel:intelligence-capability-registry-kernel",
    ],
)
