[package]
name = "oya-payroll-run-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-payroll-run-domain = { path = "../oya-payroll-run-domain" }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
oya-hr-employment-api = { path = "../../../hr/crates/oya-hr-employment-api" }
oya-hr-employment-app = { path = "../../../hr/crates/oya-hr-employment-app" }
oya-payroll-run-app = { path = "../oya-payroll-run-app" }
serde_json = { workspace = true }

[lib]
name = "oya_payroll_run_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
