buildscript.run = false

['cfg(target_arch = "aarch64")']
cfgs = ["asm", "switchable_stack"]

[['cfg(target_arch = "aarch64")'.cxx_library]]
name = "psm_asm"
srcs = ["src/arch/aarch_aapcs64.s"]
headers = ["src/arch/psm.h", "src/arch/gnu_stack_note.s"]
compiler_flags = ["-xassembler-with-cpp"]
preprocessor_flags = [
    "-DCFG_TARGET_ARCH_aarch64",
    "-DCFG_TARGET_ENV_",
]
preprocessor_flags_select = [
    { "prelude//os:linux" = ["-DCFG_TARGET_OS_linux"], "DEFAULT" = ["-DCFG_TARGET_OS_darwin"] },
]
preferred_linkage = "static"
