rust_library(
    name = "oya-tenancy-per-tenant-quota-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_tenancy_per_tenant_quota_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
