rust_library(
    name = "workflow-execution-engine-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_execution_engine_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/adapters/execution-engine-adapter:workflow-execution-engine-adapter",
        "//workflow/ports/execution-engine-api:workflow-execution-engine-api",
    ],
)

rust_test(
    name = "workflow-execution-engine-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_execution_engine_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/adapters/execution-engine-adapter:workflow-execution-engine-adapter",
        "//workflow/ports/execution-engine-api:workflow-execution-engine-api",
    ],
)
