rust_library(
    name = "oya-recordings-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_recordings_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/meet/crates/oya-meet-domain:oya-meet-domain",
    ],
)

rust_test(
    name = "oya-recordings-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_recordings_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/meet/crates/oya-meet-domain:oya-meet-domain",
    ],
)
