[package]
name = "tenancy-cell-assignment"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
cell-placement = { path = "../../../cell/ports/placement" }
tenancy-kernel = { path = "../kernel" }

[lints]
workspace = true
