rust_library(
    name = "oya-cloud-capacity-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_capacity_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-billing/crates/oya-cloud-billing-domain:oya-cloud-billing-domain",
        "//cloud/cloud-billing/crates/oya-metering-domain:oya-metering-domain",
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//compute/core/resource:compute-resource",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-capacity-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_capacity_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-billing/crates/oya-cloud-billing-domain:oya-cloud-billing-domain",
        "//cloud/cloud-billing/crates/oya-metering-domain:oya-metering-domain",
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//compute/core/resource:compute-resource",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-cloud-capacity-domain-cloud-ops-foundation",
    srcs = ["tests/cloud_ops_foundation.rs"],
    crate = "oya_cloud_capacity_domain_cloud_ops_foundation",
    crate_root = "tests/cloud_ops_foundation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-capacity-domain",
        "//cloud/cloud-billing/crates/oya-cloud-billing-domain:oya-cloud-billing-domain",
        "//cloud/cloud-billing/crates/oya-metering-domain:oya-metering-domain",
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//compute/core/resource:compute-resource",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
