rust_library(
    name = "comms-mail-mailbox-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-app:comms-mail-mailbox-app",
        "//comms/core/mail-mailbox-usecase:comms-mail-mailbox-usecase",
    ],
)

rust_test(
    name = "comms-mail-mailbox-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_mail_mailbox_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "//comms/ports/mail-mailbox-api:comms-mail-mailbox-api",
        "//comms/core/mail-mailbox-app:comms-mail-mailbox-app",
        "//comms/core/mail-mailbox-usecase:comms-mail-mailbox-usecase",
    ],
)
