[package]
name = "comms-mail-mailbox-rest"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-mail-mailbox-app = { path = "../../core/mail-mailbox-app" }
comms-mail-mailbox-api = { path = "../../ports/mail-mailbox-api" }
comms-mail-mailbox-usecase = { path = "../../core/mail-mailbox-usecase" }
shared-hyperscaler-metrics-kernel = { path = "../../core/shared-hyperscaler-metrics-kernel" }
shared-postgres-command-kernel = { path = "../../../base/shared-postgres-command-kernel" }

[lib]
name = "comms_mail_mailbox_rest"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
