rust_library(
    name = "pipeline-repository-git-draft",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "pipeline_repository_git_draft",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//pipeline/ports/draft/repository:pipeline-repository-draft",
    ],
)

rust_test(
    name = "pipeline-repository-git-draft-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "pipeline_repository_git_draft",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//pipeline/ports/draft/repository:pipeline-repository-draft",
    ],
)
