rust_library(
    name = "intelligence-bypass-ledger-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_bypass_ledger_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "intelligence-bypass-ledger-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_bypass_ledger_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
