rust_library(
    name = "intelligence-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/application/crates/application-app:application-app",
    ],
)

rust_test(
    name = "intelligence-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/application/crates/application-app:application-app",
    ],
)

rust_test(
    name = "intelligence-api-capability-invoke-api",
    srcs = ["tests/capability_invoke_api.rs"],
    crate = "intelligence_api_capability_invoke_api",
    crate_root = "tests/capability_invoke_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-api",
        "//oya/application/crates/application-app:application-app",
    ],
)
