rust_library(
    name = "iam-tenant-rbac-statutory-filing-evidence",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_statutory_filing_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-tenant-rbac-statutory-filing-evidence-statutory-filing",
    srcs = ["tests/statutory_filing.rs"],
    crate = "iam_tenant_rbac_statutory_filing_evidence_statutory_filing",
    crate_root = "tests/statutory_filing.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-statutory-filing-evidence",
    ],
)
