rust_library(
    name = "iam-tenant-rbac-tenant-admission-policy",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_admission_policy",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "iam-tenant-rbac-tenant-admission-policy-admission-policy",
    srcs = ["tests/admission_policy.rs"],
    crate = "iam_tenant_rbac_tenant_admission_policy_admission_policy",
    crate_root = "tests/admission_policy.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)
