[package]
name = "iam-tenant-rbac-tenant-admission-policy"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-tenant-workload-manifest = { path = "../tenant-rbac-tenant-workload-manifest" }

[lib]
name = "iam_tenant_rbac_tenant_admission_policy"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
