[package]
name = "oya-foundry-fitness-banned-primitives"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "oya-foundry-fitness-banned-primitives"
path = "src/main.rs"

[dependencies]
oya-foundry-fitness-banned-primitives-kernel = { path = "../../crates/oya-foundry-fitness-banned-primitives-kernel" }
