rust_library(
    name = "oya-managed-k8s-sla-observability-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_managed_k8s_sla_observability_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/managed-k8s-control-plane-host/crates/oya-managed-k8s-control-plane-host-adapter-inmemory:oya-managed-k8s-control-plane-host-adapter-inmemory",
        "//cloud/managed-k8s-control-plane-host/crates/oya-managed-k8s-control-plane-host-api:oya-managed-k8s-control-plane-host-api",
        "//cloud/managed-k8s-sla-observability/crates/oya-managed-k8s-sla-observability-adapter-inmemory:oya-managed-k8s-sla-observability-adapter-inmemory",
        "//cloud/managed-k8s-sla-observability/crates/oya-managed-k8s-sla-observability-api:oya-managed-k8s-sla-observability-api",
        "//cloud/managed-k8s-sla-observability/crates/oya-managed-k8s-sla-observability-kernel:oya-managed-k8s-sla-observability-kernel",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
    ],
)
