[package]
name = "secrets-kms-oci"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "secrets_kms_oci"
path = "src/lib.rs"
doctest = false

[dependencies]
secrets-kms-domain = { path = "../../core/kms-domain" }

[dev-dependencies]
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }

[lints]
workspace = true
