rust_library(
    name = "oya-http-wide-event-middleware-infrastructure",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_wide_event_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/tenancy/crates/oya-tenancy-kernel:oya-tenancy-kernel",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-shared-hyperscaler-metrics-kernel:oya-shared-hyperscaler-metrics-kernel",
        "third-party//:futures-util",
        "third-party//:http",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tower",
    ],
)

rust_test(
    name = "oya-http-wide-event-middleware-infrastructure-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_wide_event_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/tenancy/crates/oya-tenancy-kernel:oya-tenancy-kernel",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-shared-hyperscaler-metrics-kernel:oya-shared-hyperscaler-metrics-kernel",
        "third-party//:futures-util",
        "third-party//:http",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tower",
    ],
)
