rust_library(
    name = "oya-http-wide-event-middleware-infrastructure",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_wide_event_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "third-party//:futures-util",
        "third-party//:http",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tower",
    ],
)

rust_test(
    name = "oya-http-wide-event-middleware-infrastructure-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_wide_event_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "third-party//:futures-util",
        "third-party//:http",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tower",
    ],
)
