rust_library(
    name = "oya-office-sheets-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_sheets_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/office/oya-office-kernel:oya-office-kernel",
        "//app/office/oya-office-sheet-domain:oya-office-sheet-domain",
    ],
)

rust_test(
    name = "oya-office-sheets-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_sheets_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/office/oya-office-kernel:oya-office-kernel",
        "//app/office/oya-office-sheet-domain:oya-office-sheet-domain",
    ],
)
