[package]
name = "oya-office-sheets-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-office-kernel = { path = "../oya-office-kernel" }
oya-office-sheet-domain = { path = "../oya-office-sheet-domain" }

[lib]
name = "oya_office_sheets_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
