rust_library(
    name = "mail-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "mail_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/mail/core/kernel:mail-kernel",
    ],
)

rust_test(
    name = "mail-api-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "mail_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/mail/core/kernel:mail-kernel",
    ],
)
