[package]
name = "oya-cloud-cell-application"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../oya-cloud-region-domain" }
oya-cell-domain = { path = "../oya-cell-domain" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_cell_application"
path = "src/lib.rs"
doctest = false
