rust_library(
    name = "oya-community-social-post-composition-adapter-postgres",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_community_social_post_composition_adapter_postgres",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
    ],
)
