[package]
name = "oya-analytics-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-shared-olap-client-kernel = { path = "../oya-shared-olap-client-kernel" }

[lib]
name = "oya_analytics_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
