rust_library(
    name = "oya-data-outbox-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_data_outbox_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "third-party//:serde",
    ],
)

rust_test(
    name = "oya-data-outbox-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_data_outbox_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
