[package]
name = "oya-mail-mailbox-store-grpc"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-mail-mailbox-store-api = { path = "../oya-mail-mailbox-store-api" }
oya-mail-mailbox-store-app = { path = "../oya-mail-mailbox-store-app" }
oya-shared-postgres-command-kernel = { path = "../oya-shared-postgres-command-kernel" }
oya-shared-protocol-transport-kernel = { path = "../oya-shared-protocol-transport-kernel" }

[lib]
name = "oya_mail_mailbox_store_grpc"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
