rust_library(
    name = "tenancy-tenant-lifecycle-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tenancy/core/tenant-lifecycle-domain:tenancy-tenant-lifecycle-domain",
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "//compute/core/resource-provider-contract-kernel:shared-resource-provider-contract-kernel",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "tenancy-tenant-lifecycle-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "tenancy_tenant_lifecycle_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tenancy/core/tenant-lifecycle-domain:tenancy-tenant-lifecycle-domain",
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "//compute/core/resource-provider-contract-kernel:shared-resource-provider-contract-kernel",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "tenancy-tenant-lifecycle-usecase-conformance",
    srcs = glob(["tests/**/*.rs"]),
    crate = "tenancy_tenant_lifecycle_usecase_conformance",
    crate_root = "tests/conformance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":tenancy-tenant-lifecycle-usecase",
        "//tenancy/core/tenant-lifecycle-domain:tenancy-tenant-lifecycle-domain",
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "//compute/core/resource-provider-contract-kernel:shared-resource-provider-contract-kernel",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "tenancy-tenant-lifecycle-usecase-reconcile",
    srcs = glob(["tests/**/*.rs"]),
    crate = "tenancy_tenant_lifecycle_usecase_reconcile",
    crate_root = "tests/reconcile.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":tenancy-tenant-lifecycle-usecase",
        "//tenancy/core/tenant-lifecycle-domain:tenancy-tenant-lifecycle-domain",
        "//tenancy/core/tenant-lifecycle-kernel:tenancy-tenant-lifecycle-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "//compute/core/resource-provider-contract-kernel:shared-resource-provider-contract-kernel",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)
