[package]
name = "oya-messenger-message-stream-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-shared-protocol-parity-kernel = { path = "../oya-shared-protocol-parity-kernel" }

[lib]
name = "oya_messenger_message_stream_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
