rust_library(
    name = "oya-shared-pdp-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-shared-pdp-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
