[package]
name = "workflow-trigger-orchestrator-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-trigger-orchestrator-kernel = { path = "../trigger-orchestrator-kernel" }

[lib]
name = "workflow_trigger_orchestrator_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
