[package]
name = "oya-http-middleware-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
bytes.workspace = true
oya-http-router-kernel = { path = "../oya-http-router-kernel" }

[lib]
name = "oya_http_middleware_kernel"
path = "src/lib.rs"
doctest = false
