rust_library(
    name = "oya-workflow-engine-event-bus-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_event_bus_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-event-bus-kernel:oya-workflow-engine-event-bus-kernel",
    ],
)
