rust_library(
    name = "oya-authn-device-firmware",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_authn_device_firmware",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
