rust_library(
    name = "oya-mail-mailbox-store-grpc",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_mail_mailbox_store_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//oya/mail/crates/oya-mail-mailbox-store-api:oya-mail-mailbox-store-api",
        "//oya/mail/crates/oya-mail-mailbox-store-app:oya-mail-mailbox-store-app",
    ],
)
