[package]
name = "oya-foundry-eval-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-eval-domain = { path = "../oya-foundry-eval-domain" }

[lib]
name = "oya_foundry_eval_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
