use compute_resource::CloudResourceError;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CloudNetworkError {
    InvalidTenantId,
    InvalidResourceId,
    ResourceTenantMismatch,
    ResourceRegionMismatch,
    ResourceKindMismatch,
    InvalidDataClass,
    InvalidVpcState,
    InvalidSubnetState,
    InvalidLbState,
    InvalidDnsZoneState,
    InvalidIpv4Cidr,
    InvalidIpv6Cidr,
    Ipv6Required,
    InvalidRouteTableId,
    InvalidRoute,
    DuplicateRoute,
    InvalidSecurityGroupId,
    InvalidSecurityRule,
    DuplicateSecurityGroup,
    InvalidAzCode,
    AzRegionMismatch,
    SubnetOutsideVpc,
    OverlappingSubnet,
    DuplicateSubnet,
    UnknownVpc,
    UnknownSubnet,
    InvalidTargetGroupId,
    DuplicateTargetGroup,
    InvalidListener,
    DuplicateListenerPort,
    ListenerTargetGroupMissing,
    L7RequiresTls,
    GrpcRequiresMtls,
    InvalidCertificateRef,
    InvalidWafPolicyId,
    InvalidDnsName,
    InvalidDnssecKeyRef,
    DnssecRequired,
    PrivateZoneRequiresVpc,
    PublicZoneMustNotBindVpc,
    InvalidCdnState,
    InvalidCdnOrigin,
    DuplicateCdnOrigin,
    UnknownLoadBalancer,
    UnknownDnsZone,
    CdnWafRequired,
    CdnTlsRequired,
    DuplicateCdnHostname,
    InvalidInterconnectPartnerId,
    InvalidInterconnectPortId,
    InvalidPeeringLocation,
    InvalidInterconnectState,
    InvalidBandwidth,
    InvalidVlanTag,
    InvalidBgpSessionId,
    InvalidBgpSession,
    DuplicateBgpSession,
    InvalidAsn,
    InterconnectRedundancyRequired,
    InterconnectSlaRequired,
    RegionalInterconnectDiversityRequired,
    UnknownInterconnectPartner,
    DuplicateInterconnectPartner,
    DuplicateDirectInterconnect,
    InvalidDdosState,
    UnknownProtectedResource,
    DuplicateProtectedResource,
    ScrubbingRegionRequired,
    LineRateScrubbingRequired,
    DdosAlwaysOnRequired,
    InvalidRunbookRef,
    InvalidOnCallGroupRef,
    DuplicateDdosProtection,
    InvalidMeshId,
    InvalidCellId,
    InvalidMeshNamespace,
    InvalidMeshState,
    InvalidMeshMode,
    InvalidMeshGateway,
    MeshMtlsRequired,
    MeshExtAuthzRequired,
    InvalidCedarPolicyRef,
    InvalidAuditStreamRef,
    InvalidHealthAlarmRef,
    MeshControlPlaneReplicasRequired,
    MeshUpgradeDrillRequired,
    DefaultDenyIngressRequired,
    DefaultDenyEgressRequired,
    DnsEgressExceptionRequired,
    CrossCellDefaultTrafficForbidden,
    EnvoyExtAuthzRequired,
    EnvoyFailClosedRequired,
    CoreDnsInsecurePodModeForbidden,
    EvidenceRefMissing,
    EvidenceRefLooksSecretLike,
    DuplicateServiceMesh,
    InvalidFlowAnomalyId,
    FlowLogsRequired,
    DuplicateFlowAnomaly,
    DuplicateVpc,
    DuplicateLoadBalancer,
    DuplicateDnsZone,
    DuplicateCdnDistribution,
    /// A CIDR string stored directly in an `Ipv4Cidr` or `Ipv6Cidr` value
    /// field could not be parsed (e.g. bypassed the constructor).
    InvalidCidrPrefix,
}

pub(crate) fn map_resource_error(error: CloudResourceError) -> CloudNetworkError {
    match error {
        CloudResourceError::InvalidResourceId => CloudNetworkError::InvalidResourceId,
        CloudResourceError::ResourceIdTenantMismatch => CloudNetworkError::ResourceTenantMismatch,
        CloudResourceError::ResourceIdRegionMismatch => CloudNetworkError::ResourceRegionMismatch,
        CloudResourceError::ResourceIdKindMismatch => CloudNetworkError::ResourceKindMismatch,
        CloudResourceError::InvalidTenantId => CloudNetworkError::InvalidTenantId,
        _ => CloudNetworkError::InvalidResourceId,
    }
}
