rust_library(
    name = "oya-cloud-iac-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_iac_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-iac/crates/oya-cloud-iac-api:oya-cloud-iac-api",
        "//cloud/cloud-iac/crates/oya-cloud-iac-domain:oya-cloud-iac-domain",
        "//cloud/cloud-iac/crates/oya-cloud-iac-runtime:oya-cloud-iac-runtime",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "third-party//:sha2",
    ],
)

rust_binary(
    name = "oya-cloud-iac",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-iac/crates/oya-cloud-iac-app:oya-cloud-iac-app",
        "//cloud/cloud-iac/crates/oya-cloud-iac-api:oya-cloud-iac-api",
        "//cloud/cloud-iac/crates/oya-cloud-iac-domain:oya-cloud-iac-domain",
        "//cloud/cloud-iac/crates/oya-cloud-iac-runtime:oya-cloud-iac-runtime",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "third-party//:sha2",
    ],
)
