rust_library(
    name = "iam-identity-workload-svid-operator-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_svid_operator_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
    ],
)

rust_test(
    name = "iam-identity-workload-svid-operator-kernel-tests",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs"]),
    crate = "iam_identity_workload_svid_operator_kernel_tests",
    crate_root = "tests/reconcile.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-svid-operator-kernel",
        "third-party//:serde",
    ],
)
