rust_library(
    name = "oya-ops-workspace-shell-rest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_ops_workspace_shell_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ops/crates/oya-ops-workspace-shell-adapter:oya-ops-workspace-shell-adapter",
        "//oya/ops/crates/oya-ops-workspace-shell-kernel:oya-ops-workspace-shell-kernel",
        "//oya/ops/crates/oya-ops-workspace-shell-usecase:oya-ops-workspace-shell-usecase",
    ],
)
