rust_library(
    name = "oya-cloud-os-init-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_init_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-block-domain:oya-cloud-os-block-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machined-domain:oya-cloud-os-machined-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_binary(
    name = "oya-cloud-os-init-app-init-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-os-init-app",
        "//cloud/cloud-os/crates/oya-cloud-os-block-domain:oya-cloud-os-block-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machined-domain:oya-cloud-os-machined-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_binary(
    name = "oya-cloud-os-init-app-svc-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/svc.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-os-init-app",
        "//cloud/cloud-os/crates/oya-cloud-os-block-domain:oya-cloud-os-block-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machined-domain:oya-cloud-os-machined-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "third-party//:libc",
    ],
)

rust_test(
    name = "oya-cloud-os-init-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_init_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-block-domain:oya-cloud-os-block-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-cosi-domain:oya-cloud-os-cosi-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machined-domain:oya-cloud-os-machined-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "third-party//:libc",
    ],
)
