rust_library(
    name = "gateway-salesforce-connector",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "gateway_salesforce_connector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//gateway/core/connector-kernel:shared-connector-kernel",
    ],
)

rust_test(
    name = "gateway-salesforce-connector-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "gateway_salesforce_connector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//gateway/core/connector-kernel:shared-connector-kernel",
    ],
)
