rust_library(
    name = "oya-cloud-dcops-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_cloud_dcops_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
