[package]
name = "oya-cloud-dcops-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../../../cloud-cell/crates/oya-cloud-region-domain" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }

[lib]
name = "oya_cloud_dcops_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
