rust_library(
    name = "oya-cloud-intelligence-eventsink-valkey-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_intelligence_eventsink_valkey_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-intelligence/crates/oya-cloud-intelligence-kernel:oya-cloud-intelligence-kernel",
        "third-party//:redis",
        "third-party//:serde",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)

rust_test(
    name = "oya-cloud-intelligence-eventsink-valkey-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_intelligence_eventsink_valkey_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-intelligence/crates/oya-cloud-intelligence-kernel:oya-cloud-intelligence-kernel",
        "third-party//:redis",
        "third-party//:serde",
        "third-party//:tokio",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)
