rust_library(
    name = "oya-messenger-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_messenger_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//oya/messenger/crates/oya-messenger-message-stream-adapter-postgres:oya-messenger-message-stream-adapter-postgres",
        "//oya/messenger/crates/oya-messenger-message-stream-api:oya-messenger-message-stream-api",
        "//oya/messenger/crates/oya-messenger-message-stream-usecase:oya-messenger-message-stream-usecase",
    ],
)
