rust_library(
    name = "billing-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "billing-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "billing-app-integration-test",
    srcs = ["src/main.rs"],
    crate = "billing_app_main_integration_test",
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-app",
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_binary(
    name = "billing-app-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-app",
        "third-party//:tokio",
    ],
)
