rust_library(
    name = "audit-ledger-file",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "audit_ledger_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//audit/core/chain-domain:audit-chain-domain",
    ],
)

rust_test(
    name = "audit-ledger-file-file-ledger",
    srcs = ["tests/file_ledger.rs"],
    crate = "audit_ledger_file_file_ledger",
    crate_root = "tests/file_ledger.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":audit-ledger-file",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//audit/core/chain-domain:audit-chain-domain",
    ],
)
