rust_library(
    name = "oya-office-sheet-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_sheet_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/office/oya-office-drive-domain:oya-office-drive-domain",
        "//app/office/oya-office-format-domain:oya-office-format-domain",
        "//app/office/oya-office-kernel:oya-office-kernel",
    ],
)

rust_test(
    name = "oya-office-sheet-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_sheet_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/office/oya-office-drive-domain:oya-office-drive-domain",
        "//app/office/oya-office-format-domain:oya-office-format-domain",
        "//app/office/oya-office-kernel:oya-office-kernel",
    ],
)
