[package]
name = "check-adapter-with-no-importer-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "check_adapter_with_no_importer_kernel"
path = "src/lib.rs"
doctest = false

[dependencies]

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
