rust_library(
    name = "ci-planning-projection",
    srcs = glob(["src/**/*.rs"]),
    crate = "ci_planning_projection",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "ci-planning-projection-unittest",
    srcs = glob(["src/**/*.rs", "src/**/*.json"]),
    crate = "ci_planning_projection",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde_json",
    ],
)
