rust_library(
    name = "oya-community-post-store-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_post_store_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-hyperscaler-metrics-kernel:oya-shared-hyperscaler-metrics-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//oya/community/crates/oya-community-post-store-api:oya-community-post-store-api",
        "//oya/community/crates/oya-community-post-store-app:oya-community-post-store-app",
        "//oya/community/crates/oya-community-post-store-domain:oya-community-post-store-domain",
        "//oya/community/crates/oya-community-post-store-usecase:oya-community-post-store-usecase",
    ],
)
