[package]
name = "oya-governance-authoritative-tracked-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "oya-governance-authoritative-tracked-app"
path = "src/main.rs"

[dependencies]
oya-governance-authoritative-tracked-kernel = { path = "../../libs/oya-governance-authoritative-tracked-kernel" }

[lints]
workspace = true
