rust_library(
    name = "intelligence-attribution-worker",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_attribution_worker",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/adapters/attribution-adapter:intelligence-attribution-adapter",
        "//intelligence/core/attribution-usecase:intelligence-attribution-usecase",
    ],
)

rust_test(
    name = "intelligence-attribution-worker-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_attribution_worker",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/adapters/attribution-adapter:intelligence-attribution-adapter",
        "//intelligence/core/attribution-usecase:intelligence-attribution-usecase",
    ],
)
