packages:
  - .

allowBuilds:
  esbuild: true
  '@parcel/watcher': false

catalogs:
  default:
    '@tanstack/server-functions-plugin': 1.99.5

overrides:
  '@tanstack/server-functions-plugin': 1.99.5
