rust_library(
    name = "oya-ci-webhook-gateway-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_ci_webhook_gateway_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
    ],
)
