[package]
name = "oya-http-runtime-hyper-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-http-router-kernel = { path = "../oya-http-router-kernel" }
oya-http-middleware-kernel = { path = "../oya-http-middleware-kernel" }
hyper.workspace = true
hyper-util.workspace = true
tokio.workspace = true
http-body-util.workspace = true
bytes.workspace = true


[lib]
name = "oya_http_runtime_hyper_adapter"
path = "src/lib.rs"
doctest = false
