rust_library(
    name = "data-analytics-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/olap-client-kernel:shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "third-party//:serde",
    ],
)

rust_test(
    name = "data-analytics-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/olap-client-kernel:shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "third-party//:serde",
    ],
)
