rust_library(
    name = "oya-managed-k8s-control-plane-host-api",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_managed_k8s_control_plane_host_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/managed-k8s-control-plane-host/crates/oya-managed-k8s-control-plane-host-kernel:oya-managed-k8s-control-plane-host-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
