[package]
name = "oya-cloud-os-machined-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"


[lib]
name = "oya_cloud_os_machined_domain"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-cloud-os-block-domain = { path = "../oya-cloud-os-block-domain" }
oya-cloud-os-cosi-domain = { path = "../oya-cloud-os-cosi-domain" }
oya-cloud-os-kernel = { path = "../oya-cloud-os-kernel" }
oya-cloud-os-runtime-cri-domain = { path = "../oya-cloud-os-runtime-cri-domain" }

[lints]
workspace = true
