rust_library(
    name = "oya-tenant-rbac-postgres-rls-transaction-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_postgres_rls_transaction_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-postgres-rls-write-contract:oya-tenant-rbac-postgres-rls-write-contract",
    ],
)

rust_test(
    name = "oya-tenant-rbac-postgres-rls-transaction-contract-transaction-contract",
    srcs = ["tests/transaction_contract.rs"],
    crate = "oya_tenant_rbac_postgres_rls_transaction_contract_transaction_contract",
    crate_root = "tests/transaction_contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-postgres-rls-transaction-contract",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-postgres-rls-write-contract:oya-tenant-rbac-postgres-rls-write-contract",
    ],
)
