rust_library(
    name = "oya-shared-olap-clickhouse-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_olap_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "third-party//:clickhouse",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
    ],
)
