rust_library(
    name = "oya-shared-olap-clickhouse-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_olap_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "third-party//:clickhouse",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-shared-olap-clickhouse-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_olap_clickhouse_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-olap-client-kernel:oya-shared-olap-client-kernel",
        "third-party//:clickhouse",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
