[package]
name = "oya-intelligence-capability-registry-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_intelligence_capability_registry_app"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-intelligence-capability-registry-kernel = { path = "../oya-intelligence-capability-registry-kernel" }
oya-intelligence-capability-registry-domain = { path = "../oya-intelligence-capability-registry-domain" }

[lints]
workspace = true
