[package]
name = "oya-tenant-rbac-workflow-adapter-inmemory"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-tenant-rbac-application = { path = "../oya-tenant-rbac-application" }
oya-tenant-rbac-domain = { path = "../oya-tenant-rbac-domain" }

[lib]
name = "oya_tenant_rbac_workflow_adapter_inmemory"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
