rust_library(
    name = "intelligence-evidence-file-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_evidence_file_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//intelligence/core/evidence-domain:intelligence-evidence-domain",
    ],
)

rust_test(
    name = "intelligence-evidence-file-adapter-file-evidence",
    srcs = ["tests/file_evidence.rs"],
    crate = "intelligence_evidence_file_adapter_file_evidence",
    crate_root = "tests/file_evidence.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-evidence-file-adapter",
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//intelligence/core/evidence-domain:intelligence-evidence-domain",
    ],
)
