[package]
name = "intelligence-evidence-file-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
intelligence-evidence-domain = { path = "../../core/evidence-domain" }


[lib]
name = "intelligence_evidence_file_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
