rust_library(
    name = "oya-intelligence-registry-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_registry_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//libs/oya-governance-eval-domain:oya-governance-eval-domain",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
    ],
)

rust_test(
    name = "oya-intelligence-registry-api-foundry-capability-publish-api",
    srcs = ["tests/foundry_capability_publish_api.rs"],
    crate = "oya_intelligence_registry_api_foundry_capability_publish_api",
    crate_root = "tests/foundry_capability_publish_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-intelligence-registry-api",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//libs/oya-governance-eval-domain:oya-governance-eval-domain",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
    ],
)
