rust_library(
    name = "oya-crm-revenue-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_crm_revenue_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-crm-revenue",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/crm/crates/oya-crm-revenue-app:oya-crm-revenue-app",
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
