rust_library(
    name = "intelligence-provider-pool-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_provider_pool_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-kernel:intelligence-account-kernel",
    ],
)

rust_test(
    name = "intelligence-provider-pool-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_provider_pool_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-kernel:intelligence-account-kernel",
    ],
)
