rust_library(
    name = "oya-intelligence-adapter-gemini-api-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_adapter_gemini_api_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-account-domain:oya-intelligence-account-domain",
        "//oya/intelligence/crates/oya-intelligence-adapter-gemini-api-kernel:oya-intelligence-adapter-gemini-api-kernel",
    ],
)

rust_test(
    name = "oya-intelligence-adapter-gemini-api-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_adapter_gemini_api_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-account-domain:oya-intelligence-account-domain",
        "//oya/intelligence/crates/oya-intelligence-adapter-gemini-api-kernel:oya-intelligence-adapter-gemini-api-kernel",
    ],
)
