rust_library(
    name = "oya-shared-scim-server-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_scim_server_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
    ],
)
