rust_binary(
    name = "oya-tenant",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap-4",
        "third-party//:clap_complete-4",
    ],
)
