rust_library(
    name = "oya-accounting-journal-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_accounting_journal_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/accounting/crates/oya-accounting-journal-app:oya-accounting-journal-app",
        "//oya/accounting/crates/oya-accounting-journal-domain:oya-accounting-journal-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
