[package]
name = "mail-sqlite-store"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
mail-kernel = { path = "../../core/kernel" }
mail-api = { path = "../../ports/api" }
rusqlite.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
mail-parser = { version = "=0.11.9", features = ["full_encoding"] }
mail-builder = { version = "=1.0.0", default-features = false }

[lints]
workspace = true
