use corpus_doc_parser::{AdrParseInput, parse_adr_decision};
use oya_check_adr_index::{generate_adr_index_from_ir, validate_adr_index_from_ir};

fn decision(number: u16, status: &str) -> corpus_doc_parser::AdrDecisionIr {
    let id = format!("ADR-{number:04}");
    let source = format!(
        "---\nid: {id}\nstatus: {status}\ndate: 2026-06-08\nowner: council-architecture\nsupersedes: []\nsuperseded_by: []\namends: []\namended_by: []\ndepends_on: []\nrelated: []\n---\n\n# {id}: Decision {number}\n"
    );
    parse_adr_decision(&AdrParseInput::new(
        format!("docs/decisions/{id}-decision-{number}.md"),
        source,
    ))
    .expect("fixture decision parses")
}

#[test]
fn index_is_a_deterministic_renderer_over_canonical_adr_ir() {
    let first = generate_adr_index_from_ir([decision(2, "Accepted"), decision(1, "Proposed")])
        .expect("IR renders");
    let second = generate_adr_index_from_ir([decision(1, "Proposed"), decision(2, "Accepted")])
        .expect("equivalent IR renders");

    assert_eq!(first, second, "input ordering cannot alter generated bytes");
    assert!(first.markdown.contains("Proposed 1"));
    assert!(first.markdown.contains("Accepted 1"));
    assert!(first.json.contains("\"adr\": \"ADR-0001\""));
    assert!(first.json.contains("\"adr\": \"ADR-0002\""));
    assert!(
        first
            .json
            .contains("\"path\": \"decisions/ADR-0001-decision-1.md\"")
    );
    assert!(!first.json.contains("\"path\": \"docs/decisions/"));
}

#[test]
fn index_preserves_lifecycle_status_spelling_from_ir() {
    let artifacts =
        generate_adr_index_from_ir([decision(1, "Accepted (amendment)")]).expect("IR renders");

    assert_eq!(
        artifacts.report.status_counts.get("Accepted (amendment)"),
        Some(&1)
    );
    assert!(
        artifacts
            .json
            .contains("\"status\": \"Accepted (amendment)\"")
    );
}

#[test]
fn index_validation_compares_current_artifacts_to_ir_rendering() {
    let records = [decision(1, "Proposed"), decision(3, "Accepted")];
    let artifacts = generate_adr_index_from_ir(records.clone()).expect("IR renders");

    let report = validate_adr_index_from_ir(records, &artifacts.markdown, &artifacts.json)
        .expect("matching artifacts validate");

    assert_eq!(report.gaps, ["ADR-0002"]);
    assert_eq!(report.next_adr, "ADR-0004");
}
