rust_library(
    name = "oya-cloud-network-vpc-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_cloud_network_vpc_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
