rust_library(
    name = "data-ontology-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_ontology_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//data/core/ontology-domain:data-ontology-domain",
    ],
)

rust_test(
    name = "data-ontology-api-object-graph-entity-upsert-api",
    srcs = ["tests/object_graph_entity_upsert_api.rs"],
    crate = "data_ontology_api_object_graph_entity_upsert_api",
    crate_root = "tests/object_graph_entity_upsert_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":data-ontology-api",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//data/core/ontology-domain:data-ontology-domain",
    ],
)
