rust_library(
    name = "oya-contract-lifecycle-management-contract-obligation-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_contract_lifecycle_management_contract_obligation_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-contract-lifecycle-management-contract-obligation",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/contract-lifecycle-management/crates/oya-contract-lifecycle-management-contract-obligation-app:oya-contract-lifecycle-management-contract-obligation-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
