# developer-sdk-package-registry-nuget default values
replicaCount: 3
image:
  repository: oyatie-internal/developer-sdk-package-registry-nuget
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
networkPolicy:
  enabled: true
  ciliumLayered: true
  ambientZtunnel: true
