rust_library(
    name = "oya-dsr-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_dsr_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/compliance/crates/oya-dsr-domain:oya-dsr-domain",
    ],
)
