rust_library(
    name = "oya-dsr-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_dsr_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/compliance/crates/oya-dsr-domain:oya-dsr-domain",
    ],
)

rust_test(
    name = "oya-dsr-usecase-dsr-cascade-execute-api",
    srcs = ["tests/dsr_cascade_execute_api.rs"],
    crate = "oya_dsr_usecase_dsr_cascade_execute_api",
    crate_root = "tests/dsr_cascade_execute_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-dsr-usecase",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/compliance/crates/oya-dsr-domain:oya-dsr-domain",
    ],
)
