rust_library(
    name = "billing-saas-bench",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_saas_bench",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//marketplace/core/plugin-kernel:marketplace-plugin-kernel",
        "//app/application/facade/saas-plugin-app:saas-plugin-app",
        "//workflow/facade/saas-app:workflow-saas-app",
        "//workflow/facade/saas-domain:workflow-saas-domain",
        "//workflow/facade/saas-kernel:workflow-saas-kernel",
    ],
)

rust_test(
    name = "billing-saas-bench-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_saas_bench",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//marketplace/core/plugin-kernel:marketplace-plugin-kernel",
        "//app/application/facade/saas-plugin-app:saas-plugin-app",
        "//workflow/facade/saas-app:workflow-saas-app",
        "//workflow/facade/saas-domain:workflow-saas-domain",
        "//workflow/facade/saas-kernel:workflow-saas-kernel",
    ],
)
