rust_library(
    name = "oya-cloud-network-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_network_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-compute/crates/oya-cloud-resource-domain:oya-cloud-resource-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
