[package]
name = "oya-cloud-network-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-region-domain = { path = "../../../cloud-cell/crates/oya-cloud-region-domain" }
oya-cloud-resource-domain = { path = "../../../cloud-compute/crates/oya-cloud-resource-domain" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_network_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
