rust_library(
    name = "oya-shared-presence-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_presence_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "oya-shared-presence-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_presence_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-shared-presence-kernel-awareness",
    srcs = ["tests/awareness.rs"],
    crate = "oya_shared_presence_kernel_awareness",
    crate_root = "tests/awareness.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-shared-presence-kernel",
    ],
)
