rust_library(
    name = "oya-mail-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_mail_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-mail-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_mail_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-mail-domain-spf-dkim-signing-input-acceptance",
    srcs = ["tests/spf_dkim_signing_input_acceptance.rs"],
    crate = "oya_mail_domain_spf_dkim_signing_input_acceptance",
    crate_root = "tests/spf_dkim_signing_input_acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-mail-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
