rust_library(
    name = "ci-dependency-automation",
    srcs = glob(["src/**/*.rs"]),
    crate = "ci_dependency_automation",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:toml",
    ],
)

rust_binary(
    name = "oya-cloud-ci-dependency-automation-app-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":ci-dependency-automation",
        "third-party//:toml",
    ],
)

rust_test(
    name = "ci-dependency-automation-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "ci_dependency_automation",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:toml",
    ],
)

rust_test(
    name = "ci-dependency-automation-gate",
    srcs = glob(["tests/**/*.rs"]),
    crate = "ci_dependency_automation_gate",
    crate_root = "tests/dependency_automation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":ci-dependency-automation",
        "third-party//:toml",
    ],
)
