rust_library(
    name = "oya-office-collab-gateway-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_collab_gateway_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)

rust_binary(
    name = "oya-office-collab-gateway",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/office/oya-office-collab-gateway-app:oya-office-collab-gateway-app",
    ],
)

rust_test(
    name = "oya-office-collab-gateway-app-tests",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_office_collab_gateway_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)
