[package]
name = "console-docs-portal-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
console-docs-portal-kernel = { path = "../../ports/docs-portal-kernel" }


[lib]
name = "console_docs_portal_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
