[package]
name = "iam-tenant-rbac-deployment-evidence"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-deployment-manifest = { path = "../../core/tenant-rbac-deployment-manifest" }
iam-tenant-rbac-tenant-workload-manifest = { path = "../../core/tenant-rbac-tenant-workload-manifest" }

[lib]
name = "iam_tenant_rbac_deployment_evidence"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
