[package]
name = "oya-office-drive-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-office-authz-domain = { path = "../oya-office-authz-domain" }
oya-office-drive-domain = { path = "../oya-office-drive-domain" }
oya-office-kernel = { path = "../oya-office-kernel" }

[lib]
name = "oya_office_drive_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
