[package]
name = "oya-foundry-vcs-review-mergequeue"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-vcs-kernel = { path = "../oya-foundry-vcs-kernel" }

[lib]
name = "oya_foundry_vcs_review_mergequeue"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
