rust_library(
    name = "oya-policy-cedar-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_policy_cedar_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-policy-cedar-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_policy_cedar_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-policy-cedar-domain-rebac-tuple-port",
    srcs = ["tests/rebac_tuple_port.rs"],
    crate = "oya_policy_cedar_domain_rebac_tuple_port",
    crate_root = "tests/rebac_tuple_port.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-policy-cedar-domain",
        "third-party//:serde_json",
    ],
)
