rust_library(
    name = "oya-policy-cedar-domain",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_policy_cedar_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
    ],
)
