rust_library(
    name = "iam-tenant-rbac-listener-gateway",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_listener_gateway",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-auth-app:iam-tenant-rbac-auth-app",
        "//iam/core/tenant-rbac-cloud-deployment-manifest:iam-tenant-rbac-cloud-deployment-manifest",
        "//iam/facade/tenant-rbac-local-runtime-composition:iam-tenant-rbac-local-runtime-composition",
    ],
)

rust_test(
    name = "iam-tenant-rbac-listener-gateway-listener-gateway",
    srcs = ["tests/listener_gateway.rs"],
    crate = "iam_tenant_rbac_listener_gateway_listener_gateway",
    crate_root = "tests/listener_gateway.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-listener-gateway",
        "//iam/core/tenant-rbac-auth-app:iam-tenant-rbac-auth-app",
        "//iam/core/tenant-rbac-cloud-deployment-manifest:iam-tenant-rbac-cloud-deployment-manifest",
        "//iam/facade/tenant-rbac-local-runtime-composition:iam-tenant-rbac-local-runtime-composition",
    ],
)
