[package]
name = "iam-tenant-rbac-listener-gateway"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-auth-app = { path = "../../core/tenant-rbac-auth-app" }
iam-tenant-rbac-deployment-manifest = { path = "../../core/tenant-rbac-deployment-manifest" }
iam-tenant-rbac-local-runtime-composition = { path = "../tenant-rbac-local-runtime-composition" }

[lib]
name = "iam_tenant_rbac_listener_gateway"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
