[package]
name = "intelligence-account-adapter-inmemory"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "intelligence_account_adapter_inmemory"
path = "src/lib.rs"
doctest = false

[dependencies]
intelligence-account-domain = { path = "../../core/account-domain" }

[lints]
workspace = true
