rust_library(
    name = "community-spaces-memory",
    srcs = glob(["src/**/*.rs"]),
    crate = "community_spaces_memory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/community/ports/spaces-api:community-spaces-api",
    ],
)

rust_test(
    name = "community-spaces-memory-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "community_spaces_memory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/community/ports/spaces-api:community-spaces-api",
    ],
)

rust_test(
    name = "community-spaces-memory-contract",
    srcs = ["tests/contract.rs"],
    crate = "contract",
    crate_root = "tests/contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":community-spaces-memory",
        "//app/community/core/spaces-usecase:community-spaces-usecase",
        "//app/community/ports/post-store-api:community-post-store-api",
        "//app/community/ports/spaces-api:community-spaces-api",
    ],
)
