rust_library(
    name = "check-license-policy",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_license_policy",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "check-license-policy-license-policy",
    srcs = ["tests/license_policy.rs"],
    crate = "check_license_policy_license_policy",
    crate_root = "tests/license_policy.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":check-license-policy",
    ],
)
