rust_library(
    name = "iam-tenant-rbac-tenant-residency-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_residency_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "iam-tenant-rbac-tenant-residency-contract-residency",
    srcs = ["tests/residency.rs"],
    crate = "iam_tenant_rbac_tenant_residency_contract_residency",
    crate_root = "tests/residency.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-residency-contract",
        "//iam/core/tenant-rbac-tenant-admission-policy:iam-tenant-rbac-tenant-admission-policy",
        "//iam/core/tenant-rbac-tenant-workload-manifest:iam-tenant-rbac-tenant-workload-manifest",
    ],
)
