rust_library(
    name = "oya-hr-employment-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_hr_employment_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//oya/hr/crates/oya-hr-employment-api:oya-hr-employment-api",
        "//oya/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//oya/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
