rust_library(
    name = "oya-incident-management-sre-incident-command-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_incident_management_sre_incident_command_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-incident-management-sre-incident-command",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/incident-management/crates/oya-incident-management-sre-incident-command-app:oya-incident-management-sre-incident-command-app",
        "third-party//:clap-4",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
