[package]
name = "compute-k8s-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
compute-domain = { path = "../../core/domain" }
compute-resource = { path = "../../core/resource" }
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }
network-residency = { path = "../../../network/core/residency" }

[lib]
name = "compute_k8s_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
