rust_library(
    name = "oya-shared-oidc-client-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_oidc_client_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_json-1",
    ],
)
