rust_library(
    name = "oya-community-post-store-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_post_store_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/community/crates/oya-community-post-store-api:oya-community-post-store-api",
        "//oya/community/crates/oya-community-post-store-domain:oya-community-post-store-domain",
    ],
)

rust_test(
    name = "oya-community-post-store-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_post_store_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/community/crates/oya-community-post-store-api:oya-community-post-store-api",
        "//oya/community/crates/oya-community-post-store-domain:oya-community-post-store-domain",
    ],
)
