[package]
name = "oya-payments-payout-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_payments_payout_usecase"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-payments-charge-kernel = { path = "../oya-payments-charge-kernel" }
oya-payments-payout-domain = { path = "../oya-payments-payout-domain" }

[lints]
workspace = true
