rust_library(
    name = "iam-tenant-rbac-auth-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_auth_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-tenant-rbac-auth-app-auth-runtime",
    srcs = ["tests/auth_runtime.rs"],
    crate = "iam_tenant_rbac_auth_app_auth_runtime",
    crate_root = "tests/auth_runtime.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-auth-app",
    ],
)
