rust_library(
    name = "ci-tide-github-adapter",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml"]),
    crate = "ci_tide_github_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ci-tide/crates/oya-ci-tide-kernel:oya-ci-tide-kernel",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
