rust_library(
    name = "oya-cloud-iac-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_iac_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-iac/crates/oya-cloud-iac-domain:oya-cloud-iac-domain",
    ],
)

rust_test(
    name = "oya-cloud-iac-api-cloud-iac-api",
    srcs = ["tests/cloud_iac_api.rs"],
    crate = "oya_cloud_iac_api_cloud_iac_api",
    crate_root = "tests/cloud_iac_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-iac-api",
        "//cloud/cloud-iac/crates/oya-cloud-iac-domain:oya-cloud-iac-domain",
    ],
)
