rust_library(
    name = "k8s-cluster-lifecycle-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_cluster_lifecycle_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/core/cluster-lifecycle-kernel:k8s-cluster-lifecycle-kernel",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/ports/tenant-quota-api:k8s-tenant-quota-api",
        "third-party//:serde",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "k8s-cluster-lifecycle-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "k8s_cluster_lifecycle_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//k8s/core/cluster-lifecycle-kernel:k8s-cluster-lifecycle-kernel",
        "//k8s/ports/control-plane-host-api:k8s-control-plane-host-api",
        "//k8s/ports/tenant-quota-api:k8s-tenant-quota-api",
        "third-party//:serde",
        "third-party//:tokio",
    ],
)
