[package]
name = "oya-payroll-run-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-payroll-run-domain = { path = "../oya-payroll-run-domain" }

[lib]
name = "oya_payroll_run_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
