[package]
name = "hr-employment-infrastructure"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
http-runtime-hyper-adapter = { path = "../../../../gateway/adapters/http-runtime-hyper" }
http-router-kernel = { path = "../../../../gateway/core/http-router-kernel" }
http-middleware-kernel = { path = "../../../../gateway/core/http-middleware-kernel" }



hr-employment-api = { path = "../../ports/employment-api" }
hr-employment-app = { path = "../../facade/employment-app" }
hr-employment-domain = { path = "../../core/employment-domain" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
name = "hr_employment_infrastructure"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
