[package]
name = "oya-ops-workspace-shell-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-ops-workspace-shell-kernel = { path = "../oya-ops-workspace-shell-kernel" }


[lib]
name = "oya_ops_workspace_shell_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
