[package]
name = "oya-workflow-engine-event-bus-adapter-redpanda"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-event-bus-adapter = { path = "../oya-workflow-engine-event-bus-adapter" }

[lib]
name = "oya_workflow_engine_event_bus_adapter_redpanda"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
