rust_library(
    name = "oya-application-shell-frontend-prototype",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_application_shell_frontend_prototype",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:console_error_panic_hook",
        "third-party//:leptos",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:wasm-bindgen",
        "third-party//:wasm-bindgen-futures",
        "third-party//:web-sys",
    ],
)

rust_binary(
    name = "oya-application-shell-frontend-prototype-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/application/crates/oya-application-shell-frontend-prototype:oya-application-shell-frontend-prototype",
        "third-party//:console_error_panic_hook",
        "third-party//:leptos",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:wasm-bindgen",
        "third-party//:wasm-bindgen-futures",
        "third-party//:web-sys",
    ],
)
