rust_library(
    name = "oya-cloud-os-difftest-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_os_difftest_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-init-app:oya-cloud-os-init-app",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-kubernetes-domain:oya-cloud-os-kubernetes-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-secrets-domain:oya-cloud-os-secrets-domain",
    ],
)

filegroup(
    name = "testdata",
    srcs = glob(["configs/**", "vectors/**"]),
)

rust_test(
    name = "oya-cloud-os-difftest-app-differential",
    srcs = glob(["tests/**/*.rs"]),
    crate = "differential",
    crate_root = "tests/differential.rs",
    visibility = ["PUBLIC"],
    env = {
        "OYA_TESTDATA_DIR": "$(location :testdata)",
    },
    deps = [
        ":oya-cloud-os-difftest-app",
        "//cloud/cloud-os/crates/oya-cloud-os-controllers-domain:oya-cloud-os-controllers-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-init-app:oya-cloud-os-init-app",
        "//cloud/cloud-os/crates/oya-cloud-os-kernel:oya-cloud-os-kernel",
        "//cloud/cloud-os/crates/oya-cloud-os-kubernetes-domain:oya-cloud-os-kubernetes-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-machine-config-domain:oya-cloud-os-machine-config-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-network-domain:oya-cloud-os-network-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-platform-domain:oya-cloud-os-platform-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-runtime-cri-domain:oya-cloud-os-runtime-cri-domain",
        "//cloud/cloud-os/crates/oya-cloud-os-secrets-domain:oya-cloud-os-secrets-domain",
    ],
)
