rust_library(
    name = "oya-real-estate-portfolio-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_real_estate_portfolio_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-real-estate-portfolio-domain-real-estate-portfolio",
    srcs = ["tests/real_estate_portfolio.rs"],
    crate = "oya_real_estate_portfolio_domain_real_estate_portfolio",
    crate_root = "tests/real_estate_portfolio.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-real-estate-portfolio-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
