rust_binary(
    name = "oya-governance-adapter-with-no-importer-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/check/adapter-with-no-importer-kernel:check-adapter-with-no-importer-kernel",
    ],
)
