rust_binary(
    name = "oya-governance-adapter-with-no-importer-app",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-adapter-with-no-importer-kernel:oya-governance-adapter-with-no-importer-kernel",
    ],
)
