rust_library(
    name = "oya-check-wasm-runtime-discipline",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_check_wasm_runtime_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
