rust_library(
    name = "oya-tenancy-lifecycle-locks-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenancy_lifecycle_locks_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
