rust_library(
    name = "oya-cloud-kms-adapter-oci",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_kms_adapter_oci",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-kms/crates/oya-cloud-kms-domain:oya-cloud-kms-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
