rust_library(
    name = "shared-transactional-outbox-poller-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_transactional_outbox_poller_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/shared-transactional-outbox-kernel:shared-transactional-outbox-kernel",
        "//data/core/shared-transactional-outbox-worker-app:shared-transactional-outbox-worker-app",
    ],
)
