[package]
name = "oya-shared-backbone-grpc-transport-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
community-post-store-domain = { path = "../../app/community/core/post-store-domain" }
comms-mail-mailbox-api = { path = "../../comms/ports/mail-mailbox-api" }
shared-backbone-grpc-generated-adapter = { path = "../../gateway/core/shared-backbone-grpc-generated-adapter" }
shared-postgres-command-kernel = { path = "../../base/shared-postgres-command-kernel" }
tonic = { workspace = true, features = ["router", "transport"] }

[dev-dependencies]
tokio.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
