rust_library(
    name = "oya-intelligence-dispatch-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_dispatch_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/guardrails-domain:intelligence-guardrails-domain",
        "//intelligence/core/model-routing-domain:intelligence-model-routing-domain",
    ],
)

rust_test(
    name = "oya-intelligence-dispatch-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_dispatch_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/guardrails-domain:intelligence-guardrails-domain",
        "//intelligence/core/model-routing-domain:intelligence-model-routing-domain",
    ],
)
