[package]
name = "oya-foundry-api-graphql-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_foundry_api_graphql_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-foundry-api-rest-kernel = { path = "../oya-foundry-api-rest-kernel" }

oya-foundry-api-graphql-kernel = { path = "../oya-foundry-api-graphql-kernel" }

[dev-dependencies]

