rust_library(
    name = "secrets-file",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//secrets/core/domain:secrets-domain",
    ],
)

rust_test(
    name = "secrets-file-file-secret-store",
    srcs = ["tests/file_secret_store.rs"],
    crate = "secrets_file_file_secret_store",
    crate_root = "tests/file_secret_store.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":secrets-file",
        "//secrets/core/domain:secrets-domain",
    ],
)
