[package]
name = "secrets-file"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
secrets-domain = { path = "../../core/domain" }

[lib]
name = "secrets_file"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
