rust_library(
    name = "ci-controller-k8s-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "ci_controller_k8s_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//ci/controller/kernel:ci-controller-kernel",
        "third-party//:k8s-openapi",
        "third-party//:kube",
        "third-party//:kube-runtime",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)

rust_test(
    name = "ci-controller-k8s-adapter-tests",
    srcs = glob(["src/**/*.rs"]),
    crate = "ci_controller_k8s_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//ci/controller/kernel:ci-controller-kernel",
        "third-party//:k8s-openapi",
        "third-party//:kube",
        "third-party//:kube-runtime",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
    ],
)
