[package]
name = "billing-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../../../compute/core/resource" }

billing-metering = { path = "../metering" }

[lib]
name = "billing_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
