rust_library(
    name = "secrets-kms-openbao",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_kms_openbao",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//secrets/core/kms-enclave:secrets-kms-enclave",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "third-party//:base64",
        "third-party//:zeroize",
    ],
)

rust_test(
    name = "unit-test",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_kms_openbao_unit_test",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//secrets/core/kms-enclave:secrets-kms-enclave",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "third-party//:base64",
        "third-party//:zeroize",
    ],
)

rust_test(
    name = "root-custody-test",
    srcs = glob(["tests/root_custody.rs"]),
    crate = "secrets_kms_openbao_root_custody_test",
    crate_root = "tests/root_custody.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":secrets-kms-openbao",
        "//secrets/core/kms-enclave:secrets-kms-enclave",
        "third-party//:base64",
    ],
)
