rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_engine_trigger_orchestrator_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
