rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_trigger_orchestrator_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
