rust_library(
    name = "oya-community-social-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_community_social_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//oya/community/crates/oya-community-social-post-composition-adapter-postgres:oya-community-social-post-composition-adapter-postgres",
        "//oya/community/crates/oya-community-social-post-composition-api:oya-community-social-post-composition-api",
        "//oya/community/crates/oya-community-social-post-composition-usecase:oya-community-social-post-composition-usecase",
    ],
)
