rust_library(
    name = "oya-check-documentation-system",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_check_documentation_system",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
