rust_library(
    name = "oya-workflow-engine-execution-engine-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_workflow_engine_execution_engine_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-adapter:oya-workflow-engine-execution-engine-adapter",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-api:oya-workflow-engine-execution-engine-api",
    ],
)
