rust_library(
    name = "comms-messenger-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "comms-messenger-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_messenger_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "comms-messenger-domain-reaction-tdd-red",
    srcs = ["tests/reaction_tdd_red.rs"],
    crate = "comms_messenger_domain_reaction_tdd_red",
    crate_root = "tests/reaction_tdd_red.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":comms-messenger-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "comms-messenger-domain-thread-lifecycle-tdd-red",
    srcs = ["tests/thread_lifecycle_tdd_red.rs"],
    crate = "comms_messenger_domain_thread_lifecycle_tdd_red",
    crate_root = "tests/thread_lifecycle_tdd_red.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":comms-messenger-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
