use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const STREAMS: [(&str, &str); 2] = [
    ("src/items", "classification.generated.rs"),
    ("tests/items", "classification_contract_tests.generated.rs"),
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    for (relative_dir, output_name) in STREAMS {
        let item_dir = manifest_dir.join(relative_dir);
        println!("cargo:rerun-if-changed={}", item_dir.display());
        let generated = render_membership(&item_dir).map_err(std::io::Error::other)?;
        fs::write(out_dir.join(output_name), generated)?;
    }
    Ok(())
}

/// Concatenate every regular `*.rs` entry of `item_dir` in filename order. A
/// missing or empty directory renders the header alone; a `.rs` name outside
/// the snake_case identifier grammar is refused, because Cargo and Buck both
/// hand it to this scanner and neither may admit it.
fn render_membership(item_dir: &Path) -> Result<String, String> {
    let mut generated =
        String::from("// @generated by build.rs from direct Rust item files; do not edit.\n\n");
    let Ok(entries) = fs::read_dir(item_dir) else {
        return Ok(generated);
    };
    let mut items = Vec::new();
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("cannot read {}: {error}", item_dir.display()))?;
        let is_file = entry
            .file_type()
            .map(|kind| kind.is_file())
            .unwrap_or(false);
        let Ok(file_name) = entry.file_name().into_string() else {
            return Err(format!("item name in {} is not UTF-8", item_dir.display()));
        };
        let Some(stem) = file_name.strip_suffix(".rs") else {
            continue;
        };
        if !is_file {
            continue;
        }
        if !snake_case(stem) {
            return Err(format!("invalid direct Rust item name {file_name}"));
        }
        items.push((file_name, entry.path()));
    }
    items.sort();
    for (index, (file_name, path)) in items.iter().enumerate() {
        let contents = fs::read_to_string(path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        generated.push_str("// source: ");
        generated.push_str(file_name);
        generated.push('\n');
        generated.push_str(&contents);
        if !contents.ends_with('\n') {
            generated.push('\n');
        }
        if index + 1 < items.len() {
            generated.push('\n');
        }
    }
    Ok(generated)
}

fn snake_case(name: &str) -> bool {
    name.as_bytes().first().is_some_and(u8::is_ascii_lowercase)
        && !name.ends_with('_')
        && !name.contains("__")
        && name
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicUsize, Ordering};

    static NEXT_FIXTURE: AtomicUsize = AtomicUsize::new(0);
    const HEADER: &str = "// @generated by build.rs from direct Rust item files; do not edit.\n\n";

    struct Fixture(PathBuf);

    impl Fixture {
        fn new() -> Self {
            let sequence = NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed);
            let root = std::env::temp_dir().join(format!(
                "data-classification-scanner-{}-{sequence}",
                std::process::id()
            ));
            fs::create_dir(&root).expect("fixture directory");
            Self(root)
        }

        fn path(&self) -> &Path {
            &self.0
        }

        fn write(&self, name: &str, contents: &str) {
            fs::write(self.0.join(name), contents).expect("fixture item");
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).expect("fixture removal");
        }
    }

    #[test]
    fn entries_are_sorted_by_filename_and_non_rust_entries_are_skipped() {
        let fixture = Fixture::new();
        fixture.write("z_last.rs", "pub const LAST: u8 = 2;\n");
        fixture.write("a_first.rs", "pub const FIRST: u8 = 1;");
        fixture.write("notes.txt", "not Rust\n");
        fixture.write("Not-Snake.rs.bak", "not a Rust item\n");
        fs::create_dir(fixture.path().join("nested.rs")).expect("nested directory");

        let expected = format!(
            "{HEADER}// source: a_first.rs\npub const FIRST: u8 = 1;\n\n// source: z_last.rs\npub const LAST: u8 = 2;\n"
        );
        assert_eq!(super::render_membership(fixture.path()).unwrap(), expected);
        assert_eq!(super::render_membership(fixture.path()).unwrap(), expected);
    }

    #[test]
    fn add_rename_and_remove_follow_the_directory() {
        let fixture = Fixture::new();
        fixture.write("b_existing.rs", "pub const EXISTING: u8 = 1;\n");
        fixture.write("a_added.rs", "pub const ADDED: u8 = 2;\n");
        let added = super::render_membership(fixture.path()).unwrap();
        assert!(added.find("a_added.rs") < added.find("b_existing.rs"));

        fs::rename(
            fixture.path().join("b_existing.rs"),
            fixture.path().join("c_renamed.rs"),
        )
        .expect("rename");
        let renamed = super::render_membership(fixture.path()).unwrap();
        assert!(!renamed.contains("b_existing.rs") && renamed.contains("c_renamed.rs"));

        fs::remove_file(fixture.path().join("a_added.rs")).expect("remove");
        let removed = super::render_membership(fixture.path()).unwrap();
        assert!(!removed.contains("a_added.rs") && removed.contains("c_renamed.rs"));
    }

    #[test]
    fn missing_and_empty_directories_render_an_empty_module() {
        let fixture = Fixture::new();
        assert_eq!(super::render_membership(fixture.path()).unwrap(), HEADER);
        let missing = fixture.path().join("missing");
        assert_eq!(super::render_membership(&missing).unwrap(), HEADER);
    }

    #[test]
    fn non_snake_case_rust_item_is_refused() {
        let fixture = Fixture::new();
        fixture.write("Not-Snake.rs", "pub const INVALID: u8 = 1;\n");
        let error = super::render_membership(fixture.path()).unwrap_err();
        assert_eq!(error, "invalid direct Rust item name Not-Snake.rs");
    }
}
