rust_library(
    name = "messaging-substrate-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "messaging_substrate_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "messaging-substrate-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "messaging_substrate_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "messaging-substrate-kernel-conformance",
    srcs = glob(["tests/**/*.rs"]),
    crate = "messaging_substrate_kernel_conformance",
    crate_root = "tests/reference_substrate.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":messaging-substrate-kernel",
    ],
)
