rust_library(
    name = "connect-address-book-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "connect_address_book_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/connect-address-book-domain:connect-address-book-domain",
        "//comms/ports/connect-address-book-api:connect-address-book-api",
    ],
)

rust_test(
    name = "connect-address-book-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "connect_address_book_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/connect-address-book-domain:connect-address-book-domain",
        "//comms/ports/connect-address-book-api:connect-address-book-api",
    ],
)
