[package]
name = "connect-address-book-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
connect-address-book-domain = { path = "../connect-address-book-domain" }
connect-address-book-api = { path = "../../ports/connect-address-book-api" }

[lib]
name = "connect_address_book_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
