//! One fixture per exit path of the driver process.
//!
//! The load-bearing assertion in every nonzero case is the same: git takes whatever the driver
//! leaves in `%A` as the conflicted working tree and never re-runs its own text merge, so `%A` must
//! never come back as unmarked `ours`. If it does, `theirs` is gone and a reflexive `git add`
//! commits the loss with nothing on screen to stop it.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

fn driver_bin() -> PathBuf {
    match std::env::var("OYA_CARGO_LOCK_MERGE_DRIVER") {
        Ok(path) => PathBuf::from(path),
        Err(err) => {
            assert!(false, "missing OYA_CARGO_LOCK_MERGE_DRIVER: {err}");
            PathBuf::from("missing-oya-cargo-lock-merge-driver")
        }
    }
}

fn unique_dir(label: &str) -> PathBuf {
    let nanos = match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_nanos(),
        Err(_) => 0,
    };
    let mut dir = std::env::temp_dir();
    dir.push(format!(
        "oya-cargo-lock-merge-driver-{label}-{}-{nanos}",
        std::process::id()
    ));
    match std::fs::create_dir_all(&dir) {
        Ok(()) => dir,
        Err(err) => {
            assert!(false, "failed to create temp dir {}: {err}", dir.display());
            dir
        }
    }
}

fn write_file(path: &Path, contents: &str) {
    if let Err(err) = std::fs::write(path, contents) {
        assert!(false, "failed to write {}: {err}", path.display());
    }
}

fn read_file(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(contents) => contents,
        Err(err) => {
            assert!(false, "failed to read {}: {err}", path.display());
            String::new()
        }
    }
}

fn lockfile(packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{packages}"
    )
}

fn package(name: &str, version: &str) -> String {
    format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n")
}

fn run_driver(base: &Path, current: &Path, other: &Path) -> Output {
    run_driver_with_extras(base, current, other, &[])
}

/// `extras` are the placeholders git may substitute AFTER `%O %A %B` — `%L`, `%P`, `%S`, `%X`,
/// `%Y`. Requiring exactly three arguments was a data-loss bug in its own right, so every exit
/// path is exercised with a tail present as well as without.
fn run_driver_with_extras(base: &Path, current: &Path, other: &Path, extras: &[&str]) -> Output {
    match Command::new(driver_bin())
        .arg(base)
        .arg(current)
        .arg(other)
        .args(extras)
        .output()
    {
        Ok(output) => output,
        Err(err) => panic!("failed to run merge driver: {err}"),
    }
}

/// The whole point of the crate: whatever ends up in `%A` after a nonzero exit must carry every
/// side and must not be mistakable for a resolved lockfile.
fn assert_marked_conflict(current: &Path, must_contain: &[&str]) {
    let merged = read_file(current);
    for marker in ["<<<<<<< ours", "||||||| base", "=======", ">>>>>>> theirs"] {
        assert!(
            merged.contains(marker),
            "%A is missing the {marker:?} marker; git would present it as a clean file:\n{merged}"
        );
    }
    for needle in must_contain {
        assert!(merged.contains(needle), "%A lost {needle:?}:\n{merged}");
    }
}

/// Exit 1 — semantic conflict (same package resolved to two versions).
#[test]
fn version_divergence_writes_every_side_into_current() {
    let dir = unique_dir("version-divergence");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("serde", "1.0.0")));
    write_file(&current, &lockfile(&package("serde", "1.0.1")));
    write_file(&other, &lockfile(&package("serde", "1.0.2")));

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["1.0.0", "1.0.1", "1.0.2"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 1 — removal on one side, edit on the other.
#[test]
fn removal_vs_edit_writes_every_side_into_current() {
    let dir = unique_dir("removal-vs-edit");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("serde", "1.0.0")));
    write_file(&current, &lockfile(""));
    write_file(
        &other,
        &lockfile("[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nchecksum = \"deadbeef\"\n"),
    );

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["deadbeef"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 1 — a side that does not parse. Abstaining here would resolve to `ours` just as silently
/// as a semantic conflict does, so unmodelled input takes the same marked-conflict path.
#[test]
fn parse_failure_writes_every_side_into_current() {
    let dir = unique_dir("parse-failure");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, "not = [valid");
    write_file(&current, &lockfile(&package("serde", "1.0.0")));
    write_file(&other, &lockfile(&package("theirs-only", "0.2.0")));

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["theirs-only", "not = [valid"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 1 — a side git handed us that cannot be read. `theirs` is unrecoverable, so the file must
/// say so under markers rather than hand back a clean-looking `ours`.
#[test]
fn unreadable_other_side_writes_marked_conflict_into_current() {
    let dir = unique_dir("unreadable-other");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("missing.lock"),
    );
    write_file(&base, &lockfile(&package("serde", "1.0.0")));
    write_file(&current, &lockfile(&package("serde", "1.0.1")));

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["could not be read"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 1 — the four-placeholder registration. `merge.oya-faces` in this repo is registered as
/// `%O %A %B %P`, and git also documents `%L`, `%S`, `%X` and `%Y`. Demanding exactly three
/// arguments made that shape take the usage branch and exit WITHOUT writing `%A`, which is the
/// same silent data loss the conflict path was fixed for, entered through a different door.
#[test]
fn four_placeholder_registration_writes_every_side_into_current() {
    let dir = unique_dir("four-placeholder-conflict");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("shared", "1.0.0")));
    write_file(&current, &lockfile(&package("shared", "1.0.1")));
    write_file(&other, &lockfile(&package("shared", "1.0.2")));

    // The trailing argument is `%P`, exactly as `merge.oya-faces` is registered.
    let output = run_driver_with_extras(&base, &current, &other, &["Cargo.lock"]);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["1.0.0", "1.0.1", "1.0.2"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 1 — the five-placeholder form `%O %A %B %L %P` from gitattributes(5)'s own example. The
/// tail is accepted and ignored, so a longer registration cannot resurrect the arity hole.
#[test]
fn five_placeholder_registration_writes_every_side_into_current() {
    let dir = unique_dir("five-placeholder-conflict");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("shared", "1.0.0")));
    write_file(&current, &lockfile(&package("shared", "1.0.1")));
    write_file(&other, &lockfile(&package("shared", "1.0.2")));

    let output = run_driver_with_extras(&base, &current, &other, &["7", "Cargo.lock"]);

    assert_eq!(output.status.code(), Some(1));
    assert_marked_conflict(&current, &["1.0.0", "1.0.1", "1.0.2"]);
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 0 — a clean merge must still be clean under the four-placeholder registration, so the
/// arity fix is not merely "conflicts loudly on every input".
#[test]
fn four_placeholder_registration_merges_cleanly() {
    let dir = unique_dir("four-placeholder-clean");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("alpha", "1.0.0")));
    write_file(
        &current,
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("ours-only", "0.1.0")
        )),
    );
    write_file(
        &other,
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("theirs-only", "0.2.0")
        )),
    );

    let output = run_driver_with_extras(&base, &current, &other, &["Cargo.lock"]);

    assert_eq!(output.status.code(), Some(0));
    let merged = read_file(&current);
    assert!(merged.contains("ours-only"), "{merged}");
    assert!(merged.contains("theirs-only"), "{merged}");
    assert!(!merged.contains("<<<<<<<"), "{merged}");
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 129 — too few arguments to even know which file is `%A`. >128 is git's documented "the
/// driver crashed" range: git abandons the merge instead of recording a conflict, so no `UU` path
/// with unmarked `ours` can exist for a reflexive `git add` to commit. Exit 2 here would produce
/// exactly that state, which is why exit 2 no longer exists.
#[test]
fn missing_arguments_abort_the_merge() {
    let output = match Command::new(driver_bin()).output() {
        Ok(output) => output,
        Err(err) => panic!("failed to run merge driver: {err}"),
    };
    assert_eq!(
        output.status.code(),
        Some(129),
        "an exit code <=128 would tell git 'conflict' while %A was never written"
    );
}

/// Exit 129 — a panic. `std::env::args()` panics on an argument that is not valid Unicode, which
/// makes this the one panic reachable from outside the process, and it lands in the only window
/// that matters: before the conflict document has been written to `%A`. A bare panic exits 101,
/// and 101 is <=128, so git would record an ordinary conflict over an untouched `%A` — the data
/// loss again. The panic hook turns it into an abandoned merge instead.
#[test]
fn non_utf8_argument_aborts_the_merge() {
    use std::ffi::OsStr;
    use std::os::unix::ffi::OsStrExt;

    let output = match Command::new(driver_bin())
        .arg("base.lock")
        .arg(OsStr::from_bytes(b"current-\xff\xfe.lock"))
        .arg("other.lock")
        .output()
    {
        Ok(output) => output,
        Err(err) => panic!("failed to run merge driver: {err}"),
    };

    assert_eq!(
        output.status.code(),
        Some(129),
        "a panic must abandon the merge; 101 would tell git 'conflict' over an untouched %A"
    );
}

/// Exit 129 — `%A` is known but cannot be written (its directory does not exist). Same reasoning:
/// the driver cannot make `%A` correct, so it must not let git believe a merge happened.
#[test]
fn unwritable_current_aborts_the_merge() {
    let dir = unique_dir("unwritable-current");
    let (base, other) = (dir.join("base.lock"), dir.join("other.lock"));
    let current = dir.join("no-such-dir").join("current.lock");
    write_file(&base, &lockfile(&package("serde", "1.0.0")));
    write_file(&other, &lockfile(&package("serde", "1.0.2")));

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(129));
    let _ = std::fs::remove_dir_all(dir);
}

/// Exit 0 — disjoint additions still merge, and `%A` holds the merged result with no markers.
#[test]
fn disjoint_additions_merge_cleanly() {
    let dir = unique_dir("clean-merge");
    let (base, current, other) = (
        dir.join("base.lock"),
        dir.join("current.lock"),
        dir.join("other.lock"),
    );
    write_file(&base, &lockfile(&package("alpha", "1.0.0")));
    write_file(
        &current,
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("ours-only", "0.1.0")
        )),
    );
    write_file(
        &other,
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("theirs-only", "0.2.0")
        )),
    );

    let output = run_driver(&base, &current, &other);

    assert_eq!(output.status.code(), Some(0));
    let merged = read_file(&current);
    assert!(merged.contains("ours-only"), "{merged}");
    assert!(merged.contains("theirs-only"), "{merged}");
    assert!(!merged.contains("<<<<<<<"), "{merged}");
    let _ = std::fs::remove_dir_all(dir);
}
