use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn driver_bin() -> PathBuf {
    match std::env::var("OYA_CARGO_LOCK_MERGE_DRIVER") {
        Ok(path) => PathBuf::from(path),
        Err(err) => {
            assert!(false, "missing OYA_CARGO_LOCK_MERGE_DRIVER: {err}");
            PathBuf::from("missing-oya-cargo-lock-merge-driver")
        }
    }
}

fn unique_dir(label: &str) -> PathBuf {
    let nanos = match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_nanos(),
        Err(_) => 0,
    };
    let mut dir = std::env::temp_dir();
    dir.push(format!(
        "oya-cargo-lock-merge-driver-{label}-{}-{nanos}",
        std::process::id()
    ));
    match std::fs::create_dir_all(&dir) {
        Ok(()) => dir,
        Err(err) => {
            assert!(false, "failed to create temp dir {}: {err}", dir.display());
            dir
        }
    }
}

fn write_file(path: &Path, contents: &str) {
    if let Err(err) = std::fs::write(path, contents) {
        assert!(false, "failed to write {}: {err}", path.display());
    }
}

fn read_file(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(contents) => contents,
        Err(err) => {
            assert!(false, "failed to read {}: {err}", path.display());
            String::new()
        }
    }
}

fn lockfile(packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{packages}"
    )
}

fn package(name: &str, version: &str) -> String {
    format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n")
}

#[test]
fn parse_failure_returns_exit_2() {
    let dir = unique_dir("parse-failure");
    let base = dir.join("base.lock");
    let current = dir.join("current.lock");
    let other = dir.join("other.lock");
    write_file(&base, "not = [valid");
    write_file(&current, &lockfile(&package("serde", "1.0.0")));
    write_file(&other, &lockfile(&package("serde", "1.0.0")));

    let output = match Command::new(driver_bin())
        .arg(&base)
        .arg(&current)
        .arg(&other)
        .output()
    {
        Ok(output) => output,
        Err(err) => {
            assert!(false, "failed to run merge driver: {err}");
            return;
        }
    };

    assert_eq!(output.status.code(), Some(2));
    let _ = std::fs::remove_dir_all(dir);
}

#[test]
fn current_file_stays_unchanged_on_conflict() {
    let dir = unique_dir("conflict-current-untouched");
    let base = dir.join("base.lock");
    let current = dir.join("current.lock");
    let other = dir.join("other.lock");
    let original_current = lockfile(&package("serde", "1.0.1"));
    write_file(&base, &lockfile(""));
    write_file(&current, &original_current);
    write_file(&other, &lockfile(&package("serde", "1.0.2")));

    let output = match Command::new(driver_bin())
        .arg(&base)
        .arg(&current)
        .arg(&other)
        .output()
    {
        Ok(output) => output,
        Err(err) => {
            assert!(false, "failed to run merge driver: {err}");
            return;
        }
    };

    assert_eq!(output.status.code(), Some(1));
    assert_eq!(read_file(&current), original_current);
    let _ = std::fs::remove_dir_all(dir);
}
