//! End-to-end against a real `git merge`.
//!
//! The unit fixtures in `cli_fixtures.rs` prove what the driver writes and what it exits with.
//! They cannot prove what GIT DOES with those two facts, and that is where the data loss lived:
//! git does not re-run its own text merge when a driver exits nonzero, it takes whatever the
//! driver left in `%A` as the conflicted working tree. Only a real merge shows that.
//!
//! Every test here registers the driver the way a real clone does and then asserts on the working
//! tree afterwards. The invariant under test is a single sentence: **after any merge, the working
//! tree must never be byte-identical to `ours` while git believes a merge happened.**

use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

/// Absolute, because git runs the merge driver with the cwd set to the repository being merged —
/// the project-relative `buck-out/...` path `$(location)` hands over would simply not resolve
/// there, and git would report a driver it could not execute rather than the behaviour under test.
fn driver_bin() -> PathBuf {
    let raw = match std::env::var("OYA_CARGO_LOCK_MERGE_DRIVER") {
        Ok(path) => PathBuf::from(path),
        Err(err) => panic!("missing OYA_CARGO_LOCK_MERGE_DRIVER: {err}"),
    };
    match std::fs::canonicalize(&raw) {
        Ok(absolute) => absolute,
        Err(err) => panic!("merge driver {} is not resolvable: {err}", raw.display()),
    }
}

/// `git`, with the ambient user/system config cut out so a developer's own `merge.*` registrations
/// and `init.defaultBranch` cannot change what these tests observe.
fn git(repo: &Path, args: &[&str]) -> std::process::Output {
    match Command::new("git")
        .current_dir(repo)
        .args(args)
        .env("GIT_CONFIG_GLOBAL", "/dev/null")
        .env("GIT_CONFIG_SYSTEM", "/dev/null")
        .env("GIT_AUTHOR_NAME", "merge-driver-test")
        .env("GIT_AUTHOR_EMAIL", "merge-driver-test@oyatie.invalid")
        .env("GIT_COMMITTER_NAME", "merge-driver-test")
        .env("GIT_COMMITTER_EMAIL", "merge-driver-test@oyatie.invalid")
        .output()
    {
        Ok(output) => output,
        Err(err) => panic!("failed to run `git {}`: {err}", args.join(" ")),
    }
}

fn git_ok(repo: &Path, args: &[&str]) -> String {
    let output = git(repo, args);
    assert!(
        output.status.success(),
        "`git {}` failed: {}{}",
        args.join(" "),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn lockfile(packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{packages}"
    )
}

fn package(name: &str, version: &str) -> String {
    format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n")
}

fn write_lock(repo: &Path, contents: &str) {
    if let Err(err) = std::fs::write(repo.join("Cargo.lock"), contents) {
        panic!("failed to write Cargo.lock: {err}");
    }
}

fn read_lock(repo: &Path) -> String {
    match std::fs::read_to_string(repo.join("Cargo.lock")) {
        Ok(contents) => contents,
        Err(err) => panic!("failed to read Cargo.lock: {err}"),
    }
}

/// A repo with `base` committed on `main` and on `theirs`, the driver registered with
/// `placeholders`, and `Cargo.lock` bound to it. Returns the repo root.
fn repo_with_driver(
    label: &str,
    placeholders: &str,
    base: &str,
    ours: &str,
    theirs: &str,
) -> PathBuf {
    let nanos = match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_nanos(),
        Err(_) => 0,
    };
    let mut repo = std::env::temp_dir();
    repo.push(format!(
        "oya-cargo-lock-merge-e2e-{label}-{}-{nanos}",
        std::process::id()
    ));
    if let Err(err) = std::fs::create_dir_all(&repo) {
        panic!("failed to create {}: {err}", repo.display());
    }

    git_ok(&repo, &["init", "-q", "-b", "main", "."]);
    git_ok(&repo, &["config", "merge.cargo-lock.name", "test driver"]);
    let driver = format!("{} {placeholders}", driver_bin().display());
    git_ok(&repo, &["config", "merge.cargo-lock.driver", &driver]);
    if let Err(err) = std::fs::write(repo.join(".gitattributes"), "Cargo.lock merge=cargo-lock\n") {
        panic!("failed to write .gitattributes: {err}");
    }

    write_lock(&repo, base);
    git_ok(&repo, &["add", "-A"]);
    git_ok(&repo, &["commit", "-qm", "base"]);

    git_ok(&repo, &["checkout", "-q", "-b", "theirs"]);
    write_lock(&repo, theirs);
    git_ok(&repo, &["commit", "-qam", "theirs"]);

    git_ok(&repo, &["checkout", "-q", "main"]);
    write_lock(&repo, ours);
    git_ok(&repo, &["commit", "-qam", "ours"]);

    repo
}

/// THE regression. Registered with four placeholders — the shape `merge.oya-faces` already uses in
/// the Oyatie clone — a driver that demanded exactly three exited without writing `%A`. Git still
/// marked the path `UU`, so the working tree came back byte-identical to `ours`: no markers,
/// `theirs`' packages simply gone, and `git add && git commit` committed the loss.
#[test]
fn four_placeholder_registration_does_not_lose_theirs() {
    let ours = lockfile(&format!(
        "{}\n{}",
        package("shared", "1.0.1"),
        package("ours-only", "0.1.0")
    ));
    let repo = repo_with_driver(
        "four-placeholder",
        "%O %A %B %P",
        &lockfile(&package("shared", "1.0.0")),
        &ours,
        &lockfile(&format!(
            "{}\n{}",
            package("shared", "1.0.2"),
            package("theirs-only", "0.2.0")
        )),
    );

    let merge = git(&repo, &["merge", "theirs"]);
    let merged = read_lock(&repo);

    assert!(
        !merge.status.success(),
        "a same-package version divergence must not merge cleanly"
    );
    assert_ne!(
        merged, ours,
        "the working tree came back byte-identical to `ours` — `theirs` was silently dropped"
    );
    for needle in [
        "<<<<<<< ours",
        "||||||| base",
        ">>>>>>> theirs",
        "1.0.2",
        "theirs-only",
    ] {
        assert!(
            merged.contains(needle),
            "merged tree lost {needle:?}:\n{merged}"
        );
    }
    // The second backstop: even a human who blindly `git add`s cannot build, because the
    // conflicted document does not parse as TOML.
    let staged = git(&repo, &["add", "Cargo.lock"]);
    assert!(staged.status.success());
    assert!(
        read_lock(&repo).contains("<<<<<<<"),
        "staging must not silently rewrite the conflict away"
    );

    let _ = std::fs::remove_dir_all(repo);
}

/// The same four-placeholder registration must still resolve a genuinely disjoint merge, or the
/// fix would just be "conflict on everything".
#[test]
fn four_placeholder_registration_merges_disjoint_additions() {
    let repo = repo_with_driver(
        "four-placeholder-clean",
        "%O %A %B %P",
        &lockfile(&package("alpha", "1.0.0")),
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("ours-only", "0.1.0")
        )),
        &lockfile(&format!(
            "{}\n{}",
            package("alpha", "1.0.0"),
            package("theirs-only", "0.2.0")
        )),
    );

    let merge = git(&repo, &["merge", "theirs"]);
    assert!(
        merge.status.success(),
        "disjoint additions must merge cleanly: {}",
        String::from_utf8_lossy(&merge.stderr)
    );

    let merged = read_lock(&repo);
    assert!(merged.contains("ours-only"), "{merged}");
    assert!(merged.contains("theirs-only"), "{merged}");
    assert!(!merged.contains("<<<<<<<"), "{merged}");
    assert!(
        git_ok(&repo, &["status", "--short"]).trim().is_empty(),
        "a clean merge must leave no conflicted paths"
    );

    let _ = std::fs::remove_dir_all(repo);
}

/// The unavoidable case: registered so badly that `%A` is not identifiable. The driver exits >128,
/// which git documents as a crash — it abandons the merge rather than recording a conflict. This
/// is what makes "cannot write `%A`" safe: no `MERGE_HEAD`, no `UU` path, nothing to `git add`.
#[test]
fn unusable_registration_aborts_the_merge_instead_of_conflicting() {
    let ours = lockfile(&package("shared", "1.0.1"));
    let repo = repo_with_driver(
        "unusable-registration",
        "%O",
        &lockfile(&package("shared", "1.0.0")),
        &ours,
        &lockfile(&package("shared", "1.0.2")),
    );

    let merge = git(&repo, &["merge", "theirs"]);

    assert!(!merge.status.success(), "the merge must not report success");
    assert!(
        !repo.join(".git").join("MERGE_HEAD").exists(),
        "git must have abandoned the merge, not left a conflict state a `git add` could commit"
    );
    assert_eq!(
        read_lock(&repo),
        ours,
        "an abandoned merge must leave the working tree exactly as it was"
    );
    assert!(
        git_ok(&repo, &["status", "--short"]).trim().is_empty(),
        "an abandoned merge must leave nothing staged or conflicted"
    );

    let _ = std::fs::remove_dir_all(repo);
}
