use oya_cargo_lock_merge_driver_app::{MergeErrorKind, merge_lockfiles};

fn lockfile(packages: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{packages}"
    )
}

fn package(name: &str, version: &str) -> String {
    format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n")
}

fn assert_merge_ok(base: &str, ours: &str, theirs: &str) -> String {
    match merge_lockfiles(base, ours, theirs) {
        Ok(output) => output,
        Err(err) => {
            assert!(false, "merge should have succeeded, got {err}");
            String::new()
        }
    }
}

fn assert_merge_conflict(base: &str, ours: &str, theirs: &str, wanted_detail: &str) {
    match merge_lockfiles(base, ours, theirs) {
        Ok(output) => assert!(false, "merge should have conflicted, got output:\n{output}"),
        Err(err) => {
            assert_eq!(err.kind(), MergeErrorKind::Conflict);
            assert!(
                err.to_string().contains(wanted_detail),
                "wanted detail {wanted_detail:?} in error {err}"
            );
        }
    }
}

#[test]
fn disjoint_adds_merge_both_new_package_sections() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));
    let theirs = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("prost", "0.14.0")
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert!(merged.contains("name = \"serde\""));
    assert!(merged.contains("name = \"tokio\""));
    assert!(merged.contains("name = \"prost\""));
}

#[test]
fn version_divergence_conflicts_for_same_package_identity() {
    let base = lockfile("");
    let ours = lockfile(&package("serde", "1.0.1"));
    let theirs = lockfile(&package("serde", "1.0.2"));

    assert_merge_conflict(&base, &ours, &theirs, "version-divergence");
}

#[test]
fn removal_vs_edit_conflicts_for_existing_package() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile("");
    let theirs = lockfile(&package("serde", "1.0.1"));

    assert_merge_conflict(&base, &ours, &theirs, "removal-vs-edit");
}

#[test]
fn unchanged_three_way_merge_is_idempotent() {
    let base = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));

    let merged = assert_merge_ok(&base, &base, &base);

    assert_eq!(merged, base);
}

#[test]
fn generated_header_and_lockfile_version_are_preserved() {
    let base = lockfile(&package("serde", "1.0.0"));
    let ours = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("tokio", "1.0.0")
    ));
    let theirs = lockfile(&format!(
        "{}\n{}",
        package("serde", "1.0.0"),
        package("prost", "0.14.0")
    ));

    let merged = assert_merge_ok(&base, &ours, &theirs);

    assert!(merged.starts_with(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n"
    ));
}
