[package]
name = "oya-http-tenant-middleware-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-http-middleware-kernel = { path = "../oya-http-middleware-kernel" }
bytes.workspace = true

[dev-dependencies]
oya-http-router-kernel = { path = "../oya-http-router-kernel" }


[lib]
name = "oya_http_tenant_middleware_domain"
path = "src/lib.rs"
doctest = false
