rust_library(
    name = "intelligence-supervisor-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_supervisor_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//intelligence/core/autonomy-ceiling-kernel:intelligence-autonomy-ceiling-kernel",
    ],
)

rust_test(
    name = "intelligence-supervisor-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_supervisor_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//intelligence/core/account-domain:intelligence-account-domain",
        "//intelligence/core/autonomy-ceiling-kernel:intelligence-autonomy-ceiling-kernel",
    ],
)
