[package]
name = "iam-control-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
iam-domain = { path = "../domain-control" }
iam-policy-cedar-domain = { path = "../policy-cedar-domain" }

[dev-dependencies]


[lints]
workspace = true
