rust_library(
    name = "oya-saas-workflow-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_saas_workflow_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-saas-workflow-domain:oya-saas-workflow-domain",
        "//oya/workflow-engine/crates/oya-saas-workflow-kernel:oya-saas-workflow-kernel",
    ],
)
