rust_library(
    name = "oya-payroll-run-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_payroll_run_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/payroll/crates/oya-payroll-run-domain:oya-payroll-run-domain",
    ],
)
