rust_library(
    name = "comms-meet-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_meet_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/meet-domain:comms-meet-domain",
        "//comms/ports/meet-api:comms-meet-api",
    ],
)

rust_test(
    name = "comms-meet-usecase-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "comms_meet_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/meet-domain:comms-meet-domain",
        "//comms/ports/meet-api:comms-meet-api",
    ],
)

rust_test(
    name = "comms-meet-usecase-room-session-lifecycle-acceptance",
    srcs = ["tests/room_session_lifecycle_acceptance.rs"],
    crate = "comms_meet_usecase_room_session_lifecycle_acceptance",
    crate_root = "tests/room_session_lifecycle_acceptance.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":comms-meet-usecase",
        "//comms/core/meet-domain:comms-meet-domain",
        "//comms/ports/meet-api:comms-meet-api",
    ],
)
