[package]
name = "comms-meet-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
comms-meet-domain = { path = "../meet-domain" }
comms-meet-api = { path = "../../ports/meet-api" }

[lib]
name = "comms_meet_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
