rust_library(
    name = "oya-buck-test-wiring-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_buck_test_wiring_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:anyhow",
        "third-party//:clap",
    ],
)

rust_binary(
    name = "oya-buck-test-wiring",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    env = {"CARGO_PKG_NAME": "oya-buck-test-wiring-app", "CARGO_PKG_VERSION": "0.1.0"},
    visibility = ["PUBLIC"],
    deps = [
        ":oya-buck-test-wiring-app",
        "third-party//:anyhow",
        "third-party//:clap",
    ],
)

rust_test(
    name = "oya-buck-test-wiring-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_buck_test_wiring_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:anyhow",
        "third-party//:clap",
    ],
)
