rust_library(
    name = "foundry-blob-sqlite-draft",
    srcs = glob(["src/**/*.rs"]),
    crate = "foundry_blob_sqlite_draft",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/foundry/ports/draft/blob:foundry-blob-draft",
        "third-party//:rusqlite",
    ],
)

rust_test(
    name = "foundry-blob-sqlite-draft-conformance",
    srcs = ["tests/sqlite_blob.rs"],
    crate = "sqlite_blob",
    crate_root = "tests/sqlite_blob.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":foundry-blob-sqlite-draft",
        "//app/foundry/ports/draft/blob:foundry-blob-draft",
        "third-party//:rusqlite",
    ],
)
