rust_library(
    name = "iam-cloud-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_cloud_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/cloud-domain:iam-cloud-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//iam/core/policy-cedar-domain:iam-policy-cedar-domain",
    ],
)

rust_test(
    name = "iam-cloud-app-cedar-policy-bind",
    srcs = ["tests/cedar_policy_bind.rs"],
    crate = "iam_cloud_app_cedar_policy_bind",
    crate_root = "tests/cedar_policy_bind.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-cloud-app",
        "//iam/core/cloud-domain:iam-cloud-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//iam/core/policy-cedar-domain:iam-policy-cedar-domain",
    ],
)
