[package]
name = "iam-cloud-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
iam-cloud-domain = { path = "../cloud-domain" }
iam-policy-cedar-domain = { path = "../policy-cedar-domain" }

[dev-dependencies]
data-boundary-kernel = { path = "../../../data/core/boundary-kernel" }

[lints]
workspace = true
