rust_library(
    name = "oya-community-post-store-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_community_post_store_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//oya/community/crates/oya-community-post-store-adapter-postgres:oya-community-post-store-adapter-postgres",
        "//oya/community/crates/oya-community-post-store-api:oya-community-post-store-api",
        "//oya/community/crates/oya-community-post-store-domain:oya-community-post-store-domain",
        "//oya/community/crates/oya-community-post-store-usecase:oya-community-post-store-usecase",
    ],
)
