rust_library(
    name = "compute-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//iam/core/domain-control:iam-domain",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compute_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//iam/core/domain-control:iam-domain",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "compute-domain-cloud-compute-foundation",
    srcs = ["tests/cloud_compute_foundation.rs"],
    crate = "compute_domain_cloud_compute_foundation",
    crate_root = "tests/cloud_compute_foundation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":compute-domain",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)
