[package]
name = "compute-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-cloud-domain = { path = "../../../iam/core/cloud-domain" }
network-domain = { path = "../../../network/core/domain" }
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../resource" }

network-residency = { path = "../../../network/core/residency" }

[lib]
name = "compute_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
