rust_library(
    name = "oya-crm-customer-engagement-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_crm_customer_engagement_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-crm-customer-engagement-domain-customer-engagement",
    srcs = ["tests/customer_engagement.rs"],
    crate = "oya_crm_customer_engagement_domain_customer_engagement",
    crate_root = "tests/customer_engagement.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-crm-customer-engagement-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
