rust_library(
    name = "iam-tenant-rbac-storage-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_storage_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)

rust_test(
    name = "iam-tenant-rbac-storage-inmemory-storage",
    srcs = ["tests/storage.rs"],
    crate = "iam_tenant_rbac_storage_inmemory_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-storage-inmemory",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//iam/core/tenant-rbac-usecase:iam-tenant-rbac-usecase",
        "//iam/core/tenant-rbac-domain:iam-tenant-rbac-domain",
    ],
)
