[package]
name = "iam-tenant-rbac-storage-inmemory"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-usecase = { path = "../../core/tenant-rbac-usecase" }
iam-tenant-rbac-domain = { path = "../../core/tenant-rbac-domain" }

[dev-dependencies]
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }

[lib]
name = "iam_tenant_rbac_storage_inmemory"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
