rust_library(
    name = "oya-crate-registrar-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_crate_registrar_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-crate-registrar-kernel:oya-crate-registrar-kernel",
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-crate-registrar-app-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_crate_registrar_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-crate-registrar-kernel:oya-crate-registrar-kernel",
        "//libs/oya-workspace-members-kernel:oya-workspace-members-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
