rust_library(
    name = "oya-accounting-journal-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_accounting_journal_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//oya/accounting/crates/oya-accounting-journal-api:oya-accounting-journal-api",
        "//oya/accounting/crates/oya-accounting-journal-app:oya-accounting-journal-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-accounting-journal-infrastructure-runtime",
    srcs = ["tests/runtime.rs"],
    crate = "oya_accounting_journal_infrastructure_runtime",
    crate_root = "tests/runtime.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-accounting-journal-infrastructure",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//oya/accounting/crates/oya-accounting-journal-api:oya-accounting-journal-api",
        "//oya/accounting/crates/oya-accounting-journal-app:oya-accounting-journal-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
