rust_library(
    name = "oya-ci-tide-app",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml"]),
    crate = "oya_ci_tide_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ci-tide/crates/oya-ci-tide-kernel:oya-ci-tide-kernel",
        "//ci/adapters/tide-github-adapter:ci-tide-github-adapter",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "oya-ci-tide-app-tests",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_ci_tide_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ci-tide/crates/oya-ci-tide-kernel:oya-ci-tide-kernel",
        "//ci/adapters/tide-github-adapter:ci-tide-github-adapter",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-ci-tide",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml"]),
    crate_root = "src/bin/oya-ci-tide.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-ci-tide-app",
        "//oya/ci-tide/crates/oya-ci-tide-kernel:oya-ci-tide-kernel",
        "//ci/adapters/tide-github-adapter:ci-tide-github-adapter",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
