export_file(
    name = "BUCK",
    visibility = ["PUBLIC"],
)

export_file(
    name = "lib-src",
    src = "src/lib.rs",
    visibility = ["PUBLIC"],
)

export_file(
    name = "main-src",
    src = "src/main.rs",
    visibility = ["PUBLIC"],
)

rust_library(
    name = "oya-adr-index-regenerator-app-lib",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_adr_index_regenerator_app",
    crate_root = "src/lib.rs",
    deps = [
        "//libs/oya-check-adr-index:oya-check-adr-index",
    ],
    visibility = ["PUBLIC"],
)

rust_library(
    name = "oya-adr-index-regenerator-app-bin-src",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_adr_index_regenerator_app_bin",
    crate_root = "src/main.rs",
    deps = [
        ":oya-adr-index-regenerator-app-lib",
    ],
    visibility = ["PUBLIC"],
)

genrule(
    name = "adr-index-regenerator-unit-tests",
    srcs = {
        "libs/oya-check-adr-index/src/lib.rs": "//libs/oya-check-adr-index:lib-src",
        "libs/oya-check-adr-index/src/lifecycle.rs": "//libs/oya-check-adr-index:lifecycle-src",
        "src/lib.rs": "src/lib.rs",
    },
    out = "adr-index-regenerator-unit-tests.txt",
    cmd = "mkdir -p $TMP/oya-adr-index-regenerator-app && rustc --edition=2024 -D warnings --crate-name oya_check_adr_index --crate-type=lib libs/oya-check-adr-index/src/lib.rs -o $TMP/oya-adr-index-regenerator-app/liboya_check_adr_index.rlib && rustc --edition=2024 -D warnings tools/oya-adr-index-regenerator-app/src/lib.rs --test --extern oya_check_adr_index=$TMP/oya-adr-index-regenerator-app/liboya_check_adr_index.rlib -L dependency=$TMP/oya-adr-index-regenerator-app -o $TMP/oya-adr-index-regenerator-app/oya-adr-index-regenerator-tests && $TMP/oya-adr-index-regenerator-app/oya-adr-index-regenerator-tests > $OUT",
    cacheable = False,
    remote = False,
    repo_relative_root = True,
    visibility = ["PUBLIC"],
)
