rust_library(
    name = "network-lb",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_lb",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "network-lb-cloud-network-lb-api",
    srcs = ["tests/cloud_network_lb_api.rs"],
    crate = "network_lb_cloud_network_lb_api",
    crate_root = "tests/cloud_network_lb_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":network-lb",
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
