rust_library(
    name = "shared-audit-event-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "shared_audit_event_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "shared-audit-event-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "shared_audit_event_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
