rust_library(
    name = "oya-check-authority-cohesion",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_authority_cohesion",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
