rust_library(
    name = "intelligence-policy-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_policy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
        "//intelligence/core/policy-domain:intelligence-policy-domain",
    ],
)

rust_test(
    name = "intelligence-policy-api-foundry-policy-api",
    srcs = ["tests/foundry_policy_api.rs"],
    crate = "intelligence_policy_api_foundry_policy_api",
    crate_root = "tests/foundry_policy_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-policy-api",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//intelligence/core/capability-domain:intelligence-capability-domain",
        "//intelligence/core/policy-domain:intelligence-policy-domain",
    ],
)
