[package]
name = "intelligence-policy-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
intelligence-capability-domain = { path = "../capability-domain" }
intelligence-policy-domain = { path = "../policy-domain" }


[lib]
name = "intelligence_policy_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
