[package]
name = "workflow-event-bus-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-event-bus-api = { path = "../../ports/event-bus-api" }

[lib]
name = "workflow_event_bus_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
