rust_library(
    name = "oya-shared-hyperscaler-metrics-adapter-otlp",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_hyperscaler_metrics_adapter_otlp",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "third-party//:opentelemetry",
        "third-party//:opentelemetry-otlp",
        "third-party//:opentelemetry_sdk",
    ],
)

rust_test(
    name = "oya-shared-hyperscaler-metrics-adapter-otlp-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_hyperscaler_metrics_adapter_otlp",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//comms/core/shared-hyperscaler-metrics-kernel:shared-hyperscaler-metrics-kernel",
        "third-party//:opentelemetry",
        "third-party//:opentelemetry-otlp",
        "third-party//:opentelemetry_sdk",
    ],
)
