rust_library(
    name = "iam-pdp-bundle-file",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_pdp_bundle_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/pdp-kernel:iam-pdp-kernel",
        "//audit/adapters/digest-awslc:shared-audit-digest-adapter-awslc",
        "//audit/core/event-kernel:shared-audit-event-kernel",
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-pdp-bundle-file-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_pdp_bundle_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/pdp-kernel:iam-pdp-kernel",
        "//audit/adapters/digest-awslc:shared-audit-digest-adapter-awslc",
        "//audit/core/event-kernel:shared-audit-event-kernel",
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
