#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CloudResourceError {
    InvalidResourceId,
    ResourceIdRegionMismatch,
    ResourceIdTenantMismatch,
    ResourceIdKindMismatch,
    InvalidTenantId,
    InvalidPrincipalId,
    InvalidPolicyId,
    DuplicatePolicyId,
    InvalidTagKey,
    InvalidTagValue,
    InvalidMeteringTag,
    InvalidDataClass,
    InvalidInitialState,
    InvalidStateTransition,
    InvalidTimeOrder,
    AzRequiredForResourceKind,
    AzRegionMismatch,
    CellLocationMismatch,
    ResidencyRegionMismatch,
    DuplicateResource,
    UnknownResource,
}
