rust_library(
    name = "cell-region",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_region",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/routing:cell-routing",
        "//network/core/residency:network-residency",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "cell-region-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_region",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cell/core/routing:cell-routing",
        "//network/core/residency:network-residency",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)
