[package]
name = "cell-region"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
cell-location = { path = "../../ports/location" }
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
cell-routing = { path = "../routing" }

network-residency = { path = "../../../network/core/residency" }

[lib]
doctest = false

[lints]
workspace = true
