rust_library(
    name = "billing-accounting-http-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_accounting_http_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//billing/ports/accounting-api:billing-accounting-api",
        "//billing/core/accounting-app:billing-accounting-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "billing-accounting-http-adapter-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_accounting_http_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//billing/ports/accounting-api:billing-accounting-api",
        "//billing/core/accounting-app:billing-accounting-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "billing-accounting-http-adapter-runtime",
    srcs = ["tests/runtime.rs"],
    crate = "billing_accounting_http_adapter_runtime",
    crate_root = "tests/runtime.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-accounting-http-adapter",
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//billing/ports/accounting-api:billing-accounting-api",
        "//billing/core/accounting-app:billing-accounting-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
