[package]
name = "billing-accounting-http-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
http-runtime-hyper-adapter = { path = "../../../gateway/adapters/http-runtime-hyper" }
http-router-kernel = { path = "../../../gateway/core/http-router-kernel" }
http-middleware-kernel = { path = "../../../gateway/core/http-middleware-kernel" }
billing-accounting-api = { path = "../../ports/accounting-api" }
billing-accounting-app = { path = "../../core/accounting-app" }



serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
name = "billing_accounting_http_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
