[package]
name = "workflow-execution-engine-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-execution-engine-domain = { path = "../execution-engine-domain" }

[lib]
name = "workflow_execution_engine_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
