rust_binary(
    name = "oya-governance-adr-shape-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-adr-shape-kernel:oya-governance-adr-shape-kernel",
    ],
)

rust_test(
    name = "oya-governance-adr-shape-app-integration",
    srcs = glob(["src/**/*.rs", "tests/**/*.md"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-adr-shape-kernel:oya-governance-adr-shape-kernel",
    ],
)
