[package]
name = "iam-cloud-selfhosted"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "iam_cloud_selfhosted"
path = "src/lib.rs"
doctest = false

[dependencies]
iam-cloud-domain = { path = "../../core/cloud-domain" }

[lints]
workspace = true
