// Pipeline-as-product gate self-conformance live-corpus test.
// ADR-0083 Tier-3: integration tests use unwrap/expect/panic to assert invariants.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use ci_gate_self_conformance::{
    GATE_ID, Verdict, collect_observed_gates, evaluate, production_rust_slice,
};
use serde_json::Value;

fn repo_root() -> PathBuf {
    let mut dir = std::env::current_dir().expect("current dir");
    loop {
        if dir.join("specs/root-hub-pointers.json").is_file() {
            return dir;
        }
        assert!(dir.pop(), "repo root marker not found from current dir");
    }
}

fn gate_dir(root: &Path) -> PathBuf {
    root.join("ci/facade/gate-self-conformance")
}

fn load_policy(root: &Path) -> Value {
    let path = gate_dir(root).join("gate-self-conformance-policy.json");
    serde_json::from_str(&fs::read_to_string(&path).expect("read gate-self-conformance policy"))
        .expect("parse gate-self-conformance policy")
}

fn gate_names(observed: &Value) -> BTreeSet<String> {
    observed["gates"]
        .as_array()
        .expect("gates array")
        .iter()
        .map(|row| row["name"].as_str().expect("gate name").to_owned())
        .collect()
}

#[test]
fn committed_policy_gate_id_matches_contract() {
    let policy = load_policy(&repo_root());
    assert_eq!(policy["gate_id"], GATE_ID);
}

#[test]
fn live_gate_fleet_is_green_against_declared_exceptions() {
    let root = repo_root();
    let policy = load_policy(&root);
    let observed = collect_observed_gates(&root, &policy).expect("collect live gate observations");
    let names = gate_names(&observed);
    assert!(
        names.len() >= 35,
        "self-conformance should cover the real gate fleet, not an empty or tiny scan: {names:?}"
    );
    assert!(
        names.contains("gate-self-conformance"),
        "the meta-gate must scan itself"
    );
    assert!(
        names.contains("generated-artifact-freshness"),
        "freshness orchestrator exception must be visible in the scan"
    );
    let report = evaluate(&policy, &observed);
    assert_eq!(
        report.verdict,
        Verdict::Green,
        "live gate self-conformance findings: {:#?}",
        report.findings
    );
}

#[test]
fn freshness_system_time_is_limited_to_temp_path_helpers() {
    let root = repo_root();
    let path = root.join("ci/facade/generated-artifact-freshness/src/lib.rs");
    let text = fs::read_to_string(&path).expect("read freshness lib");
    let production = production_rust_slice(&text);
    let lines: Vec<&str> = production.lines().collect();
    let mut hits = Vec::new();
    for (idx, line) in lines.iter().enumerate() {
        if line.contains("SystemTime::now") {
            let context_start = idx.saturating_sub(4);
            let context = lines[context_start..=idx].join("\n");
            hits.push((idx + 1, context.clone()));
            assert!(
                context.contains("fn temporary_"),
                "freshness SystemTime::now must stay isolated to temporary_* helpers, not verdict logic: line {}\n{}",
                idx + 1,
                context
            );
        }
    }
    assert!(
        !hits.is_empty(),
        "test must prove the current SystemTime exception is observed"
    );
}

#[test]
fn freshness_shellout_exception_has_cutover_note() {
    let policy = load_policy(&repo_root());
    let exceptions = policy["hermetic_exceptions"]
        .as_array()
        .expect("hermetic exceptions array");
    let freshness = exceptions
        .iter()
        .filter(|row| row["gate"] == "generated-artifact-freshness")
        .collect::<Vec<_>>();
    assert!(
        freshness.len() >= 2,
        "freshness needs command and temp-clock exceptions"
    );
    assert!(freshness.iter().any(|row| {
        row["cutover_note"]
            .as_str()
            .unwrap_or_default()
            .contains("typed Buck2/reconciler API")
            && row["tokens"]
                .as_array()
                .map(|tokens| tokens.iter().any(|token| token == "Command::new"))
                .unwrap_or(false)
    }));
    assert!(freshness.iter().any(|row| {
        row["reason"]
            .as_str()
            .unwrap_or_default()
            .contains("does not feed the regenerated bytes comparison or pass/fail verdict")
            && row["tokens"]
                .as_array()
                .map(|tokens| tokens.iter().any(|token| token == "SystemTime::now"))
                .unwrap_or(false)
    }));
}

// ---------------------------------------------------------------------------
// Skip-on-missing firewall.
//
// A live-corpus test that opens with `if !path.is_file() { eprintln!("skip…"); return; }` turns a
// renamed or relocated input into a PASSING test: the gate stops reading its subject and reports
// green over nothing. Three such tests in //ci/facade/affected-target-set were mutation-proven —
// `mv specs/integ-branch-envelopes.json` left 13 tests passing across 3 suites, in the gate that
// decides which targets CI runs — and all three carried the tell in their own names
// (`…_when_present`), which made the fail-open read as deliberate.
//
// The rule is the empty set, not a hand-maintained allowlist of exceptions:
//
//   1. No `#[test]` under ci/facade/*/tests/ may `return;` in its body. An early return
//      turns a missing input into a pass. Branch with if/else, or fail closed.
//   2. No test may encode a fail-open in its NAME (`_when_present` / `_if_present`).
// ---------------------------------------------------------------------------

/// One `#[test]` fn plus the facts this scan needs about it.
struct ScannedTest {
    key: String,
    name: String,
    returns_early: bool,
}

/// Collect every `#[test]` / `#[tokio::test]` fn under `ci/facade/*/tests/`.
///
/// Deliberately line-oriented rather than brace-matching: the corpus is rustfmt-normalized, so a
/// top-level item always closes with `}` in column zero, and an early return always trims to
/// exactly `return;`. `return Ok(())`, `return false` and friends are not early returns of the
/// test body, and a commented-out `// return;` does not trim to `return;`.
fn scan_facade_tests(root: &Path) -> Vec<ScannedTest> {
    let mut files = Vec::new();
    for gate in sorted_child_dirs(&root.join("ci/facade")) {
        let tests_dir = gate.join("tests");
        if tests_dir.is_dir() {
            collect_rs_files(&tests_dir, &mut files);
        }
    }
    files.sort();

    let mut out: Vec<ScannedTest> = Vec::new();
    for file in files {
        let rel = file
            .strip_prefix(root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        let text = fs::read_to_string(&file).unwrap_or_else(|e| panic!("read {rel}: {e}"));
        let mut pending_attribute = false;
        let mut current: Option<usize> = None;
        for line in text.lines() {
            let trimmed = line.trim();
            if trimmed == "#[test]" || trimmed == "#[tokio::test]" {
                pending_attribute = true;
                continue;
            }
            if pending_attribute {
                if let Some(name) = test_fn_name(trimmed) {
                    pending_attribute = false;
                    current = Some(out.len());
                    out.push(ScannedTest {
                        key: format!("{rel}::{name}"),
                        name,
                        returns_early: false,
                    });
                }
                continue;
            }
            if line == "}" {
                current = None;
                continue;
            }
            if let Some(index) = current
                && (trimmed == "return;" || trimmed.starts_with("return; "))
            {
                out[index].returns_early = true;
            }
        }
    }
    out
}

/// `fn foo(` / `pub fn foo(` / `async fn foo(` -> `foo`, for an already-trimmed line.
fn test_fn_name(trimmed: &str) -> Option<String> {
    let mut rest = trimmed;
    for prefix in ["pub ", "async "] {
        rest = rest.strip_prefix(prefix).unwrap_or(rest);
    }
    let rest = rest.strip_prefix("fn ")?;
    let name: String = rest
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if name.is_empty() { None } else { Some(name) }
}

fn sorted_child_dirs(dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .map(|entry| entry.expect("dir entry").path())
        .filter(|path| path.is_dir())
        .collect();
    out.sort();
    out
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

/// Gate directory name from a `ci/facade/<gate>/tests/...` key.
fn gate_of(key: &str) -> Option<&str> {
    key.split('/').nth(2)
}

#[test]
fn facade_tests_do_not_return_early() {
    let root = repo_root();
    let scanned = scan_facade_tests(&root);

    // Structural non-vacuity, expressed as a SET so that paying debt down never reds it and a
    // collapsed walk cannot hide behind a count that merely got smaller: every gate crate that
    // ships a tests/ directory must have contributed at least one `#[test]`.
    let gates_with_tests: BTreeSet<String> = sorted_child_dirs(&root.join("ci/facade"))
        .into_iter()
        .filter(|gate| gate.join("tests").is_dir())
        .map(|gate| {
            gate.file_name()
                .and_then(|name| name.to_str())
                .expect("gate dir name")
                .to_owned()
        })
        .collect();
    let gates_scanned: BTreeSet<String> = scanned
        .iter()
        .filter_map(|test| gate_of(&test.key).map(str::to_owned))
        .collect();
    assert_eq!(
        gates_scanned, gates_with_tests,
        "the skip-on-missing scan must reach every ci/facade gate that ships tests; a gate on \
         only one side means the walk stopped seeing it"
    );

    let early: Vec<&str> = scanned
        .iter()
        .filter(|test| test.returns_early)
        .map(|test| test.key.as_str())
        .collect();
    assert!(
        early.is_empty(),
        "ci/facade test(s) {early:?} `return;` in the test body — that is fail-open on a \
         missing input. Branch with if/else, or fail closed. Do not maintain an exception list."
    );
}

#[test]
fn no_facade_test_encodes_a_fail_open_in_its_name() {
    let root = repo_root();
    let named: Vec<String> = scan_facade_tests(&root)
        .into_iter()
        .filter(|test| test.name.contains("_when_present") || test.name.contains("_if_present"))
        .map(|test| test.key)
        .collect();
    assert!(
        named.is_empty(),
        "test name(s) {named:?} encode a conditional bind in the NAME, which is how the \
         //ci/facade/affected-target-set fail-opens read as intentional for as long as they did. \
         A live-corpus test binds its subject or goes red; it does not bind it 'when present'"
    );
}
