// Pipeline-as-product gate self-conformance live-corpus test.
// ADR-0083 Tier-3: integration tests use unwrap/expect/panic to assert invariants.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use ci_gate_self_conformance::{
    GATE_ID, Verdict, collect_observed_gates, evaluate, production_rust_slice,
};
use serde_json::Value;

fn repo_root() -> PathBuf {
    let mut dir = std::env::current_dir().expect("current dir");
    loop {
        if dir.join("specs/root-hub-pointers.json").is_file() {
            return dir;
        }
        assert!(dir.pop(), "repo root marker not found from current dir");
    }
}

fn gate_dir(root: &Path) -> PathBuf {
    root.join("ci/facade/gate-self-conformance")
}

fn load_policy(root: &Path) -> Value {
    let path = gate_dir(root).join("gate-self-conformance-policy.json");
    serde_json::from_str(&fs::read_to_string(&path).expect("read gate-self-conformance policy"))
        .expect("parse gate-self-conformance policy")
}

fn gate_names(observed: &Value) -> BTreeSet<String> {
    observed["gates"]
        .as_array()
        .expect("gates array")
        .iter()
        .map(|row| row["name"].as_str().expect("gate name").to_owned())
        .collect()
}

#[test]
fn committed_policy_gate_id_matches_contract() {
    let policy = load_policy(&repo_root());
    assert_eq!(policy["gate_id"], GATE_ID);
}

#[test]
fn live_gate_fleet_is_green_against_declared_exceptions() {
    let root = repo_root();
    let policy = load_policy(&root);
    let observed = collect_observed_gates(&root, &policy).expect("collect live gate observations");
    let names = gate_names(&observed);
    assert!(
        names.len() >= 35,
        "self-conformance should cover the real gate fleet, not an empty or tiny scan: {names:?}"
    );
    assert!(
        names.contains("gate-self-conformance"),
        "the meta-gate must scan itself"
    );
    assert!(
        names.contains("generated-artifact-freshness"),
        "freshness orchestrator exception must be visible in the scan"
    );
    let report = evaluate(&policy, &observed);
    assert_eq!(
        report.verdict,
        Verdict::Green,
        "live gate self-conformance findings: {:#?}",
        report.findings
    );
}

#[test]
fn freshness_system_time_is_limited_to_temp_path_helpers() {
    let root = repo_root();
    let path = root.join("ci/facade/generated-artifact-freshness/src/lib.rs");
    let text = fs::read_to_string(&path).expect("read freshness lib");
    let production = production_rust_slice(&text);
    let lines: Vec<&str> = production.lines().collect();
    let mut hits = Vec::new();
    for (idx, line) in lines.iter().enumerate() {
        if line.contains("SystemTime::now") {
            let context_start = idx.saturating_sub(4);
            let context = lines[context_start..=idx].join("\n");
            hits.push((idx + 1, context.clone()));
            assert!(
                context.contains("fn temporary_"),
                "freshness SystemTime::now must stay isolated to temporary_* helpers, not verdict logic: line {}\n{}",
                idx + 1,
                context
            );
        }
    }
    assert!(
        !hits.is_empty(),
        "test must prove the current SystemTime exception is observed"
    );
}

#[test]
fn freshness_shellout_exception_has_cutover_note() {
    let policy = load_policy(&repo_root());
    let exceptions = policy["hermetic_exceptions"]
        .as_array()
        .expect("hermetic exceptions array");
    let freshness = exceptions
        .iter()
        .filter(|row| row["gate"] == "generated-artifact-freshness")
        .collect::<Vec<_>>();
    assert!(
        freshness.len() >= 2,
        "freshness needs command and temp-clock exceptions"
    );
    assert!(freshness.iter().any(|row| {
        row["cutover_note"]
            .as_str()
            .unwrap_or_default()
            .contains("typed Buck2/reconciler API")
            && row["tokens"]
                .as_array()
                .map(|tokens| tokens.iter().any(|token| token == "Command::new"))
                .unwrap_or(false)
    }));
    assert!(freshness.iter().any(|row| {
        row["reason"]
            .as_str()
            .unwrap_or_default()
            .contains("does not feed the regenerated bytes comparison or pass/fail verdict")
            && row["tokens"]
                .as_array()
                .map(|tokens| tokens.iter().any(|token| token == "SystemTime::now"))
                .unwrap_or(false)
    }));
}
