rust_library(
    name = "data-analytics-tenant-bootstrap",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_tenant_bootstrap",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/shared-olap-clickhouse-adapter:shared-olap-clickhouse-adapter",
        "//data/core/shared-olap-client-kernel:shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "data-analytics-tenant-bootstrap-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/facade/analytics-tenant-bootstrap:data-analytics-tenant-bootstrap",
        "//data/core/shared-olap-clickhouse-adapter:shared-olap-clickhouse-adapter",
        "//data/core/shared-olap-client-kernel:shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "data-analytics-tenant-bootstrap-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_analytics_tenant_bootstrap",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/shared-olap-clickhouse-adapter:shared-olap-clickhouse-adapter",
        "//data/core/shared-olap-client-kernel:shared-olap-client-kernel",
        "//data/core/analytics-domain:data-analytics-domain",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
