#![forbid(unsafe_code)]

use std::env;
use std::fs;
use std::io::{self, Read};
use std::process::ExitCode;

use serde_json::Value;

use oya_cloud_ci_generated_artifact_control_plane_app::generated_output_diff_policy_violations;

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(code) => code,
    }
}

fn run() -> Result<(), ExitCode> {
    let manifest_path = parse_manifest_path()?;
    let manifest_bytes = fs::read(&manifest_path).map_err(|error| {
        eprintln!("generated-output-diff-policy: read {manifest_path}: {error}");
        ExitCode::from(2)
    })?;
    let manifest: Value = serde_json::from_slice(&manifest_bytes).map_err(|error| {
        eprintln!("generated-output-diff-policy: parse {manifest_path}: {error}");
        ExitCode::from(2)
    })?;

    let mut diff_name_status = String::new();
    io::stdin()
        .read_to_string(&mut diff_name_status)
        .map_err(|error| {
            eprintln!("generated-output-diff-policy: read diff-name-status stdin: {error}");
            ExitCode::from(2)
        })?;

    let (manifest_findings, violations) =
        generated_output_diff_policy_violations(&manifest, &diff_name_status);
    if !manifest_findings.is_empty() {
        eprintln!("generated-output-diff-policy: manifest is not policy-valid:");
        for finding in manifest_findings {
            eprintln!("  {} {}", finding.code, finding.key);
        }
        return Err(ExitCode::from(2));
    }

    if !violations.is_empty() {
        eprintln!(
            "Generated outputs are regenerated by cloud-ci and must not be PR merge surfaces:"
        );
        for violation in violations {
            eprintln!("  {} {}", violation.status, violation.path);
        }
        eprintln!(
            "Delete obsolete generated outputs or change canonical sources/generators instead."
        );
        return Err(ExitCode::FAILURE);
    }

    println!("generated-output-diff-policy: no non-deletion generated output edits.");
    Ok(())
}

fn parse_manifest_path() -> Result<String, ExitCode> {
    let mut args = env::args().skip(1);
    let mut manifest_path = None;
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--manifest" => {
                manifest_path = args.next();
            }
            "--help" | "-h" => {
                println!(
                    "usage: oya-cloud-ci-generated-output-diff-policy --manifest <path> < diff-name-status.tsv"
                );
                return Err(ExitCode::SUCCESS);
            }
            other => {
                eprintln!("generated-output-diff-policy: unknown argument {other}");
                return Err(ExitCode::from(2));
            }
        }
    }
    manifest_path.ok_or_else(|| {
        eprintln!("generated-output-diff-policy: --manifest is required");
        ExitCode::from(2)
    })
}
