[package]
name = "oya-foundry-adapter-gemini-subscription-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_foundry_adapter_gemini_subscription_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-foundry-account-domain = { path = "../oya-foundry-account-domain" }
oya-foundry-adapter-gemini-subscription-kernel = { path = "../oya-foundry-adapter-gemini-subscription-kernel" }
