rust_library(
    name = "oya-tenant-rbac-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-usecase:oya-tenant-rbac-usecase",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-domain:oya-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
