rust_library(
    name = "billing-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "billing-service-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "billing-service-integration-test",
    srcs = ["src/main.rs"],
    crate = "billing_service_main_integration_test",
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-service",
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_binary(
    name = "billing-service-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/facade/billing-service:billing-service",
        "third-party//:tokio",
    ],
)
