[package]
name = "check-adapter-with-no-importer-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[[bin]]
name = "oya-governance-adapter-with-no-importer-app"
path = "src/main.rs"

[dependencies]
check-adapter-with-no-importer-kernel = { path = "../adapter-with-no-importer-kernel" }

[lints]
workspace = true
