rust_library(
    name = "kernel-asterinas-boundary",
    srcs = glob(["src/**/*.rs", "pins/**/*.json"]),
    crate = "kernel_asterinas_boundary",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "kernel-asterinas-boundary-unittest",
    srcs = glob(["src/**/*.rs", "pins/**/*.json"]),
    crate = "kernel_asterinas_boundary",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
