#!/usr/bin/env python3
"""Render/check a compact ledger from /specs/cross-cutting/masterplan.json."""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MASTERPLAN = ROOT / "specs/cross-cutting/masterplan.json"
DEFAULT_OUTPUT = ROOT / "evidence/master-plan-ledger.md"


def fail(message: str) -> int:
    print(f"render-master-plan-ledger: {message}", file=sys.stderr)
    return 1


def iter_items(index: dict):
    for milestone in index.get("milestones", []):
        yield "milestone", milestone
        for phase in milestone.get("phases", []):
            yield "phase", phase
            for ip in phase.get("implementation_plans", []):
                yield "ip", ip


def load_index() -> dict:
    data = json.loads(MASTERPLAN.read_text())
    return data["live_implementation_index"]


def validate_index(index: dict) -> list[str]:
    errors: list[str] = []
    for kind, item in iter_items(index):
        item_id = item.get("id", "<missing-id>")
        if not item.get("status"):
            errors.append(f"{kind} {item_id} missing status")
        for key in ("path", "index", "file"):
            rel = item.get(key)
            if rel and not (ROOT / rel).exists():
                errors.append(f"{kind} {item_id} references missing {key}: {rel}")
        if kind == "ip":
            if item.get("execution_unit") != "ChangeSet":
                errors.append(f"ip {item_id} execution_unit is not ChangeSet")
            if item.get("changeset_contract") != "claimable-verifiable-bundleable-promotable":
                errors.append(f"ip {item_id} changeset_contract is invalid")
    coverage = index.get("coverage", {})
    for key, value in coverage.items():
        if key.startswith("all_") and value is not True:
            errors.append(f"coverage {key} is not true")
    return errors


def render(index: dict) -> str:
    counts = collections.Counter()
    for kind, item in iter_items(index):
        counts[(kind, item.get("status", "<missing>"))] += 1
    lines = [
        "# Master Plan Ledger",
        "",
        "<!-- generated by scripts/render-master-plan-ledger.py -->",
        "",
        f"- Source: `{MASTERPLAN.relative_to(ROOT)}`",
        f"- Milestones: {index.get('milestone_count')}",
        f"- Phases: {index.get('phase_count')}",
        f"- Implementation plans: {index.get('implementation_plan_count')}",
        "",
        "## Status counts",
        "",
        "| Kind | Status | Count |",
        "|---|---|---:|",
    ]
    for (kind, status), count in sorted(counts.items()):
        lines.append(f"| {kind} | {status} | {count} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args(argv)

    try:
        index = load_index()
    except Exception as exc:
        return fail(str(exc))
    errors = validate_index(index)
    if errors:
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return fail("ledger validation failed")
    rendered = render(index)
    output = pathlib.Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)
        print(f"wrote {output.relative_to(ROOT)}")
        return 0
    if args.check:
        if output.exists() and output.read_text() != rendered:
            return fail(f"{output.relative_to(ROOT)} is stale; run with --write")
        status = "output parity ok" if output.exists() else "output absent; source ledger ok"
        print(f"render-master-plan-ledger: {status}")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
