#!/usr/bin/env python3
"""Render or check the M02 exit checklist scaffold from canonical P22 inputs."""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PHASE_DIR = ROOT / ".omc/plans/milestones/M02-substrate/phases/P22-m02-exit-gate"
DEFAULT_OUTPUT = ROOT / "docs/architecture/m02-exit-checklist.md"
REQUIRED_INPUTS = ["phase-spec.md", "impl-plan.md", "INDEX.md"]


def fail(message: str) -> int:
    print(f"render-m02-exit-checklist: {message}", file=sys.stderr)
    return 1


def read_required_inputs() -> dict[str, str]:
    contents: dict[str, str] = {}
    for name in REQUIRED_INPUTS:
        path = PHASE_DIR / name
        if not path.exists():
            raise FileNotFoundError(path.relative_to(ROOT))
        contents[name] = path.read_text()
    return contents


def render() -> str:
    contents = read_required_inputs()
    required_phrases = [
        "Flip all 14 CI fitness lanes",
        "Application B2B shell",
        "sibling-team self-sufficiency",
    ]
    missing = [phrase for phrase in required_phrases if phrase not in contents["phase-spec.md"]]
    if missing:
        raise ValueError("phase-spec missing expected P22 phrases: " + ", ".join(missing))

    return "\n".join(
        [
            "# M02 Exit Gate Checklist",
            "",
            "<!-- generated by scripts/render-m02-exit-checklist.py; write with --write when P22 is active -->",
            "",
            "**Milestone:** M02-substrate",
            "**Phase:** P22-m02-exit-gate",
            "**Status:** not-yet-active; source inputs present",
            "",
            "## Source inputs",
            "",
            "| Source | Status |",
            "|---|---|",
            "| `.omc/plans/milestones/M02-substrate/phases/P22-m02-exit-gate/phase-spec.md` | present |",
            "| `.omc/plans/milestones/M02-substrate/phases/P22-m02-exit-gate/impl-plan.md` | present |",
            "| `.omc/plans/milestones/M02-substrate/phases/P22-m02-exit-gate/INDEX.md` | present |",
            "",
            "## Gate families",
            "",
            "- 14 CI fitness lanes flipped from report-only to BLOCKER.",
            "- Application B2B shell deployability evidence.",
            "- Sibling-team onboarding validation evidence.",
            "- Full workspace compile, nextest, deny, plane, and wave gates.",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify source inputs and output parity if output exists")
    parser.add_argument("--write", action="store_true", help="write the rendered checklist")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args(argv)

    try:
        rendered = render()
    except Exception as exc:
        return fail(str(exc))

    output = pathlib.Path(args.output)
    if not output.is_absolute():
        output = ROOT / output

    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)
        print(f"wrote {output.relative_to(ROOT)}")
        return 0

    if args.check:
        if output.exists() and output.read_text() != rendered:
            return fail(f"{output.relative_to(ROOT)} is stale; run with --write")
        status = "output parity ok" if output.exists() else "output absent because P22 is not active; source inputs ok"
        print(f"render-m02-exit-checklist: {status}")
        return 0

    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
