//! Complete upstream app-server protocol schema artifact access.
//!
//! The checked schema is generated by upstream Codex from the Rust
//! `codex-app-server-protocol` crate and mirrors the Python SDK's generated
//! `v2_all.py` model source.
//!
//! Source: <https://github.com/openai/codex/tree/main/codex-rs/app-server-protocol/schema/json>

use std::collections::BTreeMap;

use serde_json::Value;

use crate::error::{CodexError, Result};

/// Raw JSON schema for the current upstream app-server protocol.
pub const APP_SERVER_PROTOCOL_SCHEMA_JSON: &str =
    include_str!("../protocol/codex_app_server_protocol.v2.schemas.json");

/// Summary metadata for the checked app-server protocol schema.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppServerProtocolSchemaSummary {
    pub title: Option<String>,
    pub definition_count: usize,
}

/// Return the raw JSON schema for the current upstream app-server protocol.
pub fn app_server_protocol_schema_json() -> &'static str {
    APP_SERVER_PROTOCOL_SCHEMA_JSON
}

/// Return summary metadata for the checked app-server protocol schema.
pub fn app_server_protocol_schema_summary() -> Result<AppServerProtocolSchemaSummary> {
    let schema = parse_schema()?;
    let title = schema
        .get("title")
        .and_then(Value::as_str)
        .map(ToOwned::to_owned);
    let definition_count = definitions(&schema)?.len();
    Ok(AppServerProtocolSchemaSummary {
        title,
        definition_count,
    })
}

/// Return sorted definition names from the checked app-server protocol schema.
pub fn app_server_protocol_definition_names() -> Result<Vec<String>> {
    let schema = parse_schema()?;
    let mut names = definitions(&schema)?
        .keys()
        .map(ToOwned::to_owned)
        .collect::<Vec<_>>();
    names.sort();
    Ok(names)
}

/// Return one schema definition by name.
pub fn app_server_protocol_definition(name: &str) -> Result<Value> {
    let schema = parse_schema()?;
    definitions(&schema)?.get(name).cloned().ok_or_else(|| {
        CodexError::Protocol(format!("app-server schema definition {name:?} not found"))
    })
}

fn parse_schema() -> Result<Value> {
    serde_json::from_str(APP_SERVER_PROTOCOL_SCHEMA_JSON).map_err(CodexError::from)
}

fn definitions(schema: &Value) -> Result<BTreeMap<String, Value>> {
    let definitions = schema
        .get("definitions")
        .and_then(Value::as_object)
        .ok_or_else(|| CodexError::Protocol("app-server schema missing definitions".to_string()))?;
    Ok(definitions
        .iter()
        .map(|(name, value)| (name.clone(), value.clone()))
        .collect())
}
