rust_library(
    name = "observability-aggregate",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "observability_aggregate",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//compute/core/resource:compute-resource",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//observability/core/domain:observability-domain",
    ],
)

rust_test(
    name = "observability-aggregate-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "observability_aggregate",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//compute/core/resource:compute-resource",
        "//cloud/cloud-iam/crates/oya-cloud-iam-domain:oya-cloud-iam-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//observability/core/domain:observability-domain",
    ],
)
