[package]
name = "observability-aggregate"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-cloud-domain = { path = "../../../iam/core/cloud-domain" }
cell-region = { path = "../../../cell/core/region" }
compute-resource = { path = "../../../compute/core/resource" }
audit-chain-domain = { path = "../../../audit/core/chain-domain" }
data-boundary-kernel = { path = "../../../base/data-boundary-kernel" }
observability-domain = { path = "../domain" }
network-residency = { path = "../../../network/core/residency" }

[lib]
name = "observability_aggregate"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
