rust_library(
    name = "workspace-forms-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workspace_forms_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//workflow/facade/forms-domain:workflow-forms-domain",
    ],
)

rust_test(
    name = "workspace-forms-api-workspace-forms-api",
    srcs = ["tests/workspace_forms_api.rs"],
    crate = "workspace_forms_api_workspace_forms_api",
    crate_root = "tests/workspace_forms_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":workspace-forms-api",
        "//base/data-boundary-kernel:data-boundary-kernel",
        "//workflow/facade/forms-domain:workflow-forms-domain",
    ],
)
