rust_library(
    name = "oya-cloud-intelligence-ops-infrastructure",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs", "**/*.json", "**/*.yaml", "**/*.yml"]),
    crate = "oya_cloud_intelligence_ops_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-cloud-intelligence-ops-infrastructure-tests",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs", "**/*.json", "**/*.yaml", "**/*.yml"]),
    crate = "oya_cloud_intelligence_ops_infrastructure_tests",
    crate_root = "tests/xproxy_ops_readonly.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-cloud-intelligence-ops-infrastructure",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
