rust_library(
    name = "oya-payments-charge-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_payments_charge_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/payments/crates/oya-payments-charge-grpc:oya-payments-charge-grpc",
        "//oya/payments/crates/oya-payments-charge-rest:oya-payments-charge-rest",
    ],
)
