rust_library(
    name = "oya-managed-k8s-sla-observability-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_managed_k8s_sla_observability_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/managed-k8s-sla-observability/crates/oya-managed-k8s-sla-observability-kernel:oya-managed-k8s-sla-observability-kernel",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
