rust_library(
    name = "oya-meter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_meter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:tokio",
    ],
)

rust_binary(
    name = "oya-meter-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-billing/crates/oya-meter:oya-meter",
        "third-party//:tokio",
    ],
)
