rust_library(
    name = "network-provider-oci",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_provider_oci",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "network-provider-oci-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "network_provider_oci",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/domain:network-domain",
        "//network/core/residency:network-residency",
        "//data/core/data-boundary-kernel:data-boundary-kernel",
    ],
)
