rust_library(
    name = "oya-tenancy-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenancy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//cloud/tenancy/crates/oya-tenancy-domain:oya-tenancy-domain",
    ],
)
