rust_library(
    name = "oya-tenancy-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenancy_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//cloud/tenancy/crates/oya-tenancy-domain:oya-tenancy-domain",
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-tenancy-api-tenant-create-api",
    srcs = ["tests/tenant_create_api.rs"],
    crate = "oya_tenancy_api_tenant_create_api",
    crate_root = "tests/tenant_create_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenancy-api",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//cloud/tenancy/crates/oya-tenancy-domain:oya-tenancy-domain",
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde_json",
    ],
)
