rust_library(
    name = "workflow-trigger-orchestrator-sdk",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_trigger_orchestrator_sdk",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/ports/trigger-orchestrator-rest:workflow-trigger-orchestrator-rest",
    ],
)

rust_test(
    name = "workflow-trigger-orchestrator-sdk-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "workflow_trigger_orchestrator_sdk",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//workflow/ports/trigger-orchestrator-rest:workflow-trigger-orchestrator-rest",
    ],
)
