rust_library(
    name = "cell-capacity-commercial",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_capacity_commercial",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "cell-capacity-commercial-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_capacity_commercial",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "cell-capacity-commercial-cloud-ops-foundation",
    srcs = ["tests/cloud_ops_foundation.rs"],
    crate = "cell_capacity_commercial_cloud_ops_foundation",
    crate_root = "tests/cloud_ops_foundation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":cell-capacity-commercial",
        "//billing/core/billing:billing-domain",
        "//billing/core/metering:billing-metering",
        "//cell/core/region:cell-region",
        "//compute/core/resource:compute-resource",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
