[package]
name = "cell-capacity-commercial"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
billing-domain = { path = "../../../billing/core/billing" }
cell-region = { path = "../region" }
compute-resource = { path = "../../../compute/core/resource" }
data-boundary-kernel = { path = "../../../libs/data-boundary-kernel" }
billing-metering = { path = "../../../billing/core/metering" }

[lib]
name = "cell_capacity_commercial"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
