rust_library(
    name = "oya-http-telemetry-middleware-infrastructure",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_telemetry_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
    ],
)
