[package]
name = "oya-cloud-network-lb-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-network-domain = { path = "../oya-cloud-network-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }

[dev-dependencies]
oya-residency-domain = { path = "../oya-residency-domain" }

[lib]
name = "oya_cloud_network_lb_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
