[package]
name = "oya-cloud-network-lb-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-network-kernel = { path = "../oya-cloud-network-kernel" }
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }

[dev-dependencies]
oya-platform-residency-kernel = { path = "../oya-platform-residency-kernel" }

[lib]
name = "oya_cloud_network_lb_api"
path = "src/lib.rs"
doctest = false
