[package]
name = "workflow-saas-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-saas-kernel = { path = "../saas-kernel" }

[lib]
name = "workflow_saas_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
