rust_library(
    name = "oya-identity-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_identity_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-domain:oya-identity-domain",
    ],
)

rust_test(
    name = "oya-identity-api-identity-user-upsert-api",
    srcs = ["tests/identity_user_upsert_api.rs"],
    crate = "oya_identity_api_identity_user_upsert_api",
    crate_root = "tests/identity_user_upsert_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-identity-api",
        "//oya/identity/crates/oya-identity-domain:oya-identity-domain",
    ],
)
