rust_library(
    name = "oya-governance-substance-bar",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_governance_substance_bar",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_yaml",
        "third-party//:walkdir-2",
    ],
)

rust_binary(
    name = "oya-governance-substance-bar-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/cli.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-substance-bar:oya-governance-substance-bar",
        "third-party//:anyhow-1",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:serde_yaml",
        "third-party//:walkdir-2",
    ],
)
