rust_library(
    name = "oya-buck-syntax-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_buck_syntax_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "oya-buck-syntax-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_buck_syntax_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
