[package]
name = "iam-cloud-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
cell-region = { path = "../../../cell/core/region" }

iam-identity-domain = { path = "../identity-domain" }

[lib]
name = "iam_cloud_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
