rust_library(
    name = "oya-community-post-store-grpc",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_community_post_store_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//oya/community/crates/oya-community-post-store-api:oya-community-post-store-api",
        "//oya/community/crates/oya-community-post-store-app:oya-community-post-store-app",
        "//oya/community/crates/oya-community-post-store-domain:oya-community-post-store-domain",
    ],
)
