rust_library(
    name = "shared-realtime-transport-kernel",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_realtime_transport_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "shared-realtime-transport-kernel-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_realtime_transport_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "shared-realtime-transport-kernel-budget-and-resume",
    srcs = ["tests/budget_and_resume.rs"],
    crate = "shared_realtime_transport_kernel_budget_and_resume",
    crate_root = "tests/budget_and_resume.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":shared-realtime-transport-kernel",
    ],
)
