rust_library(
    name = "oya-mail-mailbox-store-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_mail_mailbox_store_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
        "//oya/mail/crates/oya-mail-mailbox-store-adapter-postgres:oya-mail-mailbox-store-adapter-postgres",
        "//oya/mail/crates/oya-mail-mailbox-store-api:oya-mail-mailbox-store-api",
        "//oya/mail/crates/oya-mail-mailbox-store-usecase:oya-mail-mailbox-store-usecase",
    ],
)
