rust_library(
    name = "storage-object-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_object_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//storage/core/domain:storage-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "storage-object-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "storage_object_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//storage/core/domain:storage-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "storage-object-api-cloud-storage-object-api",
    srcs = ["tests/cloud_storage_object_api.rs"],
    crate = "storage_object_api_cloud_storage_object_api",
    crate_root = "tests/cloud_storage_object_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":storage-object-api",
        "//compute/core/resource:compute-resource",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//network/core/residency:network-residency",
        "//storage/core/domain:storage-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
