rust_library(
    name = "iam-identity-workload-oidc",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_oidc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:aws-lc-rs",
        "third-party//:base64",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-identity-workload-oidc-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_oidc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:aws-lc-rs",
        "third-party//:base64",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-identity-workload-oidc-token-validation",
    srcs = ["tests/token_validation.rs"],
    crate = "iam_identity_workload_oidc_token_validation",
    crate_root = "tests/token_validation.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-oidc",
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:aws-lc-rs",
        "third-party//:base64",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
