rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-sdk",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_engine_trigger_orchestrator_sdk",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-rest:oya-workflow-engine-trigger-orchestrator-rest",
    ],
)
