rust_library(
    name = "oya-marketplace-doc-set-scaffold",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_marketplace_doc_set_scaffold",
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)
