rust_library(
    name = "oya-http-tenant-middleware-infrastructure",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_http_tenant_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/tenancy/crates/oya-tenancy-kernel:oya-tenancy-kernel",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
    ],
)
