rust_library(
    name = "oya-whiteboard-canvas-collaboration-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_whiteboard_canvas_collaboration_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-whiteboard-canvas-collaboration",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/whiteboard/crates/oya-whiteboard-canvas-collaboration-app:oya-whiteboard-canvas-collaboration-app",
        "third-party//:clap",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:toml",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
