rust_library(
    name = "iam-identity-workload-authz-cedar",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_authz_cedar",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:cedar-policy",
    ],
)

rust_test(
    name = "iam-identity-workload-authz-cedar-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_identity_workload_authz_cedar",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:cedar-policy",
    ],
)

rust_test(
    name = "iam-identity-workload-authz-cedar-authz-allow-deny",
    srcs = ["tests/authz_allow_deny.rs"],
    crate = "iam_identity_workload_authz_cedar_authz_allow_deny",
    crate_root = "tests/authz_allow_deny.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-identity-workload-authz-cedar",
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
        "third-party//:cedar-policy",
    ],
)
