rust_library(
    name = "gateway-workday-connector",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "gateway_workday_connector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//gateway/core/shared-connector-kernel:shared-connector-kernel",
    ],
)

rust_test(
    name = "gateway-workday-connector-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "gateway_workday_connector",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//gateway/core/shared-connector-kernel:shared-connector-kernel",
    ],
)
