[package]
name = "oya-intelligence-api-websocket-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "oya_intelligence_api_websocket_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-intelligence-api-rest-kernel = { path = "../oya-intelligence-api-rest-kernel" }

oya-intelligence-api-websocket-kernel = { path = "../oya-intelligence-api-websocket-kernel" }

[dev-dependencies]


[lints]
workspace = true
