rust_library(
    name = "iam-cloud-pdp-bundle-file",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_cloud_pdp_bundle_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/cloud-pdp-kernel:iam-cloud-pdp-kernel",
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "iam-cloud-pdp-bundle-file-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_cloud_pdp_bundle_file",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/cloud-pdp-kernel:iam-cloud-pdp-kernel",
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
        "third-party//:serde_json",
    ],
)
