[package]
name = "workflow-trigger-orchestrator-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-trigger-orchestrator-domain = { path = "../trigger-orchestrator-domain" }

[lib]
name = "workflow_trigger_orchestrator_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
