[package]
name = "oya-hr-employment-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-hr-employment-app = { path = "../oya-hr-employment-app" }
oya-hr-employment-domain = { path = "../oya-hr-employment-domain" }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }

[lib]
name = "oya_hr_employment_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
