rust_library(
    name = "oya-tenant-rbac-storage-adapter-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_storage_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-usecase:oya-tenant-rbac-usecase",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-domain:oya-tenant-rbac-domain",
    ],
)

rust_test(
    name = "oya-tenant-rbac-storage-adapter-inmemory-storage",
    srcs = ["tests/storage.rs"],
    crate = "oya_tenant_rbac_storage_adapter_inmemory_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-storage-adapter-inmemory",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-usecase:oya-tenant-rbac-usecase",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-domain:oya-tenant-rbac-domain",
    ],
)
