[package]
name = "intelligence-account-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "intelligence_account_domain"
path = "src/lib.rs"
doctest = false

[dependencies]
intelligence-account-kernel = { path = "../account-kernel" }

[lints]
workspace = true
