rust_library(
    name = "data-ontology-query-engine-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_ontology_query_engine_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//data/core/ontology-kernel:data-ontology-kernel",
    ],
)

rust_test(
    name = "data-ontology-query-engine-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_ontology_query_engine_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/data-boundary-kernel:data-boundary-kernel",
        "//data/core/ontology-kernel:data-ontology-kernel",
    ],
)
