rust_library(
    name = "data-pipeline-lineage-replay-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_pipeline_lineage_replay_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "data-pipeline-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/facade/pipeline-lineage-replay-service:data-pipeline-lineage-replay-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "data-pipeline-lineage-replay-service-integration",
    srcs = ["tests/integration.rs"],
    crate = "data_pipeline_lineage_replay_service_integration",
    crate_root = "tests/integration.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":data-pipeline-lineage-replay-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
