rust_library(
    name = "oya-ops-workspace-shell-usecase",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_ops_workspace_shell_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ops/crates/oya-ops-workspace-shell-kernel:oya-ops-workspace-shell-kernel",
    ],
)
