rust_library(
    name = "oya-community-social-post-composition-grpc",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_social_post_composition_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//oya/community/crates/oya-community-social-app:oya-community-social-app",
        "//oya/community/crates/oya-community-social-post-composition-api:oya-community-social-post-composition-api",
    ],
)

rust_test(
    name = "oya-community-social-post-composition-grpc-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_community_social_post_composition_grpc",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
        "//oya/community/crates/oya-community-social-app:oya-community-social-app",
        "//oya/community/crates/oya-community-social-post-composition-api:oya-community-social-post-composition-api",
    ],
)
