rust_library(
    name = "crate-registrar-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "crate_registrar_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "crate-registrar-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "crate_registrar_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)
