rust_library(
    name = "oya-shared-transactional-outbox-dispatch-app",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_transactional_outbox_dispatch_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-transactional-outbox-kernel:oya-shared-transactional-outbox-kernel",
    ],
)
