rust_library(
    name = "oya-check-adr-index",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_adr_index",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/doc-parser:corpus-doc-parser",
    ],
)

rust_test(
    name = "oya-check-adr-index-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_adr_index",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/doc-parser:corpus-doc-parser",
    ],
)
