rust_library(
    name = "oya-check-adr-index",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_adr_index",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/doc-parser:corpus-doc-parser",
    ],
)

rust_test(
    name = "oya-check-adr-index-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_adr_index",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//governance/corpus/doc-parser:corpus-doc-parser",
    ],
)

rust_test(
    name = "oya-check-adr-index-ir-contract",
    srcs = ["tests/adr_index_ir_contract.rs"],
    crate = "adr_index_ir_contract",
    crate_root = "tests/adr_index_ir_contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-check-adr-index",
        "//governance/corpus/doc-parser:corpus-doc-parser",
    ],
)
