[package]
name = "oya-eventing-file-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }
oya-eventing-domain = { path = "../oya-eventing-domain" }

[lib]
name = "oya_eventing_file_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
