rust_library(
    name = "check-i18n-coverage",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_i18n_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-i18n-kernel:oya-shared-i18n-kernel",
    ],
)

rust_test(
    name = "check-i18n-coverage-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "check_i18n_coverage",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-i18n-kernel:oya-shared-i18n-kernel",
    ],
)

rust_test(
    name = "check-i18n-coverage-coverage-thresholds",
    srcs = ["tests/coverage_thresholds.rs"],
    crate = "check_i18n_coverage_coverage_thresholds",
    crate_root = "tests/coverage_thresholds.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":check-i18n-coverage",
        "//libs/oya-shared-i18n-kernel:oya-shared-i18n-kernel",
    ],
)
