[package]
name = "check-i18n-coverage"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "check_i18n_coverage"
path = "src/lib.rs"
doctest = false

[dependencies]
oya-shared-i18n-kernel = { path = "../../../libs/oya-shared-i18n-kernel" }

[lints]
workspace = true
