rust_library(
    name = "oya-shared-protocol-transport-retry-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_protocol_transport_retry_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
    ],
)

rust_test(
    name = "oya-shared-protocol-transport-retry-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_shared_protocol_transport_retry_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-protocol-parity-kernel:oya-shared-protocol-parity-kernel",
        "//libs/oya-shared-protocol-transport-kernel:oya-shared-protocol-transport-kernel",
    ],
)
