load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")

rust_binary(
    name = "oya-identity-workload-rest-build-script",
    srcs = ["build.rs"],
    crate = "build_script_build",
    crate_root = "build.rs",
    visibility = [],
    deps = [
        "third-party//:protoc-bin-vendored-3",
        "third-party//:tonic-prost-build-0.14",
    ],
)

buildscript_run(
    name = "oya-identity-workload-rest-build-script-run",
    script = ":oya-identity-workload-rest-build-script",
)

rust_library(
    name = "oya-identity-workload-rest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_identity_workload_rest",
    crate_root = "src/lib.rs",
    env = {"OUT_DIR": "$(location :oya-identity-workload-rest-build-script-run[out_dir])"},
    visibility = ["PUBLIC"],
    deps = [
        "//oya/identity/crates/oya-identity-workload-api:oya-identity-workload-api",
        "//oya/identity/crates/oya-identity-workload-app:oya-identity-workload-app",
        "//oya/identity/crates/oya-identity-workload-authz-cedar-adapter:oya-identity-workload-authz-cedar-adapter",
        "//oya/identity/crates/oya-identity-workload-domain:oya-identity-workload-domain",
        "//oya/identity/crates/oya-identity-workload-oidc-adapter:oya-identity-workload-oidc-adapter",
        "third-party//:aws-lc-rs-1",
        "third-party//:axum",
        "third-party//:base64",
        "third-party//:http-body-util",
        "third-party//:prost",
        "third-party//:protoc-bin-vendored-3",
        "third-party//:serde-1",
        "third-party//:serde_json-1",
        "third-party//:tokio-1",
        "third-party//:tokio-1",
        "third-party//:tonic",
        "third-party//:tonic-prost",
        "third-party//:tonic-prost-build",
        "third-party//:tower",
        "third-party//:tower",
        "third-party//:tracing",
    ],
)
