rust_library(
    name = "oya-tenant-rbac-tenant-secret-boundary-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_tenant_secret_boundary_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "oya-tenant-rbac-tenant-secret-boundary-contract-secret-boundary",
    srcs = ["tests/secret_boundary.rs"],
    crate = "oya_tenant_rbac_tenant_secret_boundary_contract_secret_boundary",
    crate_root = "tests/secret_boundary.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-tenant-secret-boundary-contract",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)
