[package]
name = "http-runtime-hyper-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
http-router-kernel = { path = "../../core/http-router-kernel" }
http-middleware-kernel = { path = "../../core/http-middleware-kernel" }
hyper.workspace = true
hyper-util.workspace = true
tokio.workspace = true
http-body-util.workspace = true
bytes.workspace = true
hyper-rustls = { workspace = true }
rustls = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }


[lib]
name = "http_runtime_hyper_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
