[package]
name = "iam-tenant-rbac-identity-provider-runtime-evidence"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iam-tenant-rbac-identity-provider-verification = { path = "../tenant-rbac-identity-provider-verification" }

[lib]
name = "iam_tenant_rbac_identity_provider_runtime_evidence"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
