rust_library(
    name = "iam-cloud-pdp-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_cloud_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//base/shared-platform-contracts-kernel:shared-platform-contracts-kernel",
    ],
)

rust_test(
    name = "iam-cloud-pdp-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_cloud_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//base/shared-platform-contracts-kernel:shared-platform-contracts-kernel",
    ],
)
