rust_library(
    name = "data-outbox-adapter-postgres",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql"]),
    crate = "data_outbox_adapter_postgres",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-outbox-kernel:oya-data-outbox-kernel",
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
    ],
)

rust_test(
    name = "data-outbox-adapter-postgres-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql"]),
    crate = "data_outbox_adapter_postgres",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-outbox-kernel:oya-data-outbox-kernel",
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
        "third-party//:tokio",
    ],
)
