rust_library(
    name = "console-docs-portal-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_docs_portal_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//console/adapters/docs-portal-adapter:console-docs-portal-adapter",
        "//console/ports/docs-portal-kernel:console-docs-portal-kernel",
        "//console/core/docs-portal-usecase:console-docs-portal-usecase",
    ],
)

rust_test(
    name = "console-docs-portal-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_docs_portal_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//console/adapters/docs-portal-adapter:console-docs-portal-adapter",
        "//console/ports/docs-portal-kernel:console-docs-portal-kernel",
        "//console/core/docs-portal-usecase:console-docs-portal-usecase",
    ],
)
