[package]
name = "console-docs-portal-rest"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
console-docs-portal-adapter = { path = "../../adapters/docs-portal-adapter" }
console-docs-portal-usecase = { path = "../../core/docs-portal-usecase" }
console-docs-portal-kernel = { path = "../../ports/docs-portal-kernel" }


[lib]
name = "console_docs_portal_rest"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
