rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_workflow_engine_trigger_orchestrator_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-domain:oya-workflow-engine-trigger-orchestrator-domain",
    ],
)
