rust_library(
    name = "secrets-kms-operator-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "secrets_kms_operator_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//secrets/adapters/kms-operator-k8s:secrets-kms-operator-k8s",
        "//secrets/core/kms-operator-kernel:secrets-kms-operator-kernel",
    ],
)

rust_binary(
    name = "cloud-kms-operator",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":secrets-kms-operator-app",
        "//secrets/core/kms-domain:secrets-kms-domain",
        "//secrets/adapters/kms-operator-k8s:secrets-kms-operator-k8s",
        "//secrets/core/kms-operator-kernel:secrets-kms-operator-kernel",
        "third-party//:kube",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "secrets-kms-operator-app-tests",
    srcs = glob(["src/**/*.rs", "tests/**/*.rs"]),
    crate = "secrets_kms_operator_app_tests",
    crate_root = "tests/app.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":secrets-kms-operator-app",
        "//secrets/adapters/kms-operator-k8s:secrets-kms-operator-k8s",
        "//secrets/core/kms-operator-kernel:secrets-kms-operator-kernel",
    ],
)
