[package]
name = "secrets-kms-operator-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "secrets_kms_operator_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "cloud-kms-operator"
path = "src/main.rs"

[dependencies]
secrets-kms-domain = { path = "../../core/kms-domain" }
secrets-kms-operator-k8s = { path = "../../adapters/kms-operator-k8s" }
secrets-kms-operator-kernel = { path = "../../core/kms-operator-kernel" }
kube = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
