rust_library(
    name = "billing-accounting-storage-inmemory-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_accounting_storage_inmemory_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//billing/core/accounting-app:billing-accounting-app",
        "//billing/core/accounting-journal:billing-accounting-journal",
    ],
)

rust_test(
    name = "billing-accounting-storage-inmemory-adapter-storage",
    srcs = ["tests/storage.rs"],
    crate = "billing_accounting_storage_inmemory_adapter_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-accounting-storage-inmemory-adapter",
        "//billing/core/accounting-app:billing-accounting-app",
        "//billing/core/accounting-journal:billing-accounting-journal",
    ],
)
