[package]
name = "billing-accounting-storage-inmemory-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
billing-accounting-app = { path = "../../core/accounting-app" }

[dev-dependencies]
billing-accounting-journal = { path = "../../core/accounting-journal" }

[lib]
name = "billing_accounting_storage_inmemory_adapter"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
