rust_library(
    name = "oya-intelligence-context-aware-retrieval-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_intelligence_context_aware_retrieval_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/intelligence/crates/oya-intelligence-context-aware-retrieval-usecase:oya-intelligence-context-aware-retrieval-usecase",
    ],
)
