[package]
name = "oya-hr-employment-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-hr-employment-domain = { path = "../oya-hr-employment-domain" }

[lib]
name = "oya_hr_employment_app"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
