rust_library(
    name = "shared-postgres-command-adapter-sqlx",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_postgres_command_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "third-party//:sqlx",
        "third-party//:tokio",
    ],
)

rust_test(
    name = "shared-postgres-command-adapter-sqlx-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "shared_postgres_command_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//base/shared-postgres-command-kernel:shared-postgres-command-kernel",
        "third-party//:sqlx",
        "third-party//:tokio",
    ],
)
