[package]
name = "oya-community-post-store-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-community-post-store-api = { path = "../oya-community-post-store-api" }
oya-community-post-store-domain = { path = "../oya-community-post-store-domain" }

[lib]
name = "oya_community_post_store_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
