[package]
name = "intelligence-rag-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
data-boundary-kernel = { path = "../../../base/data-boundary-kernel" }

[lib]
name = "intelligence_rag_api"
doctest = false

[lints]
workspace = true
