[package]
name = "oya-foundry-rag-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
oya-platform-data-boundary-kernel = { path = "../oya-platform-data-boundary-kernel" }

[lib]
name = "oya_foundry_rag_api"
doctest = false
