rust_library(
    name = "oya-tenant-rbac-tenant-egress-policy-contract",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_tenant_egress_policy_contract",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)

rust_test(
    name = "oya-tenant-rbac-tenant-egress-policy-contract-egress-policy",
    srcs = ["tests/egress_policy.rs"],
    crate = "oya_tenant_rbac_tenant_egress_policy_contract_egress_policy",
    crate_root = "tests/egress_policy.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-tenant-egress-policy-contract",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-admission-policy:oya-tenant-rbac-tenant-admission-policy",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)
