pub(crate) const EXPECTED_COLUMNS: &[&str] = &[
    "clusters|1|tenant_id|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "clusters|2|resource_id|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "clusters|3|desired_spec_json|pg_catalog.jsonb|-1|true||||",
    "clusters|4|cluster_json|pg_catalog.jsonb|-1|true||||",
    "clusters|5|observed_state|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "clusters|6|desired_state|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "clusters|7|schema_version|pg_catalog.int4|-1|true||||",
    "clusters|8|created_at|pg_catalog.timestamptz|-1|true|||now()|",
    "clusters|9|updated_at|pg_catalog.timestamptz|-1|true|||now()|",
    "operations|1|tenant_id|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|2|principal_id|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|3|surface|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|4|idempotency_key|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|5|resource_id|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|6|request_fingerprint|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "operations|7|receipt_kind|pg_catalog.text|-1|false||||pg_catalog.\"default\"",
    "operations|8|receipt_json|pg_catalog.jsonb|-1|false||||",
    "operations|9|receipt_digest|pg_catalog.text|-1|false||||pg_catalog.\"default\"",
    "operations|10|schema_version|pg_catalog.int4|-1|true||||",
    "operations|11|created_at|pg_catalog.timestamptz|-1|true|||now()|",
    "operations|12|completed_at|pg_catalog.timestamptz|-1|false||||",
    "schema_migrations|1|version|pg_catalog.int8|-1|true||||",
    "schema_migrations|2|name|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "schema_migrations|3|sha256|pg_catalog.text|-1|true||||pg_catalog.\"default\"",
    "schema_migrations|4|applied_at|pg_catalog.timestamptz|-1|true|||now()|",
];

pub(crate) const EXPECTED_CONSTRAINTS: &[&str] = &[
    "clusters|clusters_created_at_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'created_at_epoch_seconds'::text AND cluster_json ? 'created_at_epoch_seconds'::text AND (cluster_json -> 'created_at_epoch_seconds'::text) = (desired_spec_json -> 'created_at_epoch_seconds'::text))",
    "clusters|clusters_data_class_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'data_class'::text AND cluster_json ? 'data_class'::text AND (cluster_json -> 'data_class'::text) = (desired_spec_json -> 'data_class'::text))",
    "clusters|clusters_database_schema_version|c|true|false|false|CHECK (schema_version = 1)",
    "clusters|clusters_desired_resource_matches|c|true|false|false|CHECK (desired_spec_json ? 'resource_id'::text AND (desired_spec_json ->> 'resource_id'::text) = resource_id)",
    "clusters|clusters_desired_state_check|c|true|false|false|CHECK (desired_state <> ''::text)",
    "clusters|clusters_desired_state_matches|c|true|false|false|CHECK (cluster_json ? 'desired_state'::text AND (cluster_json ->> 'desired_state'::text) = desired_state AND (desired_state = ANY (ARRAY['present'::text, 'deleted'::text])))",
    "clusters|clusters_desired_tenant_matches|c|true|false|false|CHECK (desired_spec_json ? 'tenant_id'::text AND (desired_spec_json ->> 'tenant_id'::text) = tenant_id)",
    "clusters|clusters_flavor_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'flavor'::text AND cluster_json ? 'flavor'::text AND (cluster_json -> 'flavor'::text) = (desired_spec_json -> 'flavor'::text))",
    "clusters|clusters_json_objects|c|true|false|false|CHECK (jsonb_typeof(desired_spec_json) = 'object'::text AND jsonb_typeof(cluster_json) = 'object'::text)",
    "clusters|clusters_node_count_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'node_pools'::text AND jsonb_typeof(desired_spec_json -> 'node_pools'::text) = 'array'::text AND cluster_json ? 'node_pool_count'::text AND (cluster_json -> 'node_pool_count'::text) = to_jsonb(jsonb_array_length(desired_spec_json -> 'node_pools'::text)))",
    "clusters|clusters_observed_state_check|c|true|false|false|CHECK (observed_state <> ''::text)",
    "clusters|clusters_observed_state_matches|c|true|false|false|CHECK (cluster_json ? 'state'::text AND (cluster_json ->> 'state'::text) = observed_state AND (observed_state = ANY (ARRAY['creating'::text, 'ready'::text, 'reconciling'::text, 'draining'::text, 'deleted'::text])))",
    "clusters|clusters_pkey|p|true|false|false|PRIMARY KEY (tenant_id, resource_id)",
    "clusters|clusters_privacy_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'control_plane_private'::text AND cluster_json ? 'control_plane_private'::text AND (cluster_json -> 'control_plane_private'::text) = (desired_spec_json -> 'control_plane_private'::text))",
    "clusters|clusters_record_resource_matches|c|true|false|false|CHECK (cluster_json ? 'resource_id'::text AND (cluster_json ->> 'resource_id'::text) = resource_id)",
    "clusters|clusters_record_schema_version|c|true|false|false|CHECK (cluster_json ? 'schema_version'::text AND (cluster_json -> 'schema_version'::text) = '2'::jsonb)",
    "clusters|clusters_record_tenant_matches|c|true|false|false|CHECK (cluster_json ? 'tenant_id'::text AND (cluster_json ->> 'tenant_id'::text) = tenant_id)",
    "clusters|clusters_region_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'region'::text AND cluster_json ? 'region'::text AND (cluster_json -> 'region'::text) = (desired_spec_json -> 'region'::text))",
    "clusters|clusters_residency_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'residency'::text AND cluster_json ? 'residency'::text AND (cluster_json -> 'residency'::text) = (desired_spec_json -> 'residency'::text))",
    "clusters|clusters_resource_id_check|c|true|false|false|CHECK (resource_id <> ''::text)",
    "clusters|clusters_tenant_id_check|c|true|false|false|CHECK (tenant_id <> ''::text)",
    "clusters|clusters_version_matches_desired|c|true|false|false|CHECK (desired_spec_json ? 'control_plane_version'::text AND cluster_json ? 'control_plane_version'::text AND (cluster_json -> 'control_plane_version'::text) = (desired_spec_json -> 'control_plane_version'::text))",
    "operations|operations_database_schema_version|c|true|false|false|CHECK (schema_version = 1)",
    "operations|operations_idempotency_key_check|c|true|false|false|CHECK (idempotency_key <> ''::text)",
    "operations|operations_pkey|p|true|false|false|PRIMARY KEY (tenant_id, principal_id, surface, idempotency_key)",
    "operations|operations_principal_id_check|c|true|false|false|CHECK (principal_id <> ''::text)",
    "operations|operations_receipt_atomicity|c|true|false|false|CHECK ((receipt_kind IS NULL) = (receipt_json IS NULL) AND (receipt_json IS NULL) = (receipt_digest IS NULL) AND (receipt_digest IS NULL) = (completed_at IS NULL))",
    "operations|operations_receipt_digest_shape|c|true|false|false|CHECK (receipt_digest IS NULL OR receipt_digest ~ '^[0-9a-f]{64}$'::text)",
    "operations|operations_receipt_kind_check|c|true|false|false|CHECK (receipt_kind = ANY (ARRAY['create'::text, 'delete'::text]))",
    "operations|operations_receipt_surface_matches|c|true|false|false|CHECK (receipt_kind IS NULL OR surface = 'cloud.compute.k8s.cluster.create'::text AND receipt_kind = 'create'::text OR surface = 'cloud.compute.k8s.cluster.delete'::text AND receipt_kind = 'delete'::text)",
    "operations|operations_request_fingerprint_check|c|true|false|false|CHECK (request_fingerprint <> ''::text)",
    "operations|operations_resource_id_check|c|true|false|false|CHECK (resource_id <> ''::text)",
    "operations|operations_surface_check|c|true|false|false|CHECK (surface = ANY (ARRAY['cloud.compute.k8s.cluster.create'::text, 'cloud.compute.k8s.cluster.delete'::text]))",
    "operations|operations_tenant_id_check|c|true|false|false|CHECK (tenant_id <> ''::text)",
    "schema_migrations|schema_migrations_name_not_empty|c|true|false|false|CHECK (name <> ''::text)",
    "schema_migrations|schema_migrations_name_unique|u|true|false|false|UNIQUE (name)",
    "schema_migrations|schema_migrations_primary_key|p|true|false|false|PRIMARY KEY (version)",
    "schema_migrations|schema_migrations_sha256_shape|c|true|false|false|CHECK (sha256 ~ '^[0-9a-f]{64}$'::text)",
    "schema_migrations|schema_migrations_version_positive|c|true|false|false|CHECK (version > 0)",
];

pub(crate) const EXPECTED_INDEXES: &[&str] = &[
    "clusters|clusters_pkey|true|true|true|true|true|CREATE UNIQUE INDEX clusters_pkey ON compute_k8s_lifecycle.clusters USING btree (tenant_id, resource_id)",
    "clusters|clusters_reconciliation_scan|false|false|true|true|true|CREATE INDEX clusters_reconciliation_scan ON compute_k8s_lifecycle.clusters USING btree (tenant_id, desired_state, updated_at, resource_id)",
    "operations|operations_pkey|true|true|true|true|true|CREATE UNIQUE INDEX operations_pkey ON compute_k8s_lifecycle.operations USING btree (tenant_id, principal_id, surface, idempotency_key)",
    "operations|operations_resource_lookup|false|false|true|true|true|CREATE INDEX operations_resource_lookup ON compute_k8s_lifecycle.operations USING btree (tenant_id, resource_id, created_at)",
    "schema_migrations|schema_migrations_name_unique|true|false|true|true|true|CREATE UNIQUE INDEX schema_migrations_name_unique ON compute_k8s_lifecycle.schema_migrations USING btree (name)",
    "schema_migrations|schema_migrations_primary_key|true|true|true|true|true|CREATE UNIQUE INDEX schema_migrations_primary_key ON compute_k8s_lifecycle.schema_migrations USING btree (version)",
];

pub(crate) const EXPECTED_POLICIES: &[&str] = &[
    "clusters|clusters_require_tenant_guc|RESTRICTIVE|{compute_k8s_lifecycle_runtime}|ALL|((current_setting('oyatie.tenant_id'::text, true) IS NOT NULL) AND (current_setting('oyatie.tenant_id'::text, true) <> ''::text))|((current_setting('oyatie.tenant_id'::text, true) IS NOT NULL) AND (current_setting('oyatie.tenant_id'::text, true) <> ''::text))",
    "clusters|clusters_tenant_isolation|PERMISSIVE|{compute_k8s_lifecycle_runtime}|ALL|(tenant_id = current_setting('oyatie.tenant_id'::text, true))|(tenant_id = current_setting('oyatie.tenant_id'::text, true))",
    "operations|operations_require_tenant_guc|RESTRICTIVE|{compute_k8s_lifecycle_runtime}|ALL|((current_setting('oyatie.tenant_id'::text, true) IS NOT NULL) AND (current_setting('oyatie.tenant_id'::text, true) <> ''::text))|((current_setting('oyatie.tenant_id'::text, true) IS NOT NULL) AND (current_setting('oyatie.tenant_id'::text, true) <> ''::text))",
    "operations|operations_tenant_isolation|PERMISSIVE|{compute_k8s_lifecycle_runtime}|ALL|(tenant_id = current_setting('oyatie.tenant_id'::text, true))|(tenant_id = current_setting('oyatie.tenant_id'::text, true))",
];

pub(crate) const EXPECTED_GRANTS: &[&str] = &[
    "schema|compute_k8s_lifecycle_runtime|USAGE|false",
    "table|clusters|compute_k8s_lifecycle_runtime|INSERT|false",
    "table|clusters|compute_k8s_lifecycle_runtime|SELECT|false",
    "table|clusters|compute_k8s_lifecycle_runtime|UPDATE|false",
    "table|operations|compute_k8s_lifecycle_runtime|INSERT|false",
    "table|operations|compute_k8s_lifecycle_runtime|SELECT|false",
    "table|operations|compute_k8s_lifecycle_runtime|UPDATE|false",
    "table|schema_migrations|compute_k8s_lifecycle_runtime|SELECT|false",
];
