[package]
name = "intelligence-dashboard-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "intelligence_dashboard_kernel"
path = "src/lib.rs"
doctest = false

[dependencies]
intelligence-account-domain = { path = "../account-domain" }

[lints]
workspace = true
