rust_library(
    name = "oya-cloud-finops-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_cloud_finops_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-billing/crates/oya-cloud-billing-domain:oya-cloud-billing-domain",
        "//cloud/cloud-billing/crates/oya-metering-domain:oya-metering-domain",
        "//cloud/cloud-cell/crates/oya-cloud-region-domain:oya-cloud-region-domain",
        "//cloud/cloud-compute/crates/oya-cloud-resource-domain:oya-cloud-resource-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
