rust_library(
    name = "oya-shared-backbone-proto-contracts-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_shared_backbone_proto_contracts_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
