[package]
name = "os-security-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"


[lib]
name = "os_security_domain"
path = "src/lib.rs"
doctest = false

[dependencies]
os-kernel = { path = "../kernel" }

[lints]
workspace = true
