rust_library(
    name = "data-sql-adapter-sqlx",
    srcs = glob(["src/**/*.rs"]),
    crate = "data_sql_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
    ],
)

rust_test(
    name = "data-sql-adapter-sqlx-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "data_sql_adapter_sqlx",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-sql-kernel:oya-data-sql-kernel",
        "//libs/oya-shared-postgres-command-kernel:oya-shared-postgres-command-kernel",
        "third-party//:sqlx",
        "third-party//:tokio",
    ],
)
