[package]
name = "oya-cloud-marketplace-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-cloud-billing-domain = { path = "../../../cloud-billing/crates/oya-cloud-billing-domain" }
cell-region = { path = "../../../../cell/core/region" }
oya-data-boundary-kernel = { path = "../../../../libs/oya-data-boundary-kernel" }
oya-metering-domain = { path = "../../../cloud-billing/crates/oya-metering-domain" }

[lib]
name = "oya_cloud_marketplace_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
