rust_library(
    name = "messaging-file-adapter",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "messaging_file_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//bus/core/domain:messaging-domain",
    ],
)

rust_test(
    name = "messaging-file-adapter-file-outbox",
    srcs = ["tests/file_outbox.rs"],
    crate = "messaging_file_adapter_file_outbox",
    crate_root = "tests/file_outbox.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":messaging-file-adapter",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//bus/core/domain:messaging-domain",
    ],
)
