rust_library(
    name = "oya-workspace-drive-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workspace_drive_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//storage/facade/drive:storage-drive-domain",
    ],
)

rust_test(
    name = "oya-workspace-drive-api-workspace-drive-api",
    srcs = ["tests/workspace_drive_api.rs"],
    crate = "oya_workspace_drive_api_workspace_drive_api",
    crate_root = "tests/workspace_drive_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-workspace-drive-api",
        "//data/core/boundary-kernel:data-boundary-kernel",
        "//storage/facade/drive:storage-drive-domain",
    ],
)
