rust_library(
    name = "oya-check-authz-tier-discipline",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_check_authz_tier_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "oya-check-authz-tier-discipline-authz-tier-discipline",
    srcs = ["tests/authz_tier_discipline.rs"],
    crate = "oya_check_authz_tier_discipline_authz_tier_discipline",
    crate_root = "tests/authz_tier_discipline.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-check-authz-tier-discipline",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
