rust_library(
    name = "oya-procurement-source-to-pay-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_procurement_source_to_pay_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "oya-procurement-source-to-pay-domain-source-to-pay",
    srcs = ["tests/source_to_pay.rs"],
    crate = "oya_procurement_source_to_pay_domain_source_to_pay",
    crate_root = "tests/source_to_pay.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-procurement-source-to-pay-domain",
        "//data/core/boundary-kernel:data-boundary-kernel",
    ],
)
