[package]
name = "oya-procurement-source-to-pay-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-boundary-kernel = { path = "../../../../data/core/boundary-kernel" }

[lib]
name = "oya_procurement_source_to_pay_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
