rust_library(
    name = "oya-workflow-engine-execution-engine-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_engine_execution_engine_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-adapter:oya-workflow-engine-execution-engine-adapter",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-rest:oya-workflow-engine-execution-engine-rest",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-sdk:oya-workflow-engine-execution-engine-sdk",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-worker:oya-workflow-engine-execution-engine-worker",
    ],
)

rust_test(
    name = "oya-workflow-engine-execution-engine-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_engine_execution_engine_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-adapter:oya-workflow-engine-execution-engine-adapter",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-rest:oya-workflow-engine-execution-engine-rest",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-sdk:oya-workflow-engine-execution-engine-sdk",
        "//oya/workflow-engine/crates/oya-workflow-engine-execution-engine-worker:oya-workflow-engine-execution-engine-worker",
    ],
)
