rust_library(
    name = "messenger-workload-http",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_workload_http",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/workload-api:messenger-workload-api",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "messenger-workload-http-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "messenger_workload_http",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/workload-api:messenger-workload-api",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "messenger-workload-http-contract",
    srcs = ["tests/contract.rs"],
    crate = "contract",
    crate_root = "tests/contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":messenger-workload-http",
        "//app/messenger/core/domain:messenger-domain",
        "//app/messenger/ports/workload-api:messenger-workload-api",
        "third-party//:serde_json",
        "third-party//:tokio",
    ],
)
