rust_library(
    name = "oya-workflow-engine-state-machine-adapter-postgres",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_workflow_engine_state_machine_adapter_postgres",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-state-machine-kernel:oya-workflow-engine-state-machine-kernel",
        "//oya/workflow-engine/crates/oya-workflow-engine-state-machine-usecase:oya-workflow-engine-state-machine-usecase",
    ],
)
