rust_binary(
    name = "oya-shared-supply-chain-check-cli",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:anyhow-1",
        "third-party//:clap-4",
    ],
)
