rust_library(
    name = "oya-cost",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cost",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:tokio-1",
    ],
)

rust_binary(
    name = "oya-cost-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-finops/crates/oya-cost:oya-cost",
        "third-party//:tokio-1",
    ],
)
