rust_library(
    name = "iam-tenant-rbac-tenant-workload-manifest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_tenant_workload_manifest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "iam-tenant-rbac-tenant-workload-manifest-tenant-workload-manifest",
    srcs = ["tests/tenant_workload_manifest.rs"],
    crate = "iam_tenant_rbac_tenant_workload_manifest_tenant_workload_manifest",
    crate_root = "tests/tenant_workload_manifest.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-tenant-workload-manifest",
    ],
)
