[package]
name = "oya-http-telemetry-middleware-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-http-middleware-kernel = { path = "../oya-http-middleware-kernel" }

[dev-dependencies]
oya-http-router-kernel = { path = "../oya-http-router-kernel" }
bytes.workspace = true


[lib]
name = "oya_http_telemetry_middleware_domain"
path = "src/lib.rs"
doctest = false
