rust_library(
    name = "oya-audit-chain-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_audit_chain_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//oya/eventing/crates/oya-eventing-domain:oya-eventing-domain",
    ],
)

rust_test(
    name = "oya-audit-chain-usecase-audit-event-emit",
    srcs = ["tests/audit_event_emit.rs"],
    crate = "oya_audit_chain_usecase_audit_event_emit",
    crate_root = "tests/audit_event_emit.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-audit-chain-usecase",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//oya/eventing/crates/oya-eventing-domain:oya-eventing-domain",
    ],
)
