rust_library(
    name = "oya-audit-chain-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_audit_chain_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/audit-chain/crates/oya-audit-chain-domain:oya-audit-chain-domain",
        "//oya/eventing/crates/oya-eventing-domain:oya-eventing-domain",
    ],
)
