rust_library(
    name = "oya-check-layered-architecture-discipline",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_check_layered_architecture_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
