rust_library(
    name = "oya-check-layered-architecture-discipline",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_check_layered_architecture_discipline",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
