rust_library(
    name = "iam-identity-workload-svid-kernel",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "iam_identity_workload_svid_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
    ],
)

rust_test(
    name = "iam-identity-workload-svid-kernel-unittest",
    srcs = glob(["src/**/*.rs", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.txt"]),
    crate = "iam_identity_workload_svid_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/identity-workload-domain:iam-identity-workload-domain",
    ],
)
