[package]
name = "storage-object-http-legacy-draft"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-classification = { path = "../../../../data/ports/classification" }
secrets-kms-domain = { path = "../../../../secrets/core/kms-domain" }
compute-resource = { path = "../../../../compute/core/resource" }
storage-domain = { path = "../../../core/domain" }


[dev-dependencies]
network-residency = { path = "../../../../network/core/residency" }

[lib]
doctest = false

[lints]
workspace = true
