rust_library(
    name = "oya-cloud-iam-pdp-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_iam_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
    ],
)

rust_test(
    name = "oya-cloud-iam-pdp-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_iam_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-shared-pdp-kernel:oya-shared-pdp-kernel",
        "//libs/oya-shared-platform-contracts-kernel:oya-shared-platform-contracts-kernel",
    ],
)
