rust_library(
    name = "oya-tenant-rbac-tenant-workload-manifest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_tenant_rbac_tenant_workload_manifest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
