[package]
name = "intelligence-credential-resolver-usecase"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
intelligence-credential-resolver-domain = { path = "../credential-resolver-domain" }

[lib]
name = "intelligence_credential_resolver_usecase"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
