rust_library(
    name = "connect-address-book-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "connect_address_book_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)

rust_test(
    name = "connect-address-book-api-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "connect_address_book_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
    ],
)
