rust_library(
    name = "oya-hr-employment-storage-adapter-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_hr_employment_storage_adapter_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//app/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
    ],
)

rust_test(
    name = "oya-hr-employment-storage-adapter-inmemory-storage",
    srcs = ["tests/storage.rs"],
    crate = "oya_hr_employment_storage_adapter_inmemory_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-hr-employment-storage-adapter-inmemory",
        "//app/hr/crates/oya-hr-employment-app:oya-hr-employment-app",
        "//app/hr/crates/oya-hr-employment-domain:oya-hr-employment-domain",
    ],
)
