rust_library(
    name = "console-workspace-shell-rest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_workspace_shell_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//console/adapters/workspace-shell-adapter:console-workspace-shell-adapter",
        "//console/ports/workspace-shell-kernel:console-workspace-shell-kernel",
        "//console/core/workspace-shell-usecase:console-workspace-shell-usecase",
    ],
)

rust_test(
    name = "console-workspace-shell-rest-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "console_workspace_shell_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//console/adapters/workspace-shell-adapter:console-workspace-shell-adapter",
        "//console/ports/workspace-shell-kernel:console-workspace-shell-kernel",
        "//console/core/workspace-shell-usecase:console-workspace-shell-usecase",
    ],
)
