[package]
name = "console-workspace-shell-rest"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
console-workspace-shell-adapter = { path = "../../adapters/workspace-shell-adapter" }
console-workspace-shell-usecase = { path = "../../core/workspace-shell-usecase" }
console-workspace-shell-kernel = { path = "../../ports/workspace-shell-kernel" }


[lib]
name = "console_workspace_shell_rest"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
