rust_library(
    name = "oya-workflow-engine-trigger-orchestrator-rest",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_workflow_engine_trigger_orchestrator_rest",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/workflow-engine/crates/oya-workflow-engine-trigger-orchestrator-api:oya-workflow-engine-trigger-orchestrator-api",
    ],
)
