rust_library(
    name = "iam-pdp-kernel",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
    ],
)

rust_test(
    name = "iam-pdp-kernel-unittest",
    srcs = glob(["src/**/*.rs"]),
    crate = "iam_pdp_kernel",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/shared-pdp-kernel:shared-pdp-kernel",
        "//iam/core/platform-contracts-kernel:shared-platform-contracts-kernel",
    ],
)
