rust_library(
    name = "oya-slides-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_slides_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/intelligence/crates/oya-collab-runtime-domain:oya-collab-runtime-domain",
        "//oya/intelligence/crates/oya-document-format-domain:oya-document-format-domain",
    ],
)

rust_test(
    name = "oya-slides-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_slides_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
        "//oya/intelligence/crates/oya-collab-runtime-domain:oya-collab-runtime-domain",
        "//oya/intelligence/crates/oya-document-format-domain:oya-document-format-domain",
    ],
)
