rust_library(
    name = "hr-employment-storage-inmemory",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "hr_employment_storage_inmemory",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//app/hr/facade/employment-app:hr-employment-app",
        "//app/hr/core/employment-domain:hr-employment-domain",
    ],
)

rust_test(
    name = "hr-employment-storage-inmemory-storage",
    srcs = ["tests/storage.rs"],
    crate = "hr_employment_storage_inmemory_storage",
    crate_root = "tests/storage.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":hr-employment-storage-inmemory",
        "//app/hr/facade/employment-app:hr-employment-app",
        "//app/hr/core/employment-domain:hr-employment-domain",
    ],
)
