rust_library(
    name = "oya-check-adr-placeholders",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_check_adr_placeholders",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "oya-check-adr-placeholders-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-check-adr-placeholders:oya-check-adr-placeholders",
    ],
)
