[package]
name = "oya-check-adr-placeholders"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"
default-run = "oya-check-adr-placeholders"

[lib]
name = "oya_check_adr_placeholders"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "oya-check-adr-placeholders"
path = "src/main.rs"

[dependencies]

[lints]
workspace = true
