rust_library(
    name = "compliance-dsr-usecase",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "compliance_dsr_usecase",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/dsr:compliance-dsr",
    ],
)

rust_test(
    name = "compliance-dsr-usecase-dsr-cascade-execute-api",
    srcs = ["tests/dsr_cascade_execute_api.rs"],
    crate = "compliance_dsr_usecase_dsr_cascade_execute_api",
    crate_root = "tests/dsr_cascade_execute_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":compliance-dsr-usecase",
        "//libs/data-boundary-kernel:data-boundary-kernel",
        "//compliance/core/dsr:compliance-dsr",
    ],
)
