rust_library(
    name = "cell-routing",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_routing",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "cell-routing-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "cell_routing",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "cell-routing-cell-router",
    srcs = ["tests/cell_router.rs"],
    crate = "cell_routing_cell_router",
    crate_root = "tests/cell_router.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":cell-routing",
        "//network/core/residency:network-residency",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
