[package]
name = "oya-identity-api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-identity-domain = { path = "../oya-identity-domain" }

[lib]
name = "oya_identity_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
