rust_library(
    name = "billing-tax-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "billing_tax_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "billing-tax-api-cloud-billing-invoice-api",
    srcs = ["tests/cloud_billing_invoice_api.rs"],
    crate = "billing_tax_api_cloud_billing_invoice_api",
    crate_root = "tests/cloud_billing_invoice_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":billing-tax-api",
    ],
)
