[package]
name = "network-oci"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "network_oci"
path = "src/lib.rs"
doctest = false

[dependencies]
network-domain = { path = "../../core/domain" }

[dev-dependencies]

network-residency = { path = "../../core/residency" }

[lints]
workspace = true
