rust_library(
    name = "oya-cloud-storage-adapter-s3",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_storage_adapter_s3",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-storage/crates/oya-cloud-storage-domain:oya-cloud-storage-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
