rust_library(
    name = "data-search-rag",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_search_rag",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/search-query:data-search-query",
        "//data/core/search-rank:data-search-rank",
        "//data/core/search-serp:data-search-serp",
    ],
)

rust_test(
    name = "data-search-rag-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "data_search_rag",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//data/core/search-query:data-search-query",
        "//data/core/search-rank:data-search-rank",
        "//data/core/search-serp:data-search-serp",
    ],
)
