[package]
name = "data-search-rag"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
data-search-serp = { path = "../search-serp" }
data-search-query = { path = "../search-query" }

[dev-dependencies]
data-search-rank = { path = "../search-rank" }

[lib]
name = "data_search_rag"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
