{{- if .Values.svidOperator.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.svidOperator.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.svidOperator.name | quote }}
    app.kubernetes.io/part-of: oyatie-microservices
    oyatie.com/adr-0349: argocd-managed
spec:
  {{- if .Values.svidOperator.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.svidOperator.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.svidOperator.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.svidOperator.name | quote }}
{{- end }}
