[package]
name = "oya-vcs-promotion-controller-kernel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-vcs-kernel = { path = "../oya-vcs-kernel" }
oya-vcs-changebundle-kernel = { path = "../oya-vcs-changebundle-kernel" }
oya-vcs-test-standard-gate-kernel = { path = "../oya-vcs-test-standard-gate-kernel" }

[lib]
name = "oya_vcs_promotion_controller_kernel"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
