rust_library(
    name = "kernel-asterinas-abi-matrix",
    srcs = glob(["src/**/*.rs", "matrix/**/*.json"]),
    crate = "kernel_asterinas_abi_matrix",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//kernel/core/asterinas-boundary:kernel-asterinas-boundary",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "kernel-asterinas-abi-matrix-unittest",
    srcs = glob(["src/**/*.rs", "matrix/**/*.json"]),
    crate = "kernel_asterinas_abi_matrix",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//kernel/core/asterinas-boundary:kernel-asterinas-boundary",
        "third-party//:serde_json",
    ],
)
