rust_library(
    name = "oya-scm-forgejo",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_scm_forgejo",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-scm:oya-scm",
        "third-party//:reqwest",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
