rust_library(
    name = "http-telemetry-middleware-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "http_telemetry_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
    ],
)

rust_test(
    name = "http-telemetry-middleware-infrastructure-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "http_telemetry_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
    ],
)
