rust_library(
    name = "intelligence-catalog-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_catalog_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)

rust_test(
    name = "intelligence-catalog-domain-catalog-record",
    srcs = ["tests/catalog_record.rs"],
    crate = "intelligence_catalog_domain_catalog_record",
    crate_root = "tests/catalog_record.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-catalog-domain",
        "//libs/data-boundary-kernel:data-boundary-kernel",
    ],
)
