rust_library(
    name = "payroll-run-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "payroll_run_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//app/payroll/ports/run-api:payroll-run-api",
        "//app/payroll/facade/run-app:payroll-run-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "payroll-run-infrastructure-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "payroll_run_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//app/payroll/ports/run-api:payroll-run-api",
        "//app/payroll/facade/run-app:payroll-run-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)

rust_test(
    name = "payroll-run-infrastructure-runtime",
    srcs = ["tests/runtime.rs"],
    crate = "payroll_run_infrastructure_runtime",
    crate_root = "tests/runtime.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":payroll-run-infrastructure",
        "//libs/http-middleware-kernel:http-middleware-kernel",
        "//libs/http-router-kernel:http-router-kernel",
        "//libs/http-runtime-hyper-adapter:http-runtime-hyper-adapter",
        "//app/payroll/ports/run-api:payroll-run-api",
        "//app/payroll/facade/run-app:payroll-run-app",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
