rust_library(
    name = "oya-tenant-rbac-runtime",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_tenant_rbac_runtime",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-api:oya-tenant-rbac-api",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-application:oya-tenant-rbac-application",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-domain:oya-tenant-rbac-domain",
        "third-party//:serde",
        "third-party//:serde_json",
    ],
)
