rust_library(
    name = "oya-itsm-escalation-policy",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_itsm_escalation_policy",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde-1",
        "third-party//:serde_json-1",
    ],
)
