rust_library(
    name = "oya-tenant-rbac-audit-chain-emission",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_tenant_rbac_audit_chain_emission",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//audit/ports/emission-api:audit-emission-api",
        "//audit/ports/emission-kernel:audit-emission-kernel",
    ],
)

rust_test(
    name = "oya-tenant-rbac-audit-chain-emission-audit-chain-emission",
    srcs = ["tests/audit_chain_emission.rs"],
    crate = "oya_tenant_rbac_audit_chain_emission_audit_chain_emission",
    crate_root = "tests/audit_chain_emission.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-tenant-rbac-audit-chain-emission",
        "//audit/ports/emission-api:audit-emission-api",
        "//audit/ports/emission-kernel:audit-emission-kernel",
    ],
)
