rust_library(
    name = "iac-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iac_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iac/core/api:iac-api",
        "//iac/core/domain:iac-domain",
        "//iac/adapters/infrastructure:iac-infrastructure",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "third-party//:sha2",
    ],
)

rust_binary(
    name = "oya-cloud-iac",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iac/facade/app:iac-app",
        "//iac/core/api:iac-api",
        "//iac/core/domain:iac-domain",
        "//iac/adapters/infrastructure:iac-infrastructure",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "third-party//:sha2",
    ],
)

rust_test(
    name = "iac-app-cloud-iac-app",
    srcs = [],
    crate = "iac_app_cloud_iac_app",
    crate_root = "cloud/cloud-iac/crates/oya-cloud-iac-app/tests/cloud_iac_app.rs",
    visibility = ["PUBLIC"],
    mapped_srcs = {
        "tests/cloud_iac_app.rs": "cloud/cloud-iac/crates/oya-cloud-iac-app/tests/cloud_iac_app.rs",
        "//cloud/cloud-iac/tofu/modules:release-index.json": "cloud/cloud-iac/tofu/modules/release-index.json",
    },
    deps = [
        ":iac-app",
        "//iac/core/api:iac-api",
        "//iac/core/domain:iac-domain",
        "//iac/adapters/infrastructure:iac-infrastructure",
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
        "//libs/oya-http-runtime-hyper-adapter:oya-http-runtime-hyper-adapter",
        "third-party//:sha2",
    ],
)
