[package]
name = "iac-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
http-runtime-hyper-adapter = { path = "../../../gateway/adapters/http-runtime-hyper" }
http-router-kernel = { path = "../../../gateway/core/http-router-kernel" }
http-middleware-kernel = { path = "../../../gateway/core/http-middleware-kernel" }
iac-api = { path = "../../core/api" }
iac-domain = { path = "../../core/domain" }
iac-infrastructure = { path = "../../adapters/infrastructure" }



sha2 = { version = "0.10", default-features = false }

[lib]
name = "iac_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "iac-app"
path = "src/main.rs"

[lints]
workspace = true
