[package]
name = "iac-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
iac-api = { path = "../../core/api" }
iac-domain = { path = "../../core/domain" }
iac-infrastructure = { path = "../../adapters/infrastructure" }



sha2 = { version = "0.10", default-features = false }

[lib]
name = "iac_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "cloud-iac"
path = "src/main.rs"

[lints]
workspace = true
