rust_binary(
    name = "pipeline-path-occupancy-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "pipeline_path_occupancy_app",
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//pipeline/core/admission:pipeline-admission",
    ],
)
