rust_binary(
    name = "oya-governance-dependency-status-lifecycle-app",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-governance-lifecycle-kernel:oya-governance-lifecycle-kernel",
    ],
)
