rust_library(
    name = "oya-ci-webhook-gateway-ed25519-adapter",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_ci_webhook_gateway_ed25519_adapter",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/ci-webhook-gateway/crates/oya-ci-webhook-gateway-kernel:oya-ci-webhook-gateway-kernel",
        "third-party//:ed25519-dalek",
        "third-party//:ed25519-dalek",
        "third-party//:rand_core",
    ],
)
