rust_library(
    name = "fabric-loop-state-app",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "fabric_loop_state_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "fabric-loop-state-bin",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//tools/fabric-loop-state-app:fabric-loop-state-app",
    ],
)

rust_test(
    name = "fabric-loop-state-app-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "fabric_loop_state_app",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "fabric-loop-state-app-contract",
    srcs = ["tests/contract.rs"],
    crate = "fabric_loop_state_app_contract",
    crate_root = "tests/contract.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":fabric-loop-state-app",
    ],
)
