rust_library(
    name = "oya-performance-management-review-calibration-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "oya_performance_management_review_calibration_service",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_binary(
    name = "oya-performance-management-service",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/performance-management/crates/oya-performance-management-review-calibration-service:oya-performance-management-review-calibration-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)

rust_test(
    name = "oya-performance-management-review-calibration-service-integration",
    srcs = ["tests/integration.rs"],
    crate = "oya_performance_management_review_calibration_service_integration",
    crate_root = "tests/integration.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":oya-performance-management-review-calibration-service",
        "third-party//:serde",
        "third-party//:serde_json",
        "third-party//:serde_json",
        "third-party//:tokio",
        "third-party//:tracing",
        "third-party//:tracing-subscriber",
    ],
)
