rust_library(
    name = "oya-tenant-rbac-cloud-deployment-evidence",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_tenant_rbac_cloud_deployment_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//oya/tenant-rbac/crates/oya-tenant-rbac-cloud-deployment-manifest:oya-tenant-rbac-cloud-deployment-manifest",
        "//oya/tenant-rbac/crates/oya-tenant-rbac-tenant-workload-manifest:oya-tenant-rbac-tenant-workload-manifest",
    ],
)
