rust_library(
    name = "iam-cloud-api",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_cloud_api",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/core/cloud-domain:iam-cloud-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)

rust_test(
    name = "iam-cloud-api-cloud-iam-api",
    srcs = ["tests/cloud_iam_api.rs"],
    crate = "iam_cloud_api_cloud_iam_api",
    crate_root = "tests/cloud_iam_api.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-cloud-api",
        "//iam/core/cloud-domain:iam-cloud-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
