rust_library(
    name = "intelligence-credential-resolver-domain",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_credential_resolver_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "intelligence-credential-resolver-domain-unittest",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "intelligence_credential_resolver_domain",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [],
)

rust_test(
    name = "intelligence-credential-resolver-domain-credential-resolver-domain",
    srcs = ["tests/credential_resolver_domain.rs"],
    crate = "intelligence_credential_resolver_domain_credential_resolver_domain",
    crate_root = "tests/credential_resolver_domain.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":intelligence-credential-resolver-domain",
    ],
)
