rust_library(
    name = "iam-tenant-rbac-workflow-runtime-evidence",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"]),
    crate = "iam_tenant_rbac_workflow_runtime_evidence",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//iam/adapters/tenant-rbac-workflow-inmemory:iam-tenant-rbac-workflow-inmemory",
    ],
)

rust_test(
    name = "iam-tenant-rbac-workflow-runtime-evidence-workflow-runtime-evidence",
    srcs = ["tests/workflow_runtime_evidence.rs"],
    crate = "iam_tenant_rbac_workflow_runtime_evidence_workflow_runtime_evidence",
    crate_root = "tests/workflow_runtime_evidence.rs",
    visibility = ["PUBLIC"],
    deps = [
        ":iam-tenant-rbac-workflow-runtime-evidence",
        "//iam/adapters/tenant-rbac-workflow-inmemory:iam-tenant-rbac-workflow-inmemory",
    ],
)
