[package]
name = "oya-workflow-engine-execution-engine-sdk"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-workflow-engine-execution-engine-rest = { path = "../oya-workflow-engine-execution-engine-rest" }

[dev-dependencies]
oya-workflow-engine-execution-engine-adapter = { path = "../oya-workflow-engine-execution-engine-adapter" }

[lib]
name = "oya_workflow_engine_execution_engine_sdk"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
