rust_library(
    name = "oya-cloud-network-adapter-oci",
    srcs = glob(["src/**/*.rs"]),
    crate = "oya_cloud_network_adapter_oci",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//cloud/cloud-network/crates/oya-cloud-network-domain:oya-cloud-network-domain",
        "//cloud/cloud-network/crates/oya-residency-domain:oya-residency-domain",
        "//libs/oya-data-boundary-kernel:oya-data-boundary-kernel",
    ],
)
