[package]
name = "oya-foundry-step-file-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-foundry-step-domain = { path = "../oya-foundry-step-domain" }
oya-data-boundary-kernel = { path = "../oya-data-boundary-kernel" }

[lib]
name = "oya_foundry_step_file_adapter"
path = "src/lib.rs"
doctest = false
