rust_library(
    name = "oya-http-latency-budget-middleware-infrastructure",
    srcs = glob(["src/**/*.rs", "migrations/**/*.sql", "**/*.cedar", "**/*.sql", "**/*.json", "**/*.toml", "**/*.yaml", "**/*.yml", "**/*.proto", "**/*.graphql", "**/*.html", "**/*.css", "**/*.txt"], allow_empty = True),
    crate = "oya_http_latency_budget_middleware_infrastructure",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "//libs/oya-http-middleware-kernel:oya-http-middleware-kernel",
        "//libs/oya-http-router-kernel:oya-http-router-kernel",
    ],
)
