[package]
name = "workflow-execution-engine-domain"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
workflow-execution-engine-kernel = { path = "../execution-engine-kernel" }

[lib]
name = "workflow_execution_engine_domain"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
