[package]
name = "storage-oci-adapter"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[lib]
name = "storage_oci_adapter"
path = "src/lib.rs"
doctest = false

[dependencies]
data-boundary-kernel = { path = "../../../data/core/data-boundary-kernel" }
storage-domain = { path = "../../core/domain" }

[dev-dependencies]


[lints]
workspace = true
