[package]
name = "oya-office-drive-api-app"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false
license = "Apache-2.0"

[dependencies]
oya-office-drive-api = { path = "../oya-office-drive-api" }
oya-office-drive-domain = { path = "../oya-office-drive-domain" }
oya-office-kernel = { path = "../oya-office-kernel" }

[lib]
name = "oya_office_drive_api_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "oya-office-drive-api-app"
path = "src/main.rs"

[lints]
workspace = true
